import { supabase } from './supabase';
import type { DashboardKPIs, MonthlyTrend, TopEntity } from './queries';
import type { SalesInvoice } from './types';
interface InvoiceRow{id:string;total:number|null;paid_amount:number|null;status:string|null;invoice_date:string;due_date:string|null;}
interface SaleItemRow{invoice_id:string|null;line_total:number|null;cost_price:number|null;quantity:number|null;}
const required=(v:number|null|undefined,f:string)=>{if(v===null||v===undefined||!Number.isFinite(v))throw new Error(`REPORT_DATA_UNAVAILABLE: required numeric field '${f}' is missing or invalid`);return v;};
const validDate=(v:string|null|undefined,f:string)=>{if(!v)throw new Error(`REPORT_DATA_UNAVAILABLE: required date field '${f}' is missing`);const d=new Date(v);if(Number.isNaN(d.getTime()))throw new Error(`REPORT_DATA_UNAVAILABLE: required date field '${f}' is invalid`);return d;};
async function load(){const {data:invoices,error:ie}=await supabase.from('sales_invoices').select('id,total,paid_amount,status,invoice_date,due_date');if(ie)throw ie;const rows=(invoices??[]) as InvoiceRow[];const ids=rows.map(x=>x.id);const {data:items,error:xe}=ids.length?await supabase.from('sale_items').select('invoice_id,line_total,cost_price,quantity').in('invoice_id',ids):{data:[],error:null};if(xe)throw xe;return{invoices:rows,items:(items??[]) as SaleItemRow[]};}
export async function fetchCanonicalDashboardKPIs():Promise<DashboardKPIs>{const {invoices,items}=await load();const {data:balances,error:be}=await supabase.from('inventory_balances').select('quantity,unit_cost');if(be)throw be;const {count:customerCount,error:ce}=await supabase.from('customers').select('id',{count:'exact',head:true});if(ce)throw ce;const {count:productCount,error:pe}=await supabase.from('products').select('id',{count:'exact',head:true});if(pe)throw pe;const {data:purchases,error:purchaseError}=await supabase.from('purchase_invoices').select('total,paid_amount');if(purchaseError)throw purchaseError;const totalSales=items.reduce((s,r)=>s+required(r.line_total,'sale_items.line_total'),0),totalCost=items.reduce((s,r)=>s+required(r.cost_price,'sale_items.cost_price')*required(r.quantity,'sale_items.quantity'),0),grossProfit=totalSales-totalCost;const hasData=invoices.length>0||(purchases??[]).length>0||(balances??[]).length>0;if(!hasData)return{totalSales:null,totalCost:null,grossProfit:null,grossMargin:null,totalReceivables:null,overdueReceivables:null,totalPayables:null,inventoryValue:null,totalCustomers:customerCount??0,activeCustomers:null,totalProducts:productCount??0,invoiceCount:0,avgInvoiceValue:null,collectionRate:null,status:'INSUFFICIENT_DATA'};const totalReceivables=invoices.reduce((s,r)=>s+required(r.total,'sales_invoices.total')-required(r.paid_amount,'sales_invoices.paid_amount'),0);const today=new Date().toISOString().split('T')[0];const overdueReceivables=invoices.filter(r=>r.due_date&&r.due_date<today&&required(r.paid_amount,'sales_invoices.paid_amount')<required(r.total,'sales_invoices.total')).reduce((s,r)=>s+required(r.total,'sales_invoices.total')-required(r.paid_amount,'sales_invoices.paid_amount'),0);const totalPayables=(purchases??[]).reduce((s,r)=>s+required(r.total,'purchase_invoices.total')-required(r.paid_amount,'purchase_invoices.paid_amount'),0),inventoryValue=(balances??[]).reduce((s,r)=>s+required(r.quantity,'inventory_balances.quantity')*required(r.unit_cost,'inventory_balances.unit_cost'),0),invoiceCount=invoices.length,totalPaid=invoices.reduce((s,r)=>s+required(r.paid_amount,'sales_invoices.paid_amount'),0),totalInvoiceAmount=invoices.reduce((s,r)=>s+required(r.total,'sales_invoices.total'),0);return{totalSales,totalCost,grossProfit,grossMargin:totalSales?(grossProfit/totalSales)*100:null,totalReceivables,overdueReceivables,totalPayables,inventoryValue,totalCustomers:customerCount??0,activeCustomers:null,totalProducts:productCount??0,invoiceCount,avgInvoiceValue:invoiceCount?totalSales/invoiceCount:null,collectionRate:totalInvoiceAmount?(totalPaid/totalInvoiceAmount)*100:null,status:'CALCULATED'};}
export async function fetchCanonicalMonthlyTrend(months=6):Promise<MonthlyTrend[]>{const {invoices,items}=await load();if(!invoices.length)return[];const sales=new Map<string,number>(),cost=new Map<string,number>();for(const r of items){if(!r.invoice_id)continue;sales.set(r.invoice_id,(sales.get(r.invoice_id)??0)+required(r.line_total,'sale_items.line_total'));cost.set(r.invoice_id,(cost.get(r.invoice_id)??0)+required(r.cost_price,'sale_items.cost_price')*required(r.quantity,'sale_items.quantity'));}const by=new Map<string,{sales:number;cost:number;invoices:number}>();for(const inv of invoices){const d=validDate(inv.invoice_date,'sales_invoices.invoice_date'),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,e=by.get(k)??{sales:0,cost:0,invoices:0};e.sales+=sales.get(inv.id)??0;e.cost+=cost.get(inv.id)??0;e.invoices++;by.set(k,e);}const labels=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],out:MonthlyTrend[]=[],now=new Date();for(let i=months-1;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,e=by.get(k)??{sales:0,cost:0,invoices:0};out.push({month:k,label:labels[d.getMonth()],sales:e.sales,cost:e.cost,profit:e.sales-e.cost,invoices:e.invoices});}return out;}
export async function fetchCanonicalTopCustomers(limit=5):Promise<TopEntity[]>{const {invoices,items}=await load();const {data:customers,error:ce}=await supabase.from('customers').select('id,name');if(ce)throw ce;const names=new Map((customers??[]).map(c=>[c.id,c.name??c.id]));const byInvoice=new Map<string,number>();for(const r of items)if(r.invoice_id)byInvoice.set(r.invoice_id,(byInvoice.get(r.invoice_id)??0)+required(r.line_total,'sale_items.line_total'));const totals=new Map<string,{name:string;value:number}>();for(const r of invoices){const id=(await Promise.resolve(r as InvoiceRow)).id;void id;}const {data:relations,error:re}=await supabase.from('sales_invoices').select('id,customer_id');if(re)throw re;for(const r of relations??[]){const id=r.customer_id as string;if(!id)continue;const e=totals.get(id)??{name:names.get(id)??id,value:0};e.value+=byInvoice.get(r.id as string)??0;totals.set(id,e);}return[...totals.entries()].map(([id,v])=>({id,name:v.name,value:v.value})).sort((a,b)=>b.value-a.value).slice(0,limit);}

/** Full report dataset for export. Intentionally independent of presentation pagination. */
export async function fetchAllSalesInvoicesForReportExport():Promise<SalesInvoice[]>{
  const pageSize=500;
  const rows:SalesInvoice[]=[];
  for(let page=0;;page++){
    const from=page*pageSize,to=from+pageSize-1;
    const {data,count,error}=await supabase.from('sales_invoices').select('*, customer:customers(id,name)',{count:'exact'}).order('invoice_date',{ascending:false}).range(from,to);
    if(error)throw error;
    const batch=(data??[]) as SalesInvoice[];
    rows.push(...batch);
    if(batch.length<pageSize || (count!=null && rows.length>=count))break;
  }
  return rows;
}
