import { BUSINESS_METRICS, type MetricDefinition } from './semanticMetrics';

export interface BIIntent { metric: MetricDefinition | null; period: 'today'|'7d'|'30d'|'90d'|'unknown'; ranking?: 'top'|'bottom'; entity?: 'products'|'customers'|'categories'; confidence: number; reason: string; }

const aliases: Record<string,string[]> = {
  net_sales:['مبيعات','المبيعات','sales','revenue','بيع'], gross_profit:['ربح','الربح','مجمل الربح','profit'], receivables:['ذمم','الذمم','تحصيل','مستحقات العملاء','receivables'], payables:['موردين','الموردين','التزامات','payables'], inventory_value:['مخزون','المخزون','قيمة المخزون','inventory'], stock_coverage:['تغطية','تغطية المخزون','days of stock'], customer_activity:['عملاء نشطين','نشاط العملاء','customers']
};
function normalize(value:string){return value.toLowerCase().replace(/[إأآ]/g,'ا').replace(/ة/g,'ه').replace(/\s+/g,' ').trim();}
export function resolveMetric(question:string){const q=normalize(question); let best:MetricDefinition|null=null; let bestScore=0; for(const metric of BUSINESS_METRICS){const words=[metric.key,metric.label,...(aliases[metric.key]||[])].map(normalize); const score=words.reduce((s,w)=>s+(q.includes(w)?Math.min(1,w.length/8):0),0); if(score>bestScore){bestScore=score;best=metric;}} return {metric:best,score:Math.min(1,bestScore)};}
export function parseBIQuestion(question:string):BIIntent{const q=normalize(question); const resolved=resolveMetric(q); const period=q.includes('اليوم')||q.includes('today')?'today':q.includes('اسبوع')||q.includes('7')?'7d':q.includes('شهر')||q.includes('30')?'30d':q.includes('90')||q.includes('ربع')?'90d':'unknown'; const ranking=q.includes('الأكثر')||q.includes('الاكثر')||q.includes('top')?'top':q.includes('الأقل')||q.includes('الاقل')||q.includes('bottom')?'bottom':undefined; const entity=q.includes('منتج')||q.includes('اصناف')||q.includes('صنف')?'products':q.includes('عميل')||q.includes('عملاء')?'customers':q.includes('تصنيف')||q.includes('فئة')?'categories':undefined; const confidence=resolved.score===0?0.05:Math.min(.97,resolved.score+(period==='unknown'?0:.12)+(ranking?0.08:0)); return {metric:resolved.metric,period,ranking,entity,confidence,reason:resolved.metric?`تم التعرف على المقياس من قاموس الأعمال: ${resolved.metric.label}`:'لم يتم التعرف على مقياس موثوق؛ لن يتم اختلاق نتيجة.'};}

export function explainBIIntent(intent:BIIntent){return {answerable:Boolean(intent.metric&&intent.confidence>=.45),status:intent.metric&&intent.confidence>=.45?'READY':'NEEDS_CLARIFICATION',message:intent.metric&&intent.confidence>=.45?`سأحلل «${intent.metric.label}» للفترة المحددة باستخدام تعريف المقياس الرسمي.`:'أحتاج إلى توضيح المقياس أو الفترة قبل إعطاء نتيجة حتى لا أقدم رقمًا غير موثوق.',evidence:intent.metric?.source||[]};}
