import { supabase } from './supabase';
import { SaleItem } from './types';

export interface DashboardKPIs { totalSales:number; totalCost:number; grossProfit:number; grossMargin:number; totalReceivables:number; overdueReceivables:number; totalPayables:number; inventoryValue:number; totalCustomers:number; activeCustomers:number; totalProducts:number; invoiceCount:number; avgInvoiceValue:number; collectionRate:number; status:'CONFIRMED'|'CALCULATED'|'INSUFFICIENT_DATA'; }
export interface MonthlyTrend { month:string; label:string; sales:number; cost:number; profit:number; invoices:number; }
export interface TopEntity { id:string; name:string; value:number; secondary?:number; }
export interface AgingBucket { bucket:string; amount:number; count:number; }
export interface CategoryBreakdown { name:string; sales:number; profit:number; quantity:number; }
interface DashboardInvoice { id:string; customer_id:string|null; total:number|null; paid_amount:number|null; subtotal:number|null; tax_amount:number|null; status:string|null; invoice_date:string; due_date:string|null; }
function required(value:number|null|undefined, field:string):number { if(value===null||value===undefined||!Number.isFinite(value)) throw new Error(`REPORT_DATA_UNAVAILABLE: ${field}`); return value; }

export async function fetchDashboardKPIs():Promise<DashboardKPIs>{
 const {data:invoices,error:ie}=await supabase.from('sales_invoices').select('id, customer_id, total, paid_amount, subtotal, tax_amount, status, invoice_date, due_date'); if(ie)throw ie;
 const inv=(invoices??[]) as DashboardInvoice[]; const ids=inv.map(i=>i.id);
 const {data:items,error:itemError}=ids.length?await supabase.from('sale_items').select('invoice_id,line_total,cost_price,quantity').in('invoice_id',ids):{data:[],error:null}; if(itemError)throw itemError;
 const {data:balances,error:be}=await supabase.from('inventory_balances').select('quantity,unit_cost'); if(be)throw be;
 const {count:customerCount,error:ce}=await supabase.from('customers').select('id',{count:'exact',head:true}); if(ce)throw ce;
 const {count:productCount,error:pe}=await supabase.from('products').select('id',{count:'exact',head:true}); if(pe)throw pe;
 const {data:purchases,error:purchaseError}=await supabase.from('purchase_invoices').select('total,paid_amount'); if(purchaseError)throw purchaseError;
 const totalSales=inv.reduce((s,i)=>s+required(i.subtotal,'sales_invoices.subtotal'),0);
 const totalCost=(items??[]).reduce((s,i)=>s+required(i.cost_price,'sale_items.cost_price')*required(i.quantity,'sale_items.quantity'),0);
 const grossProfit=totalSales-totalCost; const grossMargin=totalSales>0?(grossProfit/totalSales)*100:0;
 const totalReceivables=inv.reduce((s,i)=>s+required(i.total,'sales_invoices.total')-required(i.paid_amount,'sales_invoices.paid_amount'),0);
 const today=new Date().toISOString().slice(0,10);
 const overdueReceivables=inv.filter(i=>i.due_date&&i.due_date<today&&required(i.paid_amount,'sales_invoices.paid_amount')<required(i.total,'sales_invoices.total')).reduce((s,i)=>s+required(i.total,'sales_invoices.total')-required(i.paid_amount,'sales_invoices.paid_amount'),0);
 const totalPayables=(purchases??[]).reduce((s,p)=>s+required(p.total,'purchase_invoices.total')-required(p.paid_amount,'purchase_invoices.paid_amount'),0);
 const inventoryValue=(balances??[]).reduce((s,b)=>s+required(b.quantity,'inventory_balances.quantity')*required(b.unit_cost,'inventory_balances.unit_cost'),0);
 const invoiceCount=inv.length; const avgInvoiceValue=invoiceCount?totalSales/invoiceCount:0; const totalPaid=inv.reduce((s,i)=>s+required(i.paid_amount,'sales_invoices.paid_amount'),0); const totalInvAmount=inv.reduce((s,i)=>s+required(i.total,'sales_invoices.total'),0); const collectionRate=totalInvAmount>0?(totalPaid/totalInvAmount)*100:0;
 const activeCustomers=new Set(inv.map(i=>i.customer_id).filter((id):id is string=>Boolean(id))).size;
 return {totalSales,totalCost,grossProfit,grossMargin,totalReceivables,overdueReceivables,totalPayables,inventoryValue,totalCustomers:customerCount??0,activeCustomers,totalProducts:productCount??0,invoiceCount,avgInvoiceValue,collectionRate,status:invoiceCount||customerCount||productCount?'CALCULATED':'INSUFFICIENT_DATA'};
}

export async function fetchMonthlyTrend(months=6):Promise<MonthlyTrend[]>{ const {data:invoices,error}=await supabase.from('sales_invoices').select('id,subtotal,invoice_date').order('invoice_date',{ascending:true}); if(error)throw error; const ids=(invoices??[]).map(i=>i.id); const {data:items,error:ee}=ids.length?await supabase.from('sale_items').select('invoice_id,line_total,cost_price,quantity').in('invoice_id',ids):{data:[],error:null}; if(ee)throw ee; const cost=new Map<string,number>(); for(const i of items??[]){const c=required((i as SaleItem).cost_price,'sale_items.cost_price')*required((i as SaleItem).quantity,'sale_items.quantity'); cost.set((i as SaleItem).invoice_id,(cost.get((i as SaleItem).invoice_id)??0)+c);} const by=new Map<string,{sales:number;cost:number;invoices:number}>(); for(const i of invoices??[]){const d=new Date(i.invoice_date); if(Number.isNaN(d.getTime()))throw new Error('REPORT_DATA_UNAVAILABLE: sales_invoices.invoice_date'); const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; const e=by.get(k)??{sales:0,cost:0,invoices:0}; e.sales+=required(i.subtotal,'sales_invoices.subtotal'); e.cost+=cost.get(i.id)??0; e.invoices++; by.set(k,e);} const labels=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر']; const now=new Date(); return Array.from({length:months},(_,n)=>{const d=new Date(now.getFullYear(),now.getMonth()-(months-1-n),1); const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; const e=by.get(k)??{sales:0,cost:0,invoices:0}; return {month:k,label:labels[d.getMonth()],sales:e.sales,cost:e.cost,profit:e.sales-e.cost,invoices:e.invoices};}); }

export async function fetchTopCustomers(limit=5):Promise<TopEntity[]>{const {data,error}=await supabase.from('sales_invoices').select('customer_id,subtotal,customer:customers(name)');if(error)throw error;const by=new Map<string,{name:string;value:number}>();for(const r of data??[]){const c=Array.isArray(r.customer)?r.customer[0]:r.customer;const name=c?.name??'غير معروف';const e=by.get(r.customer_id)??{name,value:0};e.value+=required(r.subtotal,'sales_invoices.subtotal');by.set(r.customer_id,e);}return Array.from(by.entries()).map(([id,v])=>({id,name:v.name,value:v.value})).sort((a,b)=>b.value-a.value).slice(0,limit);}

export async function fetchTopProducts(limit=5):Promise<TopEntity[]>{const {data:invoices,error:ie}=await supabase.from('sales_invoices').select('id');if(ie)throw ie;const ids=(invoices??[]).map(i=>i.id);if(!ids.length)return [];const {data,error}=await supabase.from('sale_items').select('product_id,quantity,line_total,product:products(name)').in('invoice_id',ids).not('product_id','is',null);if(error)throw error;const by=new Map<string,{name:string;value:number;qty:number}>();for(const r of data??[]){if(!r.product_id)continue;const p=Array.isArray(r.product)?r.product[0]:r.product;const e=by.get(r.product_id)??{name:p?.name??'غير معروف',value:0,qty:0};e.value+=required(r.line_total,'sale_items.line_total');e.qty+=required(r.quantity,'sale_items.quantity');by.set(r.product_id,e);}return Array.from(by.entries()).map(([id,v])=>({id,name:v.name,value:v.value,secondary:v.qty})).sort((a,b)=>b.value-a.value).slice(0,limit);}

export async function fetchCategoryBreakdown():Promise<CategoryBreakdown[]>{const {data:invoices,error:ie}=await supabase.from('sales_invoices').select('id');if(ie)throw ie;const ids=(invoices??[]).map(i=>i.id);if(!ids.length)return [];const {data,error}=await supabase.from('sale_items').select('product_id,quantity,line_total,cost_price,product:products(name,category_id,category:categories(name))').in('invoice_id',ids).not('product_id','is',null);if(error)throw error;const by=new Map<string,CategoryBreakdown>();for(const r of data??[]){if(!r.product_id)continue;const p=Array.isArray(r.product)?r.product[0]:r.product;const c=Array.isArray(p?.category)?p.category[0]:p?.category;const id=p?.category_id??'uncategorized';const q=required(r.quantity,'sale_items.quantity');const sales=required(r.line_total,'sale_items.line_total');const cost=required(r.cost_price,'sale_items.cost_price')*q;const e=by.get(id)??{name:c?.name??'غير مصنف',sales:0,profit:0,quantity:0};e.sales+=sales;e.profit+=sales-cost;e.quantity+=q;by.set(id,e);}return Array.from(by.values()).sort((a,b)=>b.sales-a.sales);}

export async function fetchAgingBuckets():Promise<AgingBucket[]>{const {data:invoices,error}=await supabase.from('sales_invoices').select('total,paid_amount,due_date,invoice_date');if(error)throw error;const buckets=[{bucket:'0-30',amount:0,count:0},{bucket:'31-60',amount:0,count:0},{bucket:'61-90',amount:0,count:0},{bucket:'90+',amount:0,count:0}];const today=new Date();for(const i of invoices??[]){const outstanding=required(i.total,'sales_invoices.total')-required(i.paid_amount,'sales_invoices.paid_amount');if(outstanding<=0)continue;const due=new Date(i.due_date??i.invoice_date);if(Number.isNaN(due.getTime()))throw new Error('REPORT_DATA_UNAVAILABLE: invoice date');const days=Math.max(0,Math.floor((today.getTime()-due.getTime())/86400000));const idx=days<=30?0:days<=60?1:days<=90?2:3;buckets[idx].amount+=outstanding;buckets[idx].count++;}return buckets;}
