/** Compatibility boundary only: preserve legacy imports without owning business truth. */
import { supabase, resolveCurrentCompanyId } from './supabase';
import { fetchMonthlyTrend as canonicalFetchMonthlyTrend, fetchTopCustomers as canonicalFetchTopCustomers, fetchTopProducts as canonicalFetchTopProducts, fetchCategoryBreakdown as canonicalFetchCategoryBreakdown, fetchAgingBuckets as canonicalFetchAgingBuckets, fetchForecasts as canonicalFetchForecasts, fetchCustomers as canonicalFetchCustomers, fetchProducts as canonicalFetchProducts } from './queries';
import type { Customer, Forecast, ImportRecord, Product } from './types';
import type { MonthlyTrend, TopEntity, AgingBucket, CategoryBreakdown } from './queries';
export * from './queries';
async function requireTenant(): Promise<string> { const companyId = await resolveCurrentCompanyId(); if (!companyId) throw new Error('TENANT_REQUIRED'); return companyId; }
export async function fetchMonthlyTrend(months = 6): Promise<MonthlyTrend[]> { return canonicalFetchMonthlyTrend(months); }
export async function fetchTopCustomers(limit = 5): Promise<TopEntity[]> { return canonicalFetchTopCustomers(limit); }
export async function fetchTopProducts(limit = 5): Promise<TopEntity[]> { return canonicalFetchTopProducts(limit); }
export async function fetchCategoryBreakdown(): Promise<CategoryBreakdown[]> { return canonicalFetchCategoryBreakdown(); }
export async function fetchAgingBuckets(): Promise<AgingBucket[]> { return canonicalFetchAgingBuckets(); }
export async function fetchForecasts(): Promise<Forecast[]> { return canonicalFetchForecasts(); }
export async function fetchCustomers(): Promise<Customer[]> { return canonicalFetchCustomers(); }
export async function fetchProducts(): Promise<Product[]> { return canonicalFetchProducts(); }
export async function markAlertRead(id: string): Promise<void> { await requireTenant(); const { error } = await supabase.rpc('mark_alert_read', { p_alert_id: id }); if (error) throw error; }
export async function updateRecommendationStatus(id: string, status: string): Promise<void> { await requireTenant(); const { error } = await supabase.rpc('update_recommendation_status', { p_recommendation_id: id, p_status: status }); if (error) throw error; }
type ImportRecordInput = Omit<ImportRecord, 'id' | 'company_id' | 'created_at' | 'error_message' | 'completed_at'>;
type ImportRecordPatch = Partial<Pick<ImportRecord, 'status' | 'progress' | 'error_message' | 'completed_at'>>;
type ImportJobState = { total_rows: number | null; processed_rows: number | null; valid_rows: number | null; invalid_rows: number | null; duplicate_rows: number | null; progress: number | null; result_summary: Record<string, unknown> | null; };
const TERMINAL_IMPORT_STATUSES = new Set(['completed', 'partial', 'failed', 'cancelled']);
async function readImportJob(id: string, companyId: string): Promise<ImportJobState> { const { data, error } = await supabase.from('import_jobs').select('total_rows, processed_rows, valid_rows, invalid_rows, duplicate_rows, quarantined_rows, progress, result_summary').eq('id', id).eq('company_id', companyId).maybeSingle(); if (error) throw error; if (!data) throw new Error('IMPORT_JOB_NOT_FOUND_OR_FORBIDDEN'); return { total_rows: data.total_rows == null ? null : Number(data.total_rows), processed_rows: data.processed_rows == null ? null : Number(data.processed_rows), valid_rows: data.valid_rows == null ? null : Number(data.valid_rows), invalid_rows: data.invalid_rows == null ? null : Number(data.invalid_rows), duplicate_rows: data.duplicate_rows == null ? null : Number(data.duplicate_rows), progress: data.progress == null ? null : Number(data.progress), result_summary: (data.result_summary as Record<string, unknown> | null) ?? null }; }
export async function createImportRecord(input: ImportRecordInput): Promise<ImportRecord> { const companyId = await requireTenant(); if (input.total_rows == null) throw new Error('IMPORT_TOTAL_ROWS_REQUIRED'); const { data, error } = await supabase.rpc('import_create_job', { p_company_id: companyId, p_entity_type: input.entity_type ?? 'import', p_total_rows: input.total_rows }); if (error) throw error; return { id: String(data), company_id: companyId, ...input, error_message: null, created_at: new Date().toISOString(), completed_at: null }; }
export async function updateImportRecord(id: string, patch: ImportRecordPatch): Promise<void> { const companyId = await requireTenant(); const current = await readImportJob(id, companyId); if (patch.progress !== undefined) { if (current.total_rows == null || current.processed_rows == null || current.valid_rows == null || current.invalid_rows == null || current.duplicate_rows == null) throw new Error('IMPORT_STATE_INSUFFICIENT_DATA'); const progress = Math.min(100, Math.max(0, Number(patch.progress))); const processedRows = current.total_rows > 0 ? Math.min(current.total_rows, Math.max(current.processed_rows, Math.round(current.total_rows * progress / 100))) : current.processed_rows; const { error } = await supabase.rpc('import_update_job_progress', { p_job_id: id, p_processed_rows: processedRows, p_valid_rows: current.valid_rows, p_invalid_rows: current.invalid_rows, p_duplicate_rows: current.duplicate_rows, p_status: TERMINAL_IMPORT_STATUSES.has(patch.status ?? '') ? 'processing' : (patch.status ?? 'processing') }); if (error) throw error; } if (patch.status && TERMINAL_IMPORT_STATUSES.has(patch.status)) { const { error } = await supabase.rpc('import_finish_job', { p_job_id: id, p_status: patch.status, p_result_summary: current.result_summary ?? {}, p_error_message: patch.error_message ?? null }); if (error) throw error; } else if (patch.error_message !== undefined && patch.status === undefined) { if (current.processed_rows == null || current.valid_rows == null || current.invalid_rows == null || current.duplicate_rows == null) throw new Error('IMPORT_STATE_INSUFFICIENT_DATA'); const { error } = await supabase.rpc('import_update_job_progress', { p_job_id: id, p_processed_rows: current.processed_rows, p_valid_rows: current.valid_rows, p_invalid_rows: current.invalid_rows, p_duplicate_rows: current.duplicate_rows, p_status: 'processing' }); if (error) throw error; } }
export async function fetchImportRecords(): Promise<ImportRecord[]> { const companyId = await requireTenant(); const { data, error } = await supabase.from('import_jobs').select('id, company_id, job_type, status, total_rows, valid_rows, invalid_rows, quarantined_rows, progress, error_message, created_at, completed_at, result_summary').eq('company_id', companyId).order('created_at', { ascending: false }); if (error) throw error; return (data ?? []).map(row => ({ id: row.id, company_id: row.company_id, file_name: String((row.result_summary as Record<string, unknown> | null)?.file_name ?? row.job_type ?? 'import'), file_size: 0, source_type: 'import', status: row.status, total_rows: row.total_rows == null ? null : Number(row.total_rows), valid_rows: row.valid_rows == null ? null : Number(row.valid_rows), invalid_rows: row.invalid_rows == null ? null : Number(row.invalid_rows), quarantined_rows: row.quarantined_rows == null ? null : Number(row.quarantined_rows), entity_type: row.job_type ?? null, progress: row.progress == null ? null : Number(row.progress), error_message: row.error_message ?? null, created_at: row.created_at, completed_at: row.completed_at ?? null })); }
export interface PurchaseSummary { total: number | null; count: number; supplier_count: number; average: number | null; as_of: string; data_status: 'NO_DATA' | 'CALCULATED'; }
export async function fetchPurchaseSummary(from: string | null = null, to: string | null = null): Promise<PurchaseSummary> { const companyId = await requireTenant(); const { data, error } = await supabase.rpc('get_purchase_summary', { p_company_id: companyId, p_from: from, p_to: to }); if (error) throw error; const row = (data ?? {}) as Record<string, unknown>; return { total: row.total == null ? null : Number(row.total), count: Number(row.count ?? 0), supplier_count: Number(row.supplier_count ?? 0), average: row.average == null ? null : Number(row.average), as_of: String(row.as_of ?? ''), data_status: row.data_status === 'NO_DATA' ? 'NO_DATA' : 'CALCULATED' }; }
export interface InventoryValuation { value: number | null; row_count: number; unknown_row_count: number; data_status: 'NO_DATA' | 'INSUFFICIENT_DATA' | 'CALCULATED'; }
export async function fetchInventoryValuation(): Promise<InventoryValuation> { const companyId = await requireTenant(); const { data, error } = await supabase.rpc('get_inventory_valuation', { p_company_id: companyId }); if (error) throw error; const row = (data ?? {}) as Record<string, unknown>; return { value: row.value == null ? null : Number(row.value), row_count: Number(row.row_count ?? 0), unknown_row_count: Number(row.unknown_row_count ?? 0), data_status: row.data_status === 'INSUFFICIENT_DATA' ? 'INSUFFICIENT_DATA' : row.data_status === 'NO_DATA' ? 'NO_DATA' : 'CALCULATED' }; }
export interface CanonicalExportRow { [key: string]: string | number | null; }
async function canonicalExportRows(functionName: string): Promise<CanonicalExportRow[]> { const companyId = await requireTenant(); const { data, error } = await supabase.rpc(functionName, { p_company_id: companyId, p_max_rows: 10000 }); if (error) throw error; const payload = (data ?? {}) as Record<string, unknown>; if (!Array.isArray(payload.rows)) throw new Error('REPORT_DATA_UNAVAILABLE: canonical export rows missing'); return payload.rows as CanonicalExportRow[]; }
export const fetchSalesExportRows = () => canonicalExportRows('get_sales_export_rows');
export const fetchPurchaseExportRows = () => canonicalExportRows('get_purchase_export_rows');
export const fetchInventoryExportRows = () => canonicalExportRows('get_inventory_export_rows');
export const fetchReceivablesExportRows = () => canonicalExportRows('get_receivables_export_rows');
