export type MetricStatus = 'CONFIRMED' | 'CALCULATED' | 'ESTIMATED' | 'FORECAST' | 'INSUFFICIENT_DATA' | 'UNAVAILABLE';
export type MetricUnit = 'currency' | 'number' | 'percent' | 'days';
export interface MetricDefinition { key:string; label:string; description:string; formula:string; source:string[]; status:MetricStatus; unit:MetricUnit; dimensions?:string[]; dependencies?:string[]; }
export const BUSINESS_METRICS:MetricDefinition[]=[
 {key:'net_sales',label:'صافي المبيعات',description:'قيمة المبيعات من بنود البيع المعتمدة ضمن نفس نطاق الفاتورة.',formula:'SUM(sale_items.line_total)',source:['sales_invoices','sale_items'],status:'CALCULATED',unit:'currency',dimensions:['company','branch','customer','product','category','period'],dependencies:['sales']},
 {key:'gross_profit',label:'مجمل الربح',description:'إيراد بنود البيع ناقص تكلفة البضاعة المباعة لنفس البنود.',formula:'SUM(sale_items.line_total - sale_items.cost_price * sale_items.quantity)',source:['sales_invoices','sale_items'],status:'CALCULATED',unit:'currency',dimensions:['company','branch','product','category','period'],dependencies:['sales','pricing']},
 {key:'receivables',label:'الذمم المدينة',description:'المبالغ المستحقة غير المحصلة من العملاء.',formula:'SUM(invoice.total - invoice.paid_amount)',source:['sales_invoices'],status:'CALCULATED',unit:'currency',dimensions:['company','customer','period'],dependencies:['sales','customer','payments']},
 {key:'payables',label:'التزامات الموردين',description:'المبالغ المستحقة غير المدفوعة للموردين.',formula:'SUM(purchase.total - purchase.paid_amount)',source:['purchase_invoices'],status:'CALCULATED',unit:'currency',dimensions:['company','supplier','period'],dependencies:['purchasing','payments']},
 {key:'inventory_value',label:'قيمة المخزون',description:'قيمة الرصيد الحالي وفق تكلفة الوحدة.',formula:'SUM(inventory_balances.quantity * inventory_balances.unit_cost)',source:['inventory_balances'],status:'CALCULATED',unit:'currency',dimensions:['company','warehouse','product','category'],dependencies:['inventory']},
 {key:'inventory_velocity',label:'سرعة دوران الصنف',description:'متوسط السحب اليومي خلال نافذة التحليل.',formula:'SUM(sold_quantity) / analysis_days',source:['sales_invoices','sale_items'],status:'CALCULATED',unit:'number',dimensions:['company','product','category','period'],dependencies:['sales','demand']},
 {key:'stock_coverage',label:'تغطية المخزون',description:'عدد الأيام التي يغطيها الرصيد وفق الطلب اليومي الموزون.',formula:'normalized_stock / weighted_daily_demand',source:['inventory_balances','sale_items'],status:'FORECAST',unit:'days',dimensions:['company','product','alternative_group','warehouse'],dependencies:['inventory','sales','demand','alternative-group']},
 {key:'stockout_risk',label:'مخاطر نفاد المخزون',description:'نسبة خطر بين 0 و100 مبنية على تغطية المخزون مقابل زمن التوريد ومخزون الأمان.',formula:'MIN(100, MAX(0, 100 * (lead_time + safety_days - coverage_days) / MAX(1, lead_time + safety_days)))',source:['inventory_balances','sale_items','products'],status:'CALCULATED',unit:'percent',dimensions:['company','product','alternative_group'],dependencies:['inventory','demand','alternative-group']},
 {key:'alternative_group_demand',label:'طلب المجموعة البديلة',description:'الطلب الموحد للأصناف البديلة بعد تحويلها إلى وحدة قياس مشتركة.',formula:'SUM(member_daily_demand * conversion_factor)',source:['sale_items','alternative_group_members'],status:'CALCULATED',unit:'number',dimensions:['company','alternative_group','period'],dependencies:['sales','alternative-group']},
 {key:'alternative_group_stock',label:'رصيد المجموعة البديلة',description:'الرصيد الموحد للأصناف البديلة بعد تطبيق معاملات التحويل.',formula:'SUM(member_stock * conversion_factor)',source:['inventory_balances','alternative_group_members'],status:'CALCULATED',unit:'number',dimensions:['company','alternative_group','warehouse'],dependencies:['inventory','alternative-group']},
 {key:'lost_sales_estimate',label:'المبيعات المفقودة التقديرية',description:'طلب غير مخدوم بسبب عدم توفر الرصيد مع مراعاة البدائل عند تفعيل التجميع.',formula:'MAX(0, requested_quantity - available_group_stock)',source:['orders','inventory_balances','alternative_group_members'],status:'ESTIMATED',unit:'number',dimensions:['company','product','alternative_group','period'],dependencies:['demand','inventory','alternative-group']},
 {key:'liquidity_inventory_release',label:'سيولة قابلة للتحرير من المخزون',description:'قيمة المخزون الراكد أو بطيء الحركة المرشحة للتصريف دون المساس بمخزون الخدمة.',formula:'eligible_slow_stock * unit_cost',source:['inventory_balances','sale_items'],status:'ESTIMATED',unit:'currency',dimensions:['company','product','category'],dependencies:['inventory','demand','sales']},
 {key:'customer_activity',label:'نشاط العملاء',description:'مؤشر مركب من حداثة وتكرار وقيمة المشتريات.',formula:'RFM-derived activity score',source:['sales_invoices'],status:'CALCULATED',unit:'percent',dimensions:['company','customer','period'],dependencies:['sales','customer']},
 {key:'cash_position',label:'المركز النقدي',description:'صافي التدفقات النقدية المسجلة ضمن نطاق التحليل.',formula:'SUM(inflows) - SUM(outflows)',source:['payments'],status:'CALCULATED',unit:'currency',dimensions:['company','period'],dependencies:['payments']},
];
export function getMetricDefinition(key:string){return BUSINESS_METRICS.find(metric=>metric.key===key);} export function getMetricsByDependency(dependency:string){return BUSINESS_METRICS.filter(metric=>metric.dependencies?.includes(dependency));} export function metricStatusLabel(status:MetricStatus){return ({CONFIRMED:'مؤكد',CALCULATED:'محسوب',ESTIMATED:'تقديري',FORECAST:'تنبؤي',INSUFFICIENT_DATA:'بيانات غير كافية',UNAVAILABLE:'غير متوفر'} as Record<MetricStatus,string>)[status];} export function freshnessLabel(updatedAt?:string|null){if(!updatedAt)return{label:'غير متوفر',tone:'neutral' as const};const parsed=Date.parse(updatedAt);if(!Number.isFinite(parsed))return{label:'غير متوفر',tone:'neutral' as const};const ageMinutes=Math.max(0,(Date.now()-parsed)/60000);if(ageMinutes<=15)return{label:'محدث الآن',tone:'good' as const};if(ageMinutes<=120)return{label:`محدث منذ ${Math.round(ageMinutes)} دقيقة`,tone:'good' as const};if(ageMinutes<=1440)return{label:`محدث منذ ${Math.round(ageMinutes/60)} ساعة`,tone:'warning' as const};return{label:'بيانات قديمة',tone:'danger' as const};}
