export const specialtyLabel = (specialty: string | null | undefined): string => ({
  sales: 'المبيعات',
  purchases: 'المشتريات',
  inventory: 'المخزون',
  customers: 'العملاء',
  suppliers: 'الموردون',
  products: 'المنتجات',
  payments: 'المدفوعات',
  receivables: 'الذمم المدينة / أعمار الديون',
  other: 'مصدر عام',
}[String(specialty ?? '').toLowerCase()] ?? 'غير محدد');

export const entityLabel = (entityType: string | null | undefined): string => ({
  products: 'الأصناف والمنتجات',
  customers: 'العملاء',
  sales_invoices: 'فواتير المبيعات',
  purchase_invoices: 'فواتير المشتريات',
  suppliers: 'الموردون',
  inventory_balances: 'أرصدة المخزون',
  payments: 'المدفوعات',
  receivables: 'الذمم المدينة / أعمار الديون',
  'generic:sales': 'سجل مبيعات عام',
  'generic:purchases': 'سجل مشتريات عام',
  'generic:inventory': 'سجل مخزون عام',
  'generic:customers': 'سجل عملاء عام',
  'generic:suppliers': 'سجل موردين عام',
  'generic:products': 'سجل منتجات عام',
  'generic:payments': 'سجل مدفوعات عام',
  'generic:receivables': 'سجل ذمم عامة',
  'generic:source-data': 'سجل مصدر عام',
}[String(entityType ?? '').toLowerCase()] ?? 'غير محدد');