import type { InventoryDecision } from './inventoryEngine';
import type { AlternativeGroupDecision } from './groupDemand';

export interface DecisionEvidence { metric:string; value:number; unit?:string; source:string; period?:string; }
export interface Decision { id:string; severity:'critical'|'high'|'medium'|'low'; title:string; action:string; confidence:number; evidence:DecisionEvidence[]; }

export function inventoryDecisions(items:InventoryDecision[]):Decision[]{return items.flatMap(item=>{
 if(item.priority==='critical')return[{id:`inventory:${item.sku}`,severity:'critical',title:`إعادة طلب عاجلة للصنف ${item.sku}`,action:`اطلب ${item.recommendedOrder} وحدة قبل نفاد المخزون المتوقع في ${item.stockoutDate??'غير محدد'}.`,confidence:0.98,evidence:[{metric:'days_of_cover',value:item.daysOfCover,unit:'days',source:'inventory_engine'},{metric:'reorder_point',value:item.reorderPoint,unit:'units',source:'inventory_engine'},{metric:'recommended_order',value:item.recommendedOrder,unit:'units',source:'inventory_engine'}]}];
 if(item.classification==='frozen')return[{id:`liquidity:${item.sku}`,severity:'medium',title:`مخزون راكد يحتاج خطة تصريف ${item.sku}`,action:'راجع السعر، الحزمة، القناة البيعية أو العرض الترويجي قبل شراء كمية إضافية.',confidence:0.92,evidence:[{metric:'days_of_cover',value:item.daysOfCover,unit:'days',source:'inventory_engine'}]}];return[];});}

export function alternativeGroupDecisions(groups:AlternativeGroupDecision[]):Decision[]{return groups.flatMap(group=>{
 if(group.stockoutRisk==='critical')return[{id:`alternative-group:${group.id}`,severity:'critical',title:`خطر نفاد على مستوى المجموعة ${group.name}`,action:`اطلب ما يقارب ${group.recommendedOrder} وحدة قياسية للمجموعة، مع فحص توفر البدائل قبل اعتماد الطلب.`,confidence:0.97,evidence:[{metric:'group_stock',value:group.normalizedStock,unit:'units',source:'alternative_group_engine'},{metric:'group_daily_demand',value:group.normalizedDemand,unit:'units/day',source:'alternative_group_engine'},{metric:'group_coverage',value:group.coverageDays??0,unit:'days',source:'alternative_group_engine'}]}];
 if(group.stockoutRisk==='high')return[{id:`alternative-group:${group.id}`,severity:'high',title:`تغطية المجموعة ${group.name} تقترب من الخطر`,action:'راجع التوريد والبدائل داخل المجموعة قبل وصول الرصيد إلى نقطة الخطر.',confidence:0.94,evidence:[{metric:'group_coverage',value:group.coverageDays??0,unit:'days',source:'alternative_group_engine'},{metric:'trend_pct',value:group.trendPct,unit:'percent',source:'alternative_group_engine'}]}];
 if(group.trendPct>15)return[{id:`alternative-group-trend:${group.id}`,severity:'medium',title:`تسارع الطلب على ${group.name}`,action:'ارفع أولوية المراقبة والشراء مؤقتًا لأن حركة المجموعة تتسارع.',confidence:0.88,evidence:[{metric:'trend_pct',value:group.trendPct,unit:'percent',source:'alternative_group_engine'}]}];return[];});}
