ALTER TABLE public.metric_governance ADD COLUMN IF NOT EXISTS company_id uuid;
ALTER TABLE public.metric_governance_audit ADD COLUMN IF NOT EXISTS company_id uuid;
DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname='metric_governance_metric_id_version_key' AND conrelid='public.metric_governance'::regclass) THEN ALTER TABLE public.metric_governance DROP CONSTRAINT metric_governance_metric_id_version_key; END IF; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS uq_metric_governance_company_metric_version ON public.metric_governance(company_id, metric_id, version);
CREATE INDEX IF NOT EXISTS idx_metric_governance_company_metric_version ON public.metric_governance(company_id, metric_id, version DESC);
CREATE INDEX IF NOT EXISTS idx_metric_governance_audit_company_metric ON public.metric_governance_audit(company_id, metric_id, created_at DESC);
ALTER TABLE public.metric_governance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metric_governance_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.metric_governance FROM anon;
REVOKE ALL ON public.metric_governance_audit FROM anon;
GRANT SELECT ON public.metric_governance TO authenticated;
GRANT SELECT ON public.metric_governance_audit TO authenticated;
DROP POLICY IF EXISTS metric_governance_authenticated_tenant_read ON public.metric_governance;
CREATE POLICY metric_governance_authenticated_tenant_read ON public.metric_governance FOR SELECT TO authenticated USING (company_id = public.current_company_id());
DROP POLICY IF EXISTS metric_governance_audit_authenticated_tenant_read ON public.metric_governance_audit;
CREATE POLICY metric_governance_audit_authenticated_tenant_read ON public.metric_governance_audit FOR SELECT TO authenticated USING (company_id = public.current_company_id());
CREATE OR REPLACE FUNCTION public.metric_governance_require_tenant() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$ BEGIN IF NEW.company_id IS NULL THEN NEW.company_id=public.current_company_id(); END IF; IF NEW.company_id IS NULL THEN RAISE EXCEPTION 'metric governance tenant context required'; END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS metric_governance_require_tenant ON public.metric_governance;
CREATE TRIGGER metric_governance_require_tenant BEFORE INSERT ON public.metric_governance FOR EACH ROW EXECUTE FUNCTION public.metric_governance_require_tenant();
CREATE OR REPLACE FUNCTION public.metric_governance_audit_require_tenant() RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$ BEGIN IF NEW.company_id IS NULL THEN NEW.company_id=public.current_company_id(); END IF; IF NEW.company_id IS NULL THEN RAISE EXCEPTION 'metric governance audit tenant context required'; END IF; RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS metric_governance_audit_require_tenant ON public.metric_governance_audit;
CREATE TRIGGER metric_governance_audit_require_tenant BEFORE INSERT ON public.metric_governance_audit FOR EACH ROW EXECUTE FUNCTION public.metric_governance_audit_require_tenant();
