-- Dashboard Truth semantic boundary. Display layers must not manufacture zeroes or labels for missing facts.
CREATE OR REPLACE FUNCTION public.get_dashboard_snapshot(p_months integer DEFAULT 6,p_as_of date DEFAULT CURRENT_DATE)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY INVOKER AS $$
DECLARE v_company_id uuid:=public.current_company_id(); v_months integer:=LEAST(GREATEST(COALESCE(p_months,6),1),24); v_result jsonb;
BEGIN
 IF v_company_id IS NULL THEN RAISE EXCEPTION 'TENANT_CONTEXT_REQUIRED'; END IF;
 WITH sales_base AS (SELECT s.* FROM public.sales_invoices s WHERE s.company_id=v_company_id AND s.status IS NOT NULL AND s.status NOT IN ('cancelled','void') AND s.invoice_date<=p_as_of),
 items AS (SELECT si.* FROM public.sale_items si JOIN sales_base s ON s.id=si.invoice_id),
 purchases AS (SELECT p.* FROM public.purchase_invoices p WHERE p.company_id=v_company_id AND p.status IS NOT NULL AND p.status NOT IN ('cancelled','void') AND p.invoice_date<=p_as_of),
 inventory AS (SELECT * FROM public.inventory_balances WHERE company_id=v_company_id),
 q AS (SELECT (SELECT count(*) FROM sales_base WHERE subtotal IS NULL OR total IS NULL OR paid_amount IS NULL) bi,(SELECT count(*) FROM items WHERE quantity IS NULL OR cost_price IS NULL OR line_total IS NULL) bs,(SELECT count(*) FROM purchases WHERE total IS NULL OR paid_amount IS NULL) bp,(SELECT count(*) FROM inventory WHERE quantity IS NULL OR unit_cost IS NULL) bv),
 k AS (SELECT CASE WHEN q.bi=0 THEN (SELECT sum(subtotal) FROM sales_base) END sales,CASE WHEN q.bs=0 THEN (SELECT sum(quantity*cost_price) FROM items) END cost,CASE WHEN q.bi=0 THEN (SELECT sum(total-paid_amount) FROM sales_base) END recv,CASE WHEN q.bi=0 THEN (SELECT sum(CASE WHEN due_date IS NOT NULL AND due_date<p_as_of AND paid_amount<total THEN total-paid_amount ELSE 0 END) FROM sales_base) END overdue,CASE WHEN q.bp=0 THEN (SELECT sum(total-paid_amount) FROM purchases) END payables,CASE WHEN q.bv=0 THEN (SELECT sum(quantity*unit_cost) FROM inventory) END inv,(SELECT count(*) FROM sales_base) invoices,q.* FROM q),
 trend AS (SELECT COALESCE(jsonb_agg(jsonb_build_object('month',to_char(m,'YYYY-MM'),'label',to_char(m,'Mon'),'sales',x.sales,'cost',x.cost,'profit',CASE WHEN x.sales IS NOT NULL AND x.cost IS NOT NULL THEN x.sales-x.cost END,'invoices',x.invoices,'status',x.status) ORDER BY m),'[]'::jsonb) rows FROM generate_series(date_trunc('month',p_as_of::timestamp)-((v_months-1)*interval '1 month'),date_trunc('month',p_as_of::timestamp),interval '1 month') m LEFT JOIN LATERAL (SELECT sum(s.subtotal) sales,sum(i.quantity*i.cost_price) cost,count(DISTINCT s.id) invoices,CASE WHEN count(DISTINCT s.id)=0 THEN 'NO_DATA' WHEN bool_or(s.subtotal IS NULL OR s.total IS NULL OR s.paid_amount IS NULL OR i.quantity IS NULL OR i.cost_price IS NULL OR i.line_total IS NULL) THEN 'INSUFFICIENT_DATA' ELSE 'CALCULATED' END status FROM sales_base s LEFT JOIN items i ON i.invoice_id=s.id WHERE s.invoice_date>=m::date AND s.invoice_date<(m+interval '1 month')::date) x ON true),
 categories AS (SELECT COALESCE(jsonb_agg(jsonb_build_object('name',c.name,'categoryStatus',CASE WHEN z.category_id IS NULL THEN 'UNKNOWN' ELSE 'CALCULATED' END,'sales',z.sales,'profit',z.profit,'quantity',z.quantity) ORDER BY z.sales DESC),'[]'::jsonb) rows FROM (SELECT p.category_id,sum(i.line_total) sales,sum(i.line_total-(i.cost_price*i.quantity)) profit,sum(i.quantity) quantity FROM items i LEFT JOIN public.products p ON p.id=i.product_id AND p.company_id=v_company_id WHERE i.line_total IS NOT NULL AND i.cost_price IS NOT NULL AND i.quantity IS NOT NULL GROUP BY p.category_id) z LEFT JOIN public.categories c ON c.id=z.category_id AND c.company_id=v_company_id),
 aging_base AS (SELECT due_date,total-paid_amount outstanding,CASE WHEN due_date IS NULL THEN NULL ELSE GREATEST(0,p_as_of-due_date) END age_days FROM sales_base WHERE total IS NOT NULL AND paid_amount IS NOT NULL AND total-paid_amount>0),
 aging AS (SELECT jsonb_build_object('status',CASE WHEN count(*)=0 THEN 'NO_DATA' ELSE 'CALCULATED' END,'unknownRows',count(*) FILTER(WHERE due_date IS NULL),'totalAmount',sum(outstanding),'rows',jsonb_build_array(jsonb_build_object('bucket','0-30','amount',sum(outstanding) FILTER(WHERE age_days BETWEEN 0 AND 30),'count',count(*) FILTER(WHERE age_days BETWEEN 0 AND 30)),jsonb_build_object('bucket','31-60','amount',sum(outstanding) FILTER(WHERE age_days BETWEEN 31 AND 60),'count',count(*) FILTER(WHERE age_days BETWEEN 31 AND 60)),jsonb_build_object('bucket','61-90','amount',sum(outstanding) FILTER(WHERE age_days BETWEEN 61 AND 90),'count',count(*) FILTER(WHERE age_days BETWEEN 61 AND 90)),jsonb_build_object('bucket','90+','amount',sum(outstanding) FILTER(WHERE age_days>90),'count',count(*) FILTER(WHERE age_days>90)),jsonb_build_object('bucket','UNKNOWN','amount',sum(outstanding) FILTER(WHERE due_date IS NULL),'count',count(*) FILTER(WHERE due_date IS NULL)))) value FROM aging_base),
 counts AS (SELECT (SELECT count(*) FROM public.customers WHERE company_id=v_company_id) customers,(SELECT count(*) FROM public.products WHERE company_id=v_company_id) products)
 SELECT jsonb_build_object('status',CASE WHEN k.bi=0 AND k.bs=0 AND k.bp=0 AND k.bv=0 AND (k.invoices>0 OR k.cost IS NOT NULL OR k.inv IS NOT NULL) THEN 'CALCULATED' ELSE 'INSUFFICIENT_DATA' END,'totalSales',k.sales,'totalCost',k.cost,'grossProfit',CASE WHEN k.sales IS NOT NULL AND k.cost IS NOT NULL THEN k.sales-k.cost END,'grossMargin',CASE WHEN k.sales IS NOT NULL AND k.cost IS NOT NULL AND k.sales<>0 THEN ((k.sales-k.cost)/k.sales)*100 END,'totalReceivables',k.recv,'overdueReceivables',k.overdue,'totalPayables',k.payables,'inventoryValue',k.inv,'totalCustomers',counts.customers,'activeCustomers',NULL,'totalProducts',counts.products,'invoiceCount',k.invoices,'avgInvoiceValue',CASE WHEN k.invoices>0 AND k.sales IS NOT NULL THEN k.sales/k.invoices END,'collectionRate',CASE WHEN k.sales IS NOT NULL AND k.invoices>0 AND (SELECT sum(total) FROM sales_base)<>0 THEN ((SELECT sum(paid_amount) FROM sales_base)/(SELECT sum(total) FROM sales_base))*100 END,'trend',(SELECT rows FROM trend),'topCustomers','[]'::jsonb,'topProducts','[]'::jsonb,'categories',(SELECT rows FROM categories),'aging',(SELECT value FROM aging),'asOf',p_as_of,'months',v_months,'quality',jsonb_build_object('badInvoiceRows',k.bi,'badSaleItemRows',k.bs,'badPurchaseRows',k.bp,'badInventoryRows',k.bv)) INTO v_result FROM k CROSS JOIN counts;
 RETURN v_result;
END; $$;
REVOKE ALL ON FUNCTION public.get_dashboard_snapshot(integer,date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_dashboard_snapshot(integer,date) TO authenticated;
