export type CanonicalField='productCode'|'productName'|'category'|'brand'|'unit'|'warehouse'|'fromWarehouse'|'toWarehouse'|'openingBalance'|'openingStock'|'inbound'|'outbound'|'salesQty'|'purchaseQty'|'currentStock'|'adjustmentQty'|'returnQty'|'requestedQty'|'fulfilledQty'|'orderedQty'|'receivedQty'|'customerCode'|'customerName'|'supplierCode'|'supplierName'|'salesRep'|'documentNo'|'documentDate'|'transactionType'|'accountCode'|'accountName'|'quantity'|'unitPrice'|'sellingPrice'|'grossAmount'|'discount'|'netAmount'|'cost'|'profit'|'currency'|'paymentMethod'|'paymentTerms'|'paidAmount'|'targetAmount'|'dueDate'|'leadTimeDays'|'debit'|'credit'|'asset'|'liability'|'equity';
export interface FieldDefinition{field:CanonicalField;aliases:string[];requiredFor?:string[];type:'text'|'number'|'date'|'currency';}
const definitions:FieldDefinition[]=[
{field:'productCode',aliases:['رقم الصنف','كود الصنف','رمز الصنف','كود المنتج','رقم المنتج','الصنف','Item Code','Product Code','SKU'],type:'text'},
{field:'productName',aliases:['اسم الصنف','اسم المنتج','بيان الصنف','اسم المادة','Item Name','Product Name','Description'],type:'text'},
{field:'category',aliases:['الفئة','التصنيف','القسم','Category','Department'],type:'text'},
{field:'brand',aliases:['العلامة','الماركة','Brand'],type:'text'},
{field:'unit',aliases:['الوحدة','وحدة القياس','Unit','UOM'],type:'text'},
{field:'warehouse',aliases:['المخزن','المستودع','المستودع الرئيسي','Warehouse','Store'],type:'text'},
{field:'fromWarehouse',aliases:['من المخزن','المخزن المصدر','From Warehouse','Source Warehouse'],type:'text'},
{field:'toWarehouse',aliases:['إلى المخزن','المخزن الوجهة','To Warehouse','Destination Warehouse'],type:'text'},
{field:'openingBalance',aliases:['الرصيد الافتتاحي','رصيد أول المدة','Opening Balance'],type:'number'},
{field:'openingStock',aliases:['المخزون الافتتاحي','رصيد المخزون أول المدة','Opening Stock'],type:'number'},
{field:'inbound',aliases:['الوارد','إجمالي الوارد','كمية الوارد','Inbound','Received Qty'],type:'number'},
{field:'outbound',aliases:['الصادر','إجمالي الصادر','كمية الصادر','Outbound','Issued Qty'],type:'number'},
{field:'salesQty',aliases:['الكمية المباعة','كمية المبيعات','صافي المبيعات كمية','Sales Qty','Sold Qty'],type:'number'},
{field:'adjustmentQty',aliases:['كمية التسوية','تسويات الكمية','Adjustment Qty'],type:'number'},
{field:'returnQty',aliases:['كمية المرتجع','المرتجعات كمية','Return Qty','Returned Qty'],type:'number'},
{field:'requestedQty',aliases:['الكمية المطلوبة','الطلب الكمي','Requested Qty'],type:'number'},
{field:'fulfilledQty',aliases:['الكمية المنفذة','المحققة','Fulfilled Qty'],type:'number'},
{field:'orderedQty',aliases:['الكمية المطلوبة للشراء','كمية الطلب','Ordered Qty'],type:'number'},
{field:'receivedQty',aliases:['الكمية المستلمة','الوارد المستلم','Received Qty'],type:'number'},
{field:'purchaseQty',aliases:['كمية المشتريات','المشتريات كمية','Purchase Qty'],type:'number'},
{field:'currentStock',aliases:['الرصيد الحالي','الرصيد','الكمية المتوفرة','الكمية المتاحة','المخزون الحالي','Current Stock','Balance','On Hand'],type:'number'},
{field:'customerCode',aliases:['رقم العميل','كود العميل','رمز العميل','Customer Code'],type:'text'},
{field:'customerName',aliases:['اسم العميل','اسم الزبون','العميل','Customer Name','Customer'],type:'text'},
{field:'supplierCode',aliases:['رقم المورد','كود المورد','رمز المورد','Supplier Code'],type:'text'},
{field:'supplierName',aliases:['اسم المورد','المورد','Supplier Name','Supplier'],type:'text'},
{field:'salesRep',aliases:['المندوب','مندوب المبيعات','Sales Rep','Sales Representative','Representative'],type:'text'},
{field:'documentNo',aliases:['رقم الفاتورة','رقم المستند','رقم السند','رقم الحركة','Document No','Invoice No'],type:'text'},
{field:'documentDate',aliases:['التاريخ','تاريخ الفاتورة','تاريخ المستند','تاريخ الحركة','Document Date','Invoice Date','Date'],type:'date'},
{field:'transactionType',aliases:['نوع الحركة','نوع المعاملة','Transaction Type','Movement Type'],type:'text'},
{field:'accountCode',aliases:['كود الحساب','رقم الحساب','Account Code','GL Code'],type:'text'},
{field:'accountName',aliases:['اسم الحساب','الحساب','Account Name','GL Account'],type:'text'},
{field:'quantity',aliases:['الكمية','كمية','Quantity','Qty'],type:'number'},
{field:'unitPrice',aliases:['السعر','سعر الوحدة','سعر البيع','سعر الشراء','Unit Price','Price'],type:'currency'},
{field:'sellingPrice',aliases:['سعر البيع','السعر البيعي','Selling Price','Sales Price'],type:'currency'},
{field:'grossAmount',aliases:['الإجمالي','إجمالي القيمة','المبلغ الإجمالي','Gross Amount','Total'],type:'currency'},
{field:'discount',aliases:['الخصم','قيمة الخصم','Discount'],type:'currency'},
{field:'netAmount',aliases:['صافي المبيعات','الصافي','صافي القيمة','المبلغ الصافي','Net Amount','Net Sales'],type:'currency'},
{field:'cost',aliases:['التكلفة','تكلفة المبيعات','متوسط التكلفة','Cost','Cost of Sales','Average Cost'],type:'currency'},
{field:'profit',aliases:['الربح','إجمالي الربح','الربح الإجمالي','Profit','Gross Profit'],type:'currency'},
{field:'currency',aliases:['العملة','Currency'],type:'text'},
{field:'paymentMethod',aliases:['طريقة الدفع','وسيلة الدفع','Payment Method','Pay Method'],type:'text'},
{field:'paymentTerms',aliases:['شروط الدفع','آجال الدفع','Payment Terms','Terms'],type:'text'},
{field:'paidAmount',aliases:['المبلغ المدفوع','المدفوع','Paid Amount','Paid'],type:'currency'},
{field:'targetAmount',aliases:['المستهدف','الهدف','قيمة الهدف','Target Amount','Target'],type:'currency'},
{field:'dueDate',aliases:['تاريخ الاستحقاق','الاستحقاق','Due Date'],type:'date'},
{field:'leadTimeDays',aliases:['مدة التوريد','مدة التوصيل','Lead Time','Lead Time Days'],type:'number'},
{field:'debit',aliases:['مدين','المدين','Debit'],type:'currency'},
{field:'credit',aliases:['دائن','الدائن','Credit'],type:'currency'},
{field:'asset',aliases:['الأصول','أصول','Asset'],type:'currency'},
{field:'liability',aliases:['الخصوم','الالتزامات','Liability'],type:'currency'},
{field:'equity',aliases:['حقوق الملكية','الملكية','Equity'],type:'currency'}];
export function getCanonicalFieldDefinitions(){return definitions;}
function norm(v:string){return v.trim().toLowerCase().replace(/[إأآ]/g,'ا').replace(/[ة]/g,'ه').replace(/[ًٌٍَُِّْ]/g,'').replace(/[\s_\-./]+/g,'');}
export function matchCanonicalField(header:string){const h=norm(header);for(const d of definitions){if(d.aliases.some(a=>norm(a)===h))return d.field;}return undefined;}
