import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { assertCanonicalBoundary } from "./pkg_lib_import_canonical-truth-boundary.ts";
import { runCanonicalImportThroughDurableRunner } from "./pkg_lib_import_canonical-production-adapter.ts";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")??"";
const json=(status:number,body:Record<string,unknown>)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
const bearer=(req:Request)=>{const a=req.headers.get("authorization")??"";if(!/^Bearer\s+\S+$/i.test(a))throw new Error("AUTHENTICATED_USER_REQUIRED");return a;};
const sha256=async(b:Uint8Array)=>{const d=new Uint8Array(await crypto.subtle.digest("SHA-256",b));return Array.from(d,x=>x.toString(16).padStart(2,"0")).join("")};
Deno.serve(async(req)=>{if(req.method!=="POST")return json(405,{error:"METHOD_NOT_ALLOWED"});try{
const authorization=bearer(req);if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error("EDGE_WORKER_ENV_MISSING");
const caller=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:authorization}}});
const {data:user,error:userError}=await caller.auth.getUser();if(userError||!user?.user?.id)throw new Error("AUTHENTICATED_USER_REQUIRED");
const p:any=await req.json();
if(!p.companyId||typeof p.companyId!=="string")throw new Error("TENANT_CONTEXT_REQUIRED");
const companyId=String(p.companyId);
if(!/^[0-9a-fA-F-]{36}$/.test(companyId))throw new Error("TENANT_CONTEXT_INVALID");
const service=createClient(SUPABASE_URL,SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const {data:membership,error:membershipError}=await service.from("company_memberships").select("company_id").eq("user_id",user.user.id).eq("company_id",companyId).eq("is_active",true).maybeSingle();
if(membershipError)throw membershipError;
if(!membership?.company_id)throw new Error("TENANT_CONTEXT_REQUIRED");
if(!p.importId||!p.fileName||!p.sourceHash||!p.entityType||!Array.isArray(p.rows)||!Number.isFinite(p.qualityScore)||typeof p.qualityApproved!=="boolean")throw new Error("CANONICAL_IMPORT_WORKER_REQUEST_INVALID");
const {data:job,error:jobError}=await service.from("import_jobs").select("id,company_id,file_record_id,job_type").eq("id",p.importId).eq("company_id",companyId).maybeSingle();if(jobError)throw jobError;
if(!job?.file_record_id)throw new Error("IMPORT_JOB_SOURCE_RECORD_NOT_FOUND_OR_FORBIDDEN");if(job.job_type!==p.entityType)throw new Error("IMPORT_JOB_ENTITY_TYPE_MISMATCH");
const {data:fileRecord,error:fileError}=await service.from("file_records").select("id,file_name,file_mime,metadata").eq("id",job.file_record_id).eq("company_id",companyId).maybeSingle();if(fileError)throw fileError;if(!fileRecord)throw new Error("IMPORT_JOB_SOURCE_RECORD_NOT_FOUND_OR_FORBIDDEN");
const metadata=(fileRecord.metadata&&typeof fileRecord.metadata==="object"?fileRecord.metadata:{}) as Record<string,unknown>;const bucket=String(metadata.storage_bucket??p.sourceStorageBucket??"documents");const storagePath=String(metadata.storage_path??p.sourceStoragePath??"");
if(bucket!=="documents"||!storagePath||!storagePath.startsWith(String(companyId)+"/imports/"))throw new Error("AUTHORITATIVE_SOURCE_STORAGE_BINDING_INVALID");
const {data:blob,error:downloadError}=await service.storage.from(bucket).download(storagePath);if(downloadError||!blob)throw new Error("AUTHORITATIVE_SOURCE_DOWNLOAD_FAILED");
const actualHash="sha256:"+await sha256(new Uint8Array(await blob.arrayBuffer()));if(actualHash!==p.sourceHash)throw new Error("AUTHORITATIVE_SOURCE_HASH_MISMATCH");
for(const row of p.rows)assertCanonicalBoundary(row,String(companyId));if(p.rows.some((row:any)=>row.provenance.sourceHash!==p.sourceHash))throw new Error("CANONICAL_SOURCE_HASH_MISMATCH");
const execution=await runCanonicalImportThroughDurableRunner({importId:p.importId,fileName:fileRecord.file_name??p.fileName,sourceHash:p.sourceHash,entityType:p.entityType,rows:p.rows,qualityScore:p.qualityScore,qualityApproved:p.qualityApproved},{serverExecution:true,workerClient:service,dataClient:caller,companyId:String(companyId),requestedBy:user.user.id});
const verifiedMetadata={...metadata,storage_bucket:bucket,storage_path:storagePath,raw_bytes_sha256:p.sourceHash,server_verified_at:new Date().toISOString(),server_verified_by:user.user.id,detected_format:p.sourceFormat??metadata.detected_format};
const {error:updateFileError}=await service.from("file_records").update({file_hash:p.sourceHash,security_status:"passed",status:"ready",metadata:verifiedMetadata}).eq("id",fileRecord.id).eq("company_id",companyId);if(updateFileError)throw updateFileError;
let snapshotId:string|null=null;const {data:snapshot,error:snapshotError}=await service.from("source_analysis_snapshots").insert({company_id:companyId,import_job_id:job.id,source_hash:p.sourceHash,source_path:storagePath,source_format:p.sourceFormat??metadata.detected_format??"unknown",analysis_status:"analyzed",entity_type:"source-data",quality_score:p.qualityScore,row_count:p.rows.length,column_count:Array.isArray(p.authoritativeColumns)?p.authoritativeColumns.length:0,datasets:[{name:fileRecord.file_name??p.fileName,rowCount:p.rows.length,columnCount:Array.isArray(p.authoritativeColumns)?p.authoritativeColumns.length:0,columns:p.authoritativeColumns??[],preview:p.authoritativePreview??[]}],canonical_text:["source="+(fileRecord.file_name??p.fileName),"server_authoritative_quality="+p.qualityScore+"%","source_sha="+p.sourceHash].join(" | "),visual_assets:[],warnings:[],metadata:{fileName:fileRecord.file_name??p.fileName,sourceFormat:p.sourceFormat??metadata.detected_format??"unknown",serverAuthoritativeSource:true,serverAuthoritativeQualityScore:p.qualityScore,committed:p.rows.length,jobId:execution.jobId,sourceStoragePath:storagePath}}).select("id").single();if(!snapshotError)snapshotId=snapshot?.id??null;
return json(200,{...execution,importId:job.id,sourceHash:p.sourceHash,snapshotId,authoritativeRowCount:p.rows.length,authoritativeQualityScore:p.qualityScore,authoritativeColumns:p.authoritativeColumns??[],authoritativePreview:p.authoritativePreview??[]});
}catch(e){let detail:string;if(e instanceof Error)detail=e.message;else{try{detail=JSON.stringify(e)}catch{detail=String(e)}}return json(400,{error:"CANONICAL_IMPORT_WORKER_FAILED",detail:detail.slice(0,2000)});}});
