export type ReportCheckpointStage = 'queued' | 'fingerprinted' | 'extracted' | 'canonicalized' | 'validated' | 'analyzed' | 'decisioned' | 'committed' | 'rendered';
export type ReportExecutionStage = ReportCheckpointStage;

export interface ReportExecutionCheckpoint { stage: ReportCheckpointStage; sourceHash: string; artifactHash?: string; rowCount?: number; evidenceKeys: string[]; updatedAt: number; }
const ORDER: ReportCheckpointStage[] = ['queued','fingerprinted','extracted','canonicalized','validated','analyzed','decisioned','committed','rendered'];
function canonicalEvidence(keys: unknown): string[] {
  if (!Array.isArray(keys) || keys.some((key) => typeof key !== 'string' || !key.trim())) throw new Error('Checkpoint evidence keys must be non-blank strings');
  return [...new Set(keys)].sort();
}
export function canAdvanceCheckpoint(from: ReportCheckpointStage, to: ReportCheckpointStage): boolean { return ORDER.indexOf(to) === ORDER.indexOf(from) + 1; }
export function assertValidTransition(from: ReportCheckpointStage, to: ReportCheckpointStage): void { if (!canAdvanceCheckpoint(from, to)) throw new Error(`Invalid checkpoint transition: ${from} -> ${to}`); }
export function createInitialCheckpoint(sourceHash: string, evidenceKeys: string[] = []): ReportExecutionCheckpoint { if (!sourceHash.trim()) throw new Error('Initial checkpoint requires a source hash'); return { stage: 'queued', sourceHash, evidenceKeys: canonicalEvidence(evidenceKeys), updatedAt: Date.now() }; }
export function advanceCheckpoint(current: ReportExecutionCheckpoint, next: Omit<ReportExecutionCheckpoint, 'updatedAt'>): ReportExecutionCheckpoint { assertValidTransition(current.stage, next.stage); if (next.sourceHash !== current.sourceHash) throw new Error('Checkpoint source hash cannot change during a run'); if (next.rowCount !== undefined && (!Number.isInteger(next.rowCount) || next.rowCount < 0)) throw new Error('Checkpoint rowCount must be a non-negative integer'); const evidenceKeys = [...new Set([...canonicalEvidence(current.evidenceKeys), ...canonicalEvidence(next.evidenceKeys)])].sort(); return { ...next, evidenceKeys, updatedAt: Date.now() }; }
export function resumeFromCheckpoint(checkpoint: ReportExecutionCheckpoint): ReportCheckpointStage { if (!checkpoint.sourceHash?.trim()) throw new Error('Cannot resume a checkpoint without a source hash'); canonicalEvidence(checkpoint.evidenceKeys); if (!Number.isFinite(checkpoint.updatedAt) || checkpoint.updatedAt < 0) throw new Error('Cannot resume a checkpoint with invalid timestamp'); if (ORDER.indexOf(checkpoint.stage) < 0) throw new Error('Cannot resume an unknown checkpoint stage'); if (checkpoint.rowCount !== undefined && (!Number.isInteger(checkpoint.rowCount) || checkpoint.rowCount < 0)) throw new Error('Cannot resume a checkpoint with invalid rowCount'); return checkpoint.stage; }
