import { useEffect, useState } from 'react';
import { Plus, Save, Trash2, UsersRound, RefreshCw, AlertTriangle, Layers3, PackageSearch } from 'lucide-react';
import { supabase, resolveCurrentCompanyId } from '@/lib/supabase';
import { PageHeader, EmptyState } from '@/components/ui/States';
import { validateAlternativeGroupIsolation, type TenantScopedMember } from '@/lib/free-toolbox/alternative-group-security';

type Group={id:string;name:string;description:string|null;base_unit:string;is_active:boolean;created_at:string};
type Member={id:string;group_id:string;sku:string;conversion_factor:number};

export function AlternativeGroupsPage(){
 const [groups,setGroups]=useState<Group[]>([]); const [members,setMembers]=useState<Member[]>([]); const [selected,setSelected]=useState<string|null>(null);
 const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [baseUnit,setBaseUnit]=useState('unit'); const [sku,setSku]=useState(''); const [factor,setFactor]=useState('1');
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 const requireTenant=async()=>{const tenantId=await resolveCurrentCompanyId(); if(!tenantId) throw new Error('تعذر تحديد الشركة الحالية، تم إيقاف العملية حفاظًا على عزل البيانات'); return tenantId};
 const load=async()=>{setLoading(true);setError(''); try{await requireTenant(); const [g,m]=await Promise.all([supabase.from('alternative_item_groups').select('*').order('created_at',{ascending:false}),supabase.from('alternative_item_group_members').select('*')]); if(g.error||m.error)throw new Error((g.error||m.error)?.message||'تعذر تحميل المجموعات'); setGroups((g.data||[]) as Group[]);setMembers((m.data||[]) as Member[]);}catch(e){setGroups([]);setMembers([]);setSelected(null);setError(e instanceof Error?e.message:'تعذر تحميل المجموعات')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const reset=()=>{setSelected(null);setName('');setDescription('');setBaseUnit('unit');setSku('');setFactor('1');setError('')};
 const saveGroup=async()=>{if(!name.trim()){setError('اسم المجموعة مطلوب');return} setSaving(true);setError(''); try{const companyId=await requireTenant(); const {data,error:e}=await supabase.rpc('create_alternative_item_group',{p_company_id:companyId,p_name:name.trim(),p_description:description.trim()||null,p_base_unit:baseUnit.trim()||'unit'}); if(e)throw e; const created=Array.isArray(data)?data[0]:data; if(!created?.id)throw new Error('لم تُرجع قاعدة البيانات المجموعة المنشأة'); setGroups(v=>[created as Group,...v]);setSelected(created.id);setName('');setDescription('')}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ المجموعة')}finally{setSaving(false)}};
 const addMember=async()=>{if(!selected||!sku.trim()){setError('اختر مجموعة وأدخل SKU');return} const numeric=Number(factor); if(!Number.isFinite(numeric)||numeric<=0){setError('معامل التحويل يجب أن يكون أكبر من صفر');return} setSaving(true);setError(''); try{const companyId=await requireTenant(); const candidate:TenantScopedMember={tenantId:companyId,sku:sku.trim(),groupId:selected}; const existing=members.filter(m=>m.sku===candidate.sku&&m.group_id!==selected).map(m=>({tenantId:companyId,sku:m.sku,groupId:m.group_id})); const issues=validateAlternativeGroupIsolation([...existing,candidate]); if(issues.length)throw new Error('هذا SKU مرتبط بمجموعة بديلة أخرى داخل الشركة'); const {data,error:e}=await supabase.rpc('add_alternative_item_group_member',{p_company_id:companyId,p_group_id:selected,p_sku:sku.trim(),p_conversion_factor:numeric}); if(e)throw e; const created=Array.isArray(data)?data[0]:data; if(!created?.id)throw new Error('لم تُرجع قاعدة البيانات العضو المنشأ');setMembers(v=>[...v,created as Member]);setSku('');setFactor('1')}catch(e){setError(e instanceof Error?e.message:'تعذر إضافة الصنف')}finally{setSaving(false)}};
 const removeMember=async(id:string)=>{setSaving(true);setError('');try{const companyId=await requireTenant();const {error:e}=await supabase.rpc('remove_alternative_item_group_member',{p_company_id:companyId,p_member_id:id});if(e)throw e;setMembers(v=>v.filter(m=>m.id!==id))}catch(e){setError(e instanceof Error?e.message:'تعذر حذف الصنف')}finally{setSaving(false)}};
 const activeMembers=members.filter(m=>m.group_id===selected); const selectedGroup=groups.find(g=>g.id===selected);
 return <div dir="rtl" className="space-y-6">
  <PageHeader title="مجموعات الأصناف البديلة" subtitle="اجمع الأصناف المتكافئة لتصبح قرارات المخزون والطلب على مستوى المجموعة." actions={<button type="button" onClick={load} className="btn-secondary"><RefreshCw size={16}/> تحديث</button>} />
  {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 flex items-start gap-2"><AlertTriangle size={18} className="mt-0.5 shrink-0"/><span>{error}</span></div>}
  <section className="grid gap-3 sm:grid-cols-3">
   <div className="card p-4"><div className="text-[10px] font-black text-ink-400">المجموعات الفعالة</div><div className="mt-2 text-2xl font-black tabular-nums text-ink-950">{groups.filter(group => group.is_active).length}</div><p className="mt-1 text-[10px] text-ink-400">مجموعات يمكن استخدامها في التحليل.</p></div>
   <div className="card p-4"><div className="text-[10px] font-black text-ink-400">الأصناف المرتبطة</div><div className="mt-2 text-2xl font-black tabular-nums text-ink-950">{new Set(members.map(member => member.sku)).size}</div><p className="mt-1 text-[10px] text-ink-400">SKU ظهر ضمن عضوية مجموعة حالية.</p></div>
   <div className="card p-4"><div className="text-[10px] font-black text-ink-400">سياق المجموعة المحددة</div><div className="mt-2 text-sm font-black text-ink-950">{selectedGroup ? activeMembers.length + ' صنف' : 'لم تُحدد بعد'}</div><p className="mt-1 text-[10px] text-ink-400">التجميع لا يغيّر بيانات المصدر الأصلية.</p></div>
  </section>
  <section className="hero-surface overflow-hidden p-5 lg:p-6">
   <div className="flex items-start gap-3"><Layers3 size={20} className="mt-0.5 text-primary-700"/><div><div className="section-kicker">سياق القرار</div><h2 className="mt-1 text-lg font-black text-ink-950">المجموعة هي عدسة تحليل، وليست تصنيفًا تجميليًا.</h2><p className="mt-2 max-w-3xl text-[11px] leading-6 text-ink-500">عند اكتمال الدليل، يستخدم المسار الحالي هذه العضويات لتجميع الطلب والمخزون والمبيعات وإعادة حساب التغطية على مستوى المجموعة. لا يتم استنتاج بديل غير محفوظ في المصدر.</p></div></div>
  </section>
  <div className="grid lg:grid-cols-[360px_1fr] gap-5">
   <section className="card p-5 space-y-4"><div className="flex items-center gap-2 font-semibold"><Plus size={18}/> إنشاء مجموعة</div><div><label htmlFor="alternative-group-name" className="mb-1.5 block text-xs font-bold text-ink-600">اسم المجموعة</label><input id="alternative-group-name" className="input text-base md:text-sm" className="input" placeholder="مثال: بدائل مياه 330ml" value={name} onChange={e=>setName(e.target.value)}/><label htmlFor="alternative-group-description" className="mb-1.5 block text-xs font-bold text-ink-600">الوصف</label><textarea id="alternative-group-description" className="input min-h-20 text-base md:text-sm" placeholder="لماذا تعتبر هذه الأصناف بدائل؟" value={description} onChange={e=>setDescription(e.target.value)}/><label htmlFor="alternative-group-unit" className="mb-1.5 block text-xs font-bold text-ink-600">الوحدة الأساسية</label><input id="alternative-group-unit" className="input text-base md:text-sm" placeholder="الوحدة" value={baseUnit} onChange={e=>setBaseUnit(e.target.value)}/><button disabled={saving} onClick={saveGroup} className="btn-primary w-full"><Save size={16}/> حفظ المجموعة</button><button onClick={reset} className="btn-secondary w-full">تفريغ النموذج</button></section>
   <section className="card overflow-hidden"><div className="p-5 border-b border-ink-100 flex items-center justify-between gap-3"><div><h2 className="font-semibold">المجموعات الحالية</h2><p className="text-xs text-ink-400">{loading?'جاري التحميل…':`${groups.length} مجموعة`}</p></div><span className="badge-neutral">Tenant-scoped</span></div><div className="divide-y divide-ink-100">{groups.map(g=><button type="button" key={g.id} onClick={()=>setSelected(g.id)} aria-pressed={selected===g.id} className={`w-full text-right p-4 hover:bg-ink-50 ${selected===g.id?'bg-primary-50':''}`}><div className="font-medium">{g.name}</div><div className="text-xs text-ink-400 mt-1">{g.description||'بدون وصف'} · {members.filter(m=>m.group_id===g.id).length} أصناف</div></button>)}{!groups.length&&!loading&&<div className="p-6"><EmptyState icon={<PackageSearch size={28}/>} title="لا توجد مجموعات محفوظة" message="أنشئ مجموعة عندما تكون لديك علاقة بدائل حقيقية ومثبتة في بيانات العمل." action={<span className="mt-2 text-[10px] text-ink-400">لن يتم إنشاء بيانات افتراضية تلقائيًا.</span>}/></div>}</div></section>
  </div>
  {selectedGroup&&<section className="card p-5 space-y-5"><div><div className="section-kicker">سياق المجموعة</div><h2 className="mt-1 text-lg font-black text-ink-950">{selectedGroup.name}</h2><p className="text-sm text-ink-500">الوحدة الأساسية: {selectedGroup.base_unit}</p></div><div className="grid md:grid-cols-[1fr_180px_auto] gap-3 items-end"><div><label htmlFor="alternative-member-sku" className="mb-1.5 block text-xs font-bold text-ink-600">SKU / رقم الصنف</label><input id="alternative-member-sku" className="input text-base md:text-sm" placeholder="SKU / رقم الصنف" value={sku} onChange={e=>setSku(e.target.value)}/></div><div><label htmlFor="alternative-member-factor" className="mb-1.5 block text-xs font-bold text-ink-600">معامل التحويل</label><input id="alternative-member-factor" className="input text-base md:text-sm" type="number" min="0.000001" step="any" placeholder="1" value={factor} onChange={e=>setFactor(e.target.value)}/></div><button disabled={saving} onClick={addMember} className="btn-primary"><Plus size={16}/> إضافة</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-right text-ink-400 border-b"><th className="p-3">SKU</th><th className="p-3">معامل التحويل</th><th className="p-3">إجراء</th></tr></thead><tbody>{activeMembers.map(m=><tr key={m.id} className="border-b border-ink-50"><td className="p-3 font-medium">{m.sku}</td><td className="p-3">{m.conversion_factor}</td><td className="p-3"><button type="button" onClick={()=>removeMember(m.id)} className="rounded-lg p-2 text-danger-600 hover:bg-danger-50" aria-label={'حذف '+m.sku+' من المجموعة'}><Trash2 size={16}/></button></td></tr>)}{!activeMembers.length&&<tr><td colSpan={3} className="p-8 text-center text-ink-400">أضف الأصناف التي تعتبر بدائل متكافئة.</td></tr>}</tbody></table></div><div className="rounded-xl bg-ink-50 p-4 text-xs text-ink-500 flex gap-2"><UsersRound size={16}/><span>سيستخدم محرك التقارير هذه المجموعة لتجميع الطلب والمخزون والمبيعات وإعادة حساب التغطية على مستوى المجموعة.</span></div></section>}
 </div>
}