import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BrainCircuit, Sparkles, ArrowLeft, Send, ShieldCheck, Lightbulb, BarChart3, FileText, Workflow, MessageCircle } from 'lucide-react';

const prompts=['ما أهم ما يحتاج تدخلاً اليوم؟','فسّر لي أسباب تغير المبيعات','ما المخاطر التي يجب أن أتابعها؟','قارن بين سيناريوهين قبل اتخاذ القرار'];
const capabilities=[['المساعد الذكي','اسأل بلغة طبيعية عن البيانات والتقارير والقرارات.','/intelligence',MessageCircle],['الخبير الذكي','حوّل المؤشرات إلى تفسير، أسباب، أسئلة متابعة وخطوات عملية.','/decision-experience',Lightbulb],['التنبؤ الذكي','استكشف الاتجاهات والطلب والمخزون مع فصل واضح بين المحسوب وغير المتاح.','/intelligence/forecasts',BarChart3],['ماذا لو؟','اختبر أثر الفرضيات قبل اعتماد القرار.','/intelligence/scenarios',Workflow],['التقارير التنفيذية','أنشئ مساراً سريعاً من الحقيقة إلى القرار والطباعة.','/reports/executive',FileText]] as const;
export function AssistantHubPage(){const [question,setQuestion]=useState('');const [submitted,setSubmitted]=useState('');const available=useMemo(()=>question.trim().length>0,[question]);return <div dir="rtl" className="space-y-7 pb-10">
<section className="experience-hero overflow-hidden"><div className="relative z-10 grid gap-8 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><div className="experience-chip mb-4"><Sparkles size={14}/> AI DECISION DESK</div><h1 className="max-w-3xl text-3xl font-black tracking-tight text-white sm:text-5xl">المساعد والخبير الذكي<br/><span className="text-emerald-100">من السؤال إلى قرار قابل للتنفيذ.</span></h1><p className="mt-5 max-w-2xl text-sm leading-7 text-emerald-50/80 sm:text-base">مساحة موحدة للمحادثة، التفسير، التنبؤ، المحاكاة، وتحويل الاستنتاجات إلى أعمال — مع احترام حقيقة البيانات وعدم اختراع أي نتيجة غير موجودة.</p></div><div className="rounded-[2rem] border border-white/10 bg-white/10 p-5 backdrop-blur-xl"><ShieldCheck className="text-amber-300" size={24}/><div className="mt-3 text-sm font-bold text-white">مبدأ الثقة</div><p className="mt-2 text-xs leading-6 text-emerald-50/75">المساعد يميز بين المحسوب، المستنتج، وغير المتاح قبل تقديم توصية.</p></div></div></section>
<section className="card overflow-hidden p-0"><div className="border-b border-ink-100 bg-ink-50/60 p-5"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-700 text-white"><BrainCircuit size={22}/></div><div><h2 className="font-black text-ink-950">اسأل المساعد</h2><p className="text-xs text-ink-400">ابدأ بسؤال واحد، ثم انتقل إلى الدليل أو السيناريو أو الإجراء.</p></div></div></div><div className="grid gap-5 p-5 lg:grid-cols-[1fr_280px]"><div><div className="min-h-48 rounded-[1.5rem] border border-dashed border-ink-200 bg-white p-5"><div className="flex items-center gap-3 text-sm font-bold text-ink-700"><Sparkles size={17} className="text-amber-600"/> مساحة المحادثة جاهزة</div>{submitted&&<div className="mt-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-900"><div className="font-bold">سؤالك</div><div className="mt-1">{submitted}</div><div className="mt-3 text-xs leading-6 text-emerald-700">لم يتم اختلاق إجابة هنا: استخدم مركز الذكاء للوصول إلى الأدلة والنتائج المحسوبة فعلياً.</div></div>}</div><div className="mt-4 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&available){setSubmitted(question.trim());setQuestion('')}}} placeholder="اكتب سؤالك عن المبيعات، العملاء، المخزون أو القرار..." className="input flex-1"/><button type="button" disabled={!available} onClick={()=>{setSubmitted(question.trim());setQuestion('')}} className="btn-primary px-4" aria-label="إرسال السؤال"><Send size={17}/></button></div></div><div><div className="text-xs font-black uppercase tracking-wider text-ink-400">أسئلة مقترحة</div><div className="mt-3 space-y-2">{prompts.map(p=><button key={p} type="button" onClick={()=>setQuestion(p)} className="w-full rounded-2xl border border-ink-100 bg-ink-50/50 p-3 text-right text-xs font-semibold text-ink-600 transition hover:border-emerald-200 hover:bg-emerald-50 hover:text-emerald-800">{p}</button>)}</div></div></div></section>
<section><div className="experience-section-header"><div><div className="experience-section-title">منظومة الذكاء</div><div className="experience-section-subtitle">كل قدرة مرتبطة بمسار واضح داخل المنتج.</div></div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{capabilities.map(([title,desc,path,Icon])=><Link key={title} to={path} className="card group p-5 transition hover:-translate-y-1 hover:border-emerald-200"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><Icon size={20}/></div><h3 className="mt-4 font-black text-ink-950">{title}</h3><p className="mt-2 text-xs leading-6 text-ink-500">{desc}</p><div className="mt-4 flex items-center gap-1 text-xs font-bold text-emerald-700">فتح المساحة <ArrowLeft size={14}/></div></Link>)}</div></section>
</div>}
