import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, AlertTriangle, ArrowUpLeft, Brain, ChevronLeft, CircleDollarSign, PackageSearch, RefreshCw, TrendingUp, UsersRound, Upload, WalletCards, FileBarChart, Search } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { fetchCanonicalDashboard, type CanonicalDashboard } from '../lib/canonicalDashboard';

function money(value: number | null) { if (value === null) return 'غير متوفر'; return new Intl.NumberFormat('ar', { notation: 'compact', maximumFractionDigits: 2 }).format(value); }
function Kpi({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Activity }) { return <div className="card p-5 card-hover"><div className="flex items-start justify-between gap-4"><div><div className="text-sm text-ink-500">{label}</div><div className="mt-2 text-2xl font-bold tabular-nums text-ink-900">{value}</div></div><div className="w-11 h-11 rounded-xl bg-primary-50 text-primary-700 flex items-center justify-center"><Icon size={21} /></div></div></div>; }

const quickActions = [
  { to: '/import', label: 'إضافة بيانات', description: 'Excel · CSV · PDF', icon: Upload },
  { to: '/analytics', label: 'استكشاف', description: 'اتجاهات ومقارنات', icon: Search },
  { to: '/inventory/forecast', label: 'التنبؤ', description: 'طلب وإعادة طلب', icon: TrendingUp },
  { to: '/finance/intelligence', label: 'السيولة', description: 'نقد وتحصيل والتزامات', icon: WalletCards },
  { to: '/reports/studio', label: 'تقرير جديد', description: 'تقرير تنفيذي موثق', icon: FileBarChart },
];

export function BusinessCockpitPage() {
  const [data, setData] = useState<CanonicalDashboard | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(null); try { setData(await fetchCanonicalDashboard(6)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر تحميل بيانات غرفة القرار.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const metric = useMemo(() => new Map(data?.metrics.map(item => [item.key, item]) ?? []), [data]);
  const sales = metric.get('net_sales'); const inventory = metric.get('inventory_value'); const receivables = metric.get('receivables'); const payables = metric.get('payables');

  return <div className="space-y-6" dir="rtl">
    <section className="card overflow-hidden"><div className="p-6 lg:p-7 bg-gradient-to-l from-primary-50 via-white to-white border-b border-ink-100"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-5"><div><div className="eyebrow text-primary-700 mb-2">غرفة القرار التنفيذية</div><h1 className="text-2xl lg:text-3xl font-bold text-ink-900">ماذا يحدث في النشاط الآن؟</h1><p className="mt-2 text-sm text-ink-500 max-w-2xl">هذه الصفحة تعرض أرقامًا حقيقية من الشركة الحالية، ولا تستخدم بيانات تجريبية مخفية.</p></div><button onClick={() => void load()} className="btn-secondary self-start" disabled={loading}><RefreshCw size={16} className={loading ? 'animate-spin' : ''} /> تحديث البيانات</button></div></div><div className="p-4 flex flex-wrap items-center gap-3 text-xs"><span className="badge-success">Tenant-safe</span><span className="badge-primary">Canonical metrics</span><span className="text-ink-400">{data ? `آخر تحديث ${new Date(data.generatedAt).toLocaleTimeString('ar')}` : 'جارٍ التحميل...'}</span></div></section>

    <section className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-2.5">{quickActions.map(action => { const Icon = action.icon; return <Link key={action.to} to={action.to} className="group rounded-xl border border-ink-100 bg-white px-3 py-3.5 hover:border-primary-200 hover:bg-primary-50/40 transition-colors"><div className="flex items-center gap-3"><span className="w-9 h-9 rounded-lg bg-ink-50 group-hover:bg-primary-100 text-ink-500 group-hover:text-primary-700 flex items-center justify-center"><Icon size={17}/></span><span className="min-w-0"><span className="block text-sm font-semibold text-ink-800 truncate">{action.label}</span><span className="block text-[10px] text-ink-400 truncate mt-0.5">{action.description}</span></span></div></Link>; })}</section>

    {error && <div className="card p-5 border-danger-200 bg-danger-50 text-danger-800"><b>تعذر تحميل البيانات</b><div className="text-sm mt-1">{error}</div><button onClick={() => void load()} className="btn-secondary mt-3">إعادة المحاولة</button></div>}
    <section className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi label="صافي المبيعات" value={money(sales?.value ?? null)} icon={ArrowUpLeft} /><Kpi label="قيمة المخزون" value={money(inventory?.value ?? null)} icon={PackageSearch} /><Kpi label="الذمم المدينة" value={money(receivables?.value ?? null)} icon={CircleDollarSign} /><Kpi label="التزامات الموردين" value={money(payables?.value ?? null)} icon={UsersRound} /></section>
    <section className="grid grid-cols-1 xl:grid-cols-3 gap-5"><div className="card xl:col-span-2 p-5"><div className="flex items-center justify-between mb-5"><div><h2 className="font-bold text-ink-900">اتجاه المبيعات</h2><p className="text-xs text-ink-400 mt-1">آخر 6 أشهر من البيانات الفعلية</p></div><Link to="/analytics" className="btn-ghost text-xs">استكشف التحليل <ChevronLeft size={14} /></Link></div><div className="h-72">{data && <ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend} margin={{ top: 10, right: 10, left: -15, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={11} /><YAxis tickLine={false} axisLine={false} fontSize={11} /><Tooltip /><Area type="monotone" dataKey="sales" stroke="currentColor" fill="currentColor" fillOpacity={0.08} strokeWidth={2.5} className="text-primary-600" /></AreaChart></ResponsiveContainer>}</div></div><div className="card p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-ink-900">جودة المؤشرات</h2><p className="text-xs text-ink-400 mt-1">لا قرار بدون بيانات كافية</p></div><Activity className="text-success-600" size={20} /></div><div className="space-y-3">{data?.metrics.map(item => <div key={item.key} className="flex items-center justify-between text-sm"><span className="text-ink-500">{item.definition.label}</span><span className={item.confidence >= .7 ? 'badge-success' : 'badge-warning'}>{Math.round(item.confidence * 100)}%</span></div>)}</div></div></section>
    <section className="grid grid-cols-1 xl:grid-cols-2 gap-5"><div className="card p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-ink-900">الأولوية الآن</h2><p className="text-xs text-ink-400 mt-1">تنبيهات الشركة الحالية</p></div><AlertTriangle className="text-warning-600" size={20} /></div><div className="space-y-3">{data?.alerts.length ? data.alerts.map(alert => <div key={alert.id} className="rounded-xl border border-ink-100 p-4"><div className="font-medium text-sm text-ink-800">{alert.title}</div><div className="text-xs text-ink-400 mt-1">{alert.reason || 'راجع مركز القرار لمزيد من التفاصيل.'}</div></div>) : <div className="text-sm text-ink-400">لا توجد تنبيهات مسجلة.</div>}</div></div><div className="card p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-bold text-ink-900">توصيات قابلة للتتبع</h2><p className="text-xs text-ink-400 mt-1">التوصيات المعروضة مصدرها محرك القرار</p></div><Brain className="text-primary-600" size={20} /></div><div className="space-y-3">{data?.recommendations.length ? data.recommendations.map(rec => <div key={rec.id} className="rounded-xl bg-primary-50/50 border border-primary-100 p-4"><div className="font-medium text-sm text-ink-800">{rec.title}</div><div className="text-xs text-ink-500 mt-1">{rec.action || 'مراجعة التوصية'}</div><div className="text-xs text-ink-400 mt-2">ثقة {Math.round(rec.confidence * 100)}% · {rec.status || 'غير محدد'}</div></div>) : <div className="text-sm text-ink-400">لا توجد توصيات مسجلة.</div>}</div></div></section>
    <section className="card p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"><div className="flex items-start gap-3"><TrendingUp className="text-primary-600 mt-0.5" size={20} /><div><div className="font-semibold text-ink-900">المصدر موحد</div><div className="text-xs text-ink-500 mt-1">كل KPI في هذه الصفحة يمر عبر محرك المؤشرات المركزي مع عزل الشركة.</div></div></div><Link to="/intelligence" className="btn-primary shrink-0">فتح مركز الذكاء</Link></section>
  </div>;
}
