import { useState } from 'react';
import { ArrowUp, Database, GitBranch, MessageSquareText, ShieldCheck } from 'lucide-react';
import { executeBIQuestion, type BIExecutionResult } from '@/lib/biMetricExecutor';
import { getMetricLineage } from '@/lib/dataLineage';

function display(value: number | null) { return value === null ? 'غير متوفر' : new Intl.NumberFormat('ar', { maximumFractionDigits: 2 }).format(value); }

export function ChatBIPage() {
  const [question, setQuestion] = useState('');
  const [result, setResult] = useState<BIExecutionResult | null>(null);
  const [loading, setLoading] = useState(false);
  const submit = async (value = question.trim()) => { if (!value) return; setQuestion(value); setLoading(true); try { setResult(await executeBIQuestion(value)); } finally { setLoading(false); } };
  const lineage = result?.intent.metric ? getMetricLineage(result.intent.metric.key) : null;
  return <div className="space-y-6" dir="rtl">
    <div><p className="text-sm font-medium text-primary-600">تحليل باللغة الطبيعية</p><h1 className="mt-1 text-3xl font-bold text-ink-950">Chat2BI</h1><p className="mt-2 text-sm text-ink-500">السؤال يمر عبر تعريف المقياس الرسمي ثم تنفيذ محمي بنطاق الشركة. لا يتم اختلاق رقم عند غياب البيانات.</p></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_340px]">
      <section className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold"><MessageSquareText size={18} className="text-primary-600"/> سؤالك</div><div className="mt-4 relative"><textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder="مثال: ما صافي المبيعات هذا الشهر؟" className="min-h-32 w-full resize-none rounded-xl border border-ink-200 p-4 pl-14 outline-none focus:border-primary-500"/><button disabled={!question.trim() || loading} onClick={() => void submit()} className="absolute bottom-3 left-3 rounded-lg bg-primary-600 p-2.5 text-white disabled:opacity-40"><ArrowUp size={17}/></button></div><div className="mt-5 flex flex-wrap gap-2">{['ما صافي المبيعات هذا الشهر؟','ما قيمة المخزون؟','ما وضع الذمم المدينة؟','ما التزامات الموردين هذا الشهر؟'].map(q => <button key={q} onClick={() => void submit(q)} className="rounded-full border border-ink-200 px-3 py-2 text-xs text-ink-600 hover:border-primary-300 hover:text-primary-700">{q}</button>)}</div></section>
      <aside className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck size={17} className="text-emerald-600"/> حوكمة الإجابة</div><ul className="mt-4 space-y-3 text-xs leading-5 text-ink-600"><li>• نطاق الشركة يفرض في كل استعلام.</li><li>• المقياس مأخوذ من قاموس الأعمال.</li><li>• البيانات غير الكافية لا تتحول إلى رقم.</li><li>• المصدر ومسار البيانات يظهران مع النتيجة.</li></ul></aside>
    </div>
    {loading && <section className="rounded-2xl border border-primary-100 bg-primary-50 p-5 text-sm text-primary-800">جارٍ تنفيذ السؤال على البيانات الفعلية...</section>}
    {result && <section className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-ink-400">المقياس</p><h2 className="mt-1 text-xl font-bold text-ink-950">{result.intent.metric?.label || 'مقياس غير محدد'}</h2></div><span className="rounded-full bg-ink-100 px-3 py-1.5 text-xs">ثقة التعرف: {Math.round(result.intent.confidence * 100)}%</span></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-xl bg-ink-50 p-4"><div className="text-xs text-ink-400">النتيجة</div><div className="mt-1 text-xl font-bold">{display(result.value)}</div></div><div className="rounded-xl bg-ink-50 p-4"><div className="text-xs text-ink-400">الحالة</div><div className="mt-1 font-semibold">{result.status}</div></div><div className="rounded-xl bg-ink-50 p-4"><div className="text-xs text-ink-400">الفترة</div><div className="mt-1 font-semibold">{result.intent.period}</div></div><div className="rounded-xl bg-ink-50 p-4"><div className="text-xs text-ink-400">الأدلة</div><div className="mt-1 font-semibold">{result.evidence.length} مصدر</div></div></div>{result.error && <div className="mt-4 rounded-xl bg-danger-50 p-4 text-sm text-danger-800">{result.error}</div>}{result.metric?.warnings.length ? <div className="mt-4 rounded-xl bg-warning-50 p-4 text-sm text-warning-800">{result.metric.warnings.join(' ')}</div> : null}</section>}
    {lineage && <section className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2 font-semibold"><GitBranch size={18} className="text-primary-600"/> مسار البيانات</div><div className="mt-4 flex flex-wrap items-center gap-2">{lineage.nodes.map((node, i) => <div key={node.id} className="flex items-center gap-2"><div className="rounded-xl border border-ink-200 px-3 py-2"><div className="text-xs text-ink-400">{node.kind}</div><div className="text-sm font-medium">{node.label}</div></div>{i < lineage.nodes.length - 1 && <span className="text-ink-300">←</span>}</div>)}</div><div className="mt-4 flex items-center gap-2 text-xs text-ink-500"><Database size={14}/> {lineage.nodes.map(n => n.details).join(' • ')}</div></section>}
  </div>;
}
