import { useMemo, useState } from 'react';
import { ArrowUp, Database, GitBranch, MessageSquareText, ShieldCheck } from 'lucide-react';
import { explainBIIntent, parseBIQuestion } from '@/lib/chat2bi';
import { getMetricLineage } from '@/lib/dataLineage';

export function ChatBIPage(){const [question,setQuestion]=useState(''); const [submitted,setSubmitted]=useState(''); const intent=useMemo(()=>submitted?parseBIQuestion(submitted):null,[submitted]); const explanation=useMemo(()=>intent?explainBIIntent(intent):null,[intent]); const lineage=intent?.metric?getMetricLineage(intent.metric.key):null; return <div className="space-y-6" dir="rtl">
  <div><p className="text-sm font-medium text-primary-600">تحليل باللغة الطبيعية</p><h1 className="mt-1 text-3xl font-bold text-ink-950">Chat2BI</h1><p className="mt-2 text-sm text-ink-500">اسأل عن الأعمال بلغة طبيعية. النظام يبدأ من قاموس المقاييس الرسمي ولا يخترع أرقامًا عند غياب البيانات أو وضوح السؤال.</p></div>
  <div className="grid gap-5 lg:grid-cols-[1fr_340px]">
    <section className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold"><MessageSquareText size={18} className="text-primary-600"/> سؤالك</div><div className="mt-4 relative"><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="مثال: ما الأصناف الأكثر مبيعًا هذا الشهر؟" className="min-h-32 w-full resize-none rounded-xl border border-ink-200 p-4 pl-14 outline-none focus:border-primary-500"/><button disabled={!question.trim()} onClick={()=>setSubmitted(question.trim())} className="absolute bottom-3 left-3 rounded-lg bg-primary-600 p-2.5 text-white disabled:opacity-40"><ArrowUp size={17}/></button></div><div className="mt-5 flex flex-wrap gap-2">{['ما صافي المبيعات هذا الشهر؟','ما قيمة المخزون؟','ما وضع الذمم المدينة؟','ما الأصناف الأكثر مبيعًا؟'].map(q=><button key={q} onClick={()=>{setQuestion(q);setSubmitted(q)}} className="rounded-full border border-ink-200 px-3 py-2 text-xs text-ink-600 hover:border-primary-300 hover:text-primary-700">{q}</button>)}</div></section>
    <aside className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2 text-sm font-semibold"><ShieldCheck size={17} className="text-emerald-600"/> حوكمة الإجابة</div><ul className="mt-4 space-y-3 text-xs leading-5 text-ink-600"><li>• لا يتم اختلاق رقم عند نقص البيانات.</li><li>• كل مقياس يبدأ من تعريف رسمي.</li><li>• مصدر البيانات يظهر مع النتيجة.</li><li>• يمكن تتبع المقياس إلى مصدره.</li></ul></aside>
  </div>
  {intent&&<section className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-ink-400">فهم السؤال</p><h2 className="mt-1 text-xl font-bold text-ink-950">{intent.metric?.label||'مقياس غير محدد'}</h2></div><span className="rounded-full bg-ink-100 px-3 py-1.5 text-xs">ثقة التعرف: {Math.round(intent.confidence*100)}%</span></div><p className="mt-4 text-sm text-ink-600">{explanation?.message}</p>{intent.metric&&<div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-ink-50 p-4"><div className="text-xs text-ink-400">الفترة</div><div className="mt-1 font-semibold">{intent.period}</div></div><div className="rounded-xl bg-ink-50 p-4"><div className="text-xs text-ink-400">الحالة</div><div className="mt-1 font-semibold">{explanation?.status}</div></div><div className="rounded-xl bg-ink-50 p-4"><div className="text-xs text-ink-400">المصادر</div><div className="mt-1 font-semibold">{intent.metric.source.join(' + ')}</div></div></div>}</section>}
  {lineage&&<section className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2 font-semibold"><GitBranch size={18} className="text-primary-600"/> مسار البيانات</div><div className="mt-4 flex flex-wrap items-center gap-2">{lineage.nodes.map((node,i)=><div key={node.id} className="flex items-center gap-2"><div className="rounded-xl border border-ink-200 px-3 py-2"><div className="text-xs text-ink-400">{node.kind}</div><div className="text-sm font-medium">{node.label}</div></div>{i<lineage.nodes.length-1&&<span className="text-ink-300">←</span>}</div>)}</div><div className="mt-4 flex items-center gap-2 text-xs text-ink-500"><Database size={14}/> {lineage.nodes.map(n=>n.details).join(' • ')}</div></section>}
 </div>}
