import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowUpLeft,Boxes,RefreshCw,ShieldAlert,ShoppingCart,WalletCards,Zap} from 'lucide-react';
import {fetchFinanceSnapshot,fetchInventoryBalances,fetchInventorySales90d} from '@/lib/queries';
import {analyzeInventoryFlow,buildLiquidityActions,rankObligations,type InventoryFlow,type Obligation} from '@/lib/free-toolbox/business-command-engine';
const money=(v:number)=>new Intl.NumberFormat('ar-YE',{maximumFractionDigits:0}).format(v);
const pct=(v:number)=>`${v.toFixed(1)}%`;
export function CommandCenterPage(){
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [inventory,setInventory]=useState<any[]>([]);const [finance,setFinance]=useState<any>(null);const [sales90,setSales90]=useState<any>({invoices:[],items:[]});
 const load=async()=>{setLoading(true);setError('');try{const [b,f,s]=await Promise.all([fetchInventoryBalances(),fetchFinanceSnapshot(),fetchInventorySales90d()]);setInventory(b);setFinance(f);setSales90(s);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل بيانات مركز القرار');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const insights=useMemo(()=>{const qtyBy=new Map<string,number>();for(const item of sales90.items||[])qtyBy.set(item.product_id,(qtyBy.get(item.product_id)||0)+Number(item.quantity||0));const rows:InventoryFlow[]=inventory.map((b:any)=>{const p=b.product||{};const sold=qtyBy.get(b.product_id)||0;return{sku:String(p.sku||b.product_id||''),name:String(p.name||'صنف غير مسمى'),stock:Number(b.quantity||0),unitCost:Number(b.unit_cost??p.cost_price??0),dailySales:sold/90,weeklySales:sold/90*7,monthlySales:sold/3,lastSaleDaysAgo:sold>0?0:91,leadTimeDays:Number(p.lead_time_days||7),serviceLevel:.95};});return analyzeInventoryFlow(rows);},[inventory,sales90]);
 const obligations=useMemo<Obligation[]>(()=>{const rows:Obligation[]=[];for(const p of finance?.purchases||[]){const amount=Math.max(0,Number(p.total||0)-Number(p.paid_amount||0));if(amount>0)rows.push({partnerId:String(p.supplier_id),partnerName:String((p as any).supplier?.name||'مورد'),type:'supplier',amount,dueDate:String(p.due_date||p.invoice_date)});}for(const s of finance?.sales||[]){const amount=Math.max(0,Number(s.total||0)-Number(s.paid_amount||0));if(amount>0)rows.push({partnerId:String(s.customer_id),partnerName:String((s as any).customer?.name||'عميل'),type:'customer',amount,dueDate:String(s.due_date||s.invoice_date)});}return rankObligations(rows);},[finance]);
 const actionSummary=useMemo(()=>buildLiquidityActions(insights,obligations,{date:new Date().toISOString().slice(0,10),openingCash:0,inflow:0,outflow:0,closingCash:0,reserveGap:0,status:'safe',actions:[]}),[insights,obligations]);
 const totals=useMemo(()=>{const stock=insights.reduce((s,x)=>s+x.stockValue,0);const fast=insights.filter(x=>x.liquidity==='fast').reduce((s,x)=>s+x.stockValue,0);const frozen=insights.filter(x=>x.liquidity==='frozen').reduce((s,x)=>s+x.stockValue,0);const critical=insights.filter(x=>x.priority==='critical').length;return{stock,fast,frozen,critical};},[insights]);
 return <div dir="rtl" className="space-y-6">
  <section className="card p-6 bg-gradient-to-l from-primary-50 via-white to-white"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="text-xs font-semibold text-primary-700 flex items-center gap-2"><Zap size={15}/> مركز قيادة المخزون والسيولة</div><h1 className="mt-2 text-2xl font-bold text-ink-900">ماذا نشتري؟ ماذا نبيع؟ ومتى نتحرك؟</h1><p className="mt-2 text-sm text-ink-500 max-w-3xl">محرك قرار موحد يعتمد على حركة فعلية من النظام، ويحوّل التغطية والسرعة والاستحقاقات إلى أولويات قابلة للتنفيذ.</p></div><button onClick={load} className="btn-secondary"><RefreshCw size={16} className={loading?'animate-spin':''}/> تحديث التحليل</button></div></section>
  {error&&<div className="card p-4 border-danger-200 bg-danger-50 text-danger-800 text-sm"><ShieldAlert size={16} className="inline ml-2"/>{error}</div>}
  <section className="grid grid-cols-2 xl:grid-cols-4 gap-4"><Metric icon={Boxes} label="قيمة المخزون المحللة" value={money(totals.stock)} sub="حسب الرصيد والتكلفة"/><Metric icon={Zap} label="مخزون متحرك" value={money(totals.fast)} sub={pct(totals.stock?totals.fast/totals.stock*100:0)+' من القيمة'}/><Metric icon={AlertTriangle} label="مخزون راكد/مجمد" value={money(totals.frozen)} sub={pct(totals.stock?totals.frozen/totals.stock*100:0)+' من القيمة'}/><Metric icon={ShoppingCart} label="إعادة طلب عاجلة" value={String(totals.critical)} sub="تحت نقطة إعادة الطلب" danger/></section>
  <section className="grid grid-cols-1 xl:grid-cols-3 gap-5"><div className="card xl:col-span-2 overflow-hidden"><div className="p-5 border-b border-ink-100"><h2 className="font-bold text-ink-900">سيولة المخزون وسرعة التصريف</h2><p className="text-xs text-ink-400 mt-1">الحسابات مبنية على آخر 90 يوماً من حركة البيع المتاحة.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-right text-xs text-ink-400 border-b border-ink-100"><th className="p-4">الصنف</th><th className="p-4">التصنيف</th><th className="p-4">التغطية</th><th className="p-4">النفاد المتوقع</th><th className="p-4">طلب مقترح</th><th className="p-4">الأولوية</th></tr></thead><tbody>{insights.slice(0,30).map(x=><tr key={x.sku} className="border-b border-ink-50 hover:bg-ink-50/60"><td className="p-4 font-medium text-ink-800">{x.name}<div className="text-[11px] text-ink-400">{x.sku}</div></td><td className="p-4"><span className={`badge-${x.liquidity==='fast'?'success':x.liquidity==='frozen'?'danger':'warning'}`}>{x.liquidity==='fast'?'متحرك':x.liquidity==='frozen'?'راكد':'بطيء'}</span></td><td className="p-4 tabular-nums">{x.daysOfCover===null?'—':`${x.daysOfCover} يوم`}</td><td className="p-4">{x.stockoutDate||'غير محدد'}</td><td className="p-4 font-semibold">{x.recommendedPurchase>0?money(x.recommendedPurchase):'—'}</td><td className="p-4"><span className={`badge-${x.priority==='critical'?'danger':x.priority==='high'?'warning':'primary'}`}>{x.priority==='critical'?'عاجلة':x.priority==='high'?'عالية':x.priority==='normal'?'عادية':'منخفضة'}</span></td></tr>)}</tbody></table>{!loading&&!insights.length&&<div className="p-10 text-center text-sm text-ink-400">لا توجد بيانات مخزون قابلة للتحليل بعد.</div>}</div></div>
   <div className="card p-5"><h2 className="font-bold text-ink-900">الأولويات التنفيذية</h2><p className="text-xs text-ink-400 mt-1">مرتبة حسب الخطر والأثر وقرب الاستحقاق.</p><div className="mt-4 space-y-3">{actionSummary.slice(0,8).map((a,i)=><div key={`${a.title}-${i}`} className="rounded-xl border border-ink-100 p-4"><div className="flex items-start gap-3"><span className={`w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold ${a.priority==='critical'?'bg-danger-100 text-danger-700':a.priority==='high'?'bg-warning-100 text-warning-700':'bg-primary-100 text-primary-700'}`}>{i+1}</span><div><div className="font-semibold text-sm text-ink-800">{a.title}</div><div className="text-xs text-ink-500 mt-1 leading-5">{a.reason}</div>{a.amount!==undefined&&<div className="mt-2 text-xs font-semibold text-ink-700">القيمة: {money(a.amount)}</div>}</div></div></div>)}{!actionSummary.length&&<div className="py-8 text-center text-sm text-ink-400">لا توجد إجراءات عاجلة وفق البيانات الحالية.</div>}</div></div></section>
  <section className="grid grid-cols-1 md:grid-cols-2 gap-5"><InfoCard icon={WalletCards} title="التزامات الموردين" value={money(obligations.filter(x=>x.type==='supplier').reduce((s,x)=>s+x.amount,0))} detail={`${obligations.filter(x=>x.type==='supplier').length} استحقاق مورد تمت قراءته`} href="/finance/intelligence"/><InfoCard icon={ArrowUpLeft} title="المبالغ المستحقة من العملاء" value={money(obligations.filter(x=>x.type==='customer').reduce((s,x)=>s+x.amount,0))} detail={`${obligations.filter(x=>x.type==='customer').length} التزام تحصيل`} href="/reports/receivables"/></section>
  <div className="text-[11px] text-ink-400 flex items-center gap-2"><ShieldAlert size={13}/> لا يتم افتراض رصيد نقدي غير موجود. قرارات أزمة السيولة النقدية النهائية تحتاج مصدر رصيد فعلي للصندوق/البنوك أو إدخالاً موثقاً.</div>
 </div>;
}
function Metric({icon:Icon,label,value,sub,danger=false}:{icon:typeof Boxes;label:string;value:string;sub:string;danger?:boolean}){return <div className="card p-5"><div className="flex justify-between gap-3"><div><div className="text-xs text-ink-500">{label}</div><div className={`mt-2 text-2xl font-bold tabular-nums ${danger?'text-danger-700':'text-ink-900'}`}>{value}</div><div className="mt-2 text-[11px] text-ink-400">{sub}</div></div><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${danger?'bg-danger-50 text-danger-700':'bg-primary-50 text-primary-700'}`}><Icon size={19}/></div></div></div>}
function InfoCard({icon:Icon,title,value,detail,href}:{icon:typeof WalletCards;title:string;value:string;detail:string;href:string}){return <a href={href} className="card p-5 hover:border-primary-200 transition"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-primary-50 text-primary-700 flex items-center justify-center"><Icon size={19}/></div><div><div className="text-xs text-ink-500">{title}</div><div className="text-xl font-bold text-ink-900 mt-1">{value}</div><div className="text-[11px] text-ink-400 mt-1">{detail}</div></div></div></a>}
