import { useEffect, useState, useCallback } from 'react';
import { DollarSign, ShoppingCart, TrendingUp, Users, Package, AlertTriangle, Brain, ArrowLeftRight, Wallet, Receipt, Lightbulb, RefreshCw, CalendarRange, CheckCircle2 } from 'lucide-react';
import { KPICard } from '@/components/ui/KPICard';
import { Card, CardHeader, CardBody } from '@/components/ui/Card';
import { Badge, SeverityBadge, PriorityBadge } from '@/components/ui/Badge';
import { LoadingState, ErrorState } from '@/components/ui/States';
import { TrendChart, CategoryPieChart, HorizontalBarChart } from '@/components/ui/Charts';
import { fetchCanonicalDashboardKPIs, fetchCanonicalMonthlyTrend, fetchCanonicalTopCustomers } from '@/lib/canonicalFinancialQueries';
import { fetchTopProducts, fetchCategoryBreakdown, fetchRecommendations, fetchAlerts, fetchAgingBuckets } from '@/lib/queries';
import { formatCurrency, relativeTime } from '@/lib/format';
import type { Recommendation, Alert } from '@/lib/types';
import type { DashboardKPIs, MonthlyTrend, TopEntity, CategoryBreakdown, AgingBucket } from '@/lib/queries';
import { Link } from 'react-router-dom';
const TREND_RANGES=[{value:3,label:'3 أشهر'},{value:6,label:'6 أشهر'},{value:12,label:'12 شهرًا'}] as const;
export function DashboardPage(){
 const[kpis,setKpis]=useState<DashboardKPIs|null>(null),[trend,setTrend]=useState<MonthlyTrend[]>([]),[topCustomers,setTopCustomers]=useState<TopEntity[]>([]),[topProducts,setTopProducts]=useState<TopEntity[]>([]),[categories,setCategories]=useState<CategoryBreakdown[]>([]),[recommendations,setRecommendations]=useState<Recommendation[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[aging,setAging]=useState<AgingBucket[]>([]),[trendMonths,setTrendMonths]=useState(6),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null);
 const load=useCallback(async(silent=false)=>{try{if(silent)setRefreshing(true);else setLoading(true);setError(null);const[k,t,tc,tp,cat,recs,alts,ag]=await Promise.all([fetchCanonicalDashboardKPIs(),fetchCanonicalMonthlyTrend(trendMonths),fetchCanonicalTopCustomers(5),fetchTopProducts(5),fetchCategoryBreakdown(),fetchRecommendations(),fetchAlerts(),fetchAgingBuckets()]);setKpis(k);setTrend(t);setTopCustomers(tc);setTopProducts(tp);setCategories(cat);setRecommendations(recs);setAlerts(alts);setAging(ag);}catch(e){setError(e instanceof Error?e.message:'فشل تحميل البيانات')}finally{setLoading(false);setRefreshing(false)}},[trendMonths]);
 useEffect(()=>{void load()},[load]);
 if(loading)return <LoadingState message="جارٍ تحميل لوحة القيادة..."/>;if(error)return <ErrorState message={error} onRetry={()=>void load()}/>;if(!kpis)return null;const totalAging=aging.reduce((sum,b)=>sum+b.amount,0),dataStatusLabel=kpis.status==='INSUFFICIENT_DATA'?'بيانات غير كافية':'بيانات محسوبة من المصدر';
 return <div className="space-y-6 animate-fade-in"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-ink-900">لوحة القيادة</h1><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-medium ${kpis.status==='INSUFFICIENT_DATA'?'bg-ink-100 text-ink-500':'bg-success-50 text-success-700'}`}><CheckCircle2 size={13}/> {dataStatusLabel}</span></div><p className="mt-1 text-sm text-ink-500">نظرة تنفيذية على الأداء والذمم والمخزون والأولويات</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex items-center gap-1 rounded-xl border border-ink-200 bg-white p-1"><CalendarRange size={16} className="mx-2 text-ink-400"/>{TREND_RANGES.map(r=><button key={r.value} type="button" onClick={()=>setTrendMonths(r.value)} className={`rounded-lg px-3 py-1.5 text-xs font-medium ${trendMonths===r.value?'bg-primary-600 text-white':'text-ink-500 hover:bg-ink-50'}`}>{r.label}</button>)}</div><button type="button" onClick={()=>void load(true)} disabled={refreshing} className="btn-secondary"><RefreshCw size={16} className={refreshing?'animate-spin':''}/><span className="hidden sm:inline">تحديث</span></button></div></div>
 <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><KPICard label="إجمالي المبيعات" value={kpis.totalSales} format="currency" icon={<DollarSign size={16}/>} status={kpis.status}/><KPICard label="إجمالي الربح" value={kpis.grossProfit} format="currency" icon={<TrendingUp size={16}/>} status={kpis.status} hint={kpis.grossMargin===null?undefined:`هامش: ${kpis.grossMargin.toFixed(1)}%`}/><KPICard label="الذمم المدينة" value={kpis.totalReceivables} format="currency" icon={<Receipt size={16}/>} status={kpis.status} hint={kpis.overdueReceivables===null?undefined:`متأخرة: ${formatCurrency(kpis.overdueReceivables)}`}/><KPICard label="قيمة المخزون" value={kpis.inventoryValue} format="currency" icon={<Package size={16}/>} status={kpis.status}/><KPICard label="عدد العملاء" value={kpis.totalCustomers} format="number" icon={<Users size={16}/>} status="CONFIRMED"/><KPICard label="عدد المنتجات" value={kpis.totalProducts} format="number" icon={<Package size={16}/>} status="CONFIRMED"/><KPICard label="عدد الفواتير" value={kpis.invoiceCount} format="number" icon={<ShoppingCart size={16}/>} status="CONFIRMED"/><KPICard label="معدل التحصيل" value={kpis.collectionRate} format="percent" icon={<Wallet size={16}/>} status={kpis.status}/></div>
 <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader title="اتجاه المبيعات والربح" subtitle={`آخر ${trendMonths} أشهر`} action={<Badge variant="primary">تفاعلي</Badge>}/><CardBody><TrendChart data={trend}/></CardBody></Card><Card><CardHeader title="توزيع المبيعات حسب الفئة"/><CardBody><CategoryPieChart data={categories}/></CardBody></Card></div>
 <div className="grid grid-cols-1 gap-4 lg:grid-cols-2"><Card><CardHeader title="مركز الانتباه" action={<Link to="/intelligence">عرض الكل</Link>}/><CardBody><div className="space-y-3">{alerts.slice(0,4).map(a=><div key={a.id} className="flex items-start gap-3 rounded-lg bg-ink-50/50 p-3"><div className="mt-0.5"><AlertTriangle size={16}/></div><div className="min-w-0 flex-1"><span className="text-sm font-medium text-ink-800">{a.title}</span><SeverityBadge severity={a.severity}/>{a.description&&<p className="truncate text-xs text-ink-500">{a.description}</p>}</div><span className="text-[11px] text-ink-400">{relativeTime(a.created_at)}</span></div>)}{alerts.length===0&&<p className="py-4 text-center text-sm text-ink-400">لا توجد تنبيهات</p>}</div></CardBody></Card><Card><CardHeader title="التوصيات النشطة" action={<Link to="/intelligence/recommendations">عرض الكل</Link>}/><CardBody><div className="space-y-3">{recommendations.filter(r=>r.status==='new'||r.status==='accepted').slice(0,4).map(r=><div key={r.id} className="flex items-start gap-3 rounded-lg bg-ink-50/50 p-3"><Brain size={16}/><div><span className="text-sm font-medium text-ink-800">{r.title}</span><PriorityBadge priority={r.priority}/>{r.description&&<p className="text-xs text-ink-500">{r.description}</p>}</div></div>)}{recommendations.length===0&&<p className="py-4 text-center text-sm text-ink-400">لا توجد توصيات</p>}</div></CardBody></Card></div>
 <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card><CardHeader title="أفضل العملاء"/><CardBody><HorizontalBarChart data={topCustomers} dataKey="value" nameKey="name" height={220}/></CardBody></Card><Card><CardHeader title="أفضل المنتجات"/><CardBody><HorizontalBarChart data={topProducts} dataKey="value" nameKey="name" height={220}/></CardBody></Card><Card><CardHeader title="تحليل أعمار الذمم" subtitle={`الإجمالي: ${formatCurrency(totalAging)}`}/><CardBody><div className="space-y-3">{aging.map((b,i)=><div key={b.bucket}><div className="mb-1 flex justify-between"><span className="text-xs">{b.bucket} يوم</span><span className="text-xs">{formatCurrency(b.amount)}</span></div><div className="h-2 rounded-full bg-ink-100"><div className="h-full rounded-full bg-primary-500" style={{width:`${totalAging?(b.amount/totalAging)*100:0}%`}}/></div></div>)}{totalAging===0&&<p className="py-4 text-center text-sm text-ink-400">لا توجد ذمم مستحقة</p>}</div></CardBody></Card></div>
 <Card><CardHeader title="إجراءات سريعة"/><CardBody><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['/import',ArrowLeftRight,'استيراد بيانات'],['/reports',Receipt,'عرض التقارير'],['/analytics',TrendingUp,'التحليلات'],['/intelligence',Brain,'المساعد الذكي'],['/customers',Users,'العملاء'],['/inventory',Package,'المخزون']].map(([path,Icon,label])=>{const ActionIcon=Icon as typeof ArrowLeftRight;return <Link key={path as string} to={path as string} className="group flex flex-col items-center gap-2 rounded-lg border border-ink-100 p-4"><ActionIcon size={20}/><span className="text-xs font-medium">{label as string}</span></Link>})}</div></CardBody></Card></div>;
}