import { useCallback,useEffect,useState } from 'react';
import { AlertTriangle,Brain,CalendarRange,Database,DollarSign,Package,RefreshCw,Receipt,ShoppingCart,TrendingUp,Users,Wallet } from 'lucide-react';
import { Link } from 'react-router-dom';
import { KPICard } from '@/components/ui/KPICard';
import { Card,CardBody,CardHeader } from '@/components/ui/Card';
import { ErrorState,LoadingState } from '@/components/ui/States';
import { fetchDashboardIntelligence,fetchDashboardSnapshot } from '@/lib/dashboard-canonical';
import { formatCurrency } from '@/lib/format';
import type { DashboardKPIs } from '@/lib/dashboard-canonical';

const ranges=[{value:3,label:'3 أشهر'},{value:6,label:'6 أشهر'},{value:12,label:'12 شهرًا'}] as const;
const metric=(value:number|null)=>value===null?'INSUFFICIENT_DATA':'CONFIRMED';
export function DashboardResilientPage(){
 const[kpis,setKpis]=useState<DashboardKPIs|null>(null),[months,setMonths]=useState(6),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[intelligenceError,setIntelligenceError]=useState(false),[alertCount,setAlertCount]=useState(0),[recommendationCount,setRecommendationCount]=useState(0);
 const load=useCallback(async(silent=false)=>{silent?setRefreshing(true):setLoading(true);setError(null);setIntelligenceError(false);try{const snapshot=await fetchDashboardSnapshot(months);setKpis(snapshot.kpis);try{const intelligence=await fetchDashboardIntelligence();setAlertCount(intelligence.alerts.filter(a=>!a.is_read).length);setRecommendationCount(intelligence.recommendations.length);}catch(e){console.error('[DashboardResilientPage] intelligence failed',e);setAlertCount(0);setRecommendationCount(0);setIntelligenceError(true);}}catch(e){console.error('[DashboardResilientPage] snapshot failed',e);setError(e instanceof Error?e.message:'فشل تحميل بيانات لوحة القيادة');}finally{setLoading(false);setRefreshing(false);}},[months]);
 useEffect(()=>{void load();},[load]);
 if(loading)return <LoadingState message="جارٍ تجهيز لوحة القيادة..."/>;
 if(error)return <ErrorState message={error} onRetry={()=>void load()}/>;
 if(!kpis)return null;
 return <div dir="rtl" className="space-y-7 pb-10 animate-fade-in">
  <section className="experience-hero overflow-hidden"><div className="relative z-10 flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><span className="experience-chip border-white/10 bg-white/10 text-white"><Database size={14}/> EXECUTIVE WORKSPACE</span><h1 className="mt-5 text-4xl font-black tracking-tight text-white sm:text-6xl">صورة العمل الآن</h1><p className="mt-4 max-w-2xl text-sm leading-8 text-white/70">البيانات الأساسية أولًا. طبقات الذكاء لا تمنع الإدارة من رؤية الحقيقة المتاحة.</p></div><div className="grid grid-cols-2 gap-2"><div className="experience-kpi"><span className="text-[10px] text-white/50">المبيعات</span><strong className="mt-1 block text-lg">{kpis.totalSales===null?'—':formatCurrency(kpis.totalSales)}</strong></div><div className="experience-kpi"><span className="text-[10px] text-white/50">المخزون</span><strong className="mt-1 block text-lg">{kpis.inventoryValue===null?'—':formatCurrency(kpis.inventoryValue)}</strong></div></div></div></section>
  <section className="flex flex-wrap items-center justify-between gap-3 rounded-3xl border border-ink-100 bg-white p-4 shadow-sm"><div><div className="text-[10px] font-black tracking-[.16em] text-emerald-700">CONTROL BAR</div><div className="text-sm font-bold text-ink-900">الفترة الحالية</div></div><div className="flex flex-wrap items-center gap-2"><div className="flex items-center gap-1 rounded-xl border border-ink-200 bg-ink-50 p-1"><CalendarRange size={15} className="mx-2 text-ink-400"/>{ranges.map(r=><button key={r.value} type="button" onClick={()=>setMonths(r.value)} className={`rounded-lg px-3 py-2 text-xs font-bold ${months===r.value?'bg-white text-emerald-700 shadow-sm':'text-ink-500'}`}>{r.label}</button>)}</div><button type="button" onClick={()=>void load(true)} disabled={refreshing} className="btn-secondary"><RefreshCw size={15} className={refreshing?'animate-spin':''}/> تحديث</button></div></section>
  {intelligenceError&&<div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><AlertTriangle size={18} className="mt-0.5 text-amber-600"/><div className="flex-1"><div className="text-sm font-black text-amber-900">طبقة الذكاء غير متاحة مؤقتًا</div><p className="mt-1 text-xs leading-6 text-amber-800">تم عرض لوحة البيانات الأساسية بشكل طبيعي، ولم يتم اختراع أي إشارات أو توصيات.</p></div><Link to="/intelligence" className="text-xs font-bold text-amber-900">مركز الذكاء</Link></div>}
  {kpis.status==='INSUFFICIENT_DATA'&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><div className="font-bold">البيانات غير مكتملة لبعض المؤشرات</div><div className="mt-1 text-xs leading-6">لن نستبدل النقص بتقديرات. <Link className="font-bold underline" to="/data-quality">راجع جودة البيانات</Link>.</div></div>}
  <section><div className="mb-4"><div className="workspace-label">CORE SIGNALS</div><h2 className="workspace-title mt-1">مؤشرات القرار</h2></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><KPICard label="إجمالي المبيعات" value={kpis.totalSales} format="currency" icon={<DollarSign size={17}/>} status={metric(kpis.totalSales)}/><KPICard label="إجمالي الربح" value={kpis.grossProfit} format="currency" icon={<TrendingUp size={17}/>} status={metric(kpis.grossProfit)}/><KPICard label="الذمم المدينة" value={kpis.totalReceivables} format="currency" icon={<Receipt size={17}/>} status={metric(kpis.totalReceivables)}/><KPICard label="قيمة المخزون" value={kpis.inventoryValue} format="currency" icon={<Package size={17}/>} status={metric(kpis.inventoryValue)}/></div><div className="mt-3 grid grid-cols-2 gap-3 lg:grid-cols-4"><KPICard label="عدد العملاء" value={kpis.totalCustomers} format="number" icon={<Users size={17}/>} status={metric(kpis.totalCustomers)}/><KPICard label="عدد المنتجات" value={kpis.totalProducts} format="number" icon={<Package size={17}/>} status={metric(kpis.totalProducts)}/><KPICard label="عدد الفواتير" value={kpis.invoiceCount} format="number" icon={<ShoppingCart size={17}/>} status={metric(kpis.invoiceCount)}/><KPICard label="معدل التحصيل" value={kpis.collectionRate} format="percent" icon={<Wallet size={17}/>} status={metric(kpis.collectionRate)}/></div></section>
  <section className="grid gap-5 md:grid-cols-2"><Card><CardHeader title="التنبيهات" subtitle="من طبقة الذكاء الحالية"/><CardBody><div className="text-4xl font-black text-ink-900">{alertCount}</div><Link className="mt-3 inline-flex text-xs font-bold text-emerald-700" to="/intelligence">فتح مركز الذكاء ←</Link></CardBody></Card><Card><CardHeader title="التوصيات" subtitle="خطوات قابلة للمتابعة"/><CardBody><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><Brain size={20}/></span><div><div className="text-3xl font-black text-ink-900">{recommendationCount}</div><Link className="text-xs font-bold text-emerald-700" to="/intelligence/recommendations">مراجعة التوصيات ←</Link></div></div></CardBody></Card></section>
  <section className="experience-section"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="workspace-label">NEXT ACTION</div><h2 className="experience-section-title mt-1">من لوحة القيادة إلى القرار</h2></div><Link to="/assistant" className="btn-primary"><Brain size={16}/> اسأل المساعد الذكي</Link></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Link to="/reports" className="card p-4"><Receipt size={19} className="text-emerald-700"/><b className="mt-3 block text-sm">التقارير</b></Link><Link to="/analytics" className="card p-4"><TrendingUp size={19} className="text-emerald-700"/><b className="mt-3 block text-sm">التحليلات</b></Link><Link to="/intelligence/scenarios" className="card p-4"><Database size={19} className="text-emerald-700"/><b className="mt-3 block text-sm">ماذا لو؟</b></Link><Link to="/tasks" className="card p-4"><Users size={19} className="text-emerald-700"/><b className="mt-3 block text-sm">المهام والعمل</b></Link></div></section>
 </div>;
}
