import { useEffect, useState, useCallback } from 'react';
import { AlertTriangle, Brain, CalendarRange, Package, Receipt, RefreshCw, ShoppingCart, TrendingUp, Users, Wallet } from 'lucide-react';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { Badge, SeverityBadge, PriorityBadge } from '@/components/ui/Badge';
import { LoadingState, ErrorState } from '@/components/ui/States';
import { TrendChart, CategoryPieChart, HorizontalBarChart } from '@/components/ui/Charts';
import { KPICard } from '@/components/ui/KPICard';
import { Link } from 'react-router-dom';
import { fetchCanonicalDashboardKPIs } from '@/lib/canonical-data-truth';
import { fetchCanonicalMonthlyTrend, fetchCanonicalTopCustomers, fetchCanonicalTopProducts, fetchCanonicalCategoryBreakdown, fetchCanonicalAgingTruth, type CanonicalRowsResult, type CanonicalTopEntity, type CanonicalCategoryBreakdown, type CanonicalAgingBucket } from '@/lib/canonical-secondary-data-truth';
import { fetchRecommendations, fetchAlerts } from '@/lib/queries';
import type { Recommendation, Alert } from '@/lib/types';
import { formatCurrency, relativeTime } from '@/lib/format';

const TREND_RANGES = [{ value: 3, label: '3 أشهر' }, { value: 6, label: '6 أشهر' }, { value: 12, label: '12 شهرًا' }] as const;
type KPI = Awaited<ReturnType<typeof fetchCanonicalDashboardKPIs>>;

export function DashboardPage() {
  const [kpis, setKpis] = useState<KPI | null>(null); const [trendMonths, setTrendMonths] = useState(6);
  const [trend, setTrend] = useState<Awaited<ReturnType<typeof fetchCanonicalMonthlyTrend>>>([]);
  const [topCustomers, setTopCustomers] = useState<CanonicalRowsResult<CanonicalTopEntity>>([] as never);
  const [topProducts, setTopProducts] = useState<CanonicalRowsResult<CanonicalTopEntity>>([] as never);
  const [categories, setCategories] = useState<CanonicalRowsResult<CanonicalCategoryBreakdown>>([] as never);
  const [aging, setAging] = useState<CanonicalRowsResult<CanonicalAgingBucket>>([] as never);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async (silent = false) => { try { silent ? setRefreshing(true) : setLoading(true); setError(null); const [k,t,tc,tp,cat,ag,recs,alts] = await Promise.all([fetchCanonicalDashboardKPIs(),fetchCanonicalMonthlyTrend(trendMonths),fetchCanonicalTopCustomers(5),fetchCanonicalTopProducts(5),fetchCanonicalCategoryBreakdown(),fetchCanonicalAgingTruth(),fetchRecommendations(),fetchAlerts()]); setKpis(k);setTrend(t);setTopCustomers(tc);setTopProducts(tp);setCategories(cat);setAging(ag);setRecommendations(recs);setAlerts(alts); } catch(e:unknown){setError(e instanceof Error?e.message:'فشل تحميل البيانات');} finally{setLoading(false);setRefreshing(false);} },[trendMonths]);
  useEffect(()=>{void load();},[load]); if(loading)return <LoadingState message="جارٍ تحميل لوحة القيادة..."/>; if(error)return <ErrorState message={error} onRetry={()=>void load()}/>; if(!kpis)return null;
  const totalAging=aging.reduce((sum,b)=>sum+b.amount,0); const customerChart=topCustomers.filter(r=>r.value!==null); const productChart=topProducts.filter(r=>r.value!==null); const categoryChart=categories.filter(r=>r.sales!==null); const dataStatus=kpis.status==='INSUFFICIENT_DATA'?'بيانات غير كافية':'بيانات محسوبة من المصدر';
  return <div className="space-y-6 animate-fade-in"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-ink-900">لوحة القيادة</h1><Badge variant={kpis.status==='INSUFFICIENT_DATA'?'warning':'success'}>{dataStatus}</Badge></div><p className="mt-1 text-sm text-ink-500">المؤشرات التجارية من canonical domain truth، وليست من صفوف الصفحة.</p></div><div className="flex gap-2"><div className="flex items-center gap-1 rounded-xl border border-ink-200 bg-white p-1"><CalendarRange size={16} className="mx-2 text-ink-400"/>{TREND_RANGES.map(r=><button key={r.value} type="button" onClick={()=>setTrendMonths(r.value)} className={`rounded-lg px-3 py-1.5 text-xs font-medium ${trendMonths===r.value?'bg-primary-600 text-white':'text-ink-500 hover:bg-ink-50'}`}>{r.label}</button>)}</div><button type="button" onClick={()=>void load(true)} disabled={refreshing} className="btn-secondary"><RefreshCw size={16} className={refreshing?'animate-spin':''}/></button></div></div>
  <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><KPICard label="إجمالي المبيعات" value={kpis.totalSales} format="currency" icon={<ShoppingCart size={16}/>} status={kpis.status}/><KPICard label="إجمالي الربح" value={kpis.grossProfit} format="currency" icon={<TrendingUp size={16}/>} status={kpis.status}/><KPICard label="الذمم المدينة" value={kpis.totalReceivables} format="currency" icon={<Receipt size={16}/>} status={kpis.status}/><KPICard label="قيمة المخزون" value={kpis.inventoryValue} format="currency" icon={<Package size={16}/>} status={kpis.inventoryValue===null?'INSUFFICIENT_DATA':'CALCULATED'}/><KPICard label="عدد العملاء" value={kpis.totalCustomers} format="number" icon={<Users size={16}/>} status="CONFIRMED"/><KPICard label="عدد المنتجات" value={kpis.totalProducts} format="number" icon={<Package size={16}/>} status="CONFIRMED"/><KPICard label="عدد الفواتير" value={kpis.invoiceCount} format="number" icon={<ShoppingCart size={16}/>} status="CONFIRMED"/><KPICard label="معدل التحصيل" value={kpis.collectionRate} format="percent" icon={<Wallet size={16}/>} status={kpis.status}/></div>
  <div className="flex flex-wrap gap-2"><Badge variant={categories.status==='INSUFFICIENT_DATA'?'warning':'success'}>{categories.status==='INSUFFICIENT_DATA'?'ربحية الفئات غير مكتملة':'ربحية الفئات محسوبة'}</Badge><Badge variant={aging.status==='INSUFFICIENT_DATA'?'warning':'success'}>{aging.status==='INSUFFICIENT_DATA'?'بيانات الذمم غير مكتملة':`أعمار الذمم محسوبة — ${aging.asOf??'اليوم'}`}</Badge></div>
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader title="اتجاه المبيعات والربح" subtitle={`آخر ${trendMonths} أشهر`}/><CardBody><TrendChart data={trend}/></CardBody></Card><Card><CardHeader title="المبيعات حسب الفئة"/><CardBody><CategoryPieChart data={categoryChart}/></CardBody></Card></div>
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card><CardHeader title="أفضل العملاء"/><CardBody><HorizontalBarChart data={customerChart} dataKey="value" nameKey="name" height={240}/></CardBody></Card><Card><CardHeader title="أفضل المنتجات"/><CardBody><HorizontalBarChart data={productChart} dataKey="value" nameKey="name" height={240}/></CardBody></Card><Card><CardHeader title="أعمار الذمم" subtitle={`الإجمالي ${formatCurrency(totalAging)}`}/><CardBody><div className="space-y-2">{aging.map(r=><div key={r.bucket} className="flex justify-between text-sm"><span>{r.bucket}</span><span className="font-semibold">{formatCurrency(r.amount)} · {r.count}</span></div>)}{aging.length===0&&<div className="text-sm text-ink-400">لا توجد بيانات</div>}</div></CardBody></Card></div>
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-2"><Card><CardHeader title="مركز الانتباه" action={<Link to="/intelligence" className="text-xs text-primary-600">عرض الكل</Link>}/><CardBody><div className="space-y-2">{alerts.slice(0,4).map(a=><div key={a.id} className="flex items-start gap-2 rounded-lg bg-ink-50 p-3"><AlertTriangle size={16} className="mt-0.5 text-warning-600"/><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="text-sm font-medium">{a.title}</span><SeverityBadge severity={a.severity}/></div>{a.description&&<p className="text-xs text-ink-500">{a.description}</p>}</div><span className="text-[11px] text-ink-400">{relativeTime(a.created_at)}</span></div>)}{alerts.length===0&&<div className="text-sm text-ink-400">لا توجد تنبيهات</div>}</div></CardBody></Card><Card><CardHeader title="التوصيات النشطة" action={<Link to="/intelligence/recommendations" className="text-xs text-primary-600">عرض الكل</Link>}/><CardBody><div className="space-y-2">{recommendations.filter(r=>r.status==='new'||r.status==='accepted').slice(0,4).map(r=><div key={r.id} className="flex items-start gap-2 rounded-lg bg-ink-50 p-3"><Brain size={16} className="mt-0.5 text-accent-600"/><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="text-sm font-medium">{r.title}</span><PriorityBadge priority={r.priority}/></div>{r.description&&<p className="text-xs text-ink-500">{r.description}</p>}</div></div>)}</div></CardBody></Card></div></div>;
}
