import { useCallback, useEffect, useState } from 'react';
import type { LucideIcon } from 'lucide-react';
import { Users, Package, Warehouse, CheckCircle2, BarChart3, Sparkles, Upload, Brain, ArrowUpLeft, RefreshCw, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card, CardHeader, CardBody } from '@/components/ui/Card';
import { LoadingState, ErrorState, EmptyState } from '@/components/ui/States';
import { DataTable } from '@/components/ui/DataTable';
import { fetchDataQualitySnapshot, type QualityIssue, type EntityQuality } from '@/lib/data-quality-snapshot';
import { formatNumber } from '@/lib/format';
function scoreColor(score:number){return score>=90?'text-success-600':score>=70?'text-warning-600':'text-danger-600'}
function scoreBg(score:number){return score>=90?'bg-success-500':score>=70?'bg-warning-500':'bg-danger-500'}
function issueBadge(severity:QualityIssue['severity']){return severity==='critical'?'bg-danger-50 text-danger-700 ring-danger-100':severity==='warning'?'bg-warning-50 text-warning-700 ring-warning-100':'bg-ink-100 text-ink-600 ring-ink-200'}
const iconMap:Record<EntityQuality['icon'],LucideIcon>={users:Users,package:Package,receipt:BarChart3,warehouse:Warehouse};
export function DataQualitySnapshotPage(){
 const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[issues,setIssues]=useState<QualityIssue[]>([]);const[entities,setEntities]=useState<EntityQuality[]>([]);const[overallScore,setOverallScore]=useState(0);
 const load=useCallback(async()=>{try{setLoading(true);setError(null);const snapshot=await fetchDataQualitySnapshot();setEntities(snapshot.entities);setIssues(snapshot.issues.filter(i=>i.count>0).sort((a,b)=>b.count-a.count));const total=snapshot.entities.reduce((s,e)=>s+e.total,0);const bad=snapshot.entities.reduce((s,e)=>s+e.issues,0);setOverallScore(total===0?0:Math.max(0,Math.min(100,Math.round(((total-bad)/total)*100))))}catch(e:unknown){setError(e instanceof Error?e.message:'فشل تحميل بيانات الجودة')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 if(loading)return <LoadingState message="جارٍ فحص جودة البيانات..."/>;if(error)return <ErrorState message={error} onRetry={load}/>;
 const totalRecords=entities.reduce((s,e)=>s+e.total,0),totalIssues=entities.reduce((s,e)=>s+e.issues,0),healthy=Math.max(0,totalRecords-totalIssues),critical=issues.filter(i=>i.severity==='critical').reduce((s,i)=>s+i.count,0);
 return <div dir="rtl" className="space-y-8 pb-12 animate-fade-in">
  <section className="experience-hero relative overflow-hidden" aria-labelledby="data-trust-title"><div className="absolute -left-20 -top-24 h-72 w-72 rounded-full bg-amber-300/15 blur-3xl"/><div className="absolute bottom-[-120px] right-20 h-80 w-80 rounded-full bg-teal-300/10 blur-3xl"/><div className="relative z-10 grid gap-8 xl:grid-cols-[1.35fr_.65fr] xl:items-end"><div><div className="experience-chip"><Sparkles size={14}/> DATA TRUST</div><h1 id="data-trust-title" className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">غرفة ثقة البيانات</h1><p className="mt-4 max-w-3xl text-sm leading-8 text-white/70 sm:text-base">قبل أن نقرأ الأداء أو نبني توصية، نثبت أولًا أن المادة الخام قابلة للثقة. هذه الشاشة لا تجمّل النقص؛ تكشفه وتوصلك إلى الخطوة التالية.</p><div className="mt-7 flex flex-wrap gap-2"><Link to="/import" className="btn-primary" aria-label="إدخال أو تحديث البيانات"><Upload size={16}/> إدخال أو تحديث البيانات</Link><Link to="/intelligence" className="btn-secondary border-white/15 bg-white/10 text-white hover:bg-white/15"><Brain size={16}/> العودة إلى الذكاء</Link><button type="button" onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-xs font-bold text-white hover:bg-white/15 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-white/20"><RefreshCw size={15}/> إعادة الفحص</button></div></div><div className="grid grid-cols-2 gap-3" aria-label="ملخص الثقة"><div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur-xl"><div className="text-[10px] font-black tracking-[.16em] text-white/45">TRUST SCORE</div><div className="mt-2 text-4xl font-black text-white">{overallScore}%</div><div className="mt-1 text-xs text-white/55">درجة الثقة الحالية</div></div><div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur-xl"><div className="text-[10px] font-black tracking-[.16em] text-white/45">CRITICAL</div><div className="mt-2 text-4xl font-black text-white">{formatNumber(critical)}</div><div className="mt-1 text-xs text-white/55">سجلات حرجة</div></div></div></div></section>
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4" aria-label="مؤشرات جودة البيانات"><div className="experience-metric"><div className="experience-metric-label">إجمالي السجلات</div><div className="experience-metric-value">{formatNumber(totalRecords)}</div><div className="mt-1 text-xs text-ink-400">المادة التي تم فحصها</div></div><div className="experience-metric"><div className="experience-metric-label">سجلات سليمة</div><div className="experience-metric-value text-success-700">{formatNumber(healthy)}</div><div className="mt-1 text-xs text-ink-400">قابلة للقراءة حاليًا</div></div><div className="experience-metric"><div className="experience-metric-label">مشاكل مكتشفة</div><div className="experience-metric-value text-warning-700">{formatNumber(totalIssues)}</div><div className="mt-1 text-xs text-ink-400">تحتاج مراجعة أو معالجة</div></div><div className="experience-metric"><div className="experience-metric-label">كيانات مفحوصة</div><div className="experience-metric-value">{entities.length}</div><div className="mt-1 text-xs text-ink-400">نطاقات البيانات الحالية</div></div></section>
  <Card className="overflow-hidden rounded-[1.8rem] border-0 shadow-elevated"><CardBody className="p-5 sm:p-8"><div className="grid gap-8 lg:grid-cols-[190px_1fr] lg:items-center"><div className="relative mx-auto h-40 w-40" role="img" aria-label={`درجة الثقة ${overallScore} بالمئة`}><svg className="h-full w-full -rotate-90" viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="52" fill="none" stroke="currentColor" strokeWidth="10" className="text-ink-100"/><circle cx="60" cy="60" r="52" fill="none" stroke="currentColor" strokeWidth="10" className={scoreColor(overallScore)} strokeDasharray={`${overallScore/100*327} 327`} strokeLinecap="round"/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className={`text-4xl font-black ${scoreColor(overallScore)}`}>{overallScore}%</span><span className="mt-1 text-[11px] font-bold text-ink-400">الثقة</span></div></div><div><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-[10px] font-black tracking-[.16em] text-emerald-700">TRUTH GATE</div><h2 className="mt-1 text-2xl font-black text-ink-950">هل البيانات جاهزة للقرار؟</h2><p className="mt-1 text-xs leading-6 text-ink-400">الدرجة مبنية على السجلات والمشاكل التي أعادها مصدر الجودة الفعلي.</p></div><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-bold ${totalRecords===0?'bg-ink-100 text-ink-600':overallScore>=90?'bg-success-50 text-success-700':overallScore>=70?'bg-warning-50 text-warning-700':'bg-danger-50 text-danger-700'}`}>{totalRecords===0?'لا توجد بيانات':overallScore>=90?'جاهزة للقرار':overallScore>=70?'تحتاج مراجعة':'تحتاج معالجة'}</span></div></div></CardBody></Card>
  <section><div className="mb-5 px-1"><div className="text-[10px] font-black tracking-[.16em] text-emerald-700">ENTITY HEALTH</div><h2 className="mt-1 text-2xl font-black text-ink-950">صحة نطاقات البيانات</h2><p className="mt-1 text-xs text-ink-400">لا يكفي أن تكون الدرجة العامة جيدة؛ نرى أين توجد المشكلة بالضبط.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{entities.map(e=>{const Icon=iconMap[e.icon];return <Card key={e.name} className="group rounded-[1.5rem] border-0 shadow-elevated transition hover:-translate-y-1"><CardBody className="p-5"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon size={20}/></div><span className={`text-2xl font-black ${scoreColor(e.score)}`}>{e.score}%</span></div><div className="mt-5 font-black text-ink-800">{e.name}</div><div className="mt-1 text-xs text-ink-400">{formatNumber(e.total)} سجل</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-ink-100" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={e.score} aria-label={`جودة ${e.name}`}><div className={`h-full rounded-full ${scoreBg(e.score)}`} style={{width:`${Math.max(0,Math.min(100,e.score))}%`}}/></div><div className={`mt-3 text-xs font-semibold ${e.issues>0?'text-warning-600':'text-success-600'}`}>{e.issues>0?`${formatNumber(e.issues)} مشكلة تحتاج انتباهًا`:'البيانات بحالة جيدة'}</div></CardBody></Card>})}</div></section>
  <Card className="rounded-[1.7rem] border-0 shadow-elevated"><CardHeader title="المشاكل المكتشفة" subtitle="مرتبة حسب حجم التأثير على البيانات"/>{issues.length===0?<CardBody><EmptyState icon={<CheckCircle2 size={32}/>} title="لا توجد مشاكل في جودة البيانات" message={totalRecords===0?'لا توجد بيانات تجارية بعد؛ النتيجة EMPTY وليست نجاح جودة بيانات.':'جميع السجلات سليمة ومكتملة'}/></CardBody>:<DataTable columns={[{key:'entity',label:'الكيان',render:(r:QualityIssue)=><span className="font-bold text-ink-800">{r.entity}</span>},{key:'field',label:'الحقل',render:(r:QualityIssue)=>r.field},{key:'issue',label:'المشكلة',render:(r:QualityIssue)=>r.issue},{key:'count',label:'العدد',align:'center',render:(r:QualityIssue)=><span className="font-black">{formatNumber(r.count)}</span>},{key:'severity',label:'الخطورة',align:'center',render:(r:QualityIssue)=><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ring-1 ${issueBadge(r.severity)}`}>{r.severity==='critical'?'حرجة':r.severity==='warning'?'تحذير':'معلومة'}</span>}] } data={issues} emptyMessage="لا توجد مشاكل"/>}</Card>
  <div className="rounded-[1.7rem] border border-emerald-100 bg-gradient-to-l from-emerald-50 via-white to-amber-50/60 p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-black text-ink-900"><ShieldCheck size={18} className="text-emerald-700"/> قاعدة المنتج</div><p className="mt-1 text-xs leading-6 text-ink-500">نحن لا نحول غياب البيانات إلى نجاح مصطنع. عندما لا توجد مادة كافية، تظهر الحالة كما هي وتبقى الخطوة التالية واضحة.</p></div><Link to="/import" className="btn-secondary w-fit"><ArrowUpLeft size={15}/> تحسين المصدر</Link></div></div>
 </div>
}
