import { useCallback, useEffect, useState } from 'react';
import type { LucideIcon } from 'lucide-react';
import { Users, Package, Warehouse, CheckCircle2, AlertTriangle, Database, ShieldCheck, BarChart3, Sparkles } from 'lucide-react';
import { Card, CardHeader, CardBody } from '@/components/ui/Card';
import { PageHeader, LoadingState, ErrorState, EmptyState } from '@/components/ui/States';
import { DataTable } from '@/components/ui/DataTable';
import { fetchDataQualitySnapshot, type QualityIssue, type EntityQuality } from '@/lib/data-quality-snapshot';
import { formatNumber } from '@/lib/format';

function scoreColor(score: number): string { if (score >= 90) return 'text-success-600'; if (score >= 70) return 'text-warning-600'; return 'text-danger-600'; }
function scoreBg(score: number): string { if (score >= 90) return 'bg-success-500'; if (score >= 70) return 'bg-warning-500'; return 'bg-danger-500'; }
function issueBadge(severity: QualityIssue['severity']): string { return severity === 'critical' ? 'bg-danger-50 text-danger-700 ring-danger-100' : severity === 'warning' ? 'bg-warning-50 text-warning-700 ring-warning-100' : 'bg-ink-100 text-ink-600 ring-ink-200'; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'فشل تحميل بيانات الجودة'; }
const iconMap: Record<EntityQuality['icon'], LucideIcon> = { users: Users, package: Package, receipt: BarChart3, warehouse: Warehouse };

export function DataQualitySnapshotPage() {
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [issues, setIssues] = useState<QualityIssue[]>([]); const [entities, setEntities] = useState<EntityQuality[]>([]); const [overallScore, setOverallScore] = useState(0);
  const load = useCallback(async () => { try { setLoading(true); setError(null); const snapshot = await fetchDataQualitySnapshot(); setEntities(snapshot.entities); setIssues(snapshot.issues.filter(i => i.count > 0).sort((a,b) => b.count-a.count)); const totalRecords = snapshot.entities.reduce((s,e)=>s+e.total,0); const totalIssues = snapshot.entities.reduce((s,e)=>s+e.issues,0); setOverallScore(totalRecords === 0 ? 0 : Math.max(0, Math.min(100, Math.round(((totalRecords-totalIssues)/totalRecords)*100)))); } catch (e: unknown) { setError(errorMessage(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <LoadingState message="جارٍ فحص جودة البيانات..." />;
  if (error) return <ErrorState message={error} onRetry={load} />;
  const totalRecords = entities.reduce((s,e)=>s+e.total,0); const totalIssues = entities.reduce((s,e)=>s+e.issues,0);
  const healthyRecords = Math.max(0,totalRecords-totalIssues);
  return <div dir="rtl" className="space-y-7 pb-8 animate-fade-in">
    <section className="experience-hero relative overflow-hidden rounded-[2rem] px-6 py-8 sm:px-9 sm:py-10 lg:px-12">
      <div className="absolute -left-16 -top-20 h-64 w-64 rounded-full bg-amber-300/15 blur-3xl"/><div className="absolute bottom-[-100px] right-10 h-72 w-72 rounded-full bg-teal-300/10 blur-3xl"/>
      <div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between">
        <div className="max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[11px] font-bold tracking-[.15em] text-amber-100"><Sparkles size={13}/>DATA TRUST</div><h1 className="text-3xl font-black text-white sm:text-5xl">جودة البيانات</h1><p className="mt-4 text-sm leading-7 text-emerald-50/75 sm:text-base">غرفة ثقة البيانات: اكتشف النقص والتعارضات قبل أن تتحول إلى قرار خاطئ، مع إبقاء الحقيقة القادمة من المصدر كما هي.</p></div>
        <button type="button" onClick={()=>void load()} className="inline-flex items-center justify-center rounded-xl border border-white/15 bg-white/10 px-5 py-3 text-sm font-bold text-white backdrop-blur transition hover:bg-white/15">إعادة الفحص</button>
      </div>
    </section>

    <Card className="overflow-hidden rounded-[1.75rem] border-0 shadow-elevated"><CardBody className="p-5 sm:p-7"><div className="grid gap-7 lg:grid-cols-[180px_1fr] lg:items-center">
      <div className="relative mx-auto h-40 w-40"><svg className="h-full w-full -rotate-90" viewBox="0 0 120 120"><circle cx="60" cy="60" r="52" fill="none" stroke="currentColor" strokeWidth="10" className="text-ink-100"/><circle cx="60" cy="60" r="52" fill="none" stroke="currentColor" strokeWidth="10" className={overallScore>=90?'text-success-500':overallScore>=70?'text-warning-500':'text-danger-500'} strokeDasharray={`${(overallScore/100)*327} 327`} strokeLinecap="round"/></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className={`text-4xl font-black ${scoreColor(overallScore)}`}>{overallScore}%</span><span className="mt-1 text-[11px] font-bold text-ink-400">درجة الثقة</span></div></div>
      <div><div className="mb-5 flex items-end justify-between"><div><h2 className="text-xl font-black text-ink-900">ملخص الحالة</h2><p className="mt-1 text-xs text-ink-400">قراءة مجمعة للكيانات المفحوصة</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${overallScore>=90?'bg-success-50 text-success-700':overallScore>=70?'bg-warning-50 text-warning-700':'bg-danger-50 text-danger-700'}`}>{overallScore>=90?'جاهزة للقرار':overallScore>=70?'تحتاج مراجعة':'تحتاج معالجة'}</span></div>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-ink-50 p-4"><Database className="text-primary-600" size={18}/><div className="mt-3 text-2xl font-black text-ink-900">{formatNumber(totalRecords)}</div><div className="mt-1 text-xs text-ink-400">إجمالي السجلات</div></div><div className="rounded-2xl bg-success-50/70 p-4"><CheckCircle2 className="text-success-600" size={18}/><div className="mt-3 text-2xl font-black text-success-700">{formatNumber(healthyRecords)}</div><div className="mt-1 text-xs text-ink-400">سجلات سليمة</div></div><div className="rounded-2xl bg-warning-50/70 p-4"><AlertTriangle className="text-warning-600" size={18}/><div className="mt-3 text-2xl font-black text-warning-700">{formatNumber(totalIssues)}</div><div className="mt-1 text-xs text-ink-400">مشاكل مكتشفة</div></div><div className="rounded-2xl bg-emerald-50 p-4"><ShieldCheck className="text-emerald-700" size={18}/><div className="mt-3 text-2xl font-black text-ink-900">{entities.length}</div><div className="mt-1 text-xs text-ink-400">كيانات مفحوصة</div></div></div></div>
    </div></CardBody></Card>

    <section><div className="mb-4 px-1"><h2 className="text-lg font-black text-ink-900">صحة الكيانات</h2><p className="mt-1 text-xs text-ink-400">مقارنة سريعة لجودة كل نطاق من نطاقات البيانات.</p></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{entities.map(e=>{const Icon=iconMap[e.icon];return <Card key={e.name} className="rounded-[1.4rem] border-0 shadow-elevated transition-transform hover:-translate-y-0.5"><CardBody className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon size={20}/></div><span className={`text-2xl font-black ${scoreColor(e.score)}`}>{e.score}%</span></div><div className="mt-5 font-bold text-ink-800">{e.name}</div><div className="mt-1 text-xs text-ink-400">{formatNumber(e.total)} سجل</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-ink-100"><div className={`h-full rounded-full transition-all duration-700 ${scoreBg(e.score)}`} style={{width:`${Math.max(0,Math.min(100,e.score))}%`}}/></div><div className={`mt-3 text-xs font-semibold ${e.issues>0?'text-warning-600':'text-success-600'}`}>{e.issues>0?`${formatNumber(e.issues)} مشكلة تحتاج انتباهًا`:'البيانات بحالة جيدة'}</div></CardBody></Card>})}</div></section>

    <Card className="rounded-[1.5rem] border-0 shadow-elevated"><CardHeader title="المشاكل المكتشفة" subtitle="مرتبة حسب حجم التأثير على البيانات" />{issues.length===0?<CardBody><EmptyState icon={<CheckCircle2 size={32}/>} title="لا توجد مشاكل في جودة البيانات" message={totalRecords===0?'لا توجد بيانات تجارية بعد؛ النتيجة EMPTY وليست نجاح جودة بيانات.':'جميع السجلات سليمة ومكتملة'}/></CardBody>:<DataTable columns={[{key:'entity',label:'الكيان',render:(r:QualityIssue)=><span className="font-bold text-ink-800">{r.entity}</span>},{key:'field',label:'الحقل',render:(r:QualityIssue)=>r.field},{key:'issue',label:'المشكلة',render:(r:QualityIssue)=>r.issue},{key:'count',label:'العدد',align:'center',render:(r:QualityIssue)=><span className="font-black text-ink-800">{formatNumber(r.count)}</span>},{key:'severity',label:'الخطورة',align:'center',render:(r:QualityIssue)=><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ring-1 ${issueBadge(r.severity)}`}>{r.severity==='critical'?'حرجة':r.severity==='warning'?'تحذير':'معلومة'}</span>}] } data={issues} emptyMessage="لا توجد مشاكل"/>}</Card>
  </div>;
}
