import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileSearch, Lightbulb, Play, ShieldCheck, Target, Workflow } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { fetchAlerts, fetchRecommendations } from '@/lib/queries';
import { convertAcceptedTaskProposal, fetchTaskProposals, type PersistedTaskProposal } from '@/lib/role-task-persistence';
import { fetchActiveTenantAssignees, fetchApprovedDecisions, fetchDecisionWorkItems, completeDecisionWorkItem, recordDecisionOutcome, startDecisionWorkItem, type RuntimeDecision, type RuntimeWorkItem, type TenantAssignee } from '@/lib/decision-runtime';
import type { Alert, Recommendation } from '@/lib/types';

type Stage = 'command' | 'evidence' | 'decision' | 'approval' | 'work' | 'outcome';
const stages: { id: Stage; label: string; description: string }[] = [
 { id: 'command', label: 'مركز القيادة', description: 'المعلومة والأولوية' },
 { id: 'evidence', label: 'الدليل', description: 'المصدر والسياق' },
 { id: 'decision', label: 'القرار', description: 'التوصية والقرار المحفوظ' },
 { id: 'approval', label: 'الموافقة', description: 'حالة الاعتماد الفعلية' },
 { id: 'work', label: 'التنفيذ', description: 'المهمة والمتابعة' },
 { id: 'outcome', label: 'النتيجة والتعلّم', description: 'Expected → Actual' },
];
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="rounded-2xl border border-dashed border-ink-300 bg-ink-50 p-6 text-center"><p className="font-semibold text-ink-800">{title}</p><p className="mt-2 text-xs leading-6 text-ink-500">{detail}</p></div>; }
function Notice({ children, tone = 'amber' }: { children: string; tone?: 'amber' | 'green' | 'red' }) { const cls = tone === 'green' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : tone === 'red' ? 'border-red-200 bg-red-50 text-red-900' : 'border-amber-200 bg-amber-50 text-amber-900'; return <div role="status" className={`rounded-2xl border p-4 text-sm ${cls}`}>{children}</div>; }
const assigneeLabel = (a: TenantAssignee) => `${a.role} · ${a.user_id.slice(0, 8)}…`;

export function DecisionExperiencePage() {
 const [params, setParams] = useSearchParams();
 const requested = params.get('stage') as Stage | null;
 const [stage, setStage] = useState<Stage>(stages.some(s => s.id === requested) ? requested! : 'command');
 const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [proposals, setProposals] = useState<PersistedTaskProposal[]>([]); const [decisions, setDecisions] = useState<RuntimeDecision[]>([]); const [assignees, setAssignees] = useState<TenantAssignee[]>([]); const [workItems, setWorkItems] = useState<RuntimeWorkItem[]>([]);
 const [selectedId, setSelectedId] = useState(params.get('recommendationId')); const [proposalId, setProposalId] = useState(params.get('proposalId')); const [decisionId, setDecisionId] = useState(params.get('decisionId')); const [assigneeId, setAssigneeId] = useState(''); const [evidenceSnapshotId, setEvidenceSnapshotId] = useState(''); const [actualImpact, setActualImpact] = useState(''); const [outcomeLabel, setOutcomeLabel] = useState<'correct' | 'incorrect' | 'partial' | 'unknown'>('unknown'); const [outcomeNotes, setOutcomeNotes] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
 const load = useCallback(async () => { setLoading(true); setError(null); try { const [r, a, p, d, m] = await Promise.all([fetchRecommendations(), fetchAlerts(), fetchTaskProposals(), fetchApprovedDecisions(), fetchActiveTenantAssignees()]); setRecommendations(r); setAlerts(a); setProposals(p); setDecisions(d); setAssignees(m); setSelectedId(current => current && r.some(x => x.id === current) ? current : r[0]?.id ?? null); setProposalId(current => current && p.some(x => x.id === current) ? current : p.find(x => x.status === 'accepted')?.id ?? null); setDecisionId(current => current && d.some(x => x.id === current) ? current : d.find(x => x.recommendation_id === selectedId)?.id ?? d[0]?.id ?? null); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تحميل دورة القرار.'); } finally { setLoading(false); } }, [selectedId]);
 useEffect(() => { void load(); }, [load]);
 const selected = recommendations.find(r => r.id === selectedId) ?? null; const selectedProposal = proposals.find(p => p.id === proposalId) ?? null; const selectedDecision = decisions.find(d => d.id === decisionId) ?? null; const selectedWork = workItems.find(w => w.decision_id === decisionId) ?? null;
 useEffect(() => { if (!decisionId) { setWorkItems([]); return; } void fetchDecisionWorkItems(decisionId).then(setWorkItems).catch(e => setError(e instanceof Error ? e.message : 'تعذر تحميل المهمة التنفيذية.')); }, [decisionId]);
 const go = (next: Stage, id = selectedId) => { setStage(next); const p = new URLSearchParams(params); p.set('stage', next); if (id) p.set('recommendationId', id); else p.delete('recommendationId'); if (proposalId) p.set('proposalId', proposalId); if (decisionId) p.set('decisionId', decisionId); setParams(p, { replace: true }); };
 const approvedForRecommendation = useMemo(() => decisions.filter(d => !selectedId || d.recommendation_id === selectedId), [decisions, selectedId]);
 const convert = async () => { if (!selectedProposal || !selectedDecision) return; setBusy(true); setError(null); try { const id = await convertAcceptedTaskProposal({ proposalId: selectedProposal.id, decisionId: selectedDecision.id, assigneeId: assigneeId || null, assigneeLabel: assigneeId ? assignees.find(a => a.user_id === assigneeId) ? assigneeLabel(assignees.find(a => a.user_id === assigneeId)!) : null : null }); setDecisionId(selectedDecision.id); setWorkItems(await fetchDecisionWorkItems(selectedDecision.id)); setError(null); const p = new URLSearchParams(params); p.set('stage', 'work'); p.set('decisionId', selectedDecision.id); p.set('proposalId', selectedProposal.id); setParams(p, { replace: true }); setStage('work'); void id; } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تحويل المقترح إلى مهمة.'); } finally { setBusy(false); } };
 const start = async () => { if (!selectedWork) return; setBusy(true); try { await startDecisionWorkItem(selectedWork.id); setWorkItems(await fetchDecisionWorkItems(selectedWork.decision_id)); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر بدء المهمة.'); } finally { setBusy(false); } };
 const complete = async () => { if (!selectedWork) return; setBusy(true); try { await completeDecisionWorkItem(selectedWork.id, actualImpact === '' ? null : Number(actualImpact), evidenceSnapshotId); setWorkItems(await fetchDecisionWorkItems(selectedWork.decision_id)); setStage('outcome'); const p = new URLSearchParams(params); p.set('stage', 'outcome'); setParams(p, { replace: true }); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر إكمال المهمة.'); } finally { setBusy(false); } };
 const outcome = async () => { if (!selectedWork || !selectedDecision) return; setBusy(true); try { await recordDecisionOutcome({ decisionFingerprint: selectedDecision.decision_key, evidenceSnapshotId, workItemId: selectedWork.id, label: outcomeLabel, actualValue: actualImpact === '' ? null : Number(actualImpact), expectedValue: selectedWork.expected_impact, impactValue: actualImpact === '' || selectedWork.expected_impact == null ? null : Number(actualImpact) - selectedWork.expected_impact, notes: outcomeNotes }); setError(null); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تسجيل النتيجة.'); } finally { setBusy(false); } };
 return <div dir="rtl" className="space-y-5 pb-8"><header className="rounded-3xl bg-ink-950 p-6 text-white lg:p-8"><div className="flex items-center gap-2 text-sm font-semibold text-primary-300"><Workflow size={17}/> منظومة القرار التنفيذية</div><h1 className="mt-2 text-2xl font-bold lg:text-3xl">من البيانات إلى الدليل، ثم القرار والنتيجة</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-ink-300">هذه الشاشة تقرأ الحالة المحفوظة فعليًا: قرار معتمد، مهمة تنفيذية، انتقالات الحالة، ودليل النتيجة. لا يتم إنشاء حالة نجاح محليًا.</p></header>
 <nav aria-label="مراحل دورة القرار" className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{stages.map(s => <button key={s.id} type="button" aria-current={stage === s.id ? 'step' : undefined} onClick={() => go(s.id)} className={`rounded-2xl border p-3 text-right focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 ${stage === s.id ? 'border-primary-500 bg-primary-50' : 'border-ink-200 bg-white hover:bg-ink-50'}`}><span className="block text-xs font-bold">{s.label}</span><span className="mt-1 block text-[11px] text-ink-500">{s.description}</span></button>)}</nav>
 {error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><div className="flex items-center gap-2 font-semibold"><AlertTriangle size={17}/> تعذر تنفيذ العملية</div><p className="mt-1 break-words">{error}</p></div>}
 {stage === 'command' && <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><Lightbulb size={19}/><h2 className="font-bold">التوصيات</h2></div><div className="mt-4 space-y-2">{!loading && recommendations.length === 0 && <Empty title="لا توجد توصيات" detail="لا يتم إنشاء بيانات تجريبية."/>}{recommendations.slice(0, 8).map(r => <button key={r.id} type="button" onClick={() => { setSelectedId(r.id); go('evidence', r.id); }} className="w-full rounded-xl border border-ink-100 p-3 text-right hover:bg-ink-50"><p className="text-sm font-semibold">{r.title}</p><p className="mt-1 text-xs text-ink-500">{r.expected_impact == null ? 'الأثر المتوقع غير متاح' : `الأثر المتوقع: ${r.expected_impact}`}</p></button>)}</div></div><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">التنبيهات</h2><div className="mt-4 space-y-2">{!loading && alerts.length === 0 && <Empty title="لا توجد تنبيهات" detail="لا توجد تنبيهات في المصدر الحالي."/>}{alerts.slice(0, 6).map(a => <div key={a.id} className="rounded-xl border border-ink-100 p-3"><p className="text-sm font-semibold">{a.title}</p></div>)}</div></div></section>}
 {stage === 'evidence' && <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">اختيار التوصية</h2><div className="mt-4 space-y-2">{recommendations.map(r => <button key={r.id} type="button" aria-pressed={selectedId === r.id} onClick={() => { setSelectedId(r.id); go('evidence', r.id); }} className={`w-full rounded-xl border p-3 text-right ${selectedId === r.id ? 'border-primary-400 bg-primary-50' : 'border-ink-100'}`}>{r.title}</button>)}</div></div><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><FileSearch size={19}/><h2 className="font-bold">Evidence Workspace</h2></div>{selected ? <div className="mt-5 space-y-4"><h3 className="text-lg font-bold">{selected.title}</h3><p className="text-sm leading-7 text-ink-600">{selected.description || 'الوصف غير متاح من المصدر الحالي.'}</p><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-ink-50 p-4"><p className="text-xs text-ink-500">Recommendation</p><p className="mt-1 break-all text-xs font-bold">{selected.id}</p></div><div className="rounded-xl bg-ink-50 p-4"><p className="text-xs text-ink-500">Decision</p><p className="mt-1 text-xs font-bold">{approvedForRecommendation.length ? `${approvedForRecommendation.length} معتمد` : 'لا يوجد قرار معتمد'}</p></div><div className="rounded-xl bg-ink-50 p-4"><p className="text-xs text-ink-500">Evidence</p><p className="mt-1 text-xs font-bold">يُطلب عند التنفيذ</p></div></div><Notice>لا يتم اختلاق raw evidence. الدليل التنفيذي يجب أن يأتي من snapshot موثوق قبل الإكمال.</Notice><button type="button" onClick={() => go('decision')} className="rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white">متابعة إلى القرار</button></div> : <Empty title="اختر توصية" detail="اختر عنصرًا موجودًا لفحص السياق."/>}</div></section>}
 {stage === 'decision' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck size={19}/><h2 className="font-bold">القرارات المعتمدة</h2></div><div className="mt-4 space-y-2">{approvedForRecommendation.length === 0 ? <Empty title="لا يوجد قرار APPROVED" detail="لن نسمح بتحويل المقترح إلى مهمة قبل وجود قرار معتمد محفوظ في قاعدة البيانات."/> : approvedForRecommendation.map(d => <button key={d.id} type="button" onClick={() => setDecisionId(d.id)} className={`w-full rounded-xl border p-4 text-right ${decisionId === d.id ? 'border-primary-400 bg-primary-50' : 'border-ink-100'}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-semibold">{d.decision_type}</span><span className="text-xs text-emerald-700">APPROVED</span></div><p className="mt-2 break-all text-xs text-ink-500">{d.decision_key}</p><p className="mt-2 text-xs">Confidence: {d.confidence ?? 'غير متاح'} · Expected impact: {d.expected_impact ?? 'غير متاح'}</p></button>)}</div></div>{selectedProposal?.status === 'accepted' && selectedDecision && <div className="rounded-2xl border border-primary-200 bg-primary-50 p-5"><h2 className="font-bold">تحويل المقترح المقبول إلى Work Item</h2><p className="mt-2 text-sm leading-6">المقترح <span className="font-semibold">{selectedProposal.title}</span> مقبول، والقرار المحدد APPROVED. التحويل محمي من قاعدة البيانات ويظل داخل المستأجر.</p><label className="mt-4 block text-xs font-semibold">المسؤول (عضو نشط في المستأجر)</label><select value={assigneeId} onChange={e => setAssigneeId(e.target.value)} className="mt-2 w-full rounded-xl border border-ink-200 bg-white px-3 py-2.5 text-sm"><option value="">المستخدم المنفذ الحالي / بدون تعيين صريح</option>{assignees.map(a => <option key={a.user_id} value={a.user_id}>{assigneeLabel(a)}</option>)}</select><button type="button" disabled={busy} onClick={() => void convert()} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><Target size={15}/>{busy ? 'جارٍ التحويل…' : 'تحويل إلى Work Item'}</button></div>}{selectedDecision && <Notice tone="green">القرار المحدد: APPROVED · {selectedDecision.decision_key}</Notice>}</section>}
 {stage === 'approval' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">Approval Center</h2><p className="mt-3 text-sm leading-7 text-ink-600">هذه المرحلة تعرض الاعتماد الفعلي فقط. لا توجد موافقة وهمية داخل الواجهة.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{decisions.slice(0, 12).map(d => <div key={d.id} className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-bold">APPROVED</p><p className="mt-2 break-all text-xs">{d.decision_key}</p><p className="mt-2 text-[11px] text-ink-600">approved_at: {d.approved_at || 'غير متاح'}</p></div>)}</div></div>{decisions.length === 0 && <Empty title="لا توجد قرارات معتمدة" detail="أنشئ واعتمد القرار عبر المسار المخول ثم سيظهر هنا."/>}</section>}
 {stage === 'work' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><Target size={19}/><h2 className="font-bold">Personal Workbench</h2></div>{selectedWork ? <div className="mt-4 space-y-4"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary-50 px-3 py-1 text-xs font-semibold">{selectedWork.status}</span><span className="rounded-full bg-ink-100 px-3 py-1 text-xs">{selectedWork.department}</span><span className="rounded-full bg-ink-100 px-3 py-1 text-xs">{selectedWork.priority}</span></div><h3 className="text-lg font-bold">{selectedWork.title}</h3><p className="text-sm leading-7 text-ink-600">{selectedWork.description || 'لا يوجد وصف إضافي.'}</p><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-ink-50 p-3"><p className="text-xs text-ink-500">Expected</p><p className="mt-1 font-bold">{selectedWork.expected_impact ?? 'غير متاح'}</p></div><div className="rounded-xl bg-ink-50 p-3"><p className="text-xs text-ink-500">Actual</p><p className="mt-1 font-bold">{selectedWork.actual_impact ?? 'لم يُسجل'}</p></div><div className="rounded-xl bg-ink-50 p-3"><p className="text-xs text-ink-500">Assignee</p><p className="mt-1 break-all text-xs font-bold">{selectedWork.assignee_label || selectedWork.assignee_id || 'الحالي عند التنفيذ'}</p></div></div>{selectedWork.status === 'OPEN' && <button type="button" disabled={busy} onClick={() => void start()} className="inline-flex items-center gap-2 rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><Play size={15}/> بدء التنفيذ</button>}{selectedWork.status === 'IN_PROGRESS' && <div className="rounded-2xl border border-primary-200 bg-primary-50 p-4"><p className="text-sm font-semibold">إكمال المهمة يتطلب Evidence Snapshot</p><input value={evidenceSnapshotId} onChange={e => setEvidenceSnapshotId(e.target.value)} placeholder="UUID / id لـ evidence snapshot" className="mt-3 w-full rounded-xl border border-ink-200 bg-white px-3 py-2.5 text-sm"/><input value={actualImpact} onChange={e => setActualImpact(e.target.value)} inputMode="decimal" placeholder="Actual impact (اختياري)" className="mt-2 w-full rounded-xl border border-ink-200 bg-white px-3 py-2.5 text-sm"/><button type="button" disabled={busy || !evidenceSnapshotId.trim()} onClick={() => void complete()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50"><CheckCircle2 size={15}/>{busy ? 'جارٍ الإكمال…' : 'إكمال مع الدليل'}</button></div>}{selectedWork.status === 'COMPLETED' && <Notice tone="green">تم إكمال Work Item مع Actual Impact ودليل مقبول من طبقة قاعدة البيانات.</Notice>}</div> : <Empty title="لا توجد Work Item مرتبطة" detail="حوّل مقترحًا مقبولًا إلى قرار APPROVED ثم Work Item، أو اختر قرارًا يملك مهمة محفوظة."/>}</div></section>}
 {stage === 'outcome' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">Outcome & Learning</h2>{selectedWork?.status === 'COMPLETED' && selectedDecision ? <div className="mt-4 space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-ink-100 p-4"><p className="text-xs font-bold">EXPECTED</p><p className="mt-2 text-sm font-semibold">{selectedWork.expected_impact ?? 'غير متاح'}</p></div><div className="rounded-xl border border-ink-100 p-4"><p className="text-xs font-bold">ACTUAL</p><p className="mt-2 text-sm font-semibold">{selectedWork.actual_impact ?? 'غير متاح'}</p></div><div className="rounded-xl border border-ink-100 p-4"><p className="text-xs font-bold">DELTA</p><p className="mt-2 text-sm font-semibold">{selectedWork.actual_impact == null || selectedWork.expected_impact == null ? 'غير محسوب' : selectedWork.actual_impact - selectedWork.expected_impact}</p></div></div><label className="block text-xs font-semibold">حالة النتيجة</label><select value={outcomeLabel} onChange={e => setOutcomeLabel(e.target.value as typeof outcomeLabel)} className="w-full rounded-xl border border-ink-200 bg-white px-3 py-2.5 text-sm"><option value="correct">correct</option><option value="partial">partial</option><option value="incorrect">incorrect</option><option value="unknown">unknown</option></select><label className="block text-xs font-semibold">Evidence Snapshot ID</label><input value={evidenceSnapshotId} onChange={e => setEvidenceSnapshotId(e.target.value)} placeholder="نفس الدليل أو snapshot جديد موثوق" className="w-full rounded-xl border border-ink-200 px-3 py-2.5 text-sm"/><textarea value={outcomeNotes} onChange={e => setOutcomeNotes(e.target.value)} placeholder="ملاحظات النتيجة والتعلم" className="min-h-28 w-full rounded-xl border border-ink-200 px-3 py-2.5 text-sm"/><button type="button" disabled={busy || !evidenceSnapshotId.trim()} onClick={() => void outcome()} className="rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">تسجيل Outcome + Learning</button></div> : <Empty title="Outcome غير متاح بعد" detail="لا يمكن تسجيل النتيجة قبل أن تكون المهمة COMPLETED وبها evidence صالح وقرار APPROVED."/>}</div></section>}
 </div>;
}
