import { useCallback,useEffect,useState } from 'react';
import { AlertTriangle, FileSearch, Lightbulb, ShieldCheck, Target, Workflow, CheckCircle2 } from 'lucide-react';
import { Link,useSearchParams } from 'react-router-dom';
import { fetchAlerts,fetchRecommendations } from '@/lib/queries';
import type { Alert,Recommendation } from '@/lib/types';

type Stage='command'|'evidence'|'decision'|'approval'|'work'|'outcome';
const stages:{id:Stage;label:string;description:string}[]=[{id:'command',label:'مركز القيادة',description:'المعلومة والأولوية'},{id:'evidence',label:'الدليل',description:'المصدر والسياق'},{id:'decision',label:'القرار',description:'التوصية والسبب'},{id:'approval',label:'الموافقة',description:'المسؤولية والاعتماد'},{id:'work',label:'التنفيذ',description:'العمل والمتابعة'},{id:'outcome',label:'النتيجة والتعلّم',description:'Expected → Actual'}];
function Empty({title,detail}:{title:string;detail:string}){return <div className="experience-section flex min-h-40 flex-col items-center justify-center text-center"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-ink-50 text-ink-300"><FileSearch size={19}/></div><p className="mt-3 font-bold text-ink-800">{title}</p><p className="mt-1 max-w-md text-xs leading-6 text-ink-500">{detail}</p></div>}
function Blocked({children}:{children:string}){return <div role="status" className="rounded-2xl border border-warning-100 bg-warning-50/70 px-4 py-3 text-xs font-medium leading-6 text-warning-900"><AlertTriangle size={15} className="ml-1 inline"/>{children}</div>}
export function DecisionExperiencePage(){const[params,setParams]=useSearchParams();const requested=params.get('stage') as Stage|null;const[stage,setStage]=useState<Stage>(stages.some(s=>s.id===requested)?requested!:'command');const[recommendations,setRecommendations]=useState<Recommendation[]>([]);const[alerts,setAlerts]=useState<Alert[]>([]);const[selectedId,setSelectedId]=useState(params.get('recommendationId'));const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[r,a]=await Promise.all([fetchRecommendations(),fetchAlerts()]);setRecommendations(r);setAlerts(a);setSelectedId(current=>current&&r.some(x=>x.id===current)?current:r[0]?.id??null);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل بيانات القرار.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const selected=recommendations.find(r=>r.id===selectedId)??null;const go=(next:Stage,id=selectedId)=>{setStage(next);const p=new URLSearchParams(params);p.set('stage',next);if(id)p.set('recommendationId',id);else p.delete('recommendationId');setParams(p,{replace:true})};
 return <div dir="rtl" className="space-y-6 pb-8 animate-fade-in">
  <section className="experience-hero"><div className="relative z-10"><div className="flex items-center gap-2 text-xs font-semibold text-primary-200"><Workflow size={16}/> Decision Workspace</div><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">من البيانات إلى الدليل، ثم القرار والنتيجة</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-ink-300">رحلة موحدة تحفظ السياق ولا تعرض نجاحًا أو دليلًا موثقًا إلا من المصدر المعتمد.</p><div className="mt-5 flex flex-wrap gap-2"><span className="experience-chip border-white/10 bg-white/10 text-white">{recommendations.length} توصية</span><span className="experience-chip border-white/10 bg-white/10 text-white">{alerts.length} تنبيه</span><span className="experience-chip border-white/10 bg-white/10 text-white">لا mutation محلي</span></div></div></section>
  <nav aria-label="مراحل دورة القرار" className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{stages.map((s,index)=><button key={s.id} type="button" aria-current={stage===s.id?'step':undefined} onClick={()=>go(s.id)} className={`relative rounded-2xl border p-3 text-right transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 ${stage===s.id?'border-primary-300 bg-primary-50 shadow-sm':'border-ink-100 bg-white hover:border-ink-200 hover:bg-ink-50/60'}`}><span className="mb-2 flex h-7 w-7 items-center justify-center rounded-lg bg-ink-50 text-[10px] font-black text-ink-400">{String(index+1).padStart(2,'0')}</span><span className="block text-xs font-bold text-ink-800">{s.label}</span><span className="mt-1 block text-[10px] leading-5 text-ink-500">{s.description}</span></button>)}</nav>
  {error&&<div role="alert" className="rounded-2xl border border-danger-100 bg-danger-50 p-4 text-sm text-danger-800"><div className="font-bold"><AlertTriangle size={16} className="ml-1 inline"/> تعذر تحميل البيانات</div><p className="mt-1 text-xs">{error}</p><button type="button" onClick={()=>void load()} className="btn-secondary mt-3">إعادة المحاولة</button></div>}
  {loading&&<div className="card p-5 text-center text-xs text-ink-400">جارٍ تجهيز مساحة القرار...</div>}
  {!loading&&stage==='command'&&<section className="grid gap-4 lg:grid-cols-2"><div className="experience-section"><div className="experience-section-header"><div><h2 className="experience-section-title">التوصيات</h2><p className="experience-section-subtitle">اختر المرشح الذي تريد فحصه.</p></div><Lightbulb size={19} className="text-primary-600"/></div><div className="space-y-2">{recommendations.length===0&&<Empty title="لا توجد توصيات" detail="لا يتم إنشاء بيانات تجريبية."/>}{recommendations.slice(0,8).map(r=><button key={r.id} type="button" onClick={()=>{setSelectedId(r.id);go('evidence',r.id)}} className="w-full rounded-2xl border border-ink-100 bg-white p-3 text-right transition hover:-translate-y-0.5 hover:border-primary-200 hover:bg-primary-50/30"><p className="text-sm font-bold text-ink-800">{r.title}</p><p className="mt-1 text-xs text-ink-500">{r.expected_impact==null?'الأثر المتوقع غير متاح':`الأثر المتوقع: ${r.expected_impact}`}</p></button>)}</div></div><div className="experience-section"><div className="experience-section-header"><div><h2 className="experience-section-title">التنبيهات</h2><p className="experience-section-subtitle">الإشارات المرتبطة بسياق القرار.</p></div><AlertTriangle size={19} className="text-warning-600"/></div><div className="space-y-2">{alerts.length===0&&<Empty title="لا توجد تنبيهات" detail="لا توجد تنبيهات في المصدر الحالي."/>}{alerts.slice(0,6).map(a=><Link key={a.id} to={`/decision-experience?stage=decision${selectedId?`&recommendationId=${encodeURIComponent(selectedId)}`:''}`} className="block rounded-2xl border border-ink-100 p-3 transition hover:border-ink-200 hover:bg-ink-50"><p className="text-sm font-semibold text-ink-800">{a.title}</p></Link>)}</div></div></section>}
  {!loading&&stage==='evidence'&&<section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="experience-section"><h2 className="experience-section-title">اختيار التوصية</h2><div className="mt-4 space-y-2">{recommendations.length===0?<Empty title="لا توجد توصيات" detail="لا يمكن فحص دليل لتوصية غير موجودة."/>:recommendations.map(r=><button key={r.id} type="button" aria-pressed={selectedId===r.id} onClick={()=>{setSelectedId(r.id);go('evidence',r.id)}} className={`w-full rounded-2xl border p-3 text-right text-sm font-semibold transition ${selectedId===r.id?'border-primary-300 bg-primary-50 text-primary-900':'border-ink-100 hover:bg-ink-50'}`}>{r.title}</button>)}</div></div><div className="experience-section"><div className="flex items-center gap-2"><FileSearch size={19} className="text-primary-600"/><h2 className="experience-section-title">Evidence Workspace</h2></div>{selected?<div className="mt-5 space-y-4"><h3 className="text-lg font-black text-ink-900">{selected.title}</h3><p className="text-sm leading-7 text-ink-600">{selected.description||'الوصف غير متاح من المصدر الحالي.'}</p><div className="grid gap-3 sm:grid-cols-2"><div className="experience-metric"><p className="experience-metric-label">Reliability</p><p className="experience-metric-value text-lg">NOT_VERIFIED</p></div><div className="experience-metric"><p className="experience-metric-label">Source</p><p className="experience-metric-value text-lg">NOT_AVAILABLE</p></div></div><Blocked>RUNTIME_REQUIRED — لا توجد raw evidence مصطنعة ولا يتم استنتاج المصدر من التوصية.</Blocked><button type="button" onClick={()=>go('decision')} className="btn-primary"><CheckCircle2 size={15}/> متابعة إلى القرار</button></div>:<Empty title="اختر توصية" detail="اختر عنصرًا موجودًا لفحص الدليل."/>}</div></section>}
  {!loading&&stage==='decision'&&<section className="space-y-4"><div className="experience-section"><div className="flex items-center gap-2"><ShieldCheck size={19} className="text-primary-600"/><h2 className="experience-section-title">Decision Workspace</h2></div>{selected?<div className="mt-4"><p className="font-bold text-ink-900">{selected.title}</p><p className="mt-2 text-sm leading-6 text-ink-500">DECISION CANDIDATE — لا تُعتبر recommendation حالة قرار persisted.</p></div>:<Empty title="لا يوجد مرشح قرار" detail="لا يوجد قرار يمكن ربطه بتوصية حالية."/>}</div><Blocked>Authenticated runtime + tenant authority مطلوبة قبل أي approval أو mutation. لا يتم تحويل candidate إلى approved محليًا.</Blocked><div className="grid gap-3 sm:grid-cols-3">{['PROPOSED','PENDING_APPROVAL','APPROVED / REJECTED'].map(s=><div key={s} className="experience-metric"><p className="text-xs font-black text-ink-700">{s}</p><p className="mt-2 text-xs leading-5 text-ink-500">تصميم lifecycle فقط، وليس دليل حالة persisted.</p></div>)}</div></section>}
  {!loading&&stage==='approval'&&<section className="space-y-4"><div className="experience-section"><div className="flex items-center gap-2"><ShieldCheck size={19} className="text-primary-600"/><h2 className="experience-section-title">Approval Center</h2></div><p className="mt-3 text-sm leading-7 text-ink-600">الموافقة تحتاج authority وevidence runtime موثقة.</p></div><Blocked>Approval action unavailable — لا يتم إنشاء approver أو timestamp أو approval محليًا.</Blocked></section>}
  {!loading&&stage==='work'&&<section className="space-y-4"><div className="experience-section"><div className="flex items-center gap-2"><Target size={19} className="text-primary-600"/><h2 className="experience-section-title">Personal Workbench</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{['MY APPROVALS','MY TASKS','IN PROGRESS','OVERDUE','COMPLETED','OUTCOME FOLLOW-UP'].map(s=><div key={s} className="experience-metric"><p className="text-xs font-black text-ink-700">{s}</p><p className="mt-2 text-xs text-ink-500">لا توجد بيانات runtime متاحة.</p></div>)}</div></div><Blocked>لا يمكن اختلاق مهام أو حالات إنجاز. Authenticated runtime required.</Blocked></section>}
  {!loading&&stage==='outcome'&&<section className="space-y-4"><div className="experience-section"><h2 className="experience-section-title">Outcome & Learning</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['EXPECTED',selected?.expected_impact==null?'Expected impact not available':String(selected.expected_impact)],['ACTUAL','Actual outcome not yet available'],['DELTA','Delta cannot yet be calculated'],['QUALITY','Outcome quality not yet available'],['FEEDBACK','Feedback not yet available'],['LEARNING SIGNAL','Learning signal not yet verified']].map(([l,v])=><div key={l} className="experience-metric"><p className="experience-metric-label">{l}</p><p className="mt-2 text-sm font-bold text-ink-800">{v}</p></div>)}</div></div><Blocked>Repository Learning ≠ Runtime Learning. لا يوجد actual outcome أو feedback أو learning evidence runtime.</Blocked></section>}
 </div>}
