import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, FileSearch, Lightbulb, Play, ShieldCheck, Target, Workflow } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { fetchAlerts, fetchRecommendations, fetchSourceAnalysisSnapshots, type SourceAnalysisSnapshot } from '@/lib/queries';
import { convertAcceptedTaskProposal, fetchTaskProposals, type PersistedTaskProposal } from '@/lib/role-task-persistence';
import { fetchActiveTenantAssignees, fetchApprovedDecisions, fetchDecisionWorkItems, completeDecisionWorkItem, recordDecisionOutcome, startDecisionWorkItem, type RuntimeDecision, type RuntimeWorkItem, type TenantAssignee } from '@/lib/decision-runtime';
import { fetchAlternativeGroups, type AlternativeGroup } from '@/lib/alternative-queries';
import { buildDecisionAlternatives, type DecisionAlternative } from '@/lib/decision-alternative-bridge';
import type { Alert, Recommendation } from '@/lib/types';

type Stage = 'command' | 'evidence' | 'decision' | 'approval' | 'work' | 'outcome';
const stages: { id: Stage; label: string; description: string }[] = [
 { id: 'command', label: 'مركز القيادة', description: 'المعلومة والأولوية' }, { id: 'evidence', label: 'الدليل', description: 'المصدر والسياق' }, { id: 'decision', label: 'القرار', description: 'التوصية والقرار المحفوظ' }, { id: 'approval', label: 'الموافقة', description: 'حالة الاعتماد الفعلية' }, { id: 'work', label: 'التنفيذ', description: 'المهمة والمتابعة' }, { id: 'outcome', label: 'النتيجة والتعلّم', description: 'Expected → Actual' },
];
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="rounded-2xl border border-dashed border-ink-300 bg-ink-50 p-6 text-center"><p className="font-semibold text-ink-800">{title}</p><p className="mt-2 text-xs leading-6 text-ink-500">{detail}</p></div>; }
function Notice({ children, tone = 'amber' }: { children: string; tone?: 'amber' | 'green' | 'red' }) { const cls = tone === 'green' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : tone === 'red' ? 'border-red-200 bg-red-50 text-red-900' : 'border-amber-200 bg-amber-50 text-amber-900'; return <div role="status" className={`rounded-2xl border p-4 text-sm ${cls}`}>{children}</div>; }
const assigneeLabel = (a: TenantAssignee) => `${a.role} · ${a.user_id.slice(0, 8)}…`;

export function DecisionExperiencePage() {
 const [params, setParams] = useSearchParams(); const requested = params.get('stage') as Stage | null; const [stage, setStage] = useState<Stage>(stages.some(s => s.id === requested) ? requested! : 'command');
 const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [proposals, setProposals] = useState<PersistedTaskProposal[]>([]); const [decisions, setDecisions] = useState<RuntimeDecision[]>([]); const [assignees, setAssignees] = useState<TenantAssignee[]>([]); const [workItems, setWorkItems] = useState<RuntimeWorkItem[]>([]); const [alternatives, setAlternatives] = useState<AlternativeGroup[]>([]); const [snapshots, setSnapshots] = useState<SourceAnalysisSnapshot[]>([]);
 const [selectedId, setSelectedId] = useState(params.get('recommendationId')); const [proposalId, setProposalId] = useState(params.get('proposalId')); const [decisionId, setDecisionId] = useState(params.get('decisionId')); const [assigneeId, setAssigneeId] = useState(''); const [evidenceSnapshotId, setEvidenceSnapshotId] = useState(''); const [actualImpact, setActualImpact] = useState(''); const [outcomeLabel, setOutcomeLabel] = useState<'correct' | 'incorrect' | 'partial' | 'unknown'>('unknown'); const [outcomeNotes, setOutcomeNotes] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
 const load = useCallback(async () => { setLoading(true); setError(null); try { const [r, a, p, d, m, g, s] = await Promise.all([fetchRecommendations(), fetchAlerts(), fetchTaskProposals(), fetchApprovedDecisions(), fetchActiveTenantAssignees(), fetchAlternativeGroups(), fetchSourceAnalysisSnapshots()]); const nextRecommendation = r.find(x => x.id === selectedId)?.id ?? r[0]?.id ?? null; const nextProposal = p.find(x => x.id === proposalId)?.id ?? p.find(x => x.status === 'accepted')?.id ?? null; const nextDecision = d.find(x => x.id === decisionId)?.id ?? d.find(x => x.recommendation_id === nextRecommendation)?.id ?? d[0]?.id ?? null; setRecommendations(r); setAlerts(a); setProposals(p); setDecisions(d); setAssignees(m); setAlternatives(g); setSnapshots(s); setSelectedId(nextRecommendation); setProposalId(nextProposal); setDecisionId(nextDecision); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تحميل دورة القرار.'); } finally { setLoading(false); } }, [decisionId, proposalId, selectedId]);
 useEffect(() => { void load(); }, [load]);
 const selected = recommendations.find(r => r.id === selectedId) ?? null; const selectedProposal = proposals.find(p => p.id === proposalId) ?? null; const selectedDecision = decisions.find(d => d.id === decisionId) ?? null; const selectedWork = workItems.find(w => w.decision_id === decisionId) ?? null; const decisionAlternatives = useMemo<DecisionAlternative[]>(() => buildDecisionAlternatives(selected, alternatives), [selected, alternatives]);
 useEffect(() => { if (!decisionId) { setWorkItems([]); return; } void fetchDecisionWorkItems(decisionId).then(setWorkItems).catch(e => setError(e instanceof Error ? e.message : 'تعذر تحميل المهمة التنفيذية.')); }, [decisionId]);
 const go = (next: Stage, id = selectedId) => { setStage(next); const p = new URLSearchParams(params); p.set('stage', next); if (id) p.set('recommendationId', id); else p.delete('recommendationId'); if (proposalId) p.set('proposalId', proposalId); if (decisionId) p.set('decisionId', decisionId); setParams(p, { replace: true }); };
 const approvedForRecommendation = useMemo(() => decisions.filter(d => !selectedId || d.recommendation_id === selectedId), [decisions, selectedId]);
 const convert = async () => { if (!selectedProposal || !selectedDecision) return; setBusy(true); setError(null); try { await convertAcceptedTaskProposal({ proposalId: selectedProposal.id, decisionId: selectedDecision.id, assigneeId: assigneeId || null, assigneeLabel: assigneeId ? assignees.find(a => a.user_id === assigneeId) ? assigneeLabel(assignees.find(a => a.user_id === assigneeId)!) : null : null }); setWorkItems(await fetchDecisionWorkItems(selectedDecision.id)); setStage('work'); const p = new URLSearchParams(params); p.set('stage', 'work'); p.set('decisionId', selectedDecision.id); p.set('proposalId', selectedProposal.id); setParams(p, { replace: true }); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تحويل المقترح إلى مهمة.'); } finally { setBusy(false); } };
 const start = async () => { if (!selectedWork) return; setBusy(true); try { await startDecisionWorkItem(selectedWork.id); setWorkItems(await fetchDecisionWorkItems(selectedWork.decision_id)); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر بدء المهمة.'); } finally { setBusy(false); } };
 const complete = async () => { if (!selectedWork || !evidenceSnapshotId) { setError('اختر Evidence Snapshot محفوظًا قبل إكمال المهمة.'); return; } setBusy(true); try { await completeDecisionWorkItem(selectedWork.id, actualImpact === '' ? null : Number(actualImpact), evidenceSnapshotId); setWorkItems(await fetchDecisionWorkItems(selectedWork.decision_id)); setStage('outcome'); const p = new URLSearchParams(params); p.set('stage', 'outcome'); setParams(p, { replace: true }); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر إكمال المهمة.'); } finally { setBusy(false); } };
 const outcome = async () => { if (!selectedWork || !selectedDecision || !evidenceSnapshotId) { setError('Evidence Snapshot مطلوب لتسجيل النتيجة.'); return; } setBusy(true); try { await recordDecisionOutcome({ decisionFingerprint: selectedDecision.id, evidenceSnapshotId, workItemId: selectedWork.id, label: outcomeLabel, actualValue: actualImpact === '' ? null : Number(actualImpact), expectedValue: selectedWork.expected_impact, impactValue: actualImpact === '' || selectedWork.expected_impact == null ? null : Number(actualImpact) - selectedWork.expected_impact, notes: outcomeNotes }); setError(null); setWorkItems(await fetchDecisionWorkItems(selectedDecision.id)); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تسجيل النتيجة.'); } finally { setBusy(false); } };
 return <div dir="rtl" className="space-y-5 pb-8"><header className="rounded-3xl bg-ink-950 p-6 text-white lg:p-8"><div className="flex items-center gap-2 text-sm font-semibold text-primary-300"><Workflow size={17}/> منظومة القرار التنفيذية</div><h1 className="mt-2 text-2xl font-bold lg:text-3xl">من البيانات إلى الدليل، ثم القرار والنتيجة</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-ink-300">هذه الشاشة تقرأ الحالة المحفوظة فعليًا: قرار معتمد، مهمة تنفيذية، انتقالات الحالة، ودليل النتيجة. لا يتم إنشاء حالة نجاح محليًا.</p></header>
 <nav aria-label="مراحل دورة القرار" className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{stages.map(s => <button key={s.id} type="button" aria-current={stage === s.id ? 'step' : undefined} onClick={() => go(s.id)} className={`rounded-2xl border p-3 text-right focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 ${stage === s.id ? 'border-primary-500 bg-primary-50' : 'border-ink-200 bg-white hover:bg-ink-50'}`}><span className="block text-xs font-bold">{s.label}</span><span className="mt-1 block text-[11px] text-ink-500">{s.description}</span></button>)}</nav>
 {error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><div className="flex items-center gap-2 font-semibold"><AlertTriangle size={17}/> تعذر تنفيذ العملية</div><p className="mt-1 break-words">{error}</p></div>}
 {stage === 'command' && <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><Lightbulb size={19}/><h2 className="font-bold">التوصيات</h2></div><div className="mt-4 space-y-2">{!loading && recommendations.length === 0 && <Empty title="لا توجد توصيات" detail="لا يتم إنشاء بيانات تجريبية."/>}{recommendations.slice(0, 8).map(r => <button key={r.id} type="button" onClick={() => { setSelectedId(r.id); go('evidence', r.id); }} className="w-full rounded-xl border border-ink-100 p-3 text-right hover:bg-ink-50"><p className="text-sm font-semibold">{r.title}</p><p className="mt-1 text-xs text-ink-500">{r.expected_impact == null ? 'الأثر المتوقع غير متاح' : `الأثر المتوقع: ${r.expected_impact}`}</p></button>)}</div></div><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">التنبيهات</h2><div className="mt-4 space-y-2">{!loading && alerts.length === 0 && <Empty title="لا توجد تنبيهات" detail="لا توجد تنبيهات في المصدر الحالي."/>}{alerts.slice(0, 6).map(a => <div key={a.id} className="rounded-xl border border-ink-100 p-3"><p className="text-sm font-semibold">{a.title}</p></div>)}</div></div></section>}
 {stage === 'evidence' && <section className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">اختيار التوصية</h2><div className="mt-4 space-y-2">{recommendations.map(r => <button key={r.id} type="button" aria-pressed={selectedId === r.id} onClick={() => { setSelectedId(r.id); go('evidence', r.id); }} className={`w-full rounded-xl border p-3 text-right ${selectedId === r.id ? 'border-primary-400 bg-primary-50' : 'border-ink-100'}`}>{r.title}</button>)}</div></div><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><FileSearch size={19}/><h2 className="font-bold">Evidence Workspace</h2></div>{selected ? <div className="mt-5 space-y-4"><h3 className="text-lg font-bold">{selected.title}</h3><p className="text-sm leading-7 text-ink-600">{selected.description || 'الوصف غير متاح من المصدر الحالي.'}</p><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-ink-50 p-4"><p className="text-xs text-ink-500">Recommendation</p><p className="mt-1 break-all text-xs font-bold">{selected.id}</p></div><div className="rounded-xl bg-ink-50 p-4"><p className="text-xs text-ink-500">Decision</p><p className="mt-1 text-xs font-bold">{approvedForRecommendation.length ? `${approvedForRecommendation.length} معتمد` : 'لا يوجد قرار معتمد'}</p></div><div className="rounded-xl bg-ink-50 p-4"><p className="text-xs text-ink-500">Evidence</p><p className="mt-1 text-xs font-bold">{snapshots.length ? `${snapshots.length} snapshot محفوظ` : 'لا توجد snapshots محفوظة'}</p></div></div><Notice>لا يتم اختلاق raw evidence. الدليل التنفيذي يجب أن يأتي من snapshot موثوق قبل الإكمال.</Notice><button type="button" onClick={() => go('decision')} className="rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white">متابعة إلى القرار</button></div> : <Empty title="اختر توصية" detail="اختر عنصرًا موجودًا لفحص السياق."/>}</div></section>}
 {stage === 'decision' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck size={19}/><h2 className="font-bold">القرارات المعتمدة</h2></div><div className="mt-4 space-y-2">{approvedForRecommendation.length === 0 ? <Empty title="لا يوجد قرار APPROVED" detail="لن نسمح بتحويل المقترح إلى مهمة قبل وجود قرار معتمد محفوظ في قاعدة البيانات."/> : approvedForRecommendation.map(d => <button key={d.id} type="button" onClick={() => { setDecisionId(d.id); go('approval'); }} className={`w-full rounded-xl border p-4 text-right ${decisionId === d.id ? 'border-primary-400 bg-primary-50' : 'border-ink-100'}`}><p className="font-semibold">{d.decision_key}</p><p className="mt-1 text-xs text-ink-500">{d.policy_key ?? 'بدون policy'} · confidence {d.confidence ?? 'غير متاح'}</p></button>)}</div></div><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">البدائل</h2>{decisionAlternatives.length === 0 ? <p className="mt-3 text-sm text-ink-500">لا توجد بدائل مرتبطة بالتوصية الحالية في البيانات المحفوظة.</p> : <div className="mt-4 space-y-2">{decisionAlternatives.slice(0, 10).map(a => <article key={a.memberId} className={`rounded-xl border p-3 ${a.selectionEligible ? 'border-ink-100' : 'border-amber-200 bg-amber-50'}`}><div className="flex items-center justify-between gap-3"><div><p className="font-semibold">{a.productName ?? a.sku}</p><p className="text-xs text-ink-500">SKU {a.sku} · تحويل {a.conversionFactor} · Rank #{a.rank}</p></div><span className="text-xs font-semibold">{a.selectionEligible ? 'مؤهل' : 'غير مؤهل'}</span></div><p className="mt-2 text-xs text-ink-500">{a.reason}</p></article>)}</div>}</div></section>}
 {stage === 'approval' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">بوابة الموافقة</h2>{selectedDecision ? <><p className="mt-2 text-sm">الحالة المحفوظة: <strong>{selectedDecision.status}</strong></p><p className="mt-1 text-xs text-ink-500">لا يتم إنشاء الموافقة من هذه الشاشة؛ نعرض الاعتماد المحفوظ فقط.</p><Link to={`/decision-experience?stage=work&decisionId=${selectedDecision.id}&recommendationId=${selectedId ?? ''}`} className="mt-4 inline-flex rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold">متابعة للتنفيذ</Link></> : <Empty title="لا يوجد قرار محدد" detail="اختر قرارًا معتمدًا أولًا."/>}</div></section>}
 {stage === 'work' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex items-center gap-2"><Target size={19}/><h2 className="font-bold">التنفيذ</h2></div>{selectedDecision && selectedProposal ? <div className="mt-4 space-y-3"><p className="text-sm">Proposal: <strong>{selectedProposal.title}</strong></p><label className="block text-xs font-semibold">المكلّف<select value={assigneeId} onChange={e => setAssigneeId(e.target.value)} className="mt-1 w-full rounded-xl border border-ink-200 bg-white p-2.5"><option value="">بدون تغيير</option>{assignees.map(a => <option key={a.user_id} value={a.user_id}>{assigneeLabel(a)}</option>)}</select></label><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => void convert()} className="rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">تحويل إلى مهمة</button>{selectedWork?.status === 'OPEN' && <button disabled={busy} onClick={() => void start()} className="inline-flex items-center gap-2 rounded-xl border border-ink-200 px-4 py-2.5 text-xs font-bold"><Play size={15}/> بدء</button>}</div>{selectedWork && <div className="rounded-xl bg-ink-50 p-4 text-xs"><p className="font-bold">{selectedWork.title}</p><p className="mt-1">الحالة: {selectedWork.status}</p><label className="mt-3 block font-semibold">Evidence Snapshot<select value={evidenceSnapshotId} onChange={e => setEvidenceSnapshotId(e.target.value)} className="mt-1 w-full rounded-xl border border-ink-200 bg-white p-2.5"><option value="">اختر snapshot</option>{snapshots.map(s => <option key={s.id} value={s.id}>{s.source_path} · {s.source_hash.slice(0, 12)}…</option>)}</select></label><label className="mt-3 block font-semibold">Actual Impact<input value={actualImpact} onChange={e => setActualImpact(e.target.value)} inputMode="decimal" className="mt-1 w-full rounded-xl border border-ink-200 bg-white p-2.5" placeholder="اتركه فارغًا إن لم يتوفر" /></label>{selectedWork.status === 'IN_PROGRESS' && <button disabled={busy} onClick={() => void complete()} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-xs font-bold text-white"><CheckCircle2 size={15}/> إكمال المهمة</button>}</div>}</div> : <Empty title="المهمة غير جاهزة" detail="يلزم مقترح مقبول وقرار معتمد قبل إنشاء مهمة تنفيذية."/>}</div></section>}
 {stage === 'outcome' && <section className="space-y-4"><div className="rounded-2xl border border-ink-200 bg-white p-5"><h2 className="font-bold">النتيجة والتعلّم</h2>{selectedWork && selectedDecision ? <div className="mt-4 space-y-3"><p className="text-sm">Expected: {selectedWork.expected_impact ?? 'غير متاح'} · Actual: {actualImpact || selectedWork.actual_impact || 'غير مسجل'} </p><label className="block text-xs font-semibold">Evidence Snapshot<select value={evidenceSnapshotId} onChange={e => setEvidenceSnapshotId(e.target.value)} className="mt-1 w-full rounded-xl border border-ink-200 bg-white p-2.5"><option value="">اختر snapshot</option>{snapshots.map(s => <option key={s.id} value={s.id}>{s.source_path} · {s.source_hash.slice(0, 12)}…</option>)}</select></label><label className="block text-xs font-semibold">تقييم النتيجة<select value={outcomeLabel} onChange={e => setOutcomeLabel(e.target.value as typeof outcomeLabel)} className="mt-1 w-full rounded-xl border border-ink-200 bg-white p-2.5"><option value="unknown">غير معروف</option><option value="correct">صحيحة</option><option value="partial">جزئية</option><option value="incorrect">غير صحيحة</option></select></label><label className="block text-xs font-semibold">ملاحظات<textarea value={outcomeNotes} onChange={e => setOutcomeNotes(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border border-ink-200 bg-white p-2.5" /></label><button disabled={busy} onClick={() => void outcome()} className="rounded-xl bg-ink-950 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">حفظ النتيجة</button></div> : <Empty title="لا توجد مهمة مرتبطة" detail="لا يمكن تسجيل نتيجة دون work item وقرار محفوظ."/>}</div></section>}
 </div>;
}
