import { useCallback, useEffect,useMemo,useState } from 'react';
import { Activity, TrendingUp, TrendingDown, Minus, RefreshCw, ShieldCheck } from 'lucide-react';
import { Card,CardHeader,CardBody } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { PageHeader,LoadingState,ErrorState } from '@/components/ui/States';
import { BusinessInvestigationDrawer, type InvestigationTarget } from '@/components/BusinessInvestigationDrawer';
import { fetchProductDemandSeries, type ProductDemandSeries } from '@/lib/free-toolbox/sales-demand-series';
import { formatNumber } from '@/lib/format';
import { resolveCurrentCompanyId } from '@/lib/supabase';
import { SavedViewMenu, type SavedViewValue } from '@/components/ui/SavedViewMenu';

export function DemandVelocityPage(){
 const[data,setData]=useState<ProductDemandSeries[]>([]);const[days,setDays]=useState(180);const[companyId,setCompanyId]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[investigation,setInvestigation]=useState<InvestigationTarget|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await fetchProductDemandSeries(days))}catch(e:unknown){setError(e instanceof Error?e.message:'تعذر تحميل حركة الطلب')}finally{setLoading(false)}},[days]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{void resolveCurrentCompanyId().then(setCompanyId)},[]);const summary=useMemo(()=>({items:data.length,units:data.reduce((s,x)=>s+x.totalQuantity,0),accelerating:data.filter(x=>x.trend>.2).length,declining:data.filter(x=>x.trend<-.2).length}),[data]);if(loading)return <LoadingState message="جارٍ تحليل حركة الطلب التاريخية..."/>;if(error)return <ErrorState message={error} onRetry={load}/>;
 const savedViewKey=companyId?'report-advisor.saved-views.'+companyId+'.demand-velocity':'';const applySavedView=(value:SavedViewValue)=>{const nextDays=Number(value.days);if([30,90,180,365].includes(nextDays))setDays(nextDays)};const resetView=()=>setDays(180);
 const openDemand=(x:ProductDemandSeries)=>{const up=x.trend>.2,down=x.trend<-.2;setInvestigation({title:x.name,eyebrow:'Demand Lens · إشارة حركة',severity:up?'opportunity':down?'warning':'info',summary:up?'الحركة التاريخية تشير إلى تسارع وفق المقياس الحالي. السبب التجاري غير مثبت من السلسلة وحدها.':down?'الحركة التاريخية تشير إلى تراجع وفق المقياس الحالي. السبب التجاري غير مثبت من السلسلة وحدها.':'الحركة ضمن النطاق المحايد للمقياس الحالي؛ لا يتم اختلاق تفسير عند غياب إشارة قوية.',facts:[{label:'SKU',value:x.sku||'غير متاح'},{label:'إجمالي الوحدات',value:formatNumber(x.totalQuantity)},{label:'المتوسط اليومي',value:x.averageDaily.toFixed(2)},{label:'الذروة اليومية',value:formatNumber(x.peakDaily)},{label:'الاتجاه',value:String((x.trend*100).toFixed(1))+'%'}],confirmedReasons:['الاتجاه مشتق من سلسلة المبيعات التاريخية للفترة المحددة.'],missingEvidence:['سبب تغير الطلب أو التراجع.','أثر أي موسمية أو حدث تشغيلي خارج السلسلة.','النتيجة الفعلية بعد أي إجراء.'],actions:[{label:'افتح ذكاء المخزون',path:'/inventory',hint:'اربط حركة الطلب بالتغطية والرأس المال.'},{label:'افتح مركز العمل',path:'/work-center',hint:'راجع ما يحتاج تحققًا أو معالجة.'},{label:'افتح تجربة القرار',path:'/decision-experience?stage=evidence',hint:'افحص الدليل قبل اعتماد الإجراء.'}],evidence:{source:'fetchProductDemandSeries',asOf:'نطاق '+String(days)+' يومًا',period:String(days)+' يومًا',status:'CANONICAL',formula:'اتجاه الحركة من سلسلة الكمية المباعة'}})};
 const openFirst=(kind:'all'|'up'|'down')=>{const x=kind==='up'?data.find(r=>r.trend>.2):kind==='down'?data.find(r=>r.trend<-.2):data[0];if(x)openDemand(x)};
 return <div dir="rtl" className="space-y-5 animate-fade-in"><PageHeader title="سرعة الطلب وإشارات الحركة" subtitle="Demand Lens: اكتشاف التغير من البيانات التاريخية ثم التحقيق في السياق قبل القرار." actions={<button type="button" onClick={load} className="btn-secondary"><RefreshCw size={16}/> تحديث</button>}/><section className="rounded-[18px] border border-[#15372f] bg-[#0d2a24] p-4 text-white sm:p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[10px] font-black tracking-[0.14em] text-white/40">SIGNAL → CONTEXT → EVIDENCE</div><h2 className="mt-1 text-lg font-black">ما الذي تغيّر في الطلب؟</h2><p className="mt-1 max-w-2xl text-[11px] leading-5 text-white/55">التسارع والتراجع إشارات قياسية وليست تفسيرًا للسبب. افتح الصف للوصول إلى الأدلة والحدود.</p></div><button type="button" onClick={()=>openFirst('all')} className="btn-secondary border-white/10 bg-white/10 text-white hover:bg-white/15"><ShieldCheck size={15}/> افحص أول إشارة</button></div></section>
 <div className="filter-toolbar flex flex-wrap items-center gap-2" role="toolbar" aria-label="الفترة الزمنية">{[30,90,180,365].map(n=><button type="button" key={n} aria-pressed={days===n} onClick={()=>setDays(n)} className={"filter-chip "+(days===n?'filter-chip-active':'hover:bg-white')}>{n} يوم</button>)}{savedViewKey&&<SavedViewMenu storageKey={savedViewKey} value={{days}} onApply={applySavedView} onReset={resetView}/>}<button type="button" onClick={resetView} className="filter-chip">إعادة الضبط</button></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card hover onClick={()=>openFirst('all')}><CardBody><div className="text-xs text-ink-500">الأصناف ذات الحركة</div><div className="display-number mt-1">{formatNumber(summary.items)}</div></CardBody></Card><Card hover onClick={()=>openFirst('all')}><CardBody><div className="text-xs text-ink-500">إجمالي الوحدات</div><div className="display-number mt-1">{formatNumber(summary.units)}</div></CardBody></Card><Card hover onClick={()=>openFirst('up')}><CardBody><div className="text-xs text-ink-500">طلب متسارع</div><div className="display-number mt-1 text-success-700">{summary.accelerating}</div><div className="mt-1 text-[11px] text-ink-400">افتح أول إشارة للتحقيق</div></CardBody></Card><Card hover onClick={()=>openFirst('down')}><CardBody><div className="text-xs text-ink-500">طلب متراجع</div><div className="display-number mt-1 text-danger-700">{summary.declining}</div><div className="mt-1 text-[11px] text-ink-400">افتح أول إشارة للتحقيق</div></CardBody></Card></div>
 <Card><CardHeader title="خريطة حركة الطلب" subtitle="الصف يصبح نقطة دخول للتحقيق، لا مجرد سطر ترتيب."/><CardBody><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-right text-xs text-ink-400 border-b"><th className="py-3">الصنف</th><th>SKU</th><th>إجمالي الوحدات</th><th>المتوسط اليومي</th><th>الذروة اليومية</th><th>الاتجاه</th></tr></thead><tbody>{data.slice(0,50).map(x=>{const up=x.trend>.2,down=x.trend<-.2;return <tr key={x.productId} className="border-b border-ink-50"><td className="py-3 font-medium"><button type="button" onClick={()=>openDemand(x)} className="text-primary-700 hover:underline text-right">{x.name}</button></td><td className="text-ink-500">{x.sku||'—'}</td><td>{formatNumber(x.totalQuantity)}</td><td>{x.averageDaily.toFixed(2)}</td><td>{formatNumber(x.peakDaily)}</td><td><Badge variant={up?'success':down?'danger':'neutral'}>{up?<TrendingUp size={13}/>:down?<TrendingDown size={13}/>:<Minus size={13}/>} {String((x.trend*100).toFixed(1))+'%'}</Badge></td></tr>})}</tbody></table>{data.length===0&&<div className="py-10 text-center text-sm text-ink-400"><Activity className="mx-auto mb-2" size={24}/>لا توجد مبيعات ضمن الفترة المحددة</div>}</div></CardBody></Card>
 <div className="rounded-2xl border border-ink-200 bg-white px-4 py-3 text-[11px] text-ink-500">الإشارة الإحصائية لا تثبت السبب. السبب التجاري يحتاج سياقًا إضافيًا، والنتيجة لا تُعتبر محققة قبل ظهور أثر موثق.</div>
 <BusinessInvestigationDrawer target={investigation} onClose={()=>setInvestigation(null)} /></div>;
}
