import { useCallback,useEffect,useState } from 'react';
import { FileText,Printer,ShieldCheck,Sparkles,ArrowUpLeft,AlertTriangle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { fetchDashboardIntelligence,fetchDashboardSnapshot,type DashboardKPIs } from '@/lib/dashboard-canonical';
import type { Alert, Recommendation } from '@/lib/types';
import { formatCurrency } from '@/lib/format';

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><p className="text-[11px] font-bold text-emerald-100/60">{label}</p><p className="mt-2 text-xl font-black text-white sm:text-2xl">{value}</p></div>}
export function ExecutiveReportPage(){const[kpis,setKpis]=useState<DashboardKPIs|null>(null);const[data,setData]=useState<{alerts:Alert[];recommendations:Recommendation[]}|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const load=useCallback(async()=>{setLoading(true);setError(null);try{const [snapshot,intelligence]=await Promise.all([fetchDashboardSnapshot(3),fetchDashboardIntelligence()]);setKpis(snapshot.kpis);setData(intelligence);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل التقرير التنفيذي.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);return <div dir="rtl" className="space-y-7 pb-10 animate-fade-in">
<header className="experience-hero relative overflow-hidden rounded-[2rem] p-6 sm:p-9 lg:p-11"><div className="absolute -left-20 -top-20 h-72 w-72 rounded-full bg-amber-300/15 blur-3xl"/><div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[11px] font-bold tracking-[.15em] text-amber-100"><Sparkles size={13}/>EXECUTIVE REPORT</div><h1 className="text-3xl font-black text-white sm:text-5xl">القصة التنفيذية</h1><p className="mt-4 text-sm leading-7 text-emerald-50/75 sm:text-base">تجميع واحد لما حدث، وما الدليل، وما الذي يحتاج قرارًا. التقرير يحافظ على حدود الحقيقة ولا يستبدل البيانات المفقودة بتقديرات.</p></div><button type="button" onClick={()=>window.print()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-ink-900 shadow-lg"><Printer size={17}/>طباعة / PDF</button></div>{!loading&&!error&&<div className="relative mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="المبيعات" value={kpis?.totalSales==null?'غير متاح':formatCurrency(kpis.totalSales)}/><Metric label="الهامش" value={kpis?.grossMargin==null?'غير متاح':`${kpis.grossMargin.toFixed(1)}%`}/><Metric label="التحصيل" value={kpis?.collectionRate==null?'غير متاح':`${kpis.collectionRate.toFixed(1)}%`}/><Metric label="الذمم المتأخرة" value={kpis?.overdueReceivables==null?'غير متاح':formatCurrency(kpis.overdueReceivables)}/></div>}</header>
{loading&&<div role="status" className="rounded-2xl border border-ink-100 bg-white p-6 text-sm text-ink-500 shadow-sm">جارٍ بناء التقرير من المصادر المعتمدة…</div>}{error&&<div role="alert" className="rounded-2xl border border-danger-100 bg-danger-50 p-6 text-sm text-danger-800">{error}<button type="button" onClick={()=>void load()} className="mr-3 rounded-lg border border-danger-200 bg-white px-3 py-1.5 font-bold">إعادة المحاولة</button></div>}{!loading&&!error&&<>
<section className="grid grid-cols-1 gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-[1.5rem] border border-ink-100 bg-white p-6 shadow-elevated sm:p-7"><div className="flex items-center justify-between gap-3"><div><div className="text-[10px] font-black tracking-[.14em] text-emerald-700">EXECUTIVE SUMMARY</div><h2 className="mt-1 text-xl font-black text-ink-900">قراءة سريعة للقرار</h2></div><FileText className="text-emerald-600" size={22}/></div><p className="mt-5 max-w-3xl text-sm leading-8 text-ink-600">هذه الصفحة ليست مجرد نسخة مطبوعة من لوحة القيادة؛ إنها طبقة سردية تجمع المؤشرات والتنبيهات والتوصيات في مسار واحد، مع إظهار حدود البيانات عندما لا تكفي لإثبات النتيجة.</p><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-ink-50 p-4"><p className="text-xs text-ink-400">حالة المؤشرات</p><p className="mt-2 font-black text-ink-900">{kpis?.status==='INSUFFICIENT_DATA'?'بيانات غير مكتملة':'محسوبة من المصدر'}</p></div><div className="rounded-2xl bg-emerald-50/70 p-4"><p className="text-xs text-ink-400">التوصيات المتاحة</p><p className="mt-2 font-black text-emerald-800">{data?.recommendations?.length??0}</p></div></div></div><div className="rounded-[1.5rem] bg-ink-950 p-6 text-white shadow-elevated"><AlertTriangle className="text-amber-300" size={23}/><h2 className="mt-5 text-xl font-black">ما يحتاج انتباهًا</h2><p className="mt-2 text-sm leading-7 text-ink-300">التنبيهات التالية مصدرها طبقة الذكاء المعتمدة ولا يتم رفع أولويتها يدويًا داخل الواجهة.</p><div className="mt-5 text-3xl font-black">{data?.alerts?.length??0}</div><Link to="/intelligence" className="mt-5 inline-flex items-center gap-1.5 text-xs font-bold text-amber-200">فتح مركز الذكاء <ArrowUpLeft size={14}/></Link></div></section>
<section className="rounded-[1.5rem] border border-ink-100 bg-white p-6 shadow-elevated sm:p-7"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black tracking-[.14em] text-emerald-700">CRITICAL INSIGHTS</div><h2 className="mt-1 text-xl font-black text-ink-900">التنبيهات والتوصيات</h2></div><span className="text-xs text-ink-400">حتى 8 عناصر</span></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{(data?.alerts??[]).slice(0,8).map((a:Alert)=><article key={a.id} className="rounded-2xl border border-ink-100 bg-ink-50/50 p-4 transition hover:bg-white"><p className="font-bold text-ink-800">{a.title}</p>{a.description&&<p className="mt-1 text-xs leading-5 text-ink-500">{a.description}</p>}<Link to="/decision-experience?stage=decision" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-emerald-700">فتح سياق القرار <ArrowUpLeft size={13}/></Link></article>)}{(data?.alerts??[]).length===0&&<p className="text-sm text-ink-500">لا توجد توصيات مصدرية حاليًا.</p>}</div></section>
<section className="grid grid-cols-1 gap-5 lg:grid-cols-2"><div className="rounded-[1.5rem] border border-amber-200 bg-amber-50/60 p-6"><div className="flex items-center gap-2"><ShieldCheck className="text-amber-700" size={20}/><h2 className="text-lg font-black text-ink-900">Evidence</h2></div><p className="mt-4 text-sm leading-7 text-amber-900">Source / calculation / reliability: RUNTIME_REQUIRED — لا يتم اختلاق evidence ولا تحويل غياب runtime إلى نجاح.</p></div><div className="rounded-[1.5rem] border border-ink-100 bg-white p-6 shadow-elevated"><h2 className="text-lg font-black text-ink-900">Decision · Accountability · Action</h2><p className="mt-3 text-sm leading-7 text-ink-600">القرار والموافقة والتنفيذ تحتاج authority runtime موثقة ولا تُستنتج من التقرير.</p><Link to="/decision-experience" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-ink-950 px-4 py-3 text-xs font-bold text-white">فتح Decision Workspace <ArrowUpLeft size={14}/></Link></div></section>
<section className="rounded-[1.5rem] border border-ink-100 bg-white p-6 shadow-elevated"><div className="flex items-center gap-2"><ShieldCheck size={19}/><h2 className="text-lg font-black text-ink-900">Actual Outcome · Learning</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-ink-50 p-5"><p className="text-[10px] font-black tracking-wider text-ink-400">ACTUAL</p><p className="mt-2 font-bold text-ink-800">Awaiting actual outcome</p></div><div className="rounded-2xl bg-ink-50 p-5"><p className="text-[10px] font-black tracking-wider text-ink-400">LEARNING</p><p className="mt-2 font-bold text-ink-800">Not yet verified</p></div></div></section></>}</div>}
