import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { ArrowLeft, FileSearch, FileText, Printer, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { fetchDashboardIntelligence, fetchDashboardSnapshot, type DashboardKPIs } from '@/lib/dashboard-canonical';
import { formatCurrency } from '@/lib/format';
import { EVIDENCE_TRUTH_LABELS, getOutcomeMessage } from '@/lib/product-experience-contract';
import type { Recommendation, Alert } from '@/lib/types';

function RuntimeNote({ children }: { children: string }) { return <div role="status" aria-live="polite" className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{children}</div>; }
function Section({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) { return <section className="rounded-2xl border border-ink-200 bg-white p-5 shadow-sm print:break-inside-avoid"><p className="text-[11px] font-bold tracking-[0.14em] text-ink-400">{eyebrow}</p><h2 className="mt-1 text-lg font-bold text-ink-950">{title}</h2><div className="mt-4">{children}</div></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-ink-50 p-4"><p className="text-xs text-ink-500">{label}</p><p className="mt-1 text-xl font-bold text-ink-950">{value}</p></div>; }
function ContextLink({ to, children }: { to: string; children: string }) { return <Link to={to} className="inline-flex items-center gap-2 rounded-xl border border-ink-200 bg-white px-3 py-2 text-xs font-semibold text-ink-700 transition hover:bg-ink-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2"><span>{children}</span><ArrowLeft size={14} aria-hidden="true" /></Link>; }

export function ExecutiveReportPage() {
  const [searchParams] = useSearchParams();
  const recommendationId = searchParams.get('recommendationId');
  const decisionHref = (stage: string) => {
    const params = new URLSearchParams({ stage });
    if (recommendationId) params.set('recommendationId', recommendationId);
    return `/decision-experience?${params.toString()}`;
  };
  const [kpis, setKpis] = useState<DashboardKPIs | null>(null); const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [snapshot, intelligence] = await Promise.all([fetchDashboardSnapshot(3), fetchDashboardIntelligence()]); setKpis(snapshot.kpis); setRecommendations(intelligence.recommendations); setAlerts(intelligence.alerts); } catch (cause) { setError(cause instanceof Error ? cause.message : 'تعذر تحميل التقرير التنفيذي.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const printReport = () => window.print();
  return <div dir="rtl" className="space-y-5 pb-10 print:bg-white print:p-0">
    <header className="rounded-3xl bg-ink-950 p-6 text-white print:border print:border-ink-200 print:bg-white print:text-black lg:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><div className="flex items-center gap-2 text-sm font-semibold text-primary-300 print:text-ink-600"><Sparkles size={17} aria-hidden="true"/> Executive Reporting</div><h1 className="mt-2 text-2xl font-bold lg:text-3xl">قصة تنفيذية واحدة لدورة القرار</h1><p className="mt-3 text-sm leading-7 text-ink-300 print:text-ink-600">ما حدث، ولماذا، وما الدليل، وما القرار، ومن يملكه، وما النتيجة. لا تُعرض بيانات غير موجودة في المصادر المعتمدة.</p></div><button type="button" onClick={printReport} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-ink-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 print:hidden"><Printer size={17} aria-hidden="true"/> Print / PDF</button></div></header>
    {loading && <div role="status" aria-live="polite" className="rounded-2xl border border-ink-200 bg-white p-5 text-sm text-ink-500">جارٍ بناء التقرير من المصادر المعتمدة…</div>}
    {error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800"><div className="flex items-center gap-2 font-semibold"><RefreshCw size={17} aria-hidden="true"/> تعذر تحميل التقرير</div><p className="mt-2">{error}</p><button type="button" onClick={() => void load()} className="mt-3 rounded-xl border border-red-300 bg-white px-3 py-2 text-xs font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-500">إعادة المحاولة</button></div>}
    {!loading && !error && <>
      <Section title="Executive Summary" eyebrow="01 · WHAT HAPPENED?"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="المبيعات" value={kpis?.totalSales == null ? 'غير متاح' : formatCurrency(kpis.totalSales)}/><Metric label="الربحية الإجمالية" value={kpis?.grossMargin == null ? 'غير متاح' : `${kpis.grossMargin.toFixed(1)}%`}/><Metric label="التحصيل" value={kpis?.collectionRate == null ? 'غير متاح' : `${kpis.collectionRate.toFixed(1)}%`}/><Metric label="الذمم المتأخرة" value={kpis?.overdueReceivables == null ? 'غير متاح' : formatCurrency(kpis.overdueReceivables)}/></div></Section>
      <Section title="Critical Insights" eyebrow="02 · WHY?"><div className="space-y-3">{alerts.length === 0 && <p className="rounded-xl border border-dashed border-ink-300 p-4 text-sm text-ink-500">لا توجد تنبيهات مصدرية حاليًا.</p>}{alerts.slice(0, 8).map(alert => <article key={alert.id} className="rounded-xl border border-ink-100 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{alert.title}</p><p className="mt-1 text-xs text-ink-500">{alert.is_read ? 'مقروء' : 'يتطلب إجراءً'}</p></div><ContextLink to={decisionHref('decision')}>فتح سياق القرار</ContextLink></div></article>)}</div></Section>
      <Section title="Evidence" eyebrow="03 · WHERE DID THIS COME FROM?"><div className="space-y-3"><RuntimeNote>{EVIDENCE_TRUTH_LABELS.RUNTIME_BLOCKED}</RuntimeNote><div className="grid gap-3 sm:grid-cols-3"><Metric label="Source" value="Runtime required"/><Metric label="Calculation" value="Not yet verified"/><Metric label="Reliability" value="Not available"/></div><div className="flex flex-wrap gap-2"><ContextLink to={decisionHref('evidence')}>Open Evidence Workspace</ContextLink><ContextLink to="/command-center">Return to Command Center</ContextLink></div></div></Section>
      <Section title="Recommendations" eyebrow="04 · WHAT SHOULD WE DO?"><div className="space-y-3">{recommendations.length === 0 && <p className="rounded-xl border border-dashed border-ink-300 p-4 text-sm text-ink-500">لا توجد توصيات مصدرية بعد.</p>}{recommendations.slice(0, 8).map(rec => <article key={rec.id} className="rounded-xl border border-ink-100 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{rec.title}</p><p className="mt-1 text-xs text-ink-500">{rec.expected_impact == null ? 'Expected impact unavailable' : `Expected impact: ${formatCurrency(rec.expected_impact)}`}</p></div><ContextLink to={decisionHref('decision')}>فتح التوصية والقرار</ContextLink></div></article>)}</div></Section>
      <Section title="Decision · Accountability · Action" eyebrow="05 · WHO OWNS IT?"><RuntimeNote>القرار والموافقة والتنفيذ لا تُستنتج من التقرير. تحتاج إلى authority runtime موثقة.</RuntimeNote><div className="mt-3 grid gap-3 sm:grid-cols-3"><Metric label="Decision" value="Awaiting authenticated runtime"/><Metric label="Owner" value="Not available"/><Metric label="Next action" value="Runtime required"/></div><div className="mt-3"><ContextLink to={decisionHref('decision')}>فتح Decision Workspace</ContextLink></div></Section>
      <Section title="Actual Outcome · Learning" eyebrow="06 · WHAT DID WE LEARN?"><div className="grid gap-3 sm:grid-cols-2"><Metric label="Actual outcome" value="Awaiting actual outcome"/><Metric label="Delta" value="Not calculable yet"/></div><div className="mt-3 flex items-start gap-3 rounded-xl border border-ink-200 bg-ink-50 p-4"><ShieldCheck size={18} className="mt-0.5 shrink-0" aria-hidden="true"/><p className="text-sm leading-6 text-ink-600">{getOutcomeMessage('NOT_YET_EXECUTED', 'RUNTIME_BLOCKED')}. Repository learning is not runtime learning.</p></div><div className="mt-3"><ContextLink to={decisionHref('outcome')}>متابعة النتيجة والتعلّم</ContextLink></div></Section>
      <div className="flex flex-wrap gap-2 print:hidden"><button type="button" onClick={printReport} className="inline-flex items-center gap-2 rounded-xl bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500"><FileText size={16} aria-hidden="true"/> Print / Save PDF</button><button type="button" disabled className="rounded-xl border border-ink-200 px-4 py-2.5 text-sm font-semibold text-ink-400" title="يتطلب canonical snapshot موثق">Snapshot · Awaiting verified runtime</button><button type="button" disabled className="rounded-xl border border-ink-200 px-4 py-2.5 text-sm font-semibold text-ink-400" title="يتطلب زوج snapshots موثق">Diff · Snapshot pair unavailable</button><button type="button" disabled className="rounded-xl border border-ink-200 px-4 py-2.5 text-sm font-semibold text-ink-400" title="يتطلب dataset تنفيذي موثق">Board Pack · Runtime data required</button><Link to="/command-center" className="inline-flex items-center gap-2 rounded-xl border border-ink-200 px-4 py-2.5 text-sm font-semibold text-ink-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500"><FileSearch size={16} aria-hidden="true"/> Command Center</Link></div>
    </>}
  </div>;
}
