import { useEffect, useState, useCallback } from 'react';
import { Brain, Lightbulb, TrendingUp, AlertTriangle, CheckCircle2, XCircle, Target, Zap, RefreshCw, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card, CardHeader, CardBody } from '@/components/ui/Card';
import { SeverityBadge, PriorityBadge, ConfidenceBadge } from '@/components/ui/Badge';
import { LoadingState, ErrorState, EmptyState } from '@/components/ui/States';
import { ForecastChart } from '@/components/ui/Charts';
import { fetchRecommendations, fetchAlerts, fetchForecasts, updateRecommendationStatus } from '@/lib/queries';
import { formatCurrency, relativeTime } from '@/lib/format';
import type { Recommendation, Alert, Forecast } from '@/lib/types';

export function IntelligenceCenterPage() {
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [forecasts, setForecasts] = useState<Forecast[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLoading(true); setError(null); const [recs, alts, fc] = await Promise.all([fetchRecommendations(), fetchAlerts(), fetchForecasts()]); setRecommendations(recs); setAlerts(alts); setForecasts(fc); } catch (e: any) { setError(e?.message || 'تعذر تحميل مركز الذكاء'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <LoadingState />; if (error) return <ErrorState message={error} onRetry={load} />;
  const newRecs = recommendations.filter(r => r.status === 'new').length; const criticalAlerts = alerts.filter(a => a.severity === 'critical' && !a.is_read).length; const companyForecasts = forecasts.filter(f => f.entity_type === 'company');
  const forecastChartData = companyForecasts.map(f => { const d = new Date(f.period); const labels = ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر']; return { label: labels[d.getMonth()], forecast_value: f.forecast_value, upper_bound: f.upper_bound, lower_bound: f.lower_bound }; });
  return <div dir="rtl" className="space-y-6 animate-fade-in pb-10">
    <section className="rounded-3xl bg-ink-950 p-6 text-white lg:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="flex items-center gap-2 text-sm text-primary-300"><Brain size={18}/> Intelligence & Decision</div><h1 className="mt-2 text-2xl font-bold lg:text-3xl">مركز الذكاء والقرار</h1><p className="mt-2 max-w-3xl text-sm leading-7 text-ink-300">حوّل التنبيه والتوصية والتنبؤ إلى سياق قرار قابل للمراجعة — دون اختلاق بيانات أو ادعاء نتيجة غير موثقة.</p></div><div className="flex gap-2"><button type="button" onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-ink-900"><RefreshCw size={16}/> تحديث</button><Link to="/decision-experience" className="inline-flex items-center gap-2 rounded-xl border border-ink-700 px-4 py-2.5 text-sm font-semibold">مساحة القرار <ArrowLeft size={16}/></Link></div></div></section>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Card><CardBody><Brain className="mb-3 text-primary-600"/><div className="text-3xl font-bold">{newRecs}</div><div className="text-sm text-ink-500 mt-1">توصيات جديدة</div></CardBody></Card><Card><CardBody><AlertTriangle className="mb-3 text-danger-600"/><div className="text-3xl font-bold">{criticalAlerts}</div><div className="text-sm text-ink-500 mt-1">تنبيهات حرجة غير مقروءة</div></CardBody></Card><Card><CardBody><TrendingUp className="mb-3 text-accent-600"/><div className="text-3xl font-bold">{forecasts.length}</div><div className="text-sm text-ink-500 mt-1">تنبؤات نشطة</div></CardBody></Card></div>
    <Card><CardHeader title="نبض التنبؤ" subtitle="بيانات التنبؤ المتاحة من المصدر" action={<ConfidenceBadge confidence="FORECAST"/>}/><CardBody>{forecastChartData.length ? <ForecastChart data={forecastChartData}/> : <EmptyState title="لا توجد تنبؤات مصدرية" message="لن يتم إنشاء منحنى تقديري دون بيانات موثقة."/>}</CardBody></Card>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Card><CardHeader title="مركز التنبيهات" subtitle="ما يحتاج انتباهًا الآن"/><CardBody><div className="space-y-3">{alerts.slice(0,6).map((alert: Alert)=><article key={alert.id} className="rounded-xl border border-ink-100 p-3"><div className="flex items-start gap-3"><SeverityBadge severity={alert.severity}/><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{alert.title}</div>{alert.description&&<p className="mt-1 text-xs text-ink-500">{alert.description}</p>}<div className="mt-2 text-[11px] text-ink-400">{relativeTime(alert.created_at)}</div></div></div></article>)}{alerts.length===0&&<EmptyState title="لا توجد تنبيهات مصدرية حاليًا"/>}</div></CardBody></Card>
    <Card><CardHeader title="التوصيات القابلة للإجراء" subtitle="انتقل من الرؤية إلى القرار"/><CardBody><div className="space-y-3">{recommendations.filter(r=>r.status==='new').slice(0,6).map((rec: Recommendation)=><article key={rec.id} className="rounded-xl border border-ink-100 p-3"><div className="flex items-start gap-3"><div className="w-9 h-9 rounded-lg bg-accent-50 text-accent-600 flex items-center justify-center"><Lightbulb size={17}/></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold">{rec.title}</span><PriorityBadge priority={rec.priority}/><ConfidenceBadge confidence={rec.confidence}/></div>{rec.description&&<p className="mt-1 text-xs text-ink-500">{rec.description}</p>}{rec.expected_impact&&<div className="mt-2 text-xs text-success-600">الأثر المتوقع: {formatCurrency(rec.expected_impact)}</div>}<div className="mt-3 flex gap-2"><button onClick={async()=>{await updateRecommendationStatus(rec.id,'accepted'); await load();}} className="btn-primary text-xs"><CheckCircle2 size={13}/> قبول</button><button onClick={async()=>{await updateRecommendationStatus(rec.id,'rejected'); await load();}} className="btn-secondary text-xs"><XCircle size={13}/> رفض</button><Link to="/decision-experience?stage=decision" className="btn-secondary text-xs">فتح القرار</Link></div></div></div></article>)}{recommendations.filter(r=>r.status==='new').length===0&&<EmptyState title="لا توجد توصيات مصدرية حاليًا"/>}</div></CardBody></Card></div>
    <Card><CardBody><div className="flex items-center gap-3"><Target size={18} className="text-primary-600"/><div><div className="font-semibold">قاعدة الثقة</div><p className="text-xs text-ink-500 mt-1">التنبؤ Forecast، والتوصية Recommendation، والتنبيه Alert تبقى موسومة بطبيعتها. النتيجة الفعلية لا تُسجل إلا من outcome runtime موثق.</p></div><Zap size={18} className="mr-auto text-accent-600"/></div></CardBody></Card>
  </div>;
}

export { RecommendationsPage, ForecastsPage } from '@/pages/IntelligencePages';
