import { useCallback, useEffect, useMemo, useState } from 'react';
import { RefreshCw, Layers3, PackageSearch, TrendingUp, AlertTriangle, ShieldCheck } from 'lucide-react';
import { fetchInventoryIntelligenceSource } from '@/lib/free-toolbox/inventory-intelligence-canonical';
import { applyReportMode, type DetailReportRow, type ReportMode, type GroupedReportRow } from '@/lib/free-toolbox/grouped-report';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { PageHeader, LoadingState, ErrorState } from '@/components/ui/States';
import { TruthContextStrip } from '@/components/TruthContextStrip';
import { BusinessInvestigationDrawer, type InvestigationTarget } from '@/components/BusinessInvestigationDrawer';
import { formatNumber } from '@/lib/format';

type Group={id:string;name:string;members:string[]};
export function InventoryIntelligencePage(){
 const [mode,setMode]=useState<ReportMode>('grouped'); const [rows,setRows]=useState<DetailReportRow[]>([]); const [groups,setGroups]=useState<Record<string,Group>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [investigation,setInvestigation]=useState<InvestigationTarget|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const source=await fetchInventoryIntelligenceSource();setRows(source.rows);setGroups(source.groups)}catch(e:unknown){setError(e instanceof Error?e.message:'تعذر تحميل بيانات ذكاء المخزون')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]); const projected=useMemo(()=>applyReportMode(rows,mode,groups),[rows,mode,groups]); if(loading)return <LoadingState message="جارٍ بناء تحليل المخزون والمجموعات…"/>; if(error)return <ErrorState message={error} onRetry={()=>void load()}/>;
 const grouped=projected as GroupedReportRow[]; const detail=projected as DetailReportRow[]; const groupedRows=mode==='grouped'?grouped:[]; const covered=groupedRows.filter(r=>Number.isFinite(r.daysOfCover)); const missingDemand=groupedRows.filter(r=>!Number.isFinite(r.dailyDemand)); const truthStatus=projected.length===0?'INSUFFICIENT_DATA':covered.length>0?'CALCULATED':'INSUFFICIENT_DATA';
 const openGroup=(r:GroupedReportRow)=>setInvestigation({title:r.name,eyebrow:'Money + Stock Lens · مجموعة',severity:Number.isFinite(r.daysOfCover)&&r.daysOfCover<7?'warning':'info',summary:'هذه المجموعة نقطة دخول للتحقيق في رأس المال والتغطية والطلب. لا يتم اختلاق سبب النقص أو الزيادة من أرقام المخزون وحدها.',facts:[{label:'الأصناف',value:r.memberSkus.join('، ')||'غير متاحة'},{label:'الرصيد',value:formatNumber(r.stockUnits)},{label:'الطلب اليومي',value:Number.isFinite(r.dailyDemand)?formatNumber(r.dailyDemand):'غير متاح'},{label:'أيام التغطية',value:Number.isFinite(r.daysOfCover)?String(r.daysOfCover.toFixed(1)):'غير متاح'}],confirmedReasons:Number.isFinite(r.daysOfCover)?['التغطية معاد حسابها من بيانات المجموعة وفق قاعدة النظام.']:[],missingEvidence:['سبب تغير الطلب أو الرصيد.','تكلفة رأس المال أو هامش الفرصة إن لم تكن ضمن المصدر الحالي.','أثر أي إجراء بعد التنفيذ.'],actions:[{label:'افتح مركز العمل',path:'/work-center',hint:'راجع الاستثناءات والبيانات التشغيلية.'},{label:'افتح تجربة القرار',path:'/decision-experience?stage=evidence',hint:'افحص الدليل قبل أي تدخل.'}],evidence:{source:'fetchInventoryIntelligenceSource',asOf:'لقطة المخزون الحالية',period:'حسب الوضع التجميعي',status:Number.isFinite(r.daysOfCover)?'CALCULATED':'INSUFFICIENT_DATA',formula:'رصيد المجموعة ÷ الطلب اليومي للمجموعة = أيام التغطية'}});
 const openDetail=(r:DetailReportRow)=>setInvestigation({title:r.name,eyebrow:'Stock Lens · صنف',severity:'info',summary:'هذا الصنف معروض داخل سياق المجموعة. لا يعني الرصيد وحده وجود مشكلة أو أولوية دون دليل طلب وفترة مرجعية.',facts:[{label:'SKU',value:r.sku},{label:'المجموعة',value:r.groupId?groups[r.groupId]?.name||'غير متاحة':'غير مرتبط'},{label:'الرصيد',value:formatNumber(r.stockUnits)}],confirmedReasons:[],missingEvidence:['الطلب اليومي الموثق للفترة.','سبب أي تغير في الحركة.','نتيجة الإجراء بعد التنفيذ.'],actions:[{label:'افتح ذكاء المخزون',path:'/inventory',hint:'وسّع السياق إلى التغطية والمجموعات.'},{label:'افتح القرار',path:'/decision-experience?stage=evidence',hint:'راجع الدليل قبل اعتماد الإجراء.'}],evidence:{source:'fetchInventoryIntelligenceSource',asOf:'لقطة المخزون الحالية',status:'CANONICAL'}});
 return <div dir="rtl" className="space-y-5 animate-fade-in"><PageHeader title="رؤية المخزون ورأس المال" subtitle="Money + Stock Lens: من الرصيد إلى التغطية والطلب، ثم التحقيق قبل القرار." actions={<button type="button" onClick={()=>void load()} className="btn-secondary"><RefreshCw size={15}/> تحديث</button>}/><TruthContextStrip status={truthStatus} asOf="غير متاحة من المصدر" asOfLabel="حداثة المصدر" rangeLabel="لقطة المخزون الحالية"/><section className="rounded-[18px] border border-[#15372f] bg-[#0d2a24] p-4 text-white sm:p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[10px] font-black tracking-[0.14em] text-white/40">CAPITAL → COVERAGE → TRUST</div><h2 className="mt-1 text-lg font-black">ما الذي نعرفه عن المخزون الآن؟</h2><p className="mt-1 max-w-2xl text-[11px] leading-5 text-white/55">التغطية لا تُعرض عند غياب الطلب، ولا يتحول نقص البيانات إلى حالة حرجة مصطنعة.</p></div><button type="button" onClick={()=>groupedRows[0]&&openGroup(groupedRows[0])} className="btn-secondary border-white/10 bg-white/10 text-white hover:bg-white/15"><ShieldCheck size={15}/> افحص أول مجموعة</button></div></section>
 <div className="filter-toolbar w-fit"><button type="button" aria-pressed={mode==='detail'} onClick={()=>setMode('detail')} className={"filter-chip "+(mode==='detail'?'filter-chip-active':'hover:bg-white')}>تفصيل للتحقيق</button><button type="button" aria-pressed={mode==='grouped'} onClick={()=>setMode('grouped')} className={"filter-chip "+(mode==='grouped'?'filter-chip-active':'hover:bg-white')}>تجميع لفهم التعرض</button></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card hover onClick={()=>groupedRows[0]&&openGroup(groupedRows[0])}><CardBody><div className="text-xs text-ink-500">الصفوف المعروضة</div><div className="text-2xl font-bold mt-1">{formatNumber(projected.length)}</div><div className="mt-1 text-[11px] text-ink-400">نقطة دخول للتحقيق</div></CardBody></Card><Card hover onClick={()=>groupedRows[0]&&openGroup(groupedRows[0])}><CardBody><div className="text-xs text-ink-500">المجموعات</div><div className="text-2xl font-bold mt-1">{formatNumber(Object.keys(groups).length)}</div></CardBody></Card><Card hover onClick={()=>groupedRows[0]&&openGroup(groupedRows[0])}><CardBody><div className="text-xs text-ink-500">تغطية محسوبة</div><div className="text-2xl font-bold mt-1">{formatNumber(covered.length)}</div></CardBody></Card><Card hover onClick={()=>groupedRows[0]&&openGroup(groupedRows[0])}><CardBody><div className="text-xs text-ink-500">الطلب غير المتاح</div><div className="text-2xl font-bold mt-1">{formatNumber(missingDemand.length)}</div><div className="mt-1 text-[11px] text-ink-400">نقص دليل لا يعني صفرًا</div></CardBody></Card></div>
 <Card><CardHeader title={mode==='grouped'?'مجموعات رأس المال والتغطية':'أصناف داخل سياق المجموعة'} subtitle={mode==='grouped'?'ابدأ بالمجموعة ثم افتح الدليل':'الصنف نقطة تفصيل، وليس وحدة التنقل الأساسية'}/><CardBody><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-right text-ink-400">{mode==='grouped'?<><th className="p-3">المجموعة</th><th className="p-3">الأصناف</th><th className="p-3">الرصيد</th><th className="p-3">الطلب</th><th className="p-3">المبيعات</th><th className="p-3">أيام التغطية</th></>:<><th className="p-3">SKU</th><th className="p-3">الصنف</th><th className="p-3">المجموعة</th><th className="p-3">الرصيد</th></>}</tr></thead><tbody>{mode==='grouped'?groupedRows.map(r=><tr key={r.groupId} className="border-b border-ink-50"><td className="p-3"><button type="button" onClick={()=>openGroup(r)} className="font-semibold text-primary-700 hover:underline"><Layers3 size={15} className="inline ml-1"/>{r.name}</button></td><td className="p-3">{r.memberSkus.join('، ')}</td><td className="p-3">{formatNumber(r.stockUnits)}</td><td className="p-3">{formatNumber(r.requestedUnits)}</td><td className="p-3">{formatNumber(r.netSalesUnits)}</td><td className="p-3">{Number.isFinite(r.daysOfCover)?<Badge variant={r.daysOfCover<7?'danger':r.daysOfCover<14?'warning':'success'}>{r.daysOfCover.toFixed(1)} يوم</Badge>:<Badge variant="neutral">لا توجد بيانات كافية</Badge>}</td></tr>):detail.map(r=><tr key={r.sku} className="border-b border-ink-50"><td className="p-3 font-medium"><button type="button" onClick={()=>openDetail(r)} className="text-primary-700 hover:underline">{r.sku}</button></td><td className="p-3">{r.name}</td><td className="p-3">{r.groupId?groups[r.groupId]?.name:'غير مرتبط'}</td><td className="p-3">{formatNumber(r.stockUnits)}</td></tr>)}</tbody></table>{!projected.length&&<div className="p-10 text-center text-ink-400"><PackageSearch size={30} className="mx-auto mb-2"/>لا توجد بيانات مخزون قابلة للتحليل.</div>}</div></CardBody></Card>
 <div className="grid lg:grid-cols-2 gap-4"><Card><CardBody><div className="flex gap-3"><TrendingUp className="text-primary-600" size={20}/><div><div className="font-semibold">قاعدة التغطية</div><p className="text-xs text-ink-500 mt-1">في الوضع التجميعي تعاد التغطية من رصيد المجموعة ÷ الطلب اليومي للمجموعة عندما تكون البيانات مكتملة.</p></div></div></CardBody></Card><Card><CardBody><div className="flex gap-3"><AlertTriangle className="text-warning-600" size={20}/><div><div className="font-semibold">حدود الثقة</div><p className="text-xs text-ink-500 mt-1">لا تُعرض تغطية أو طلبات افتراضية عند غياب البيانات الزمنية؛ الحالة تبقى غير مكتملة.</p></div></div></CardBody></Card></div>
 <BusinessInvestigationDrawer target={investigation} onClose={()=>setInvestigation(null)} /></div>;
}
