import { useCallback, useEffect, useMemo, useState } from 'react';
import { RefreshCw, Layers3, PackageSearch, TrendingUp, AlertTriangle, Boxes, Gauge, Sparkles } from 'lucide-react';
import { fetchInventoryIntelligenceSource } from '@/lib/free-toolbox/inventory-intelligence-canonical';
import { applyReportMode, type DetailReportRow, type ReportMode, type GroupedReportRow } from '@/lib/free-toolbox/grouped-report';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { LoadingState, ErrorState } from '@/components/ui/States';
import { formatNumber } from '@/lib/format';

type Group={id:string;name:string;members:string[]};
export function InventoryIntelligencePage(){
 const [mode,setMode]=useState<ReportMode>('grouped'); const [rows,setRows]=useState<DetailReportRow[]>([]); const [groups,setGroups]=useState<Record<string,Group>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const source=await fetchInventoryIntelligenceSource();setRows(source.rows);setGroups(source.groups)}catch(e:unknown){setError(e instanceof Error?e.message:'تعذر تحميل بيانات ذكاء المخزون')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]); const projected=useMemo(()=>applyReportMode(rows,mode,groups),[rows,mode,groups]); if(loading)return <LoadingState message="جارٍ بناء تحليل المخزون والمجموعات…"/>; if(error)return <ErrorState message={error} onRetry={()=>void load()}/>;
 const grouped=projected as GroupedReportRow[]; const detail=projected as DetailReportRow[]; const groupedRows=mode==='grouped'?grouped:[]; const covered=groupedRows.filter(r=>Number.isFinite(r.daysOfCover)); const missingDemand=groupedRows.filter(r=>!Number.isFinite(r.dailyDemand));
 return <div dir="rtl" className="space-y-7 pb-10 animate-fade-in">
  <section className="experience-hero"><div className="relative z-10 flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className="experience-chip"><Boxes size={14}/> Inventory Intelligence</div><h1 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl lg:text-5xl">ذكاء المخزون</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/70">حوّل رصيد المخزون والطلب الحقيقي إلى صورة تشغيلية واضحة على مستوى الصنف والمجموعة، بدون افتراضات مخفية.</p></div><button onClick={()=>void load()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white/10 px-4 py-3 text-sm font-bold text-white ring-1 ring-white/15 backdrop-blur hover:bg-white/15"><RefreshCw size={16}/> تحديث البيانات</button></div><div className="relative z-10 mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4"><div className="experience-kpi"><span>الصفوف المعروضة</span><strong>{formatNumber(projected.length)}</strong></div><div className="experience-kpi"><span>المجموعات</span><strong>{formatNumber(Object.keys(groups).length)}</strong></div><div className="experience-kpi"><span>تغطية محسوبة</span><strong>{formatNumber(covered.length)}</strong></div><div className="experience-kpi"><span>طلب غير متاح</span><strong className="!text-amber-200">{formatNumber(missingDemand.length)}</strong></div></div></section>
  <section className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">Workspace</div><h2 className="mt-1 text-2xl font-black text-ink-900">طريقة القراءة</h2></div><div className="flex rounded-2xl bg-white p-1.5 shadow-soft ring-1 ring-ink-100"><button onClick={()=>setMode('grouped')} className={`rounded-xl px-4 py-2.5 text-sm font-bold transition ${mode==='grouped'?'bg-primary-700 text-white shadow':'text-ink-500 hover:bg-ink-50'}`}>التجميع الحقيقي</button><button onClick={()=>setMode('detail')} className={`rounded-xl px-4 py-2.5 text-sm font-bold transition ${mode==='detail'?'bg-primary-700 text-white shadow':'text-ink-500 hover:bg-ink-50'}`}>تفاصيل الأصناف</button></div></section>
  <section className="grid grid-cols-1 gap-4 lg:grid-cols-3"><Card className="overflow-hidden lg:col-span-2"><CardHeader title={mode==='grouped'?'المجموعات تحت المجهر':'الأصناف تحت المجهر'} subtitle={mode==='grouped'?'الرصيد والطلب والمبيعات والتغطية يعاد حسابها على مستوى المجموعة':'كل SKU يظهر منفردًا مع ارتباطه بالمجموعة إن وجد'} action={<Badge variant="primary">Live read-model</Badge>}/><CardBody><div className="overflow-x-auto"><table className="experience-table w-full text-sm"><thead><tr>{mode==='grouped'?<><th>المجموعة</th><th>الأصناف</th><th>الرصيد</th><th>الطلب</th><th>المبيعات</th><th>التغطية</th></>:<><th>SKU</th><th>الصنف</th><th>المجموعة</th><th>الرصيد</th></>}</tr></thead><tbody>{mode==='grouped'?groupedRows.map(r=><tr key={r.groupId}><td className="font-bold"><Layers3 size={15} className="inline ml-1 text-primary-600"/>{r.name}</td><td className="text-ink-500">{r.memberSkus.join('، ')}</td><td>{formatNumber(r.stockUnits)}</td><td>{formatNumber(r.requestedUnits)}</td><td>{formatNumber(r.netSalesUnits)}</td><td>{Number.isFinite(r.daysOfCover)?<Badge variant={r.daysOfCover<7?'danger':r.daysOfCover<14?'warning':'success'}>{r.daysOfCover.toFixed(1)} يوم</Badge>:<Badge variant="neutral">غير متاح</Badge>}</td></tr>):detail.map(r=><tr key={r.sku}><td className="font-bold">{r.sku}</td><td>{r.name}</td><td className="text-ink-500">{r.groupId?groups[r.groupId]?.name:'غير مرتبط'}</td><td>{formatNumber(r.stockUnits)}</td></tr>)}</tbody></table>{!projected.length&&<div className="py-16 text-center text-ink-400"><PackageSearch size={34} className="mx-auto mb-3"/>لا توجد بيانات مخزون قابلة للتحليل.</div>}</div></CardBody></Card>
   <div className="space-y-4"><Card className="premium-gradient-soft border-0"><CardBody><div className="flex items-center gap-2 text-primary-700"><Gauge size={18}/><span className="text-xs font-bold">مؤشر القراءة</span></div><h3 className="mt-3 text-xl font-black text-ink-900">التغطية تُحسب، لا تُخمن</h3><p className="mt-2 text-sm leading-6 text-ink-500">في العرض التجميعي تُعاد قراءة الرصيد مقابل الطلب اليومي للمجموعة عندما تكون البيانات مكتملة.</p></CardBody></Card><Card><CardBody><div className="flex items-center gap-2 text-amber-700"><Sparkles size={17}/><span className="text-xs font-bold">حدود الثقة</span></div><div className="mt-4 space-y-3 text-sm"><div className="flex items-center justify-between rounded-xl bg-emerald-50 px-3 py-3"><span>تغطية محسوبة</span><strong className="text-emerald-700">{formatNumber(covered.length)}</strong></div><div className="flex items-center justify-between rounded-xl bg-amber-50 px-3 py-3"><span>طلب غير متاح</span><strong className="text-amber-700">{formatNumber(missingDemand.length)}</strong></div></div></CardBody></Card></div>
  </section><section className="grid gap-4 lg:grid-cols-2"><Card><CardBody><div className="flex gap-3"><TrendingUp className="shrink-0 text-primary-600" size={20}/><div><div className="font-black text-ink-900">قاعدة القرار</div><p className="mt-1 text-xs leading-6 text-ink-500">لا يتم جمع أيام التغطية للأصناف؛ يعاد حسابها من رصيد المجموعة ÷ الطلب اليومي للمجموعة.</p></div></div></CardBody></Card><Card><CardBody><div className="flex gap-3"><AlertTriangle className="shrink-0 text-warning-600" size={20}/><div><div className="font-black text-ink-900">حدود البيانات الحالية</div><p className="mt-1 text-xs leading-6 text-ink-500">عند غياب البيانات الزمنية لا تُعرض تغطية أو طلبات افتراضية، وتبقى الإشارة صريحة بأنها غير متاحة.</p></div></div></CardBody></Card></section>
 </div>
}
