import type { ReactNode } from 'react';
import { useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, FileText, GitBranch, ShieldCheck, XCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { Badge, PriorityBadge } from '@/components/ui/Badge';
import { formatCurrency } from '@/lib/format';
import { buildProductVerticalSlice } from '@/lib/productVerticalSlice';
import { productVerticalSliceFixture } from '../../scripts/product-vertical-slice-fixture.mjs';
const slice=buildProductVerticalSlice(productVerticalSliceFixture);
const Info=({label,value}:{label:string;value:string})=><div className="rounded-xl border border-ink-100 p-3"><div className="text-xs text-ink-400">{label}</div><div className="mt-1 text-sm font-semibold text-ink-800">{value}</div></div>;
const Section=({title,children,action}:{title:string;children:ReactNode;action?:ReactNode})=><Card><CardHeader title={title} action={action}/><CardBody>{children}</CardBody></Card>;
function Evidence(){const m=slice.metrics.stockout_risk;return <Section title="Evidence Inspector"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Source" value={slice.evidence.source}/><Info label="Document" value="golden.inventory_ar"/><Info label="Row" value={String(slice.evidence.rowCount)}/><Info label="Fingerprint" value={slice.evidence.fingerprint}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Extracted Value" value={`${slice.source.quantity} units`}/><Info label="Normalized Value" value={`${slice.source.quantity} units`}/><Info label="Entity / SKU" value={`${slice.source.sku} · سكر`}/><Info label="Trust" value={slice.evidence.trust}/></div><div className="mt-4 rounded-xl border border-primary-100 bg-primary-50/40 p-4"><div className="flex items-center gap-2 font-semibold"><GitBranch size={16}/>Calculation lineage</div><p className="mt-2 text-sm">stock ÷ demand → coverage → lead time + safety → stockout risk</p><p className="mt-2 text-xs text-ink-500">{m.metricId} · v{m.metricVersion} · confidence {m.confidence}</p></div></Section>}
function Recommendation({next}:{next:()=>void}){const r=slice.recommendation;return <Section title="Recommendation" action={<Badge variant="success">Confidence {(r.confidence*100).toFixed(0)}%</Badge>}><p className="font-semibold">{r.reason}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info label="Evidence" value={r.evidence.join(' · ')}/><Info label="Expected Impact" value={`${r.expectedImpact.value} ${r.expectedImpact.unit}`}/><Info label="Policy" value={`${r.policy.policyId} v${r.policy.version}`}/><Info label="Approval" value={`Threshold ${r.policy.approvalThreshold}%`}/></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{r.alternatives.map((x,i)=><div key={x} className={`rounded-xl border p-3 ${i===0?'border-primary-200 bg-primary-50':'border-ink-100'}`}><div className="text-[11px] text-ink-400">Alternative {String.fromCharCode(65+i)}</div><div className="mt-1 text-sm font-medium">{x}</div><div className="mt-2 text-xs text-ink-500">{i===0?'Preferred by deterministic policy':'Fallback'}</div></div>)}</div><button onClick={next} className="btn-primary mt-4 inline-flex items-center gap-2">Inspect Decision <ArrowLeft size={16}/></button></Section>}
function Decision({next}:{next:()=>void}){const d=slice.decision;return <Section title="Decision" action={<Badge variant="success">{d.approval}</Badge>}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Info label="Why" value={d.reason}/><Info label="Metrics" value={Object.keys(d.metricVersions).join(' · ')}/><Info label="Rules" value={d.rules.join(' · ')}/><Info label="Confidence" value={`${(d.confidence*100).toFixed(0)}%`}/><Info label="Evidence" value={d.evidence.join(' · ')}/><Info label="Source Report" value={slice.report.reportId}/></div><button onClick={next} className="btn-primary mt-4">Review Approval</button></Section>}
function Approval({next}:{next:()=>void}){return <Section title="Approval" action={<ShieldCheck size={18} className="text-primary-600"/>}><div className="rounded-xl bg-ink-50 p-4"><div className="font-semibold">{slice.decision.approval==='REQUIRED'?'Pending approval':'Auto-approved by policy'}</div><p className="mt-1 text-sm text-ink-500">Review evidence, recommendation and impact. AI does not choose approval policy.</p></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={next} className="btn-primary inline-flex items-center gap-2"><CheckCircle2 size={16}/>Approve & continue</button><button className="btn-secondary"><XCircle size={16}/>Reject</button><button className="btn-secondary">Postpone</button></div></Section>}
function Task(){const t=slice.task;return <Section title="Workforce Execution" action={<Badge variant="warning">{t.status}</Badge>}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Task ID" value={t.id}/><Info label="Department" value={t.department}/><Info label="Role / Owner" value={`Procurement · ${t.owner}`}/><Info label="Priority" value={t.priority}/><Info label="Deadline / SLA" value={`${t.dueDate} · ${t.slaHours}h`}/><Info label="Why" value={t.why}/><Info label="Decision" value={t.decisionId}/><Info label="Expected Impact" value={`${t.expectedImpact} days coverage`}/></div><p className="mt-4 rounded-xl border border-warning-100 bg-warning-50 p-3 text-sm">Owner remains <strong>UNRESOLVED</strong> because no real assignment exists in the benchmark.</p></Section>}
function Report(){const r=slice.report;return <Section title="Executive Intelligence Report"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Report ID" value={r.reportId}/><Info label="Data As Of" value={r.dataAsOf}/><Info label="Generated At" value={r.generatedAt}/><Info label="Business Health" value={r.businessHealth}/></div><div className="mt-4 grid gap-3 lg:grid-cols-3"><Info label="Critical Issues" value={r.criticalIssues.join(' · ')||'None'}/><Info label="Recommendations" value={r.recommendations.map(x=>x.id).join(' · ')}/><Info label="Action Register" value={r.actionRegister.join(' · ')}/></div><div className="mt-4 flex flex-wrap gap-2"><Link to="/reports/executive-intelligence" className="btn-primary inline-flex items-center gap-2"><FileText size={16}/>Open report</Link><button onClick={()=>window.print()} className="btn-secondary inline-flex items-center gap-2"><FileText size={16}/>Print / Export PDF</button></div><p className="mt-3 text-xs text-ink-400">Actual outcome remains null until real evidence exists.</p></Section>}
export function ProductExperiencePage(){const [active,setActive]=useState('finding'); const coverageDays=slice.metrics.stock_coverage.value; const content:Record<string,ReactNode>={finding:<Section title="Stockout Risk — High" action={<PriorityBadge priority="high"/>}><p className="text-lg font-semibold">الصنف {slice.source.sku} · سكر قد ينفد قبل وصول التوريد.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info label="Risk" value={`${Math.round(slice.insight.value)}%`}/><Info label="Coverage" value={coverageDays === null ? 'UNAVAILABLE' : `${coverageDays.toFixed(1)} days`}/><Info label="Inventory Value" value={slice.metrics.inventory_value.value === null ? 'UNAVAILABLE' : formatCurrency(slice.metrics.inventory_value.value)}/></div><button onClick={()=>setActive('evidence')} className="btn-primary mt-4 inline-flex items-center gap-2">Inspect finding <ArrowLeft size={16}/></button></Section>,evidence:<Evidence/>,metric:<Section title="Semantic Metrics"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="net_sales" value={slice.metrics.net_sales.value === null ? 'UNAVAILABLE' : formatCurrency(slice.metrics.net_sales.value)}/><Info label="gross_profit" value={slice.metrics.gross_profit.value === null ? 'UNAVAILABLE' : formatCurrency(slice.metrics.gross_profit.value)}/><Info label="inventory_value" value={slice.metrics.inventory_value.value === null ? 'UNAVAILABLE' : formatCurrency(slice.metrics.inventory_value.value)}/><Info label="stockout_risk" value={slice.metrics.stockout_risk.value === null ? 'UNAVAILABLE' : `${Math.round(slice.metrics.stockout_risk.value)}%`}/></div></Section>,insight:<Section title="Insight"><div className="rounded-xl border border-warning-100 bg-warning-50 p-4"><AlertTriangle size={20} className="mb-2 text-warning-600"/><strong>High stockout risk</strong><p className="mt-1 text-sm">{slice.insight.value.toFixed(0)}% based on coverage versus lead time + safety.</p></div></Section>,recommendation:<Recommendation next={()=>setActive('decision')}/>,decision:<Decision next={()=>setActive('approval')}/>,approval:<Approval next={()=>setActive('task')}/>,task:<Task/>,report:<Report/>};return <div dir="rtl" className="space-y-5"><div><div className="flex items-center gap-2"><h1 className="text-2xl font-bold">Product Intelligence Flow</h1><Badge variant="primary">DEMO FIXTURE</Badge></div><p className="mt-1 text-sm text-ink-500">Finding → Evidence → Metric → Insight → Recommendation → Decision → Approval → Task → Report.</p></div><div className="overflow-x-auto rounded-2xl border border-ink-100 bg-white p-2"><div className="flex min-w-max gap-1">{Object.keys(content).map(id=><button key={id} onClick={()=>setActive(id)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${active===id?'bg-primary-600 text-white':'bg-ink-50 text-ink-500'}`}>{id}</button>)}</div></div>{content[active]}</div>}
export function ExecutiveIntelligenceReportPage(){return <div dir="rtl" className="space-y-5"><h1 className="text-2xl font-bold">Executive Intelligence Report</h1><Report/><Section title="Department Tasks"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{['Sales','Procurement','Warehouse','Finance'].map(x=><Info key={x} label={x} value={x==='Procurement'?slice.task.id:'No active benchmark task'}/>)}</div></Section><Section title="Outcome Capture"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{['Expected','Actual','Variance','Reason','Learning'].map(x=><Info key={x} label={x} value={x==='Expected'?String(slice.report.expectedImpact):'Not recorded'}/>)}</div></Section></div>}
export function WorkforceExecutionPage(){return <div dir="rtl" className="space-y-5"><h1 className="text-2xl font-bold">Workforce Execution</h1><Task/><div className="grid gap-3 lg:grid-cols-4">{['Sales','Procurement','Warehouse','Finance'].map(x=><Card key={x}><CardBody><div className="font-semibold">{x}</div><div className="mt-2 text-xs text-ink-500">Shared Decision/Task projection</div></CardBody></Card>)}</div></div>}
export function ProductCommandCenterPage(){return <div dir="rtl" className="space-y-5"><h1 className="text-2xl font-bold">Command Center</h1><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info label="Critical Decisions" value="1"/><Info label="Top Risks" value="1"/><Info label="Pending Approvals" value={slice.decision.approval==='REQUIRED'?'1':'0'}/><Info label="Overdue Tasks" value="0"/></div><Section title="What Changed Since Last Look"><p className="text-sm">Stockout risk = <strong>{Math.round(slice.insight.value)}%</strong>; decision = <strong>{slice.decision.id}</strong>; task = <strong>{slice.task.id}</strong>.</p></Section><Link to="/workforce" className="btn-primary inline-flex">Today's Actions</Link></div>}
