import { useCallback, useEffect, useState } from 'react';
import { Banknote, CircleAlert, ShieldCheck, TrendingUp } from 'lucide-react';
import { Card, CardBody } from '@/components/ui/Card';
import { PageHeader, LoadingState, ErrorState } from '@/components/ui/States';
import { BusinessInvestigationDrawer, type InvestigationTarget } from '@/components/BusinessInvestigationDrawer';
import { fetchProfitabilitySnapshot, type ProfitabilitySnapshot } from '@/lib/dashboard-canonical';
import { formatCurrency, formatNumber } from '@/lib/format';
import { TruthContextStrip } from '@/components/TruthContextStrip';

function knownCount(a: number | null, b: number | null): string { if (a == null || b == null) return 'غير متاح'; return formatNumber(a + b); }

export function ProfitabilityReportCanonicalPage() {
  const [snapshot, setSnapshot] = useState<ProfitabilitySnapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [investigation, setInvestigation] = useState<InvestigationTarget | null>(null);
  const load = useCallback(async () => { try { setLoading(true); setError(null); setSnapshot(await fetchProfitabilitySnapshot()); } catch (e: unknown) { setError(e instanceof Error ? e.message : 'تعذر تحميل الربحية'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); if (loading) return <LoadingState />; if (error) return <ErrorState message={error} onRetry={load} />; if (!snapshot) return null;
  const calculated = snapshot.status === 'CALCULATED' && snapshot.revenue != null && snapshot.cost != null && snapshot.gross_profit != null;
  const openMetric = (title: string, label: string, value: string, formula?: string) => setInvestigation({
    title, eyebrow: 'Money Lens · الربحية', severity: calculated ? 'info' : 'warning',
    summary: calculated ? 'القيمة محسوبة من اللقطة المالية المعتمدة. التفسير التجاري يحتاج إلى أدلة الفترة والتفاصيل التي تربط الرقم بمصدره.' : 'القيمة المالية غير قابلة للإثبات بالكامل من اللقطة الحالية؛ لن يتم تحويل نقص الدليل إلى صفر.',
    facts: [{ label, value }, { label: 'الحالة', value: calculated ? 'محسوبة' : 'بيانات غير كافية' }, { label: 'العملة', value: snapshot.currency || 'غير محددة' }, { label: 'الفواتير', value: formatNumber(snapshot.invoice_count) }],
    confirmedReasons: calculated ? ['الرقم مشتق من مسار الربحية المعتمد.'] : [],
    missingEvidence: ['تفاصيل الصفوف التي تمنع اكتمال الدليل إن وجدت.', 'السبب التجاري لأي تغير في الرقم.', 'نتيجة أي إجراء لاحق قبل اعتباره أثرًا محققًا.'],
    actions: [{ label: 'افتح مركز العمل', path: '/work-center', hint: 'راجع الاستثناءات والبيانات التي تحتاج معالجة.' }, { label: 'افتح تجربة القرار', path: '/decision-experience?stage=evidence', hint: 'افحص الدليل قبل تحويل المؤشر إلى قرار.' }],
    evidence: { source: 'fetchProfitabilitySnapshot', asOf: snapshot.as_of, status: snapshot.status, formula },
  });
  return <div dir="rtl" className="report-page space-y-5 animate-fade-in">
    <PageHeader title="الربحية والهامش" subtitle="Money Lens: الإيراد ← التكلفة ← الهامش ← الثقة، ثم التحقيق في ما تغيّر." actions={<button type="button" onClick={() => window.print()} className="btn-primary print-hide text-xs">طباعة</button>} />
    <TruthContextStrip status={snapshot.status} asOf={snapshot.as_of} rangeLabel="لقطة الربحية الحالية" />
    <section className="rounded-[18px] border border-[#15372f] bg-[#0d2a24] p-4 text-white sm:p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[10px] font-black tracking-[0.14em] text-white/40">MONEY → TRUST → ACTION</div><h2 className="mt-1 text-lg font-black">ما قيمة الربح التي نستطيع إثباتها الآن؟</h2><p className="mt-1 max-w-2xl text-[11px] leading-5 text-white/55">الرقم المالي لا يكفي وحده. النظام يوضح حالته ثم يفتح التحقيق دون اختلاق سبب للتغير.</p></div><button type="button" onClick={() => openMetric('سلسلة إثبات الربحية', 'حالة الربحية', calculated ? 'موثقة حسابيًا' : 'غير مكتملة', 'الإيراد − التكلفة = الربح الإجمالي')} className="btn-secondary border-white/10 bg-white/10 text-white hover:bg-white/15"><ShieldCheck size={15}/> افحص سلسلة الإثبات</button></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-white/10 bg-white/[.045] p-3"><div className="text-[10px] text-white/40">الهامش</div><div className="mt-1 text-xl font-black">{calculated && snapshot.gross_margin != null ? String(snapshot.gross_margin.toFixed(2)) + '%' : 'غير متاح'}</div></div><div className="rounded-xl border border-white/10 bg-white/[.045] p-3"><div className="text-[10px] text-white/40">العملة</div><div className="mt-1 text-sm font-black">{snapshot.currency || 'غير محددة'}</div></div><div className="rounded-xl border border-white/10 bg-white/[.045] p-3"><div className="text-[10px] text-white/40">حالة الدليل</div><div className="mt-1 text-sm font-black">{calculated ? 'مسار حسابي مكتمل' : 'تحتاج مراجعة'}</div></div></div></section>
    <section className="grid grid-cols-1 gap-3 md:grid-cols-3">
      <Card hover onClick={() => openMetric('الإيراد', 'الإيراد', calculated ? formatCurrency(snapshot.revenue) : 'غير متاح', 'الإيراد من السجل المالي المعتمد')}><CardBody><div className="flex items-center gap-2"><Banknote size={16} className="text-primary-600"/><div className="surface-label">الإيراد</div></div><div className="display-number mt-1">{calculated ? formatCurrency(snapshot.revenue) : 'غير متاح'}</div><div className="mt-1 text-[11px] text-ink-400">انقر للتحقيق في سلسلة الرقم</div></CardBody></Card>
      <Card hover onClick={() => openMetric('التكلفة', 'التكلفة', calculated ? formatCurrency(snapshot.cost) : 'غير متاح', 'التكلفة من السجل المالي المعتمد')}><CardBody><div className="surface-label">التكلفة</div><div className="display-number mt-1">{calculated ? formatCurrency(snapshot.cost) : 'غير متاح'}</div><div className="mt-1 text-[11px] text-ink-400">لا تُفترض التكلفة عند نقص المصدر</div></CardBody></Card>
      <Card className="hero-surface" hover onClick={() => openMetric('الربح الإجمالي', 'الربح الإجمالي', calculated ? formatCurrency(snapshot.gross_profit) : 'غير متاح', 'الإيراد − التكلفة = الربح الإجمالي')}><CardBody><div className="flex items-center gap-2"><TrendingUp size={16} className="text-success-700"/><div className="surface-label">الربح الإجمالي</div></div><div className="display-number mt-1">{calculated ? formatCurrency(snapshot.gross_profit) : 'غير متاح'}</div><div className="mt-1 text-[11px] text-ink-400">نقطة دخول للتحقيق</div></CardBody></Card>
    </section>
    <Card><CardBody><div className="grid grid-cols-2 gap-4 md:grid-cols-4"><button type="button" onClick={() => openMetric('الهامش الإجمالي', 'الهامش', calculated && snapshot.gross_margin != null ? String(snapshot.gross_margin.toFixed(2)) + '%' : 'غير متاح', 'الربح الإجمالي ÷ الإيراد')} className="text-right"><div className="surface-label">الهامش</div><div className="mt-1 text-lg font-black text-ink-900">{calculated && snapshot.gross_margin != null ? String(snapshot.gross_margin.toFixed(2)) + '%' : 'غير متاح'}</div></button><div><div className="surface-label">الفواتير</div><div className="mt-1 text-lg font-black text-ink-900">{formatNumber(snapshot.invoice_count)}</div></div><div><div className="surface-label">صفوف مالية ناقصة</div><div className="mt-1 text-lg font-black text-ink-900">{knownCount(snapshot.bad_invoice_rows, snapshot.bad_sale_item_rows)}</div></div><div><div className="surface-label">اختلاف العملة</div><div className="mt-1 text-lg font-black text-ink-900">{formatNumber(snapshot.currency_mismatch_rows)}</div></div></div>{snapshot.reasons.length > 0 && <div className="warning-callout mt-5 text-xs text-warning-800"><div className="font-bold mb-1"><CircleAlert size={14} className="inline ml-1"/> أسباب عدم كفاية الدليل</div><ul className="list-disc pr-5 space-y-1">{snapshot.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul></div>}</CardBody></Card>
    <BusinessInvestigationDrawer target={investigation} onClose={() => setInvestigation(null)} />
  </div>;
}
