import { ArrowUpLeft,BarChart3,Brain,ClipboardCheck,Database,FileBarChart,Package,Receipt,ShieldCheck,Sparkles,TrendingUp,WalletCards,Workflow,Users,CalendarDays,Printer } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card,CardBody } from '@/components/ui/Card';
import { ActionLink } from '@/components/ui/ActionButton';

const groups=[
 {title:'قيادة وإدارة',tag:'EXECUTIVE',items:[['/reports/executive','التقرير التنفيذي','لقطة إدارية موحدة للعرض واتخاذ القرار',ClipboardCheck],['/command-center','مركز القيادة','الأولويات والإشارات والإجراءات',WalletCards],['/tasks','خطة العمل','مهام اليوم والغد والمسؤولون والمتابعة',CalendarDays]]},
 {title:'أداء تجاري',tag:'PERFORMANCE',items:[['/reports/sales','المبيعات','الإيراد والفواتير والتحصيل والعملاء',BarChart3],['/reports/purchases','المشتريات','حركة الشراء والتوريد والقيمة',FileBarChart],['/reports/profitability','الربحية','التكلفة والهامش والربح وجودة النمو',TrendingUp]]},
 {title:'تشغيل وسيولة',tag:'OPERATIONS',items:[['/reports/inventory','المخزون','الرصيد والقيمة والنفاد وإعادة الطلب',Package],['/reports/receivables','الذمم والتحصيل','المستحقات وأعمار الفواتير',Receipt],['/reports/inventory-intelligence','ذكاء المخزون','قراءة تشغيلية لحالة المخزون',Database]]},
 {title:'إدارة وموارد',tag:'MANAGEMENT',items:[['/customers','إدارة العملاء','قاعدة العملاء والبحث ومسارات المتابعة',Users],['/data-quality','حوكمة البيانات','صحة البيانات والمشكلات التي تؤثر على القرار',ShieldCheck],['/import','مركز البيانات','إدخال البيانات والتحقق قبل اعتمادها',Database]]},
 {title:'ذكاء وتنبؤ',tag:'INTELLIGENCE',items:[['/intelligence/forecasts','التنبؤات','اتجاهات الطلب والمؤشرات المستقبلية المتاحة',TrendingUp],['/intelligence/recommendations','التوصيات','ما الذي يستحق إجراءً الآن؟',Brain],['/intelligence/scenarios','ماذا لو؟','محاكاة الفرضيات قبل اعتماد القرار',Workflow]]},
];

export function ReportsLandingPage(){return <div dir="rtl" className="space-y-8 pb-12 animate-fade-in">
<section className="experience-hero overflow-hidden"><div className="relative z-10 grid gap-8 xl:grid-cols-[1.5fr_.8fr] xl:items-end"><div><div className="experience-chip"><Sparkles size={14}/> REPORT COMMAND</div><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">مركز التقارير والذكاء</h1><p className="mt-4 max-w-3xl text-sm leading-8 text-white/70 sm:text-base">مركز موحد للتقارير التنفيذية والإدارية والتشغيلية والتحليلات الذكية، يبدأ من الحقيقة وينتهي بقرار وعمل قابل للمتابعة.</p><div className="mt-7 flex flex-wrap gap-2"><ActionLink to="/reports/executive" icon={<ClipboardCheck size={17}/>} size="lg">التقرير التنفيذي</ActionLink><ActionLink to="/assistant" variant="soft" icon={<Brain size={17}/>} size="lg" className="border-white/15 bg-white/10 text-white hover:bg-white/15">المساعد الذكي</ActionLink><ActionLink to="/tasks" variant="ghost" icon={<CalendarDays size={17}/>} size="lg" className="bg-white/10 text-white hover:bg-white/15">خطة العمل</ActionLink><ActionLink to="/intelligence/scenarios" variant="ghost" icon={<Workflow size={17}/>} size="lg" className="bg-white/10 text-white hover:bg-white/15">ماذا لو؟</ActionLink></div></div><div className="rounded-[2rem] border border-white/10 bg-white/10 p-6 backdrop-blur-xl"><div className="text-[10px] font-black tracking-[.18em] text-emerald-100/60">DECISION LOOP</div><div className="mt-3 text-lg font-black text-white">حقيقة → تفسير → تنبؤ → محاكاة → قرار → عمل → نتيجة</div><p className="mt-3 text-xs leading-6 text-white/60">كل انتقال يوضح ما هو محسوب وما هو غير متاح بدل صناعة أرقام وهمية.</p></div></div></section>
<section className="grid gap-5 md:grid-cols-2">{groups.map(group=><Card key={group.tag} className="overflow-hidden rounded-[1.7rem] border-0 shadow-elevated"><CardBody className="p-6"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black tracking-[.16em] text-emerald-700">{group.tag}</div><h2 className="mt-1 text-xl font-black text-ink-950">{group.title}</h2></div><div className="h-2 w-2 rounded-full bg-amber-400"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{group.items.map(([path,title,desc,Icon])=>{const I=Icon as typeof Brain;return <Link key={path} to={path as string} className="group rounded-2xl border border-ink-100 bg-ink-50/40 p-4 transition hover:-translate-y-1 hover:border-emerald-200 hover:bg-white"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><I size={18}/></span><ArrowUpLeft size={15} className="text-ink-300 group-hover:text-emerald-700"/></div><h3 className="mt-4 text-sm font-black text-ink-900">{title}</h3><p className="mt-1 text-xs leading-5 text-ink-500">{desc}</p></Link>})}</div></CardBody></Card>)}</section>
<section className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="experience-section"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black tracking-[.16em] text-amber-700">OPERATING PATH</div><h2 className="experience-section-title mt-1">من التقرير إلى التنفيذ</h2></div><ShieldCheck size={20} className="text-emerald-700"/></div><div className="mt-5 grid gap-3 sm:grid-cols-5">{[['/data-quality','1','ثقة البيانات'],['/analytics','2','فهم النمط'],['/decision-experience','3','اتخاذ القرار'],['/tasks','4','توزيع العمل'],['/assistant','5','الخبير الذكي']].map(([to,n,label])=><Link key={to} to={to} className="rounded-2xl border border-ink-100 bg-white p-4 text-center transition hover:border-emerald-200 hover:shadow-sm"><div className="mx-auto flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-900 text-xs font-black text-white">{n}</div><div className="mt-3 text-xs font-black text-ink-800">{label}</div></Link>)}</div></div><div className="rounded-[1.7rem] border border-emerald-100 bg-gradient-to-l from-emerald-50 via-white to-amber-50/50 p-6"><Brain className="text-emerald-800" size={24}/><h2 className="mt-3 text-lg font-black text-ink-950">المعلومة ليست نهاية الرحلة</h2><p className="mt-2 text-xs leading-6 text-ink-500">عندما تحتاج تفسيراً أو توقعاً أو محاكاة أو توزيعاً للعمل، انتقل مباشرة إلى المساحة المناسبة بدل تكرار نفس التقرير في شاشة جديدة.</p><div className="mt-4 flex flex-wrap gap-3"><Link to="/assistant" className="inline-flex text-xs font-black text-emerald-800">المساعد والخبير ←</Link><Link to="/tasks" className="inline-flex text-xs font-black text-emerald-800">مركز المهام ←</Link></div></div></section>
<section className="grid gap-4 md:grid-cols-3"><div className="card p-5"><Printer size={19} className="text-emerald-700"/><h3 className="mt-3 font-black text-ink-950">مخرجات قابلة للعرض</h3><p className="mt-2 text-xs leading-6 text-ink-500">التقارير التي تدعم العرض والطباعة تبقى مرتبطة ببياناتها الفعلية، دون تحويل التصميم إلى بديل عن الدليل.</p></div><div className="card p-5"><Workflow size={19} className="text-amber-700"/><h3 className="mt-3 font-black text-ink-950">ماذا لو؟ قبل القرار</h3><p className="mt-2 text-xs leading-6 text-ink-500">الفرضية تُعرض كفرضية، والنتيجة المحسوبة تُفصل عن التوقع أو البيانات غير المتاحة.</p></div><div className="card p-5"><Users size={19} className="text-teal-700"/><h3 className="mt-3 font-black text-ink-950">من القرار إلى الموظف</h3><p className="mt-2 text-xs leading-6 text-ink-500">المسار التشغيلي يربط التوصيات وبنود القرار بقائمة عمل يمكن متابعتها وتوزيعها.</p></div></section>
<section className="rounded-2xl border border-ink-100 bg-white p-5 text-xs leading-6 text-ink-500"><b className="text-ink-800">قاعدة الثقة:</b> التقارير تعرض ما تسمح به البيانات الفعلية فقط. عند نقص البيانات أو عدم توفر قدرة تشغيلية، يظهر ذلك صراحة ولا يتحول إلى رقم مصطنع.</section>
</div>}
