import { Link } from 'react-router-dom';
import { ArrowUpLeft, BarChart3, FileBarChart, Package, Receipt, Sparkles, TrendingUp, Crosshair, Brain, ClipboardCheck, Upload, LayoutDashboard, Database, ShieldCheck, Activity, WalletCards } from 'lucide-react';
import { Card, CardBody } from '@/components/ui/Card';
import { ActionLink } from '@/components/ui/ActionButton';

const reports=[
 {path:'/reports/sales',title:'المبيعات',desc:'الإيراد والفواتير والتحصيل والعملاء والمنتجات الأعلى أداءً.',icon:BarChart3,tag:'Revenue',meta:'الأداء التجاري'},
 {path:'/reports/purchases',title:'المشتريات',desc:'حركة الشراء والموردون وقيمة الفواتير ومتوسطاتها.',icon:FileBarChart,tag:'Procurement',meta:'حركة التوريد'},
 {path:'/reports/inventory',title:'المخزون',desc:'الرصيد والقيمة والنفاد ونقاط إعادة الطلب.',icon:Package,tag:'Stock',meta:'السيولة التشغيلية'},
 {path:'/reports/receivables',title:'الذمم والتحصيل',desc:'المستحقات وأعمار الفواتير والفجوة النقدية.',icon:Receipt,tag:'Cash',meta:'النقد والتحصيل'},
 {path:'/reports/profitability',title:'الربحية',desc:'المبيعات والتكلفة والربح والهامش حسب الفئة.',icon:TrendingUp,tag:'Margin',meta:'جودة النمو'},
];
const commandLinks=[
 {to:'/reports/executive',icon:ClipboardCheck,label:'التقرير التنفيذي',description:'لقطة جاهزة للعرض التنفيذي'},
 {to:'/analytics',icon:BarChart3,label:'مركز التحليلات',description:'الغوص في RFM وABC والأعمار'},
 {to:'/intelligence',icon:Brain,label:'مركز الذكاء',description:'التوصيات والتنبؤات والإشارات'},
 {to:'/command-center',icon:Crosshair,label:'مركز القيادة',description:'الأولوية والقرار والتنفيذ'},
];
const operatingLinks=[
 {to:'/import',icon:Upload,label:'إدخال البيانات',description:'ابدأ من المصدر وأدخل البيانات عبر المسار القانوني'},
 {to:'/data-quality',icon:ShieldCheck,label:'ثقة البيانات',description:'تحقق من جودة المصدر قبل قراءة النتائج'},
 {to:'/inventory',icon:Database,label:'المخزون',description:'انتقل من التقرير إلى الحالة التشغيلية'},
 {to:'/decision-experience',icon:Activity,label:'مساحة القرار',description:'حوّل الإشارة إلى قرار قابل للمتابعة'},
];

export function ReportsLandingPage(){return <div dir="rtl" className="space-y-8 pb-12 animate-fade-in">
<section className="experience-hero overflow-hidden" aria-labelledby="reports-command-title"><div className="relative z-10 grid gap-8 xl:grid-cols-[1.55fr_.8fr] xl:items-end"><div className="max-w-4xl"><div className="experience-chip"><Sparkles size={14}/> Report Command</div><h1 id="reports-command-title" className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">مركز التقارير</h1><p className="mt-4 max-w-3xl text-sm leading-8 text-white/70 sm:text-base">المكان الذي تتحول فيه أرقام العمل إلى صورة قابلة للفهم. اختر التقرير، اقرأ الدليل، ثم انتقل مباشرة إلى التحليل أو الذكاء أو القرار.</p><div className="mt-7 flex flex-wrap gap-2"><ActionLink to="/reports/executive" icon={<ClipboardCheck size={17}/>} size="lg">التقرير التنفيذي</ActionLink><ActionLink to="/import" variant="soft" icon={<Upload size={17}/>} size="lg" className="border-white/15 bg-white/10 text-white hover:bg-white/15">إدخال بيانات</ActionLink><ActionLink to="/command-center" variant="ghost" icon={<Crosshair size={17}/>} size="lg" className="bg-white/10 text-white hover:bg-white/15">مركز القيادة</ActionLink></div></div><div className="grid grid-cols-2 gap-3" aria-label="ملخص مساحة التقارير"><div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur-xl"><div className="text-[10px] font-black tracking-[.18em] text-emerald-100/60">REPORT SURFACE</div><div className="mt-2 text-3xl font-black text-white">05</div><div className="mt-1 text-xs text-white/60">مساحات تقرير أساسية</div></div><div className="rounded-3xl border border-white/10 bg-white/10 p-5 backdrop-blur-xl"><div className="text-[10px] font-black tracking-[.18em] text-amber-100/70">NEXT STEP</div><div className="mt-2 text-lg font-black text-white">تحليل ← ذكاء</div><div className="mt-1 text-xs text-white/60">لا تتوقف عند الرقم</div></div></div></div></section>

<section aria-labelledby="core-reports-title"><div className="mb-5 flex flex-col gap-2 px-1 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-[10px] font-black tracking-[.18em] text-emerald-700">CORE REPORTS</div><h2 id="core-reports-title" className="mt-1 text-2xl font-black text-ink-950">صورة العمل من خمس زوايا</h2><p className="mt-1 text-xs text-ink-400">كل بطاقة تفتح مساحة العمل الكاملة، وليس مجرد شاشة ملخص.</p></div><Link to="/" className="hidden items-center gap-1 text-xs font-bold text-emerald-700 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-emerald-500/10 sm:flex">العودة للرئيسية <LayoutDashboard size={14}/></Link></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{reports.map((r,i)=>{const Icon=r.icon;return <Link key={r.path} to={r.path} aria-label={`فتح تقرير ${r.title}`} className={`group focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-emerald-500/15 ${i===4?'md:col-span-2 xl:col-span-1':''}`}><Card hover className="h-full overflow-hidden rounded-[1.7rem] border-0 shadow-elevated"><CardBody className="relative flex min-h-[270px] flex-col justify-between p-6 sm:p-7"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-emerald-700 via-teal-500 to-amber-400"/><div><div className="flex items-start justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700 ring-1 ring-emerald-100 transition duration-300 group-hover:-translate-y-1 group-hover:shadow-lg"><Icon size={25}/></div><ArrowUpLeft aria-hidden="true" size={20} className="text-ink-300 transition duration-300 group-hover:-translate-y-1 group-hover:text-emerald-600"/></div><div className="mt-6 flex items-center justify-between gap-3"><span className="text-[10px] font-black tracking-[.16em] text-emerald-700">{r.tag}</span><span className="rounded-full bg-ink-50 px-2 py-1 text-[9px] font-bold text-ink-400">{r.meta}</span></div><h2 className="mt-2 text-xl font-black text-ink-900">تقرير {r.title}</h2><p className="mt-2 text-sm leading-6 text-ink-500">{r.desc}</p></div><div className="mt-5 flex items-center justify-between border-t border-ink-100 pt-4"><span className="text-xs font-bold text-emerald-700">فتح مساحة التقرير</span><span aria-hidden="true" className="text-xs text-ink-300 transition group-hover:text-emerald-600">←</span></div></CardBody></Card></Link>})}</div></section>

<section className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="experience-section" aria-labelledby="decision-path-title"><div className="experience-section-header"><div><div className="text-[10px] font-black tracking-[.16em] text-emerald-700">DECISION PATH</div><h2 id="decision-path-title" className="experience-section-title mt-1">ممرات القرار</h2><p className="experience-section-subtitle">من التقرير إلى التحليل ثم التوصية والقرار.</p></div><WalletCards size={20} className="text-emerald-700"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{commandLinks.map(({to,icon:Icon,label,description})=><Link key={to} to={to} aria-label={`${label}: ${description}`} className="group rounded-2xl border border-ink-100 bg-white p-4 transition hover:-translate-y-1 hover:border-emerald-100 hover:shadow-elevated focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-emerald-500/15"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Icon size={18}/></span><ArrowUpLeft aria-hidden="true" size={15} className="text-ink-300 transition group-hover:-translate-y-1 group-hover:text-emerald-700"/></div><div className="mt-4 text-sm font-black text-ink-900">{label}</div><div className="mt-1 text-xs leading-5 text-ink-400">{description}</div></Link>)}</div></div><div className="experience-section" aria-labelledby="operating-loop-title"><div className="experience-section-header"><div><div className="text-[10px] font-black tracking-[.16em] text-amber-700">OPERATING LOOP</div><h2 id="operating-loop-title" className="experience-section-title mt-1">قبل أن تثق بالرقم</h2><p className="experience-section-subtitle">المسار الصحيح يبدأ من مصدر موثوق وينتهي بإجراء واضح.</p></div><ShieldCheck size={20} className="text-amber-700"/></div><div className="mt-5 space-y-2">{operatingLinks.map(({to,icon:Icon,label,description},i)=><Link key={to} to={to} aria-label={`${label}: ${description}`} className="group flex items-center gap-3 rounded-2xl border border-ink-100 bg-white p-3 transition hover:border-emerald-100 hover:bg-emerald-50/30 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-emerald-500/15"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-ink-50 text-ink-500 group-hover:bg-emerald-50 group-hover:text-emerald-700">{i+1}</span><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white text-emerald-700 ring-1 ring-ink-100"><Icon size={16}/></span><span className="min-w-0 flex-1"><span className="block text-xs font-black text-ink-800">{label}</span><span className="mt-0.5 block text-[10px] leading-5 text-ink-400">{description}</span></span><ArrowUpLeft aria-hidden="true" size={14} className="shrink-0 text-ink-300 group-hover:text-emerald-700"/></Link>)}</div></div></section>

<section className="rounded-[1.7rem] border border-emerald-100 bg-gradient-to-l from-emerald-50 via-white to-amber-50/50 p-5 shadow-sm sm:p-6" aria-label="قاعدة الثقة"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-emerald-900 text-white shadow-lg"><ShieldCheck size={20}/></div><div><h3 className="text-sm font-black text-ink-900">قاعدة الثقة</h3><p className="mt-1 max-w-2xl text-xs leading-6 text-ink-500">التقرير لا يصنع حقيقة جديدة. إذا كانت البيانات ناقصة أو غير مكتملة، سيظهر ذلك بدل تحويل النقص إلى نتيجة وهمية.</p></div></div><ActionLink to="/data-quality" variant="secondary" icon={<Database size={15}/>}>فحص جودة البيانات</ActionLink></div></section>
</div>}
