import { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { FileBarChart, ShoppingCart, Package, Receipt, TrendingUp } from 'lucide-react';
import { Card, CardHeader, CardBody } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { PageHeader, LoadingState, ErrorState } from '@/components/ui/States';
import { DataTable } from '@/components/ui/DataTable';
import { TrendChart, HorizontalBarChart, CategoryPieChart } from '@/components/ui/Charts';
import {
  fetchDashboardKPIs, fetchMonthlyTrend, fetchTopCustomers, fetchTopProducts,
  fetchCategoryBreakdown, fetchSalesInvoices, fetchAgingBuckets,
} from '@/lib/queries';
import { fetchInventoryReportSnapshot, fetchPurchaseReportSummary } from '@/lib/report-truth';
import { fetchProfitabilityTruth, type ProfitabilityCategory } from '@/lib/report-profitability-truth';
import { formatCurrency, formatNumber, formatDate } from '@/lib/format';
import { downloadReportArtifact } from '@/lib/report-execution/download';
import type { SalesInvoice, PurchaseInvoice } from '@/lib/types';
import type { DashboardKPIs, MonthlyTrend, TopEntity, CategoryBreakdown, AgingBucket } from '@/lib/queries';
import type { InventoryReportRow } from '@/lib/report-truth';

const reportCards = [
  { path: '/reports/sales', title: 'تقرير المبيعات', desc: 'تحليل تفصيلي للمبيعات حسب الفترة والعميل والمنتج', icon: ShoppingCart, color: 'primary' },
  { path: '/reports/purchases', title: 'تقرير المشتريات', desc: 'تحليل المشتريات حسب المورد والفترة', icon: FileBarChart, color: 'accent' },
  { path: '/reports/inventory', title: 'تقرير المخزون', desc: 'حالة المخزون والحركات والتقييم', icon: Package, color: 'success' },
  { path: '/reports/receivables', title: 'تقرير الذمم والتحصيل', desc: 'تحليل الذمم المدينة وأعمار الفواتير', icon: Receipt, color: 'warning' },
  { path: '/reports/profitability', title: 'تقرير الأرباح والربحية', desc: 'تحليل الربحية حسب المنتج والعميل والفئة', icon: TrendingUp, color: 'primary' },
];

function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'تعذر تحميل التقرير'; }

export function ReportsCenterPage() {
  return <div className="space-y-6 animate-fade-in"><PageHeader title="مركز التقارير" subtitle="تقارير شاملة قابلة للتصدير والتحليل" /><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{reportCards.map((r) => <Link key={r.path} to={r.path}><Card hover className="h-full"><CardBody><div className="flex items-start gap-3"><div className={`w-11 h-11 rounded-xl bg-${r.color}-50 text-${r.color}-600 flex items-center justify-center flex-shrink-0`}><r.icon size={20} /></div><div><h3 className="font-semibold text-ink-800 text-sm">{r.title}</h3><p className="text-xs text-ink-500 mt-1">{r.desc}</p></div></div></CardBody></Card></Link>)}</div></div>;
}

export function SalesReportPage() {
  const [kpis, setKpis] = useState<DashboardKPIs | null>(null); const [trend, setTrend] = useState<MonthlyTrend[]>([]); const [topCustomers, setTopCustomers] = useState<TopEntity[]>([]); const [topProducts, setTopProducts] = useState<TopEntity[]>([]); const [categories, setCategories] = useState<CategoryBreakdown[]>([]); const [invoices, setInvoices] = useState<SalesInvoice[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { try { setLoading(true); const [k,t,tc,tp,cat,inv] = await Promise.all([fetchDashboardKPIs(),fetchMonthlyTrend(6),fetchTopCustomers(10),fetchTopProducts(10),fetchCategoryBreakdown(),fetchSalesInvoices(0,20)]); setKpis(k);setTrend(t);setTopCustomers(tc);setTopProducts(tp);setCategories(cat);setInvoices(inv.data); } catch (error) { setError(errorMessage(error)); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]); if (loading) return <LoadingState />; if (error) return <ErrorState message={error} onRetry={load} />;
  const exportSales = () => downloadReportArtifact('sales-report-page','تقرير المبيعات (الصفحة الحالية)',['رقم الفاتورة','العميل','التاريخ','الإجمالي','المدفوع','الحالة'],invoices.map((invoice)=>({'رقم الفاتورة':invoice.invoice_number,'العميل':invoice.customer?.name ?? null,'التاريخ':invoice.invoice_date,'الإجمالي':invoice.total,'المدفوع':invoice.paid_amount,'الحالة':invoice.status})));
  return <div className="space-y-6 animate-fade-in"><PageHeader title="تقرير المبيعات" subtitle="تحليل شامل لأداء المبيعات" actions={<button onClick={exportSales} className="btn-secondary text-xs">تصدير XLSX</button>} /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card><CardBody><div className="text-xs text-ink-500 mb-1">إجمالي المبيعات</div><div className="text-xl font-bold text-ink-900">{formatCurrency(kpis?.totalSales)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">عدد الفواتير</div><div className="text-xl font-bold text-ink-900">{formatNumber(kpis?.invoiceCount)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">متوسط قيمة الفاتورة</div><div className="text-xl font-bold text-ink-900">{formatCurrency(kpis?.avgInvoiceValue)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">معدل التحصيل</div><div className="text-xl font-bold text-ink-900">{kpis?.collectionRate == null ? '—' : `${kpis.collectionRate.toFixed(1)}%`}</div></CardBody></Card></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Card className="lg:col-span-2"><CardHeader title="اتجاه المبيعات" subtitle="آخر 6 أشهر" /><CardBody><TrendChart data={trend} /></CardBody></Card><Card><CardHeader title="المبيعات حسب الفئة" /><CardBody><CategoryPieChart data={categories} /></CardBody></Card></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><Card><CardHeader title="أفضل العملاء" /><CardBody><HorizontalBarChart data={topCustomers} dataKey="value" nameKey="name" height={300} /></CardBody></Card><Card><CardHeader title="أفضل المنتجات" /><CardBody><HorizontalBarChart data={topProducts} dataKey="value" nameKey="name" height={300} /></CardBody></Card></div><Card><CardHeader title="آخر الفواتير" subtitle="20 فاتورة الأخيرة" /><DataTable columns={[{key:'invoice_number',label:'رقم الفاتورة',render:(r:SalesInvoice)=><span className="font-medium text-primary-600">{r.invoice_number}</span>},{key:'customer',label:'العميل',render:(r:SalesInvoice)=>r.customer?.name||'—'},{key:'invoice_date',label:'التاريخ',render:(r:SalesInvoice)=>formatDate(r.invoice_date)},{key:'total',label:'الإجمالي',align:'right',render:(r:SalesInvoice)=>formatCurrency(r.total)},{key:'paid_amount',label:'المدفوع',align:'right',render:(r:SalesInvoice)=>formatCurrency(r.paid_amount)},{key:'status',label:'الحالة',align:'center',render:(r:SalesInvoice)=>{const map:Record<string,{variant:'success'|'primary'|'neutral';label:string}>={paid:{variant:'success',label:'مدفوعة'},confirmed:{variant:'primary',label:'مؤكدة'},draft:{variant:'neutral',label:'مسودة'}};const status=map[r.status]??{variant:'neutral',label:r.status};return <Badge variant={status.variant}>{status.label}</Badge>;}}]} data={invoices} /></Card></div>;
}

export function PurchasesReportPage() {
  const [purchases,setPurchases]=useState<PurchaseInvoice[]>([]); const [summary,setSummary]=useState<Awaited<ReturnType<typeof fetchPurchaseReportSummary>>|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{Promise.all([fetchPurchaseReportSummary(), import('@/lib/queries').then(({fetchPurchaseInvoices})=>fetchPurchaseInvoices(0,20))]).then(([s,res])=>{setSummary(s);setPurchases(res.data);setLoading(false);}).catch((e)=>{setError(errorMessage(e));setLoading(false);});},[]);
  if(loading)return <LoadingState/>; if(error)return <ErrorState message={error}/>;
  const exportPurchases=()=>downloadReportArtifact('purchase-report','تقرير المشتريات (الصفحة الحالية)',['رقم الفاتورة','المورد','التاريخ','الإجمالي','المدفوع'],purchases.map((purchase)=>({'رقم الفاتورة':purchase.invoice_number,'المورد':purchase.supplier?.name??null,'التاريخ':purchase.invoice_date,'الإجمالي':purchase.total,'المدفوع':purchase.paid_amount})));
  return <div className="space-y-6 animate-fade-in"><PageHeader title="تقرير المشتريات" subtitle="إجمالي المشتريات مصدره التجميع الخادمي؛ الجدول للعرض فقط" actions={<button onClick={exportPurchases} className="btn-secondary text-xs">تصدير الصفحة</button>} /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card><CardBody><div className="text-xs text-ink-500 mb-1">إجمالي المشتريات</div><div className="text-xl font-bold text-ink-900">{formatCurrency(summary?.totalPurchases)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">عدد الفواتير</div><div className="text-xl font-bold text-ink-900">{formatNumber(summary?.invoiceCount)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">الموردين</div><div className="text-xl font-bold text-ink-900">{formatNumber(summary?.supplierCount)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">متوسط الفاتورة</div><div className="text-xl font-bold text-ink-900">{formatCurrency(summary?.averagePurchase)}</div></CardBody></Card></div><Card><CardHeader title="آخر فواتير المشتريات" /><DataTable columns={[{key:'invoice_number',label:'رقم الفاتورة',render:(r:PurchaseInvoice)=><span className="font-medium text-primary-600">{r.invoice_number}</span>},{key:'supplier',label:'المورد',render:(r:PurchaseInvoice)=>r.supplier?.name||'—'},{key:'invoice_date',label:'التاريخ',render:(r:PurchaseInvoice)=>formatDate(r.invoice_date)},{key:'total',label:'الإجمالي',align:'right',render:(r:PurchaseInvoice)=>formatCurrency(r.total)},{key:'paid_amount',label:'المدفوع',align:'right',render:(r:PurchaseInvoice)=>formatCurrency(r.paid_amount)}]} data={purchases} /></Card></div>;
}

export function InventoryReportPage() {
  const [snapshot,setSnapshot]=useState<Awaited<ReturnType<typeof fetchInventoryReportSnapshot>>|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{fetchInventoryReportSnapshot(0,25).then((value)=>{setSnapshot(value);setLoading(false);}).catch((e)=>{setError(errorMessage(e));setLoading(false);});},[]);
  if(loading)return <LoadingState/>; if(error)return <ErrorState message={error}/>; if(!snapshot)return <ErrorState message="تعذر تحميل تقرير المخزون"/>;
  const exportInventory=()=>downloadReportArtifact('inventory-report-page','تقرير المخزون (الصفحة الحالية)',['المنتج','المستودع','الكمية','التكلفة','القيمة'],snapshot.rows.map((balance:InventoryReportRow)=>({'المنتج':balance.product?.name??null,'المستودع':balance.warehouse?.name??null,'الكمية':balance.quantity,'التكلفة':balance.unit_cost,'القيمة':balance.quantity==null||balance.unit_cost==null?null:balance.quantity*balance.unit_cost})));
  return <div className="space-y-6 animate-fade-in"><PageHeader title="تقرير المخزون" subtitle={snapshot.status==='CALCULATED'?'القيم التجارية من التجميع الخادمي؛ الجدول للعرض فقط':'البيانات غير كافية لإثبات قيمة المخزون'} actions={<button onClick={exportInventory} className="btn-secondary text-xs">تصدير الصفحة</button>} /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card><CardBody><div className="text-xs text-ink-500 mb-1">قيمة المخزون</div><div className="text-xl font-bold text-ink-900">{formatCurrency(snapshot.totalValue)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">عدد الأصناف</div><div className="text-xl font-bold text-ink-900">{formatNumber(snapshot.totalRows)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">مخزون منخفض</div><div className="text-xl font-bold text-warning-600">{formatNumber(snapshot.lowStockRows)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">نفد المخزون</div><div className="text-xl font-bold text-danger-600">{formatNumber(snapshot.outOfStockRows)}</div></CardBody></Card></div><Card><CardHeader title="تفاصيل المخزون" subtitle={`عرض ${snapshot.rows.length} من ${snapshot.totalRows} صف`} /><DataTable columns={[{key:'product',label:'المنتج',render:(r:InventoryReportRow)=>r.product?.name||'—'},{key:'warehouse',label:'المستودع',render:(r:InventoryReportRow)=>r.warehouse?.name||'—'},{key:'quantity',label:'الكمية',align:'right',render:(r:InventoryReportRow)=>formatNumber(r.quantity)},{key:'unit_cost',label:'التكلفة',align:'right',render:(r:InventoryReportRow)=>formatCurrency(r.unit_cost)},{key:'value',label:'القيمة',align:'right',render:(r:InventoryReportRow)=>formatCurrency(r.quantity==null||r.unit_cost==null?null:r.quantity*r.unit_cost)},{key:'status',label:'الحالة',align:'center',render:(r:InventoryReportRow)=>{if(r.quantity==null)return <Badge variant="neutral">بيانات ناقصة</Badge>;if(r.quantity<=0)return <Badge variant="danger">نفد</Badge>;if(r.product?.reorder_point!=null&&r.quantity<=r.product.reorder_point)return <Badge variant="warning">منخفض</Badge>;return <Badge variant="success">متاح</Badge>;}}]} data={snapshot.rows} pageSize={25}/></Card></div>;
}

export function ReceivablesReportPage() {
  const [aging,setAging]=useState<AgingBucket[]>([]); const [invoices,setInvoices]=useState<SalesInvoice[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{Promise.all([fetchAgingBuckets(),fetchSalesInvoices(0,50)]).then(([ag,inv])=>{setAging(ag);setInvoices(inv.data.filter((i)=>Number(i.total)-Number(i.paid_amount)>0));setLoading(false);}).catch(()=>setLoading(false));},[]); if(loading)return <LoadingState/>;
  const totalOutstanding=aging.reduce((s,b)=>s+b.amount,0); const exportReceivables=()=>downloadReportArtifact('receivables-report-page','تقرير الذمم والتحصيل (الصفحة الحالية)',['رقم الفاتورة','العميل','تاريخ الفاتورة','تاريخ الاستحقاق','الإجمالي','المدفوع','المتبقي'],invoices.map((invoice)=>({'رقم الفاتورة':invoice.invoice_number,'العميل':invoice.customer?.name??null,'تاريخ الفاتورة':invoice.invoice_date,'تاريخ الاستحقاق':invoice.due_date,'الإجمالي':invoice.total,'المدفوع':invoice.paid_amount,'المتبقي':invoice.total==null||invoice.paid_amount==null?null:invoice.total-invoice.paid_amount})));
  return <div className="space-y-6 animate-fade-in"><PageHeader title="تقرير الذمم والتحصيل" subtitle="تحليل الذمم المدينة وأعمار الفواتير" actions={<button onClick={exportReceivables} className="btn-secondary text-xs">تصدير XLSX</button>}/><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card><CardBody><div className="text-xs text-ink-500 mb-1">إجمالي الذمم</div><div className="text-xl font-bold text-ink-900">{formatCurrency(totalOutstanding)}</div></CardBody></Card>{aging.map((b)=><Card key={b.bucket}><CardBody><div className="text-xs text-ink-500 mb-1">{b.bucket} يوم</div><div className="text-lg font-bold text-ink-900">{formatCurrency(b.amount)}</div><div className="text-xs text-ink-400 mt-1">{b.count} فاتورة</div></CardBody></Card>)}</div><Card><CardHeader title="الفواتير المستحقة" subtitle="الفواتير غير المدفوعة بالكامل"/><DataTable columns={[{key:'invoice_number',label:'رقم الفاتورة',render:(r:SalesInvoice)=><span className="font-medium text-primary-600">{r.invoice_number}</span>},{key:'customer',label:'العميل',render:(r:SalesInvoice)=>r.customer?.name||'—'},{key:'invoice_date',label:'تاريخ الفاتورة',render:(r:SalesInvoice)=>formatDate(r.invoice_date)},{key:'due_date',label:'تاريخ الاستحقاق',render:(r:SalesInvoice)=>formatDate(r.due_date)},{key:'total',label:'الإجمالي',align:'right',render:(r:SalesInvoice)=>formatCurrency(r.total)},{key:'paid_amount',label:'المدفوع',align:'right',render:(r:SalesInvoice)=>formatCurrency(r.paid_amount)},{key:'balance',label:'المتبقي',align:'right',render:(r:SalesInvoice)=><span className="font-semibold text-danger-600">{r.total==null||r.paid_amount==null?'—':formatCurrency(r.total-r.paid_amount)}</span>}]} data={invoices}/></Card></div>;
}

export function ProfitabilityReportPage() {
  const [truth,setTruth]=useState<Awaited<ReturnType<typeof fetchProfitabilityTruth>>|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{fetchProfitabilityTruth().then((value)=>{setTruth(value);setLoading(false);}).catch((e)=>{setError(errorMessage(e));setLoading(false);});},[]);
  if(loading)return <LoadingState/>; if(error)return <ErrorState message={error}/>; if(!truth)return <ErrorState message="تعذر تحميل حقيقة الربحية"/>;
  const exportProfitability=()=>downloadReportArtifact('profitability-report','تقرير الأرباح والربحية',['الفئة','المبيعات','التكلفة','الربح','الهامش','الكمية'],truth.categories.map((category)=>({'الفئة':category.name,'المبيعات':category.revenue,'التكلفة':category.costOfSales,'الربح':category.grossProfit,'الهامش':category.marginPct==null?null:\`${category.marginPct.toFixed(1)}%\`,'الكمية':category.quantity})));
  return <div className="space-y-6 animate-fade-in"><PageHeader title="تقرير الأرباح والربحية" subtitle={truth.status==='CALCULATED'?'الحقيقة المالية من التجميع الخادمي؛ لا تُحسب من الصفحة الحالية':'البيانات المالية غير كافية لإثبات الربحية'} actions={<button onClick={exportProfitability} className="btn-secondary text-xs">تصدير XLSX</button>}/><div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Card><CardBody><div className="text-xs text-ink-500 mb-1">إجمالي المبيعات</div><div className="text-xl font-bold text-ink-900">{formatCurrency(truth.revenue)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">إجمالي التكلفة</div><div className="text-xl font-bold text-ink-900">{formatCurrency(truth.costOfSales)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">إجمالي الربح</div><div className="text-xl font-bold text-success-600">{formatCurrency(truth.grossProfit)}</div></CardBody></Card><Card><CardBody><div className="text-xs text-ink-500 mb-1">هامش الربح</div><div className="text-xl font-bold text-success-600">{truth.marginPct==null?'—':\`${truth.marginPct.toFixed(1)}%\`}</div></CardBody></Card></div>{truth.incompleteRows>0&&<div role="alert" className="rounded-xl border border-danger-200 bg-danger-50 px-4 py-3 text-sm text-danger-800">هناك {formatNumber(truth.incompleteRows)} سطرًا ناقصًا ماليًا؛ لم تُحوّل البيانات المفقودة إلى صفر.</div>}{truth.currencyCount>1&&<div role="alert" className="rounded-xl border border-danger-200 bg-danger-50 px-4 py-3 text-sm text-danger-800">توجد عدة عملات ضمن النطاق؛ لا تُعرض ربحية مركبة غير مثبتة.</div>}<Card><CardHeader title="الربحية حسب الفئة"/><DataTable columns={[{key:'name',label:'الفئة'},{key:'revenue',label:'المبيعات',align:'right',render:(r:ProfitabilityCategory)=>formatCurrency(r.revenue)},{key:'costOfSales',label:'التكلفة',align:'right',render:(r:ProfitabilityCategory)=>formatCurrency(r.costOfSales)},{key:'grossProfit',label:'الربح',align:'right',render:(r:ProfitabilityCategory)=>formatCurrency(r.grossProfit)},{key:'marginPct',label:'الهامش',align:'right',render:(r:ProfitabilityCategory)=>r.marginPct==null?'—':\`${r.marginPct.toFixed(1)}%\`},{key:'quantity',label:'الكمية',align:'right',render:(r:ProfitabilityCategory)=>formatNumber(r.quantity)}]} data={truth.categories}/></Card></div>;
}
