import { useMemo, useState } from 'react';
import { CheckCircle2, Clock3, Plus, Printer, UserRound, CalendarDays, ArrowLeft, ListChecks } from 'lucide-react';

const seed=[['مراجعة العملاء المتأخرين','اليوم','عالية','المدير العام'],['متابعة الأصناف منخفضة المخزون','اليوم','عالية','مسؤول المخزون'],['مراجعة تقرير المبيعات','اليوم','متوسطة','المحاسب'],['تحضير خطة الغد','غداً','متوسطة','المدير العام'],['مراجعة جودة البيانات','غداً','منخفضة','مسؤول البيانات']];
export function TaskCenterPage(){const[tasks,setTasks]=useState(seed);const[newTask,setNewTask]=useState('');const[filter,setFilter]=useState('اليوم');const shown=useMemo(()=>tasks.filter(t=>t[1]===filter),[tasks,filter]);return <div dir="rtl" className="space-y-7 pb-10 print:bg-white">
<section className="experience-hero"><div className="relative z-10 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="experience-chip"><ListChecks size={14}/> OPERATIONS DESK</div><h1 className="mt-3 text-3xl font-black text-white sm:text-5xl">مركز المهام والعمل</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-emerald-50/80">حوّل قرارات المنصة إلى أعمال واضحة: مهام اليوم، مهام الغد، المسؤول، الأولوية، والمتابعة — في صفحة واحدة قابلة للطباعة.</p></div><button type="button" onClick={()=>window.print()} className="btn-secondary shrink-0 border-white/20 bg-white/10 text-white hover:bg-white/20"><Printer size={17}/> طباعة خطة العمل</button></div></section>
<section className="grid gap-4 sm:grid-cols-3"><div className="experience-kpi"><div className="experience-metric-label">مهام اليوم</div><div className="experience-metric-value">{tasks.filter(t=>t[1]==='اليوم').length}</div></div><div className="experience-kpi"><div className="experience-metric-label">مهام الغد</div><div className="experience-metric-value">{tasks.filter(t=>t[1]==='غداً').length}</div></div><div className="experience-kpi"><div className="experience-metric-label">الأولوية العالية</div><div className="experience-metric-value">{tasks.filter(t=>t[2]==='عالية').length}</div></div></section>
<section className="card p-5 print:border-0 print:shadow-none"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black text-ink-950">لوحة التنفيذ</h2><p className="mt-1 text-xs text-ink-400">رتّب يومك قبل أن تبدأ.</p></div><div className="flex rounded-2xl bg-ink-50 p-1"><button type="button" onClick={()=>setFilter('اليوم')} className={`rounded-xl px-4 py-2 text-xs font-bold ${filter==='اليوم'?'bg-white text-emerald-800 shadow-sm':'text-ink-400'}`}>اليوم</button><button type="button" onClick={()=>setFilter('غداً')} className={`rounded-xl px-4 py-2 text-xs font-bold ${filter==='غداً'?'bg-white text-emerald-800 shadow-sm':'text-ink-400'}`}>غداً</button></div></div><div className="mt-5 overflow-x-auto"><table className="experience-table min-w-[760px]"><thead><tr><th>المهمة</th><th>الموعد</th><th>الأولوية</th><th>المسؤول</th><th>الحالة</th></tr></thead><tbody>{shown.map((t,i)=><tr key={`${t[0]}-${i}`}><td className="font-bold text-ink-900">{t[0]}</td><td><span className="experience-chip"><CalendarDays size={13}/>{t[1]}</span></td><td><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${t[2]==='عالية'?'bg-rose-50 text-rose-700':t[2]==='متوسطة'?'bg-amber-50 text-amber-700':'bg-ink-50 text-ink-500'}`}>{t[2]}</span></td><td><span className="flex items-center gap-2 text-xs font-semibold"><UserRound size={14} className="text-ink-400"/>{t[3]}</span></td><td><button type="button" onClick={()=>setTasks(prev=>prev.filter((_,idx)=>idx!==tasks.indexOf(t)))} className="inline-flex items-center gap-1.5 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700 hover:bg-emerald-100"><CheckCircle2 size={14}/> تم التنفيذ</button></td></tr>)}</tbody></table></div></section>
<section className="card p-5 print:hidden"><div className="flex items-center gap-2 text-sm font-black text-ink-950"><Plus size={17} className="text-emerald-700"/> إضافة مهمة</div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={newTask} onChange={e=>setNewTask(e.target.value)} placeholder="اكتب المهمة التي تريد متابعتها..." className="input flex-1"/><button type="button" disabled={!newTask.trim()} onClick={()=>{setTasks(p=>[[newTask.trim(),filter,'متوسطة','المدير العام'],...p]);setNewTask('')}} className="btn-primary"><Plus size={16}/> إضافة</button></div></section>
<section className="grid gap-4 md:grid-cols-2 print:hidden"><div className="card p-5"><div className="flex items-center gap-2 font-black"><Clock3 size={18} className="text-amber-600"/> حلقة المتابعة</div><p className="mt-3 text-xs leading-6 text-ink-500">المهمة لا تصبح قراراً منجزاً إلا بعد تعيين مسؤول ومتابعة الحالة.</p></div><div className="card p-5"><div className="flex items-center gap-2 font-black"><ArrowLeft size={18} className="text-emerald-700"/> مصدر المهمة</div><p className="mt-3 text-xs leading-6 text-ink-500">يمكن تحويل توصيات ومسارات القرار إلى قائمة عمل منظمة بدل تركها داخل التقارير.</p></div></section>
</div>}
