import { useCallback,useEffect,useMemo,useState } from 'react';
import { CheckCircle2,Clock3,Play,Plus,Printer,UserRound,CalendarDays,ListChecks,RefreshCw,ShieldCheck,AlertTriangle,Check,LockKeyhole } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Task={id:string;title:string;horizon:'today'|'tomorrow';priority:string;assignee:string;status:string;description?:string|null;source?:string;dueAt?:string|null;kind:'proposal'|'work'};
const horizonLabel=(h:Task['horizon'])=>h==='today'?'اليوم':'غداً';
const priorityLabel=(p:string)=>({critical:'حرجة',high:'عالية',medium:'متوسطة',low:'منخفضة'} as Record<string,string>)[p]??p;
const statusLabel=(s:string)=>({proposed:'مقترحة',accepted:'مقبولة',OPEN:'مفتوحة',IN_PROGRESS:'قيد التنفيذ',COMPLETED:'مكتملة',BLOCKED:'متوقفة'} as Record<string,string>)[s]??s;

export function TaskCenterPage(){
 const[tasks,setTasks]=useState<Task[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[busyId,setBusyId]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);const[filter,setFilter]=useState<Task['horizon']>('today');const[statusFilter,setStatusFilter]=useState('ALL');const[newTask,setNewTask]=useState('');const[adding,setAdding]=useState(false);const[completeId,setCompleteId]=useState<string|null>(null);const[actualImpact,setActualImpact]=useState('');const[evidenceId,setEvidenceId]=useState('');
 const load=useCallback(async(silent=false)=>{silent?setRefreshing(true):setLoading(true);setError(null);try{const [{data:proposals,error:pError},{data:work,error:wError}]=await Promise.all([supabase.from('operational_task_proposals').select('id,title,horizon,priority,status,role,reason,source_type,created_at').in('status',['proposed','accepted']).order('created_at',{ascending:false}),supabase.from('decision_work_items').select('id,title,description,priority,status,assignee_label,due_at,created_at').in('status',['OPEN','IN_PROGRESS','BLOCKED']).order('created_at',{ascending:false})]);if(pError)throw pError;if(wError)throw wError;const rows:Task[]=[...(proposals??[]).map((x:any)=>({id:x.id,title:x.title,horizon:x.horizon,priority:x.priority,assignee:x.role==='manager'?'المدير العام':x.role,status:x.status,description:x.reason,source:x.source_type,kind:'proposal'})),...(work??[]).map((x:any)=>({id:x.id,title:x.title,horizon:x.due_at&&new Date(x.due_at).toDateString()===new Date().toDateString()?'today':'tomorrow',priority:String(x.priority).toLowerCase(),assignee:x.assignee_label??'غير معيّن',status:x.status,description:x.description,dueAt:x.due_at,kind:'work'}))];setTasks(rows);}catch(e){console.error('[TaskCenterPage]',e);setError(e instanceof Error?e.message:'تعذر تحميل مركز المهام');}finally{setLoading(false);setRefreshing(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const shown=useMemo(()=>tasks.filter(t=>t.horizon===filter&&(statusFilter==='ALL'||t.status===statusFilter)),[tasks,filter,statusFilter]);
 const overdue=(t:Task)=>Boolean(t.dueAt&&new Date(t.dueAt).getTime()<Date.now()&&t.status!=='COMPLETED');
 const startWork=async(id:string)=>{setBusyId(id);setError(null);try{const {error:e}=await supabase.rpc('start_decision_work_item',{p_work_item_id:id});if(e)throw e;await load(true);}catch(e){console.error('[TaskCenterPage] start',e);setError(e instanceof Error?e.message:'تعذر بدء عنصر العمل');}finally{setBusyId(null);}};
 const acceptProposal=async(id:string)=>{setBusyId(id);setError(null);try{const {error:e}=await supabase.from('operational_task_proposals').update({status:'accepted'}).eq('id',id).eq('status','proposed');if(e)throw e;await load(true);}catch(e){console.error('[TaskCenterPage] accept',e);setError(e instanceof Error?e.message:'تعذر اعتماد المهمة');}finally{setBusyId(null);}};
 const completeWork=async()=>{if(!completeId||!actualImpact.trim()||!evidenceId.trim()){setError('إكمال المهمة يتطلب الأثر الفعلي ومعرّف دليل حقيقي؛ لا يتم إنشاء دليل مصطنع.');return;}setBusyId(completeId);setError(null);try{const impact=Number(actualImpact);if(!Number.isFinite(impact))throw new Error('الأثر الفعلي يجب أن يكون رقماً');const {error:e}=await supabase.rpc('complete_decision_work_item',{p_work_item_id:completeId,p_actual_impact:impact,p_evidence:{evidence_snapshot_id:evidenceId.trim()}});if(e)throw e;setCompleteId(null);setActualImpact('');setEvidenceId('');await load(true);}catch(e){console.error('[TaskCenterPage] complete',e);setError(e instanceof Error?e.message:'تعذر إكمال عنصر العمل');}finally{setBusyId(null);}};
 const addProposal=async()=>{if(!newTask.trim())return;setAdding(true);setError(null);try{const {data:company}=await supabase.rpc('current_company_id');if(!company)throw new Error('TENANT_CONTEXT_REQUIRED');const {error:e}=await supabase.from('operational_task_proposals').insert({company_id:company,role:'manager',horizon:filter,priority:'medium',title:newTask.trim(),reason:'مهمة تشغيلية أنشأها المدير من مركز العمل',source_type:'kpi',expected_outcome:'إتمام المهمة ومتابعة أثرها',status:'proposed',task_key:`manual-${Date.now()}`});if(e)throw e;setNewTask('');await load(true);}catch(e){console.error('[TaskCenterPage] add',e);setError(e instanceof Error?e.message:'تعذر إضافة المهمة');}finally{setAdding(false);}};
 if(loading)return <div dir="rtl" className="card min-h-64 flex items-center justify-center"><RefreshCw className="animate-spin text-emerald-700"/></div>;
 return <div dir="rtl" className="space-y-7 pb-10 print:bg-white">
 <section className="experience-hero"><div className="relative z-10 flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="experience-chip"><ListChecks size={14}/> OPERATIONS DESK</div><h1 className="mt-3 text-3xl font-black text-white sm:text-5xl">مركز المهام والعمل</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-emerald-50/80">من القرار إلى التنفيذ والنتيجة: مهمة حقيقية، مسؤول واضح، دليل، وأثر قابل للقياس.</p></div><button type="button" onClick={()=>window.print()} className="btn-secondary shrink-0 border-white/20 bg-white/10 text-white hover:bg-white/20"><Printer size={17}/> طباعة خطة العمل</button></div></section>
 <section className="grid gap-4 sm:grid-cols-4"><div className="experience-kpi"><div className="experience-metric-label">مهام اليوم</div><div className="experience-metric-value">{tasks.filter(t=>t.horizon==='today').length}</div></div><div className="experience-kpi"><div className="experience-metric-label">مهام الغد</div><div className="experience-metric-value">{tasks.filter(t=>t.horizon==='tomorrow').length}</div></div><div className="experience-kpi"><div className="experience-metric-label">قيد التنفيذ</div><div className="experience-metric-value">{tasks.filter(t=>t.status==='IN_PROGRESS').length}</div></div><div className="experience-kpi"><div className="experience-metric-label">متأخرة</div><div className="experience-metric-value">{tasks.filter(overdue).length}</div></div></section>
 {error&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900"><b>تنبيه تشغيلي:</b> {error}</div>}
 <section className="card p-5 print:border-0 print:shadow-none"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black text-ink-950">لوحة التنفيذ</h2><p className="mt-1 text-xs text-ink-400">لا يمكن إغلاق المهمة دون أثر فعلي ودليل مرتبط؛ البيانات الناقصة تبقى ظاهرة.</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-2xl bg-ink-50 p-1"><button type="button" onClick={()=>setFilter('today')} className={`rounded-xl px-4 py-2 text-xs font-bold ${filter==='today'?'bg-white text-emerald-800 shadow-sm':'text-ink-400'}`}>اليوم</button><button type="button" onClick={()=>setFilter('tomorrow')} className={`rounded-xl px-4 py-2 text-xs font-bold ${filter==='tomorrow'?'bg-white text-emerald-800 shadow-sm':'text-ink-400'}`}>غداً</button></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="input w-auto text-xs"><option value="ALL">كل الحالات</option><option value="proposed">مقترحة</option><option value="accepted">مقبولة</option><option value="OPEN">مفتوحة</option><option value="IN_PROGRESS">قيد التنفيذ</option><option value="BLOCKED">متوقفة</option></select><button type="button" onClick={()=>void load(true)} disabled={refreshing} className="btn-secondary print:hidden"><RefreshCw size={15} className={refreshing?'animate-spin':''}/> تحديث</button></div></div>
 <div className="mt-5 overflow-x-auto"><table className="experience-table min-w-[1020px]"><thead><tr><th>المهمة</th><th>الموعد</th><th>الأولوية</th><th>المسؤول</th><th>المصدر</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{shown.map(t=><tr key={`${t.kind}-${t.id}`}><td><div className="font-bold text-ink-900">{t.title}</div>{t.description&&<div className="mt-1 max-w-sm text-[10px] text-ink-400">{t.description}</div>}</td><td><span className={`experience-chip ${overdue(t)?'border-red-200 bg-red-50 text-red-700':''}`}><CalendarDays size={13}/>{overdue(t)?'متأخرة':horizonLabel(t.horizon)}</span></td><td><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${t.priority==='critical'?'bg-red-50 text-red-700':t.priority==='high'?'bg-rose-50 text-rose-700':t.priority==='medium'?'bg-amber-50 text-amber-700':'bg-ink-50 text-ink-500'}`}>{priorityLabel(t.priority)}</span></td><td><span className="flex items-center gap-2 text-xs font-semibold"><UserRound size={14} className="text-ink-400"/>{t.assignee}</span></td><td className="text-xs text-ink-500">{t.source??'تشغيلي'}</td><td><span className={`inline-flex items-center gap-1.5 rounded-xl px-3 py-2 text-xs font-bold ${t.status==='BLOCKED'?'bg-red-50 text-red-700':t.status==='COMPLETED'?'bg-teal-50 text-teal-700':'bg-emerald-50 text-emerald-700'}`}>{t.status==='BLOCKED'?<AlertTriangle size={14}/>:t.status==='COMPLETED'?<CheckCircle2 size={14}/>:<CheckCircle2 size={14}/>} {statusLabel(t.status)}</span></td><td><div className="flex items-center gap-2">{t.kind==='proposal'&&t.status==='proposed'?<button type="button" onClick={()=>void acceptProposal(t.id)} disabled={busyId===t.id} className="btn-secondary px-3 py-2 text-xs"><Check size={14}/> اعتماد</button>:null}{t.kind==='work'&&t.status==='OPEN'?<button type="button" onClick={()=>void startWork(t.id)} disabled={busyId===t.id} className="btn-primary px-3 py-2 text-xs">{busyId===t.id?<RefreshCw size={14} className="animate-spin"/>:<Play size={14}/>} {busyId===t.id?'جارٍ البدء':'ابدأ التنفيذ'}</button>:null}{t.kind==='work'&&t.status==='IN_PROGRESS'?<button type="button" onClick={()=>setCompleteId(t.id)} disabled={busyId===t.id} className="btn-primary px-3 py-2 text-xs"><CheckCircle2 size={14}/> إكمال مع الدليل</button>:null}{t.kind==='work'&&t.status==='BLOCKED'?<span className="inline-flex items-center gap-1 text-[10px] font-bold text-red-700"><LockKeyhole size={13}/> يحتاج معالجة</span>:null}</div></td></tr>)}</tbody></table>{shown.length===0&&<div className="py-14 text-center text-sm text-ink-400"><ListChecks className="mx-auto mb-3 text-ink-200" size={30}/>لا توجد مهام حقيقية بهذه الفلاتر.</div>}</div></section>
 <section className="card p-5 print:hidden"><div className="flex items-center gap-2 text-sm font-black"><Plus size={17} className="text-emerald-700"/> إضافة مهمة تشغيلية</div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={newTask} onChange={e=>setNewTask(e.target.value)} placeholder="اكتب مهمة اليوم أو الغد..." className="input flex-1"/><button type="button" disabled={!newTask.trim()||adding} onClick={()=>void addProposal()} className="btn-primary"><Plus size={16}/> {adding?'جارٍ الحفظ...':'حفظ المهمة'}</button></div></section>
 {completeId&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-ink-950/45 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-[2rem] bg-white p-6 shadow-2xl" dir="rtl"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><CheckCircle2 size={22}/></span><div><h3 className="text-lg font-black text-ink-950">إغلاق المهمة بالأثر والدليل</h3><p className="text-xs text-ink-500">لن يُنشأ دليل تلقائي أو رقم مصطنع.</p></div></div><div className="mt-5 space-y-3"><label className="block text-xs font-bold text-ink-700">الأثر الفعلي<input value={actualImpact} onChange={e=>setActualImpact(e.target.value)} inputMode="decimal" placeholder="مثال: 1250" className="input mt-2 w-full"/></label><label className="block text-xs font-bold text-ink-700">معرّف لقطة الدليل الحقيقي<input value={evidenceId} onChange={e=>setEvidenceId(e.target.value)} placeholder="evidence_snapshot_id" className="input mt-2 w-full font-mono text-xs"/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={()=>{setCompleteId(null);setActualImpact('');setEvidenceId('');}} className="btn-secondary">إلغاء</button><button type="button" onClick={()=>void completeWork()} disabled={busyId===completeId||!actualImpact.trim()||!evidenceId.trim()} className="btn-primary">{busyId===completeId?<RefreshCw size={15} className="animate-spin"/>:<CheckCircle2 size={15}/>} اعتماد النتيجة</button></div></div></div>}
 <section className="grid gap-4 md:grid-cols-2 print:hidden"><div className="card p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck size={18} className="text-emerald-700"/> عزل الشركة</div><p className="mt-3 text-xs leading-6 text-ink-500">الحفظ والاستعلام يمران بسياق الشركة الحالية، ولا يتم تجاوز RLS من الواجهة.</p></div><div className="card p-5"><div className="flex items-center gap-2 font-black"><Clock3 size={18} className="text-amber-600"/> حلقة المتابعة</div><p className="mt-3 text-xs leading-6 text-ink-500">القرار → العمل → الأثر: الإغلاق يحتاج نتيجة فعلية ودليلًا يمكن تتبعه.</p></div></section>
 </div>;
}