import type { ReactNode } from 'react';
import { AlertTriangle, CheckCircle2, CircleHelp, FileSearch, ShieldAlert, XCircle } from 'lucide-react';
import type { ControlPlaneReadModel, DataQualityReadModel, DocumentWorkspaceReadModel, ReconciliationReadModel, SchemaDiscoveryReadModel, SecondaryStatus } from '@/lib/secondary-batch02';

const tone: Record<string, string> = { HEALTHY: 'text-success-700 bg-success-50 border-success-200', WARNING: 'text-warning-700 bg-warning-50 border-warning-200', FAILED: 'text-danger-700 bg-danger-50 border-danger-200', UNKNOWN: 'text-ink-600 bg-ink-50 border-ink-200', NOT_CONFIGURED: 'text-ink-600 bg-white border-dashed border-ink-300', BLOCKED: 'text-danger-700 bg-danger-50 border-danger-200' };
function StateBadge({ status }: { status: string }) { const Icon = status === 'HEALTHY' ? CheckCircle2 : status === 'FAILED' || status === 'BLOCKED' ? XCircle : status === 'WARNING' ? AlertTriangle : CircleHelp; return <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[11px] font-semibold ${tone[status] ?? tone.UNKNOWN}`}><Icon size={13} />{status.replace('_', ' ')}</span>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section dir="rtl" className="card p-5" aria-label={title}><h2 className="text-base font-bold text-ink-900">{title}</h2>{children}</section>; }
function Missing({ status, reason }: { status: SecondaryStatus; reason?: string }) { if (status === 'READY' || status === 'HEALTHY') return null; return <div className="mt-3 rounded-lg border border-ink-100 bg-ink-50 p-3 text-sm text-ink-600"><strong>{status.replace('_', ' ')}</strong>{reason ? <span className="mr-2">— {reason}</span> : null}</div>; }

export function DataQualityCenter({ model }: { model: DataQualityReadModel }) {
  return <Panel title="مركز جودة البيانات"><Missing status={model.status} reason={model.source ? undefined : 'لا يوجد مصدر قراءة موثوق متاح.'} />
    <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{model.metrics.map(metric => <article key={metric.dimension} className="rounded-xl border border-ink-100 p-4"><div className="flex items-center justify-between gap-2"><span className="text-xs text-ink-500">{metric.dimension}</span><StateBadge status={metric.status} /></div><div className="mt-2 text-xl font-bold text-ink-900">{metric.value === undefined ? 'UNKNOWN' : `${Math.round(metric.value)}%`}</div>{metric.source && <p className="mt-2 text-[11px] text-ink-400">Evidence: {metric.source.label}</p>}{metric.reason && <p className="mt-2 text-xs text-ink-500">{metric.reason}</p>}</article>)}</div>
    <div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-right text-xs text-ink-400"><th className="p-3">Issue</th><th className="p-3">Owner</th><th className="p-3">Severity</th><th className="p-3">Remediation</th><th className="p-3">History</th></tr></thead><tbody>{model.issues.map(issue => <tr key={issue.id} className="border-b border-ink-50"><td className="p-3">{issue.id}</td><td className="p-3">{issue.owner ?? 'UNKNOWN'}</td><td className="p-3">{issue.severity ?? 'UNKNOWN'}</td><td className="p-3">{issue.remediation ?? 'UNKNOWN'}</td><td className="p-3">{issue.history?.length ?? 0}</td></tr>)}</tbody></table></div>
  </Panel>;
}

export function BusinessControlPlane({ model }: { model: ControlPlaneReadModel }) {
  return <Panel title="Business Control Plane"><Missing status={model.status} /><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{model.signals.map(signal => <article key={signal.area} className="rounded-xl border border-ink-100 p-4"><div className="flex items-start justify-between gap-3"><span className="font-semibold text-ink-800">{signal.area}</span><StateBadge status={signal.status} /></div><p className="mt-2 text-sm text-ink-500">{signal.detail ?? 'UNKNOWN — لا توجد إشارة تشغيلية كافية.'}</p>{signal.source && <p className="mt-2 text-[11px] text-ink-400">Evidence: {signal.source.label}</p>}</article>)}</div></Panel>;
}

export function DocumentIntelligenceWorkspace({ model }: { model: DocumentWorkspaceReadModel }) {
  return <Panel title="Document Intelligence Workspace"><Missing status={model.status} /><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-xl border border-ink-100 p-4"><div className="flex items-center gap-2"><FileSearch size={18} /><strong>{model.fileName ?? 'UNKNOWN FILE'}</strong></div><p className="mt-2 text-xs text-ink-400">{model.sourceRef ?? 'Source reference unavailable.'}</p><h3 className="mt-5 text-sm font-bold">Pages</h3><ul className="mt-2 space-y-2">{model.pages?.map(page => <li key={page.id} className="flex items-center justify-between rounded-lg bg-ink-50 p-2 text-sm"><span>{page.label}</span><StateBadge status={page.status ?? 'UNKNOWN'} /></li>) ?? <li className="text-sm text-ink-500">UNKNOWN</li>}</ul><h3 className="mt-5 text-sm font-bold">Detected Tables</h3><ul className="mt-2 space-y-2">{model.tables?.map(table => <li key={table.id} className="rounded-lg border border-ink-100 p-2 text-sm"><div className="flex justify-between"><span>{table.label}</span><span>{table.rows ?? 'UNKNOWN'} rows</span></div><p className="text-xs text-ink-400">{table.sourceRef ?? 'Evidence unavailable'}</p></li>) ?? <li className="text-sm text-ink-500">UNKNOWN</li>}</ul></div><div className="rounded-xl border border-ink-100 p-4"><h3 className="font-bold">Fields / Confidence / Mapping / Validation</h3><div className="mt-3 space-y-2">{model.fields?.map(field => <div key={field.name} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-lg bg-ink-50 p-3 text-sm"><span>{field.name}</span><span>{field.value ?? 'UNKNOWN'}</span><span>{field.confidence === undefined ? 'UNKNOWN' : `${Math.round(field.confidence * 100)}%`}</span></div>) ?? <p className="text-sm text-ink-500">INSUFFICIENT EVIDENCE</p>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div><h4 className="text-xs font-semibold text-ink-500">Rejected Rows</h4><p className="mt-1 text-sm">{model.rejectedRows?.length ?? 'UNKNOWN'}</p></div><div><h4 className="text-xs font-semibold text-ink-500">Quarantine</h4><p className="mt-1 text-sm">{model.quarantine?.length ?? 'UNKNOWN'}</p></div></div><h3 className="mt-5 font-bold">Lineage</h3><ol className="mt-2 space-y-1 text-sm">{model.lineage?.map((item, i) => <li key={item.id} className="flex gap-2"><span>{i + 1}.</span><span>{item.label}</span></li>) ?? <li className="text-ink-500">UNKNOWN</li>}</ol></div></div></Panel>;
}

export function SmartReconciliation({ model }: { model: ReconciliationReadModel }) {
  return <Panel title="Smart Reconciliation"><div className="mt-3 flex items-center justify-between"><StateBadge status={model.status} />{model.source && <span className="text-xs text-ink-400">Evidence: {model.source.label}</span>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Source rows', model.sourceRows], ['Canonical rows', model.canonicalRows], ['Duplicates', model.duplicates], ['Unmatched rows', model.unmatchedRows], ['Missing entities', model.missingEntities], ['Suspicious differences', model.suspiciousDifferences]].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-ink-100 p-4"><div className="text-xs text-ink-400">{label}</div><div className="mt-1 text-lg font-bold">{value ?? 'UNKNOWN'}</div></div>)}</div><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-right text-xs text-ink-400"><th className="p-3">Total</th><th className="p-3">Source</th><th className="p-3">Canonical</th><th className="p-3">Delta</th></tr></thead><tbody>{model.totals?.map(row => <tr key={row.label} className="border-b border-ink-50"><td className="p-3">{row.label}</td><td className="p-3">{row.source ?? 'UNKNOWN'}</td><td className="p-3">{row.canonical ?? 'UNKNOWN'}</td><td className="p-3">{row.delta ?? 'UNKNOWN'}</td></tr>)}</tbody></table></div><div className="mt-4 rounded-lg border border-warning-200 bg-warning-50 p-3 text-sm">{model.failureReason ?? 'Failure reason: UNKNOWN'}<br />{model.remediation ?? 'Remediation: UNKNOWN'}</div></Panel>;
}

export function SchemaDiscoveryPresentation({ model }: { model: SchemaDiscoveryReadModel }) {
  return <Panel title="Headerless Schema Discovery"><div className="mt-3 flex justify-between"><StateBadge status={model.status} /><span className="text-sm">Header: {model.header ?? 'UNKNOWN'}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><h3 className="text-xs text-ink-400">Column Types</h3><ul className="mt-2 space-y-1">{model.columnTypes?.map(c => <li key={c.name} className="rounded bg-ink-50 p-2 text-sm">{c.name}: {c.type ?? 'UNKNOWN'} ({c.confidence === undefined ? 'UNKNOWN' : `${Math.round(c.confidence * 100)}%`})</li>) ?? <li>UNKNOWN</li>}</ul></div><div><h3 className="text-xs text-ink-400">Suggested Mapping</h3><ul className="mt-2 space-y-1">{model.suggestedMapping?.map(m => <li key={`${m.source}-${m.target}`} className="rounded bg-ink-50 p-2 text-sm">{m.source} → {m.target} ({m.confidence === undefined ? 'UNKNOWN' : `${Math.round(m.confidence * 100)}%`})</li>) ?? <li>UNKNOWN</li>}</ul></div></div><div className="mt-4 text-sm text-ink-500">Rows: {model.rows ?? 'UNKNOWN'} · Sections: {model.sections?.length ?? 'UNKNOWN'} · Merged cells: {model.mergedCells ?? 'UNKNOWN'} · Tables: {model.tables ?? 'UNKNOWN'}</div></Panel>;
}
