import { useEffect,useState } from 'react';
import { fetchExecutiveDecisionReport,type ExecutiveDecisionReport } from '@/lib/executive-decision-report';

export function ExecutiveDecisionReportPanel(){
  const [report,setReport]=useState<ExecutiveDecisionReport|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{void fetchExecutiveDecisionReport(50).then(setReport).catch((e)=>setError(e instanceof Error?e.message:'تعذر تحميل سجل القرار التنفيذي.'));},[]);
  if(error) return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-lg font-bold">سجل القرار التنفيذي</h2><p className="mt-2 text-sm text-amber-900">{error} — لا يتم اختلاق بيانات عند غياب جلسة موثقة.</p></section>;
  if(!report) return <section className="rounded-2xl border border-ink-200 bg-white p-5" aria-busy="true"><h2 className="text-lg font-bold">سجل القرار التنفيذي</h2><p className="mt-2 text-sm text-ink-500">جارٍ تحميل دورة القرار المحفوظة…</p></section>;
  return <section className="rounded-2xl border border-ink-200 bg-white p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-bold">سجل القرار والتنفيذ والنتيجة</h2><p className="mt-1 text-xs text-ink-500">المصدر: سجل القرار المحفوظ · Generated {new Date(report.generated_at).toLocaleString('ar')}</p></div><span className="rounded-full bg-ink-100 px-3 py-1 text-xs font-semibold">{report.count} قرار</span></div><div className="mt-4 space-y-3">{report.rows.length===0&&<p className="rounded-xl bg-ink-50 p-4 text-sm text-ink-500">لا توجد قرارات محفوظة لهذا المستأجر حتى الآن.</p>}{report.rows.map((row)=><article key={row.decision.id} className="rounded-xl border border-ink-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">{row.recommendation?.title ?? row.decision.decision_key ?? 'قرار بدون عنوان'}</p><p className="mt-1 text-xs text-ink-500">{row.decision.decision_type ?? 'نوع غير محدد'} · {row.decision.status ?? 'حالة غير محددة'}</p></div><span className="rounded-lg bg-ink-50 px-2 py-1 text-xs">{row.approval.status}</span></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-ink-500">الموافقة</span><p className="font-semibold">{row.approval.approved_at ? new Date(row.approval.approved_at).toLocaleString('ar') : 'غير مسجلة'}</p></div><div><span className="text-ink-500">التنفيذ</span><p className="font-semibold">{row.work_items.length} مهمة · {row.work_items.filter(w=>w.status==='COMPLETED').length} مكتملة</p></div><div><span className="text-ink-500">النتيجة</span><p className="font-semibold">{row.decision_outcome?.label ?? row.recommendation_outcome?.status ?? 'غير مسجلة'}</p></div><div><span className="text-ink-500">التعلم</span><p className="font-semibold">{row.learning.sample_size} ملاحظة · {row.learning.correct} صحيحة</p></div></div>{row.decision_outcome&&<div className="mt-3 rounded-lg bg-ink-50 p-3 text-xs">Actual: {row.decision_outcome.actual_value ?? 'غير متاح'} · Expected: {row.decision_outcome.expected_value ?? 'غير متاح'} · Impact: {row.decision_outcome.impact_value ?? 'غير متاح'} · Evidence: {row.decision_outcome.evidence_snapshot_id ?? 'غير متاح'}</div>}</article>)}</div></section>;
}
