import type { ReactNode } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { LayoutDashboard, Upload, FileBarChart, BarChart3, Brain, Users, Package, Warehouse, Settings, AlertCircle, Crosshair, LogOut, Scale, Sparkles, ChevronLeft, Bot, ListChecks } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';
import { getDisplayEmail, getDisplayName } from '@/lib/profile-display';
interface NavItem { path:string; label:string; icon:ReactNode; exact?:boolean }
interface NavSection { title:string; items:NavItem[] }
const navSections:NavSection[]=[
 {title:'القيادة',items:[{path:'/',label:'لوحة القيادة',icon:<LayoutDashboard size={18}/>,exact:true},{path:'/command-center',label:'مركز القيادة التنفيذية',icon:<Crosshair size={18}/>} ]},
 {title:'البيانات',items:[{path:'/import',label:'مركز البيانات',icon:<Upload size={18}/>,exact:true},{path:'/data-quality',label:'جودة البيانات',icon:<AlertCircle size={18}/>} ]},
 {title:'الفهم',items:[{path:'/reports',label:'مركز التقارير',icon:<FileBarChart size={18}/>,exact:true},{path:'/analytics',label:'مركز التحليلات',icon:<BarChart3 size={18}/>} ]},
 {title:'الذكاء والقرار',items:[{path:'/assistant',label:'المساعد والخبير الذكي',icon:<Bot size={18}/>},{path:'/intelligence',label:'مركز الذكاء',icon:<Brain size={18}/>,exact:true},{path:'/decision-experience',label:'مساحة القرار',icon:<Scale size={18}/>} ]},
 {title:'التشغيل',items:[{path:'/tasks',label:'مركز المهام والعمل',icon:<ListChecks size={18}/>},{path:'/customers',label:'العملاء',icon:<Users size={18}/>},{path:'/products',label:'المنتجات',icon:<Package size={18}/>},{path:'/inventory',label:'المخزون',icon:<Warehouse size={18}/>} ]},
 {title:'النظام',items:[{path:'/settings',label:'الإعدادات',icon:<Settings size={18/>} ]},
];
export function Sidebar({alertCount=0,onNavigate,user}:{alertCount?:number;onNavigate?:()=>void;user?:User|null}){
 const location=useLocation(); const handleSignOut=async()=>{await supabase.auth.signOut();onNavigate?.()};
 return <aside className="flex h-screen w-[292px] shrink-0 flex-col overflow-y-auto border-l border-emerald-950/10 bg-[#fbfcf8]/95 shadow-[0_0_60px_rgba(6,78,59,.07)] backdrop-blur-xl" dir="rtl">
 <div className="sticky top-0 z-20 border-b border-ink-100/70 bg-[#fbfcf8]/90 px-4 py-5 backdrop-blur-xl"><Link to="/" onClick={onNavigate} className="group block rounded-[1.35rem] p-2 transition-all hover:bg-white hover:shadow-md focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-emerald-500/15" aria-label="العودة إلى لوحة القيادة"><div className="flex items-center gap-3"><div className="relative flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-2xl bg-gradient-to-br from-emerald-950 via-emerald-800 to-amber-700 text-xl font-black text-white shadow-lg shadow-emerald-900/20"><span className="relative z-10">ع</span><span className="absolute -left-2 -top-2 h-8 w-8 rounded-full bg-emerald-300/20 blur-md"/></div><div className="min-w-0"><div className="flex items-center gap-1.5"><span className="text-base font-black tracking-tight text-ink-950">الأغبري</span><Sparkles size={13} className="text-amber-600"/></div><div className="mt-0.5 truncate text-[10px] font-medium text-ink-400">من البيانات إلى القرار</div></div></div></Link></div>
 <nav className="flex-1 space-y-6 px-3 py-5" aria-label="التنقل الرئيسي"><div className="mb-1 rounded-2xl border border-emerald-100 bg-emerald-50/55 px-3.5 py-3"><div className="text-[9px] font-black tracking-[.16em] text-emerald-700">WORKSPACE</div><div className="mt-1 text-xs font-bold text-ink-700">مسار العمل الموحد</div></div>{navSections.map(section=><div key={section.title}><div className="mb-2.5 flex items-center gap-2 px-3 text-[9px] font-black uppercase tracking-[.16em] text-ink-400"><span>{section.title}</span><span className="h-px flex-1 bg-gradient-to-l from-ink-100 to-transparent"/></div><div className="space-y-1">{section.items.map(item=>{const active=item.exact?location.pathname===item.path:(item.path!=='/'&&location.pathname.startsWith(item.path));return <Link key={item.path} to={item.path} onClick={onNavigate} aria-current={active?'page':undefined} className={`group flex min-h-12 items-center gap-3 rounded-2xl px-3.5 py-2.5 text-[13px] font-semibold transition-all duration-200 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-emerald-500/15 ${active?'nav-item-active shadow-sm':'text-ink-600 hover:bg-white hover:text-emerald-800 hover:shadow-sm'}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl transition-all ${active?'bg-emerald-700 text-white shadow-md shadow-emerald-800/15':'bg-ink-50 text-ink-400 group-hover:bg-emerald-50 group-hover:text-emerald-700'}`}>{item.icon}</span><span className="min-w-0 flex-1 truncate">{item.label}</span>{item.path==='/intelligence'&&alertCount>0&&<span aria-label={`${alertCount} تنبيه غير مقروء`} className="rounded-full bg-rose-50 px-1.5 py-0.5 text-[10px] font-black text-rose-600">{alertCount}</span>}{active&&<ChevronLeft size={14} aria-hidden="true" className="text-emerald-700/60"/>}</Link>})}</div></div>)}</nav>
 <div className="border-t border-ink-100/70 bg-gradient-to-t from-emerald-50/60 to-transparent px-4 py-4"><div className="rounded-2xl border border-emerald-100/80 bg-white p-3.5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-800 to-teal-700 text-sm font-black text-white" aria-hidden="true">م</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold text-ink-900">{getDisplayName(user??null)}</div><div className="truncate text-[10px] text-ink-400" dir="ltr">{getDisplayEmail(user??null)}</div></div></div></div><button type="button" onClick={()=>void handleSignOut()} className="mt-2.5 flex w-full items-center justify-center gap-2 rounded-xl border border-ink-200 bg-white px-3 py-2.5 text-xs font-bold text-ink-600 transition hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-rose-500/10" aria-label="تسجيل الخروج"><LogOut size={15}/> تسجيل الخروج</button></div>
 </aside>;
}