import { discoverHeaderRow, inferTable, resolveMappings, resolveEntities } from '../src/lib/file-engine/schema-intelligence-advanced.ts';
import { reconcileByBusinessKey, stableImportFingerprint } from '../src/lib/file-engine/reconciliation.ts';
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(`Schema/entity regression: ${message}`); }
const matrix = [['تقرير المخزون', '', ''], ['', '', ''], ['رقم الصنف', 'اسم الصنف', 'الكمية', 'السعر'], ['٠٠١', 'سكر', '10', '1250'], ['002', 'أرز', '7', '2400']];
const header = discoverHeaderRow(matrix); assert(header.row === 2, 'header discovery must skip title/preamble rows'); assert(header.confidence >= 60, 'header confidence should be meaningful');
const table = inferTable(matrix); const sku = table.columns.find(column => column.field === 'sku'); const quantity = table.columns.find(column => column.field === 'quantity');
assert(sku?.sourceColumn === 'رقم الصنف', 'Arabic SKU header must map to sku'); assert(quantity?.sourceColumn === 'الكمية', 'Arabic quantity header must map to quantity');
const mappings = resolveMappings(table.columns); assert(mappings.length >= 3, 'schema mapping should produce actionable fields');
const target = [{ sku: '001', name: 'سكر', quantity: 10 }, { sku: '002', name: 'أرز', quantity: 7 }, { sku: '004', name: 'دقيق', quantity: 5 }]; const source = [{ sku: '٠٠١', name: 'سكر', quantity: 10 }, { sku: '002', name: 'أرز', quantity: 8 }, { sku: '003', name: 'زيت', quantity: 2 }];
const entities = resolveEntities(source, target, row => row.sku); assert(entities[0].matched && entities[0].confidence === 100, 'Arabic/Latin business key normalization must match'); assert(!entities[2].matched && entities[2].reason === 'not-found', 'unknown business key must not fabricate a match');
const result = reconcileByBusinessKey(source, target, row => row.sku, (left, right) => left.quantity === right.quantity ? [] : ['quantity']); assert(result.summary.total === 3, 'reconciliation total mismatch'); assert(result.summary.unchanged === 1, 'unchanged row classification mismatch'); assert(result.summary.updated === 1, 'updated row classification mismatch'); assert(result.summary.new === 1, 'new row classification mismatch'); assert(result.summary.deleted === 1, 'target-only row must be classified as deleted'); assert(result.deletedKeys.length === 1 && result.deletedKeys[0] === '004', 'deleted business key must be preserved for explicit tombstone policy');
const first = stableImportFingerprint(source, row => row.sku, row => JSON.stringify(row)); const second = stableImportFingerprint([...source].reverse(), row => row.sku, row => JSON.stringify(row)); assert(first === second, 'import fingerprint must be order independent');
console.log('Schema/entity/reconciliation golden fixtures: PASS');
