import assert from 'node:assert/strict';
import fs from 'node:fs';

const script = fs.readFileSync('scripts/provision-e2e-actors.mjs', 'utf8');
const migration = fs.readFileSync('supabase/migrations/20261002050000_reconcile_e2e_actor_service_role_key_guard.sql', 'utf8');
const workflow = fs.readFileSync('.github/workflows/full-product-browser-e2e.yml', 'utf8');
const passportRefresh = fs.readFileSync('scripts/refresh-governed-real-corpus-passports.mjs', 'utf8');
const openReportProof = fs.readFileSync('scripts/resume-open-report-server-proof.mjs', 'utf8');

assert.match(script, /auth\.admin\.createUser/);
assert.match(script, /createActor\(/);
assert.match(script, /provision_e2e_test_membership/);
assert.match(script, /async function readMembershipAudit/);
assert.match(script, /AUDIT_QUERY_FAILED/);
assert.match(script, /if \(error\)/);
assert.doesNotMatch(script, /const \[\{ data: auditA \}/);
assert.doesNotMatch(script, /\.from\(['"]company_memberships['"]\)[\s\S]{0,300}\.insert\(/);
assert.doesNotMatch(script, /\.from\(['"]company_memberships['"]\)[\s\S]{0,300}\.update\(/);
assert.match(script, /tagged =/);
assert.match(script, /actorCredentials\(/);
assert.match(script, /persistActorCredentials\(/);
assert.doesNotMatch(script, /E2E_EXISTING_USER_NOT_TAGGED/);
assert.match(script, /ensureApproverCredentials/);
assert.match(script, /E2E_ACTOR_MODE === 'ephemeral-run-scoped'/);
assert.match(script, /AUTH_RETRY_ATTEMPTS\s*=\s*4/);
assert.match(script, /isAuthRequest\(input\)/);
assert.match(script, /authRetryable/);
assert.match(script, /freshRunScoped/);
assert.match(script, /TEST_USER_A_EPHEMERAL/);
assert.match(script, /TEST_USER_B_EPHEMERAL/);
assert.match(workflow, /TEST_USER_A_EPHEMERAL=false/);
assert.match(workflow, /TEST_USER_B_EPHEMERAL=false/);
assert.match(script, /GITHUB_RUN_ID/);
assert.match(script, /GITHUB_ENV/);

assert.match(migration, /security definer/i);
assert.match(migration, /set search_path = public, pg_catalog/i);
assert.doesNotMatch(migration, /current_setting\(['"]request\.jwt\.claim\.role/);
assert.doesNotMatch(migration, /current_setting\(['"]request\.jwt\.claims/);
assert.match(migration, /revoke all on function public\.provision_e2e_test_membership/i);
assert.match(migration, /grant execute on function public\.provision_e2e_test_membership/i);
assert.match(migration, /e2e_actor/);
assert.match(migration, /e2e_actor_membership_provisioned/);

assert.match(workflow, /Start exact Netlify preview with serverless API/);
assert.ok(workflow.includes('node scripts/provision-e2e-actors.mjs'));
assert.match(passportRefresh, /AbortController/);
assert.match(passportRefresh, /REQUEST_TIMEOUT_MS/);
assert.match(passportRefresh, /REQUEST_ATTEMPTS = 3/);
assert.match(passportRefresh, /RETRYABLE_HTTP/);
assert.match(passportRefresh, /seenLogicalJobs/);
assert.match(passportRefresh, /logicalDuplicatesSkipped/);
assert.match(passportRefresh, /status: 'REFRESHING'/);
assert.match(openReportProof, /process\.env\.TEST_USER_C_EMAIL/);
assert.match(openReportProof, /process\.env\.TEST_USER_C_PASSWORD/);
assert.match(openReportProof, /required\('TEST_USER_C_EMAIL'/);
assert.match(openReportProof, /required\('TEST_USER_C_PASSWORD'/);
assert.doesNotMatch(openReportProof, /process\.env\.TEST_USER_A_(EMAIL|PASSWORD)/);
assert.match(script, /provisionMembership\(smartReportTenantId, userC\.id, 'sales', true, 'C-REAL-REPORT'\)/);
const previewStep = workflow.indexOf('Start exact Netlify preview with serverless API');
const provisionStep = workflow.indexOf('node scripts/provision-e2e-actors.mjs', previewStep);
assert.ok(previewStep >= 0 && provisionStep > previewStep);
assert.ok(/REPORT_ADVISOR_SUPABASE_URL:\s*\$\{\{\s*secrets\.REPORT_ADVISOR_SUPABASE_URL\s*\}\}|REPORT_ADVISOR_SUPABASE_URL:\s*https:\/\/fnqbvfuwbdpwvhcgzksl\.supabase\.co/.test(workflow), 'REPORT_ADVISOR_SUPABASE_URL contract missing canonical or secret endpoint');
assert.match(workflow, /SUPABASE_SERVICE_ROLE_KEY: \$\{\{ secrets\.SUPABASE_SERVICE_ROLE_KEY \}\}/);
assert.match(workflow, /Prepare rerunnable E2E actor credentials/);

console.log('E2E_ACTOR_PROVISIONING_CONTRACT_PASS');
