import { createServer, type ViteDevServer } from 'vite';
import { readFile, writeFile, access } from 'node:fs/promises';
import { resolve } from 'node:path';
import * as XLSX from 'xlsx';

type Metrics = { revenue:number|null; cost:number|null; grossProfit:number|null; quantity:number|null; status:string };
type Evidence = { timestamp:string; surface:string; tenant:string; authenticatedExecution:string; consumer:string; queryIdentity:string; actual:Metrics|null; expected:Metrics|null; comparison:'PASS'|'FAIL'|'NOT PROVEN'; classification:string; nullMissingStatus:string; dateBoundaryStatus:string; exportRowCount:number|null; note?:string };
const required=['CERT_SUPABASE_URL','CERT_SUPABASE_ANON_KEY','CERT_TENANT_A_ID','CERT_TENANT_B_ID','CERT_USER_A_JWT','CERT_USER_B_JWT'] as const;
const fixture=JSON.parse(await readFile(resolve(process.cwd(),'scripts/fixtures/gross-profit-runtime-fixture.json'),'utf8')) as {scenarios:Record<string,{tenant:string;expected:Metrics}>};
const missingConfig=required.filter(key=>!process.env[key]?.trim());
const evidence:Evidence[]=[];
const writeArtifact=async(closure='NOT PROVEN')=>writeFile(resolve(process.cwd(),'gross-profit-runtime-results.json'),JSON.stringify({generatedAt:new Date().toISOString(),targetHead:process.env.GITHUB_SHA??'unknown',auth:'authenticated JWT execution; token values redacted',independentFixture:fixture,evidence,closure},null,2)+'\n');
if(missingConfig.length){evidence.push({timestamp:new Date().toISOString(),surface:'ALL',tenant:'A/B',authenticatedExecution:'NOT EXECUTED',consumer:'NOT EXECUTED',queryIdentity:'NOT EXECUTED',actual:null,expected:null,comparison:'NOT PROVEN',classification:'RUNTIME BLOCKED',nullMissingStatus:'NOT PROVEN',dateBoundaryStatus:'NOT PROVEN',exportRowCount:null,note:`Missing required live certification configuration: ${missingConfig.join(', ')}`});await writeArtifact();console.error(`RUNTIME BLOCKED: missing live certification configuration: ${missingConfig.join(', ')}`);process.exit(10);}

const baseUrl=process.env.CERT_SUPABASE_URL!.replace(/\/$/,'');const anonKey=process.env.CERT_SUPABASE_ANON_KEY!;process.env.VITE_SUPABASE_URL=baseUrl;process.env.VITE_SUPABASE_ANON_KEY=anonKey;let activeJwt='';const nativeFetch=globalThis.fetch.bind(globalThis);globalThis.fetch=async(input,init)=>{const url=typeof input==='string'?input:input instanceof URL?input.toString():input.url;const headers=new Headers(init?.headers??(input instanceof Request?input.headers:undefined));if(url.startsWith(`${baseUrl}/`)){headers.set('apikey',anonKey);headers.set('Authorization',`Bearer ${activeJwt}`);}return nativeFetch(input,{...init,headers});};
const server:ViteDevServer=await createServer({server:{middlewareMode:true},appType:'custom'});
const sameMetrics=(a:Metrics,b:Metrics)=>a.revenue===b.revenue&&a.cost===b.cost&&a.grossProfit===b.grossProfit&&a.quantity===b.quantity&&a.status===b.status;
const expectedFor=(key:string)=>fixture.scenarios[key]?.expected??null;

async function loadQueries(){const mod=await server.ssrLoadModule('/src/lib/queries.ts');if(typeof mod.fetchDashboardKPIs!=='function')throw new Error('PRODUCTION_CONSUMER_NOT_FOUND:fetchDashboardKPIs');return mod;}
async function loadExecutive(){const mod=await server.ssrLoadModule('/src/lib/free-toolbox/executive-pipeline.ts');if(typeof mod.runExecutivePipeline!=='function')throw new Error('PRODUCTION_CONSUMER_NOT_FOUND:runExecutivePipeline');return mod;}
async function loadExport(){const mod=await server.ssrLoadModule('/src/lib/free-toolbox/gross-profit-export.ts');for(const name of ['loadCompleteGrossProfitExport','buildGrossProfitExportArtifact','exportSalesReportXlsx'])if(typeof mod[name]!=='function')throw new Error(`PRODUCTION_EXPORT_FUNCTION_NOT_FOUND:${name}`);return mod;}

async function proveTenant(tenantLabel:'A'|'B',jwt:string,expectedKey:string){
 activeJwt=jwt;const queries=await loadQueries();const actual=await queries.fetchDashboardKPIs();const metrics:Metrics={revenue:typeof actual.totalSales==='number'?actual.totalSales:null,cost:typeof actual.totalCost==='number'?actual.totalCost:null,grossProfit:typeof actual.grossProfit==='number'?actual.grossProfit:null,quantity:typeof actual.totalQuantity==='number'?actual.totalQuantity:null,status:String(actual.status)};const expected=expectedFor(expectedKey);evidence.push({timestamp:new Date().toISOString(),surface:'Dashboard',tenant:tenantLabel,authenticatedExecution:`CERT_USER_${tenantLabel}_JWT (redacted)`,consumer:'production fetchDashboardKPIs()',queryIdentity:'src/lib/queries.ts:fetchDashboardKPIs',actual:metrics,expected,comparison:expected&&sameMetrics(metrics,expected)?'PASS':'FAIL',classification:expected&&sameMetrics(metrics,expected)?'NONE':'REAL TRUTH BUG OR LIVE DATA/INDEPENDENT FIXTURE MISMATCH — ROOT CAUSE REQUIRED',nullMissingStatus:metrics.cost===null||metrics.grossProfit===null?'NULL/UNKNOWN':'NUMERIC',dateBoundaryStatus:'NOT PROVEN — date-range cases require dedicated runtime calls',exportRowCount:null});

 // Reports intentionally executes the real production consumer used by the Reports UI. It is SHARED, not independent proof.
 const reportActual=await queries.fetchDashboardKPIs();const reportMetrics:Metrics={revenue:typeof reportActual.totalSales==='number'?reportActual.totalSales:null,cost:typeof reportActual.totalCost==='number'?reportActual.totalCost:null,grossProfit:typeof reportActual.grossProfit==='number'?reportActual.grossProfit:null,quantity:typeof reportActual.totalQuantity==='number'?reportActual.totalQuantity:null,status:String(reportActual.status)};evidence.push({timestamp:new Date().toISOString(),surface:'Reports',tenant:tenantLabel,authenticatedExecution:`CERT_USER_${tenantLabel}_JWT (redacted)`,consumer:'production fetchDashboardKPIs() — same consumer as Reports UI',queryIdentity:'src/pages/ReportsPage.tsx → fetchDashboardKPIs',actual:reportMetrics,expected,comparison:expected&&sameMetrics(reportMetrics,expected)?'PASS':'FAIL',classification:'SHARED CONSUMER — runtime actual executed, but not independent cross-surface proof',nullMissingStatus:reportMetrics.cost===null||reportMetrics.grossProfit===null?'NULL/UNKNOWN':'NUMERIC',dateBoundaryStatus:'NOT PROVEN — current Reports KPI surface is not independently date-parametrized',exportRowCount:null});

 // Executive executes the actual production pipeline that the Executive UI invokes. The pipeline now carries financialTruth without NULL→0.
 const executive=await loadExecutive();const kpis=[{id:'revenue',label:'المبيعات',value:metrics.revenue!,target:metrics.revenue!,higherIsBetter:true},{id:'gross_profit',label:'مجمل الربح',value:metrics.grossProfit!,target:Math.max(0,metrics.revenue!*0.2),higherIsBetter:true},{id:'collection_rate',label:'معدل التحصيل',value:actual.collectionRate,target:80,higherIsBetter:true}];const pipeline=executive.runExecutivePipeline({series:[{period:new Date().toISOString().slice(0,10),value:metrics.revenue!}],signals:[{id:'gross-margin',label:'الهامش الإجمالي',value:actual.grossMargin!,history:[],direction:'lower-risk',staticThreshold:10}],actions:[],quality:{completeness:100,validity:100,consistency:100,uniqueness:100,timeliness:100},kpis});const executiveMetrics:Metrics={revenue:pipeline.financialTruth.revenue,cost:pipeline.financialTruth.cost,grossProfit:pipeline.financialTruth.grossProfit,quantity:pipeline.financialTruth.quantity,status:pipeline.financialTruth.status};evidence.push({timestamp:new Date().toISOString(),surface:'Executive Decision',tenant:tenantLabel,authenticatedExecution:`CERT_USER_${tenantLabel}_JWT (redacted)`,consumer:'runExecutivePipeline() invoked with production Dashboard KPI values',queryIdentity:'src/pages/ExecutiveCommandCenterPage.tsx → runExecutivePipeline',actual:executiveMetrics,expected,comparison:expected&&sameMetrics(executiveMetrics,expected)?'PASS':'FAIL',classification:expected&&sameMetrics(executiveMetrics,expected)?'PIPELINE FINANCIAL TRUTH MATCH — UI runtime event remains not independently exercised':'EXECUTIVE FINANCIAL DIVERGENCE — ROOT CAUSE REQUIRED',nullMissingStatus:executiveMetrics.cost===null||executiveMetrics.grossProfit===null?'NULL/UNKNOWN':'NUMERIC',dateBoundaryStatus:'NOT PROVEN — this run uses the selected production period only',exportRowCount:null});

 // Export executes the real complete-dataset exporter and reads the produced XLSX file. The UI click itself is not simulated.
 const exporter=await loadExport();const rows=await exporter.loadCompleteGrossProfitExport();const artifact=exporter.buildGrossProfitExportArtifact(rows);await exporter.exportSalesReportXlsx();const file=resolve(process.cwd(),`gross-profit-${new Date().toISOString().slice(0,10)}.xlsx`);await access(file);const workbook=XLSX.readFile(file);const sheet=workbook.Sheets['Gross Profit'];const exportedRows=Math.max(0,(XLSX.utils.sheet_to_json(sheet,{header:1}) as unknown[][]).length-1);const exportMetrics:Metrics={revenue:artifact.revenue,cost:artifact.cost,grossProfit:artifact.gross_profit,quantity:artifact.quantity,status:artifact.status==='COMPLETE'?'CALCULATED':'INSUFFICIENT_DATA'};evidence.push({timestamp:new Date().toISOString(),surface:'Export',tenant:tenantLabel,authenticatedExecution:`CERT_USER_${tenantLabel}_JWT (redacted)`,consumer:'production loadCompleteGrossProfitExport() + exportSalesReportXlsx()',queryIdentity:'src/lib/free-toolbox/gross-profit-export.ts',actual:exportMetrics,expected,comparison:expected&&sameMetrics(exportMetrics,expected)?'PASS':'FAIL',classification:expected&&sameMetrics(exportMetrics,expected)?'EXPORT FINANCIAL MATCH — UI click not independently simulated':'EXPORT FINANCIAL DIVERGENCE — ROOT CAUSE REQUIRED',nullMissingStatus:exportMetrics.cost===null||exportMetrics.grossProfit===null?'NULL/UNKNOWN':'NUMERIC',dateBoundaryStatus:'NOT PROVEN — dedicated boundary artifact required',exportRowCount:exportedRows,note:`Underlying rows=${rows.length}; XLSX rows=${exportedRows}; presentation page contract=20.`});
}

try{
 await proveTenant('A',process.env.CERT_USER_A_JWT!,'tenantAComplete');
 await proveTenant('B',process.env.CERT_USER_B_JWT!,'tenantBComplete');
 const nonPass=evidence.filter(e=>e.comparison!=='PASS');
 const hasCrossSurface=nonPass.length===0&&evidence.some(e=>e.surface==='Dashboard')&&evidence.some(e=>e.surface==='Reports')&&evidence.some(e=>e.surface==='Executive Decision')&&evidence.some(e=>e.surface==='Export');
 await writeArtifact(hasCrossSurface?'TRUTH-PROVEN':'NOT PROVEN');
 if(nonPass.length){console.log(`FAIL-CLOSED: ${nonPass.length} Gross Profit evidence records are not PASS.`);process.exitCode=10;}else console.log('GROSS_PROFIT_RUNTIME_SURFACES=PASS');
}finally{await server.close();}
