import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const migration = readFileSync('supabase/migrations/20260928233000_post_upload_execution_task_ledger.sql', 'utf8');
const adapter = readFileSync('src/lib/report-execution/durable-worker-adapter.ts', 'utf8');
const runner = readFileSync('src/lib/report-execution/durable-production-runner.ts', 'utf8');
const server = readFileSync('src/server/canonical-import-executor.ts', 'utf8');
const adapterBoundary = readFileSync('src/lib/import/canonical-production-adapter.ts', 'utf8');
const queries = readFileSync('src/lib/queries.ts', 'utf8');
const ui = readFileSync('src/pages/CanonicalImportPage.tsx', 'utf8');
const reportsUi = readFileSync('src/pages/ReportsPage.tsx', 'utf8');
const productionAdapter = readFileSync('src/lib/import/canonical-production-adapter.ts', 'utf8');
for (const token of ['create table if not exists public.report_execution_tasks','report_execution_tasks_tenant_select','start_report_execution_task','complete_report_execution_task','fail_report_execution_task','Execution task ordering violation','grant execute on function public.start_report_execution_task','stage = ANY (ARRAY[\'queued\'::text,\'fingerprinted\'::text,\'extracted\'::text,\'canonicalized\'::text,\'validated\'::text,\'analyzed\'::text,\'decisioned\'::text,\'committed\'::text,\'rendered\'::text])']) assert.ok(migration.includes(token), `missing task-ledger invariant: ${token}`);
for (const token of ["from('report_execution_tasks')","rpc('start_report_execution_task'","rpc('complete_report_execution_task'","rpc('fail_report_execution_task'","if (queuedTask?.status === 'queued')","startTask(jobId, workerId, job.leaseToken, 'queued'","completeTask(jobId, workerId, job.leaseToken, 'queued'"]) assert.ok(adapter.includes(token), `missing worker task RPC/claim invariant: ${token}`);
for (const token of ['activeTask','store.startTask','store.completeTask','store.failTask','while (stage !== \'rendered\')','stageEvidence','renderedOutput: stageEvidence.rendered','Promise<Record<string, unknown> | void>','const ORDER: ReportExecutionStage[] = [\'queued\', \'fingerprinted\', \'extracted\', \'canonicalized\', \'validated\', \'analyzed\', \'decisioned\', \'committed\', \'rendered\']']) assert.ok(runner.includes(token), `missing durable task lifecycle/order invariant: ${token}`);
for (const token of ["mode === 'enqueue'",'enqueue_report_execution_job','payload.durableJobId','REPORT_EXECUTION_JOB_SOURCE_HASH_MISMATCH']) assert.ok(server.includes(token), `missing authoritative queue boundary: ${token}`);
for (const token of ['enqueueCanonicalImportForExecution',"mode === 'enqueue'",'durableJobId?: string']) assert.ok(adapterBoundary.includes(token), `missing browser orchestration boundary: ${token}`);
for (const token of ['buildRenderedReportOutput','contractVersion: \'2026-09-28\'','evidenceStatus: \'AWAITING_EVIDENCE_SNAPSHOT\'','if (stage === \'rendered\') return buildRenderedReportOutput(input)','sourceSpecialty?: string']) assert.ok(productionAdapter.includes(token), `missing rendered-report manifest invariant: ${token}`);
for (const token of ['ReportExecutionTaskRecord','fetchReportExecutionTasks','ReportExecutionJobRecord','fetchReportExecutionJob','renderedOutput']) assert.ok(queries.includes(token), `missing task readback contract: ${token}`);
for (const token of ['LIVE EXECUTION REPORT','تفكيك التنفيذ الفعلي إلى 9 مهام بعد السحب','التنفيذ الحالي متسلسل تحت Worker مؤجر','EXECUTION REPORT','تقرير ما حدث فعليًا بعد السحب','fetchReportExecutionTasks','fetchReportExecutionJob','RENDERED REPORT OUTPUTS','التقارير التي أنشأها مسار التنفيذ فعليًا','stage rendered','executionReport','enqueueCanonicalImportForExecution']) assert.ok(ui.includes(token), `missing visible post-upload execution report/semantics: ${token}`);
for (const token of ['SOURCE → REPORT HANDOFF','مخرجات التقرير مرتبطة بمصدر مستورد مثبت','rendered','fetchReportExecutionJob','fetchImportEvidenceSnapshot']) assert.ok(reportsUi.includes(token), `missing report-center source handoff invariant: ${token}`);
console.log('Report execution task ledger contract: PASS');