import type { ColumnProfile, Dataset } from './types';

export interface SchemaRelationship { left:string; right:string; reason:'shared-canonical'|'key-like-pair'|'value-overlap'; confidence:number; }
export interface ReverseSchemaCandidate { column:string; canonicalField:string; confidence:number; evidence:string[]; }
export interface TableClassification { kind:'headered'|'headerless'|'transactional'|'master-data'|'unknown'; confidence:number; evidence:string[]; }
const IDS=new Set(['sku','customer_id','supplier_id','invoice_no','transaction_no','account_no','entity_id','transfer_no']);
const norm=(v:unknown)=>String(v??'').toLowerCase().normalize('NFKC').replace(/[ً-ٟ]/g,'').replace(/[\s_\-./\\]+/g,' ').trim();
export function buildSchemaRelationships(columns:ColumnProfile[]):SchemaRelationship[]{const out:SchemaRelationship[]=[];for(let i=0;i<columns.length;i++)for(let j=i+1;j<columns.length;j++){const a=columns[i],b=columns[j];if(a.mappedField&&b.mappedField&&a.mappedField===b.mappedField)out.push({left:a.name,right:b.name,reason:'shared-canonical',confidence:Math.min(a.mappingConfidence,b.mappingConfidence)});else if(a.mappedField&&IDS.has(a.mappedField)&&a.uniqueRatio>=.8&&b.uniqueRatio>=.8&&a.dataType===b.dataType)out.push({left:a.name,right:b.name,reason:'key-like-pair',confidence:72});}return out;}
export function inferHeaderlessSchema(rows:unknown[][],fields:string[]):ReverseSchemaCandidate[]{if(!rows.length)return[];const out:ReverseSchemaCandidate[]=[];const width=Math.max(...rows.slice(0,200).map(r=>r.length));for(let c=0;c<width;c++){const v=rows.slice(0,200).map(r=>r[c]).filter(x=>x!==''&&x!=null),num=v.length?v.filter(x=>!Number.isNaN(Number(String(x).replace(/,/g,'')))).length/v.length:0,uniq=v.length?new Set(v.map(norm)).size/v.length:0;for(const f of fields){let s=0,e:string[]=[];if(IDS.has(f)&&uniq>=.8){s+=40;e.push('high uniqueness');}if(/amount|price|quantity|balance/.test(f)&&num>=.8){s+=45;e.push('numeric profile');}if(/name|description|group/.test(f)&&num<.2){s+=30;e.push('text profile');}if(f==='date'&&v.filter(x=>/^\d{1,4}[-/]\d{1,2}[-/]\d{1,4}/.test(String(x))).length/v.length>.7){s+=45;e.push('date pattern');}if(s>=45)out.push({column:`column_${c+1}`,canonicalField:f,confidence:Math.min(95,s),evidence:e});}}return out.sort((a,b)=>b.confidence-a.confidence);}
export function classifyDataset(dataset:Dataset):TableClassification{const mapped=dataset.columns.filter(c=>c.mappedField).length,transactional=dataset.columns.some(c=>['invoice_no','transaction_no','date','quantity','unit_price','sales_amount'].includes(c.mappedField??'')),master=dataset.columns.some(c=>['sku','customer_id','supplier_id','account_no'].includes(c.mappedField??''))&&!transactional;const kind=transactional?'transactional':master?'master-data':mapped?'headered':'unknown';return{kind,confidence:Math.min(98,dataset.columnCount?mapped/dataset.columnCount*100+(transactional?15:0):0),evidence:[`${mapped} mapped columns`,...(transactional?['transaction fields']:[]),...(master?['master key fields']:[])]};}
