import type { ColumnProfile, Dataset } from './types';

export interface SchemaRelationship { left:string; right:string; reason:'shared-canonical'|'key-like-pair'|'value-overlap'; confidence:number; }
export interface ReverseSchemaCandidate { column:string; canonicalField:string; confidence:number; evidence:string[]; }
export interface TableClassification { kind:'headered'|'headerless'|'transactional'|'master-data'|'unknown'; confidence:number; evidence:string[]; }

const IDS=new Set(['sku','customer_id','supplier_id','invoice_no','transaction_no','account_no','entity_id','transfer_no']);
const norm=(v:unknown)=>String(v??'').toLowerCase().normalize('NFKC').replace(/[ً-ٟ]/g,'').replace(/[\s_\-./\\]+/g,' ').trim();
export function buildSchemaRelationships(columns:ColumnProfile[]):SchemaRelationship[]{const out:SchemaRelationship[]=[];for(let i=0;i<columns.length;i++)for(let j=i+1;j<columns.length;j++){const a=columns[i],b=columns[j];if(a.mappedField&&b.mappedField&&a.mappedField===b.mappedField)out.push({left:a.name,right:b.name,reason:'shared-canonical',confidence:Math.min(a.mappingConfidence,b.mappingConfidence)});else if(a.mappedField&&IDS.has(a.mappedField)&&a.uniqueRatio>=.8&&b.uniqueRatio>=.8&&a.dataType===b.dataType)out.push({left:a.name,right:b.name,reason:'key-like-pair',confidence:72});}return out;}
export function inferHeaderlessSchema(rows:unknown[][],fields:string[]):ReverseSchemaCandidate[]{if(!rows.length)return[];const out:ReverseSchemaCandidate[]=[];const width=Math.max(...rows.slice(0,200).map(r=>r.length));for(let c=0;c<width;c++){const v=rows.slice(0,200).map(r=>r[c]).filter(x=>x!==''&&x!=null),num=v.length?v.filter(x=>!Number.isNaN(Number(String(x).replace(/,/g,'')))).length/v.length:0,uniq=v.length?new Set(v.map(norm)).size/v.length:0;for(const f of fields){let s=0,e:string[]=[];if(IDS.has(f)&&uniq>=.8){s+=40;e.push('high uniqueness');}if(/amount|price|quantity|balance/.test(f)&&num>=.8){s+=45;e.push('numeric profile');}if(/name|description|group/.test(f)&&num<.2){s+=30;e.push('text profile');}if(f==='date'&&v.filter(x=>/^\d{1,4}[-/]\d{1,2}[-/]\d{1,4}/.test(String(x))).length/v.length>.7){s+=45;e.push('date pattern');}if(s>=45)out.push({column:`column_${c+1}`,canonicalField:f,confidence:Math.min(95,s),evidence:e});}}return out.sort((a,b)=>b.confidence-a.confidence);}
export function classifyDataset(dataset:Dataset):TableClassification{const mapped=dataset.columns.filter(c=>c.mappedField).length,transactional=dataset.columns.some(c=>['invoice_no','transaction_no','date','quantity','unit_price','sales_amount'].includes(c.mappedField??'')),master=dataset.columns.some(c=>['sku','customer_id','supplier_id','account_no'].includes(c.mappedField??''))&&!transactional;const kind=transactional?'transactional':master?'master-data':mapped?'headered':'unknown';return{kind,confidence:Math.min(98,dataset.columnCount?mapped/dataset.columnCount*100+(transactional?15:0):0),evidence:[`${mapped} mapped columns`,...(transactional?['transaction fields']:[]),...(master?['master key fields']:[])]};}
export type ImportedSpecialty='sales'|'purchases'|'inventory'|'receivables'|'payments'|'customers'|'products'|'other';
export interface ImportedSpecialtyDetection{specialty:ImportedSpecialty;label:string;confidence:number;evidence:string[];canonicalEntityType:'products'|'customers'|'sales_invoices'|`generic:${string}`;mappedFields:string[];}
const SPECIALTY_LABELS:Record<ImportedSpecialty,string>={sales:'المبيعات',purchases:'المشتريات',inventory:'المخزون',receivables:'الذمم والتحصيل',payments:'المدفوعات',customers:'العملاء',products:'المنتجات',other:'مصدر عام'};
const hasAll=(mapped:Set<string>,required:string[])=>required.every(field=>mapped.has(field));
const specialtyResult=(specialty:ImportedSpecialty,mapped:Set<string>,confidence:number,evidence:string[]):ImportedSpecialtyDetection=>({specialty,label:SPECIALTY_LABELS[specialty],confidence,evidence,canonicalEntityType:`generic:${specialty==='other'?'source-data':specialty}`,mappedFields:[...mapped].sort()});
export function detectImportedSpecialty(dataset:Dataset):ImportedSpecialtyDetection{
const mapped=new Set(dataset.columns.map(c=>c.mappedField).filter((v):v is string=>Boolean(v)));
if(mapped.has('customer_id')||mapped.has('customer_name')){
if(mapped.has('outstanding_balance')||mapped.has('balance')||mapped.has('age_0_30')||mapped.has('age_31_60')||mapped.has('age_61_90')||mapped.has('age_91_120')||mapped.has('age_over_120')||mapped.has('collected_amount'))return specialtyResult('receivables',mapped,96,['تمت مطابقة هوية العميل مع رصيد/أعمار الذمم أو التحصيل.']);
if(hasAll(mapped,['invoice_number','invoice_date','subtotal','tax_amount','total','paid_amount','status']))return{specialty:'sales',label:SPECIALTY_LABELS.sales,confidence:95,evidence:['اكتملت بنية فاتورة المبيعات والقيم المالية وحالة الفاتورة مع مرجع عميل.'],canonicalEntityType:'sales_invoices',mappedFields:[...mapped].sort()};
}
if(mapped.has('debit')||mapped.has('credit')||mapped.has('payment_id')||(mapped.has('paid_amount')&&(mapped.has('payment_date')||mapped.has('payment_method'))))return specialtyResult('payments',mapped,92,['اكتملت حقول حركة مالية مدين/دائن أو حركة دفع قابلة للتتبع.']);
if(mapped.has('supplier_id')||mapped.has('supplier_name')||mapped.has('purchase_order'))return specialtyResult('purchases',mapped,92,['ظهرت هوية المورد أو أمر شراء في مصدر المشتريات.']);
if(mapped.has('local_amount')&&((mapped.has('sku')||mapped.has('name')))&&!mapped.has('sales_amount')&&!mapped.has('net_sales'))return specialtyResult('purchases',mapped,90,['ظهرت هوية صنف مع مبلغ شراء/إجمالي محلي دون حقول مبيعات.']);
if(mapped.has('sales_amount')||mapped.has('net_sales')||mapped.has('discount')||mapped.has('charges')){
if(mapped.has('sku')||mapped.has('name'))return specialtyResult('sales',mapped,90,['ظهرت حقول حركة مبيعات وقيم خصم/ضريبة/صافي مرتبطة بالأصناف.']);
}
if(mapped.has('available_quantity')||mapped.has('warehouse'))return specialtyResult('inventory',mapped,90,['ظهرت هوية الصنف مع كمية متاحة أو مخزن.']);
if(hasAll(mapped,['sku','name','unit','cost_price','selling_price','min_stock','reorder_point','is_active']))return{specialty:'products',label:SPECIALTY_LABELS.products,confidence:96,evidence:['اكتملت حقول الصنف والهوية والتسعير وإعادة الطلب.'],canonicalEntityType:'products',mappedFields:[...mapped].sort()};
if(hasAll(mapped,['name','segment','credit_limit','payment_terms_days']))return{specialty:'customers',label:SPECIALTY_LABELS.customers,confidence:94,evidence:['اكتملت حقول هوية العميل وشريحة الائتمان وشروط الدفع.'],canonicalEntityType:'customers',mappedFields:[...mapped].sort()};
if(hasAll(mapped,['sku','name','unit'])&&!(mapped.has('sales_amount')||mapped.has('net_sales')||mapped.has('available_quantity')))return specialtyResult('products',mapped,88,['اكتملت هوية الصنف الأساسية؛ بقية الحقول لا تكفي لإعلان حركة مالية.']);
if(mapped.has('sku')&&mapped.has('quantity'))return specialtyResult('inventory',mapped,84,['ظهرت هوية صنف وكمية قابلة للقراءة.']);
const evidence = mapped.size ? ['تم التعرف على '+mapped.size+' حقول معيارية دون اكتمال تخصص مدعوم.'] : ['لم يتم التعرف على حقول معيارية كافية لتحديد تخصص.'];
return specialtyResult('other',mapped,Math.min(74,Math.max(20,Math.round(mapped.size/Math.max(1,dataset.columnCount)*70))),evidence);
}