import { normalizeColumnName } from './normalizer';
import type { SynonymEntry } from './types';

let synonymCache: Map<string, { canonical: string; confidence: number }> | null = null;

const BUILTIN_SYNONYMS: Array<[string, string, number]> = [
  ['sku', 'sku', 96], ['item code', 'sku', 96], ['product code', 'sku', 96], ['item id', 'sku', 92], ['رقم الصنف', 'sku', 98], ['كود الصنف', 'sku', 98], ['رمز الصنف', 'sku', 96],
  ['الباركود', 'barcode', 96], ['barcode', 'barcode', 96], ['باركود', 'barcode', 96], ['name', 'name', 96], ['item name', 'name', 98], ['product name', 'name', 98], ['اسم الصنف', 'name', 98], ['اسم المنتج', 'name', 98],
  ['description', 'description', 94], ['الوصف', 'description', 96], ['price', 'price', 96], ['sale price', 'selling_price', 98], ['selling price', 'selling_price', 98], ['selling_price', 'selling_price', 98], ['السعر', 'price', 98], ['سعر البيع', 'selling_price', 98],
  ['cost', 'cost', 94], ['cost price', 'cost_price', 98], ['cost_price', 'cost_price', 98], ['التكلفة', 'cost', 96], ['quantity', 'quantity', 96], ['qty', 'quantity', 96], ['stock', 'quantity', 94], ['available quantity', 'quantity', 96], ['الكمية', 'quantity', 98], ['المخزون', 'quantity', 96],
  ['unit', 'unit', 96], ['الوحدة', 'unit', 98], ['category', 'category', 94], ['الفئة', 'category', 96], ['التصنيف', 'category', 96], ['status', 'status', 94], ['الحالة', 'status', 96],
  ['min stock', 'min_stock', 98], ['minimum stock', 'min_stock', 96], ['min_stock', 'min_stock', 98], ['reorder point', 'reorder_point', 98], ['reorder_point', 'reorder_point', 98], ['is active', 'is_active', 98], ['is_active', 'is_active', 98], ['active', 'is_active', 92], ['نشط', 'is_active', 98],
  ['customer number', 'code', 98], ['customer code', 'code', 98], ['code', 'code', 98], ['رقم العميل', 'code', 98], ['كود العميل', 'code', 98], ['customer id', 'customer_id', 96], ['customer name', 'customer_name', 98], ['اسم العميل', 'customer_name', 98], ['phone', 'phone', 96], ['mobile', 'phone', 96], ['هاتف', 'phone', 96], ['جوال', 'phone', 96],
  ['email', 'email', 96], ['البريد الإلكتروني', 'email', 98], ['segment', 'segment', 98], ['customer segment', 'segment', 98], ['شريحة العميل', 'segment', 98], ['credit limit', 'credit_limit', 98], ['credit_limit', 'credit_limit', 98], ['حد ائتماني', 'credit_limit', 98], ['payment terms days', 'payment_terms_days', 98], ['payment_terms_days', 'payment_terms_days', 98], ['payment terms', 'payment_terms_days', 90], ['أيام شروط الدفع', 'payment_terms_days', 98],
  ['customer_id', 'customer_id', 98], ['customer name', 'customer_name', 98], ['customer_name', 'customer_name', 98], ['customer id', 'customer_id', 98],
  ['local_amount', 'local_amount', 98], ['local amount', 'local_amount', 98], ['المبلغ بالعملة المحلية', 'local_amount', 98],
  ['currency', 'currency', 98], ['العملة', 'currency', 98],
  ['outstanding balance', 'outstanding_balance', 98], ['outstanding_balance', 'outstanding_balance', 98], ['balance', 'outstanding_balance', 98], ['الرصيد المستحق', 'outstanding_balance', 98], ['المبلغ المستحق', 'outstanding_balance', 98], ['المبلغ', 'outstanding_balance', 96],
  ['إجمالي المبلغ المستحق', 'outstanding_balance', 98], ['إجمالي المبلغ', 'total', 94], ['المبلغ المستحق', 'outstanding_balance', 98], ['المبلغ', 'outstanding_balance', 96], ['الرصيد', 'outstanding_balance', 98],
  ['المندوب', 'sales_rep', 94], ['اسم المورد', 'supplier_name', 98], ['رقم المورد', 'supplier_id', 98], ['المورد', 'supplier_name', 96],
  ['7 - 15', 'age_7_15', 98], ['16 - 20', 'age_16_20', 98], ['21 - 30', 'age_21_30', 98], ['31 - 40', 'age_31_40', 98], ['> 40', 'age_over_40', 98],
  ['مبلغ المبيعات', 'sales_amount', 98], ['صافي المبيعات', 'net_sales', 98], ['مبلغ صافي المبيعات', 'net_sales', 98], ['مبلغ المبيعات', 'sales_amount', 98], ['الضريبة', 'tax_amount', 98], ['الأعباء', 'charges', 94], ['الخصم', 'discount', 98], ['مبلغ المبيعات', 'sales_amount', 98], ['ك.المجانيه', 'free_quantity', 96], ['الكمية المجانية', 'free_quantity', 98],
  ['المبلغ بالعملة المحلية', 'local_amount', 98], ['الإجمالي بالعملة المحلية', 'local_amount', 98],
  ['اﻹجمالي بالعملة المحلية', 'local_amount', 99], ['ﻹجمالي بالعملة المحلية', 'local_amount', 99], ['اﻹجمالي', 'local_amount', 96],
  ['إجمالي بالعملة المحلية', 'local_amount', 98], ['المخزن', 'warehouse', 98], ['المستودع', 'warehouse', 98], ['مبيعات غير مصروفة', 'unsold_quantity', 98], ['الكمية المتوفرة', 'available_quantity', 98], ['م.الصنف', 'item_group', 90], ['نوع الصنف', 'item_type', 94],
  ['رقمه', 'document_no', 96], ['المستند', 'document_type', 96], ['حالته', 'status', 94], ['توقيف', 'status', 94],
  ['المدينه', 'city', 94], ['المدينة', 'city', 94], ['تاريخ التعامل', 'last_transaction_date', 94], ['رقم الفرع', 'branch_id', 94], ['المجموعة', 'segment', 94], ['رقم الجوال', 'phone', 98], ['الهاتف', 'phone', 96],
  ['اجمالي الفاتورة', 'total', 99], ['اﻹجمالي', 'total', 96], ['الإجمالي', 'total', 98], ['الضريبة', 'tax_amount', 98], ['اﻷعباء', 'charges', 98], ['الأعباء', 'charges', 98], ['مبلغ الفاتورة', 'total', 98], ['نوع الفاتورة', 'invoice_type', 96], ['رقم الفاتورة', 'invoice_number', 99],
  ['الرصيد الحالي', 'balance', 98], ['اسم البنك', 'bank_name', 96], ['اسم الحساب', 'account_name', 96], ['الحساب', 'account_no', 94], ['رصيد افتتاحي', 'opening_balance', 98],
  ['خصم اﻻصناف', 'discount', 98], ['خصم الأصناف', 'discount', 98], ['العبوه', 'pack_size', 94], ['الوارد', 'incoming', 96], ['غير مستلم', 'unreceived_quantity', 94], ['مبيعات مرحل', 'posted_sales', 94], ['مبيعات غير مرحلة', 'unposted_sales', 94], ['لم يرحل', 'unposted_sales', 92],
  ['رقم البنك', 'bank_id', 96], ['رقم الحساب', 'account_no', 98], ['نوع المستند', 'document_type', 96], ['رقم المستند', 'document_no', 98], ['البيان', 'description', 96], ['رقم المرجع', 'reference_no', 96], ['مدين', 'debit', 98], ['دائن', 'credit', 98], ['الرصيد', 'balance', 98], ['المبلغ الأجنبي', 'foreign_amount', 96],
  ['الرصيد الإفتتاحي', 'opening_balance', 98], ['مبلغ المبيعات', 'sales_amount', 98], ['مبلغ المردودات', 'returns_amount', 98], ['صافي المبيعات', 'net_sales', 98], ['عمليات مدينة أخرى', 'other_debit', 96], ['المبلغ المحصل', 'collected_amount', 98], ['عمليات دائنة أخرى', 'other_credit', 96], ['المبلغ المتبقي', 'outstanding_balance', 98], ['اخر تاريخ بيع', 'last_sale_date', 98], ['آخر تاريخ سداد', 'last_payment_date', 98],
  ['رقم المجموعة', 'category', 94], ['اسم المجموعة', 'category', 94], ['الاسم الأجنبي', 'name_en', 92], ['العبوه', 'pack_size', 94], ['العبوة', 'pack_size', 94], ['وحدة رئيسية', 'base_unit', 94], ['نوع الصنف', 'item_type', 94], ['التكلفة الأولية', 'cost_price', 98], ['التكلفة المبدئية', 'cost_price', 96], ['المجموعات الفرعية', 'category', 90], ['م', 'row_index', 88],
  ['آخر سعر توريد', 'last_supply_price', 94], ['آخر سعر شراء', 'last_purchase_price', 94], ['متوسط التكلفه', 'average_cost', 96], ['الحد الأدني للتسعيرة', 'min_price', 96], ['الحد الأعلى للتسعيرة', 'max_price', 96], ['هامش الربح', 'margin', 96], ['نسبة الربح', 'margin_percent', 96], ['الكمية المتوفرة', 'available_quantity', 98],
  ['age_0_30', 'age_0_30', 98], ['age_31_60', 'age_31_60', 98], ['age_61_90', 'age_61_90', 98], ['age_91_120', 'age_91_120', 98], ['age_over_120', 'age_over_120', 98],
  ['date', 'date', 94], ['التاريخ', 'date', 96], ['invoice number', 'invoice_number', 98], ['invoice_number', 'invoice_number', 98], ['invoice date', 'invoice_date', 98], ['invoice_date', 'invoice_date', 98], ['subtotal', 'subtotal', 98], ['tax amount', 'tax_amount', 98], ['tax_amount', 'tax_amount', 98], ['paid amount', 'paid_amount', 98], ['paid_amount', 'paid_amount', 98], ['total', 'total', 94], ['الإجمالي', 'total', 96],
];

function createBuiltinMap(): Map<string, { canonical: string; confidence: number }> { const map = new Map<string, { canonical: string; confidence: number }>(); for (const [synonym, canonical, confidence] of BUILTIN_SYNONYMS) map.set(normalizeColumnName(synonym), { canonical, confidence }); return map; }
async function getBrowserSupabase() { if (typeof window === 'undefined') throw new Error('BROWSER_SUPABASE_UNAVAILABLE_IN_SERVER_FILE_ENGINE'); const { supabase } = await import('../supabase'); return supabase; }

export async function loadSynonyms(): Promise<Map<string, { canonical: string; confidence: number }>> { if (synonymCache) return synonymCache; const map = createBuiltinMap(); if (typeof window !== 'undefined') { const { supabase } = await import('../supabase'); const { data, error } = await supabase.from('synonym_dictionary').select('*').eq('is_active', true); if (!error && data) for (const entry of data as SynonymEntry[]) { const key = normalizeColumnName(entry.synonym); const existing = map.get(key); if (!existing || entry.confidence > existing.confidence) map.set(key, { canonical: entry.canonical_field, confidence: entry.confidence }); } } synonymCache = map; return map; }
export function clearSynonymCache(): void { synonymCache = null; }
export interface ColumnMapping { sourceColumn: string; mappedField: string | null; confidence: number; requiresReview: boolean; }
export async function mapColumns(sourceColumns: string[]): Promise<ColumnMapping[]> { const synonyms = await loadSynonyms(); return sourceColumns.map(col => { const normalized = normalizeColumnName(col); const match = synonyms.get(normalized); if (match) return { sourceColumn: col, mappedField: match.canonical, confidence: match.confidence, requiresReview: match.confidence < 80 }; const partialMatch = findPartialMatch(normalized, synonyms); return partialMatch ? { sourceColumn: col, mappedField: partialMatch.canonical, confidence: partialMatch.confidence, requiresReview: true } : { sourceColumn: col, mappedField: null, confidence: 0, requiresReview: true }; }); }
function findPartialMatch(normalized: string, synonyms: Map<string, { canonical: string; confidence: number }>): { canonical: string; confidence: number } | null { let bestMatch: { canonical: string; confidence: number } | null = null; let bestScore = 0; for (const [key, value] of synonyms) { if (normalized.includes(key) || key.includes(normalized)) { const score = Math.min(normalized.length, key.length) / Math.max(normalized.length, key.length) * value.confidence * 0.7; if (score > bestScore && score > 50) { bestScore = score; bestMatch = { canonical: value.canonical, confidence: Math.round(score) }; } } } return bestMatch; }
export async function addSynonym(canonicalField: string, synonym: string, language = 'ar', confidence = 90): Promise<void> { const supabase = await getBrowserSupabase(); const { error } = await supabase.from('synonym_dictionary').insert({ canonical_field: canonicalField, synonym, language, confidence, is_active: true }); if (error) throw error; clearSynonymCache(); }
export async function fetchAllSynonyms(): Promise<SynonymEntry[]> { const supabase = await getBrowserSupabase(); const { data, error } = await supabase.from('synonym_dictionary').select('*').order('canonical_field', { ascending: true }); if (error) throw error; return data as SynonymEntry[]; }
export async function updateSynonym(id: string, updates: Partial<SynonymEntry>): Promise<void> { const supabase = await getBrowserSupabase(); const { error } = await supabase.from('synonym_dictionary').update(updates).eq('id', id); if (error) throw error; clearSynonymCache(); }
export async function deleteSynonym(id: string): Promise<void> { const supabase = await getBrowserSupabase(); const { error } = await supabase.from('synonym_dictionary').delete().eq('id', id); if (error) throw error; clearSynonymCache(); }
