import { Component, type ErrorInfo, type ReactNode, useEffect, useState, useCallback, lazy, Suspense } from 'react';
import { BrowserRouter, Routes, Route, Link, useLocation } from 'react-router-dom';
import type { User } from '@supabase/supabase-js';
import { Sidebar } from '@/components/Sidebar';
import { Header } from '@/components/Header';
import { AuthGate } from '@/components/AuthGate';
import { CommandPalette } from '@/components/CommandPalette';
import { DashboardPage } from '@/pages/DashboardPage';
import { fetchAlerts, markAlertRead } from '@/lib/queries-compat';
import { getAuthenticatedUser } from '@/lib/auth-session';
import type { Alert } from '@/lib/types';
import { AlertTriangle, Home, RefreshCw, X } from 'lucide-react';

const ImportPage = lazy(() => import('@/pages/ImportPage').then(m => ({ default: m.ImportPage })));
const ReportsCenterPage = lazy(() => import('@/pages/ReportsPage').then(m => ({ default: m.ReportsCenterPage })));
const SalesReportPage = lazy(() => import('@/pages/ReportsPage').then(m => ({ default: m.SalesReportPage })));
const PurchasesReportPage = lazy(() => import('@/pages/ReportsPage').then(m => ({ default: m.PurchasesReportPage })));
const InventoryReportPage = lazy(() => import('@/pages/ReportsPage').then(m => ({ default: m.InventoryReportPage })));
const InventoryIntelligencePage = lazy(() => import('@/pages/InventoryIntelligencePage').then(m => ({ default: m.InventoryIntelligencePage })));
const DemandVelocityPage = lazy(() => import('@/pages/DemandVelocityPage').then(m => ({ default: m.DemandVelocityPage })));
