-- Materialize the canonical metric catalog per real tenant using an active membership.
-- No service-role bypass and no change to the existing tenant RLS contract.
DO $$
DECLARE v_company uuid; v_user uuid;
BEGIN
  FOR v_company IN SELECT DISTINCT company_id FROM public.company_memberships WHERE is_active LOOP
    SELECT user_id INTO v_user FROM public.company_memberships WHERE company_id=v_company AND is_active ORDER BY is_default DESC,user_id LIMIT 1;
    IF v_user IS NULL THEN RAISE EXCEPTION 'METRIC_GOVERNANCE_TENANT_MEMBER_REQUIRED:%',v_company; END IF;
    PERFORM set_config('request.jwt.claim.sub',v_user::text,true);
    INSERT INTO public.metric_governance(metric_id,name,version,definition,formula,source,dimensions,filters,time_semantics,freshness,owner,dependencies,consumers,tests,evidence,certification_status,company_id)
    VALUES
    ('metric.net_sales','صافي المبيعات',1,'قيمة المبيعات المعتمدة من subtotal المرجعي في فواتير البيع.','SUM(sales_invoices.subtotal)',jsonb_build_array('sales_invoices'),jsonb_build_array('company','branch','customer','product','category','period'),'[]'::jsonb,jsonb_build_object('period','transaction_date','primary','transaction','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',1440),'core-data',jsonb_build_array('sales'),jsonb_build_array('dashboard','reports','chatbi','forecast','recommendations','decision-engine'),jsonb_build_array('golden:net_sales'),jsonb_build_array('sales_invoices'),'REVIEWED',v_company),
    ('metric.gross_profit','مجمل الربح',1,'مجمل الربح من مبيعات البيع بعد تكلفة الأصناف.','SUM(sale_items.line_total - sale_items.cost_price * sale_items.quantity)',jsonb_build_array('sales_invoices','sale_items'),jsonb_build_array('company','branch','product','category','period'),'[]'::jsonb,jsonb_build_object('period','transaction_date','primary','transaction','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',1440),'core-data',jsonb_build_array('sales','cost'),jsonb_build_array('dashboard','reports','decision-engine'),jsonb_build_array('golden:gross_profit'),jsonb_build_array('sales_invoices','sale_items'),'REVIEWED',v_company),
    ('metric.sales_cost','تكلفة المبيعات',1,'تكلفة المبيعات المحسوبة من تكلفة الصنف في بنود البيع.','SUM(sale_items.quantity * sale_items.cost_price)',jsonb_build_array('sales_invoices','sale_items'),jsonb_build_array('company','branch','product','category','period'),'[]'::jsonb,jsonb_build_object('period','transaction_date','primary','transaction','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',1440),'core-data',jsonb_build_array('sales','cost'),jsonb_build_array('dashboard','reports','decision-engine'),jsonb_build_array('golden:sales_cost'),jsonb_build_array('sale_items'),'REVIEWED',v_company),
    ('metric.purchases','المشتريات',1,'إجمالي المشتريات المعتمدة من فواتير الشراء غير الملغاة.','SUM(purchase_invoices.total)',jsonb_build_array('purchase_invoices'),jsonb_build_array('company','supplier','period'),'[]'::jsonb,jsonb_build_object('period','transaction_date','primary','transaction','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',1440),'core-data',jsonb_build_array('purchases'),jsonb_build_array('dashboard','reports','cashflow','decision-engine'),jsonb_build_array('golden:purchases'),jsonb_build_array('purchase_invoices'),'REVIEWED',v_company),
    ('metric.receivables','الذمم المدينة',1,'الرصيد المستحق من فواتير البيع بعد المدفوعات.','SUM(sales_invoices.total - sales_invoices.paid_amount)',jsonb_build_array('sales_invoices'),jsonb_build_array('company','customer','period'),'[]'::jsonb,jsonb_build_object('period','transaction_date','primary','transaction','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',1440),'core-data',jsonb_build_array('sales'),jsonb_build_array('dashboard','reports','collections','decision-engine'),jsonb_build_array('golden:receivables'),jsonb_build_array('sales_invoices'),'REVIEWED',v_company),
    ('metric.payables','الذمم الدائنة',1,'الرصيد المستحق من فواتير الشراء بعد المدفوعات.','SUM(purchase_invoices.total - purchase_invoices.paid_amount)',jsonb_build_array('purchase_invoices'),jsonb_build_array('company','supplier','period'),'[]'::jsonb,jsonb_build_object('period','transaction_date','primary','transaction','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',1440),'core-data',jsonb_build_array('purchases'),jsonb_build_array('dashboard','reports','cashflow','decision-engine'),jsonb_build_array('golden:payables'),jsonb_build_array('purchase_invoices'),'REVIEWED',v_company),
    ('metric.cash','النقدية',1,'صافي التدفقات النقدية من المدفوعات الداخلة والخارجة ضمن فترة as-of.','SUM(inflows)-SUM(outflows)',jsonb_build_array('payments'),jsonb_build_array('company','currency','period'),'[]'::jsonb,jsonb_build_object('period','payment_date','primary','transaction','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',60),'core-data',jsonb_build_array('payments'),jsonb_build_array('dashboard','cashflow','decision-engine'),jsonb_build_array('golden:cash_liquidity'),jsonb_build_array('payments'),'REVIEWED',v_company),
    ('metric.inventory_value','قيمة المخزون',1,'قيمة المخزون من الكمية مضروبة في تكلفة الوحدة.','SUM(inventory_balances.quantity * inventory_balances.unit_cost)',jsonb_build_array('inventory_balances'),jsonb_build_array('company','warehouse','product','category'),'[]'::jsonb,jsonb_build_object('period','data_as_of','primary','snapshot','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',60),'core-data',jsonb_build_array('inventory'),jsonb_build_array('dashboard','inventory-intelligence','recommendations','decision-engine'),jsonb_build_array('golden:inventory_value'),jsonb_build_array('inventory_balances'),'REVIEWED',v_company),
    ('metric.inventory_liquidity_velocity','سيولة وحركة المخزون',1,'حركة المخزون ومتوسط المبيعات اليومية ومدة التصريف وتصنيف moving/frozen.','inventory_liquidity_velocity(company,as_of,days)',jsonb_build_array('inventory_balances','sale_items','sales_invoices','products'),jsonb_build_array('company','product','category','period'),'[]'::jsonb,jsonb_build_object('period','as_of','primary','snapshot','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',60),'core-data',jsonb_build_array('inventory','sales'),jsonb_build_array('dashboard','inventory-intelligence','recommendations','decision-engine'),jsonb_build_array('golden:inventory_velocity'),jsonb_build_array('inventory_liquidity_velocity'),'REVIEWED',v_company),
    ('metric.demand','الطلب',1,'متوسط الطلب اليومي المبني على حركة البيع ضمن نافذة as-of.','inventory_liquidity_velocity.avg_daily_sales',jsonb_build_array('sale_items','sales_invoices','products'),jsonb_build_array('company','product','period'),'[]'::jsonb,jsonb_build_object('period','as_of','primary','snapshot','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',60),'core-data',jsonb_build_array('sales','inventory'),jsonb_build_array('forecast','reorder','recommendations','decision-engine'),jsonb_build_array('golden:demand'),jsonb_build_array('inventory_liquidity_velocity','demand_reorder_snapshot'),'REVIEWED',v_company),
    ('metric.reorder','نقطة إعادة الطلب',1,'نقطة إعادة الطلب والكمية المقترحة وفق الطلب اليومي ومدة التوريد وأيام الأمان.','reorder_point=demand*(lead_time+safety); suggested=max(0,demand*(lead_time+safety+30)-stock)',jsonb_build_array('inventory_balances','sale_items','sales_invoices','products'),jsonb_build_array('company','product','period'),'[]'::jsonb,jsonb_build_object('period','as_of','primary','snapshot','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',60),'core-data',jsonb_build_array('demand','inventory'),jsonb_build_array('dashboard','reorder','recommendations','decision-engine'),jsonb_build_array('golden:reorder'),jsonb_build_array('demand_reorder_snapshot'),'REVIEWED',v_company),
    ('metric.forecast','التنبؤ',1,'قيمة التنبؤ المعتمدة مع حدود التنبؤ وجودته وثقته ونقاط البيانات.','forecasts.forecast_value with lower_bound,upper_bound,quality_score,confidence,data_points',jsonb_build_array('forecasts','sales_invoices','sale_items'),jsonb_build_array('company','entity','metric','period'),'[]'::jsonb,jsonb_build_object('period','forecast.period','primary','forecast','timezone','source'),jsonb_build_object('mode','source-derived','maxAgeMinutes',1440),'core-data',jsonb_build_array('sales','demand'),jsonb_build_array('dashboard','forecast','recommendations','decision-engine'),jsonb_build_array('golden:forecast'),jsonb_build_array('get_forecast_snapshot'),'REVIEWED',v_company)
    ON CONFLICT DO NOTHING;
  END LOOP;
END $$;
DELETE FROM public.metric_governance WHERE company_id IS NULL;
