-- Extend the existing semantic metric registry. No new RPCs or calculation engines are introduced.
-- These definitions bind existing canonical RPC/data paths to SOURCE/FORMULA/PERIOD/TENANT/AS-OF/FRESHNESS/EVIDENCE metadata.

insert into public.metric_governance
  (metric_id, version, name, definition, formula, source, dimensions, filters, time_semantics, freshness, owner, certification_status, dependencies, consumers, tests, evidence, company_id)
values
  ('metric.purchases', 1, 'المشتريات', 'إجمالي قيمة فواتير الشراء الصحيحة ضمن الفترة', 'SUM(purchase_invoices.total)', '["purchase_invoices"]'::jsonb, '["company","supplier","period"]'::jsonb, '{"status":["confirmed","posted","paid"]}'::jsonb, '{"period":"invoice_date","primary":"transaction","timezone":"source"}'::jsonb, '{"mode":"source-derived","maxAgeMinutes":1440}'::jsonb, 'semantic-metric-layer', 'REVIEWED', '[]'::jsonb, '["dashboard","reports"]'::jsonb, '["tenant","period","currency-consistency"]'::jsonb, '["purchase_invoices"]'::jsonb, null),
  ('metric.cash_net_flow', 1, 'صافي التدفق النقدي', 'التدفقات الداخلة ناقص التدفقات الخارجة لكل يوم ضمن الفترة', 'SUM(payments.in) - SUM(payments.out)', '["payments"]'::jsonb, '["company","currency","period"]'::jsonb, '{"direction":["in","out"]}'::jsonb, '{"period":"payment_date","primary":"transaction","timezone":"source"}'::jsonb, '{"mode":"source-derived","maxAgeMinutes":60}'::jsonb, 'semantic-metric-layer', 'REVIEWED', '[]'::jsonb, '["dashboard","cash-liquidity"]'::jsonb, '["tenant","period","currency-consistency"]'::jsonb, '["payments"]'::jsonb, null),
  ('metric.inventory_velocity', 1, 'سرعة دوران المخزون', 'متوسط الطلب اليومي، آخر بيع، وأيام التصفية لكل صنف', 'stock_qty / avg_daily_sales', '["inventory_balances","sale_items","sales_invoices","products"]'::jsonb, '["company","product","period"]'::jsonb, '{"status":["confirmed","posted","paid"]}'::jsonb, '{"period":"invoice_date","as_of":"requested_date","primary":"snapshot","timezone":"source"}'::jsonb, '{"mode":"source-derived","maxAgeMinutes":60}'::jsonb, 'semantic-metric-layer', 'REVIEWED', '[]'::jsonb, '["dashboard","inventory-liquidity"]'::jsonb, '["tenant","as_of","analysis_window"]'::jsonb, '["inventory_balances","sale_items","sales_invoices","products"]'::jsonb, null),
  ('metric.inventory_liquidity', 1, 'سيولة المخزون', 'تصنيف المخزون إلى متحرك أو مجمد أو نافد مع أيام التصفية', 'CASE WHEN stock_qty<=0 THEN out_of_stock WHEN avg_daily_sales<=0 OR last_sale_date IS NULL THEN frozen WHEN stock_qty/avg_daily_sales>180 THEN frozen ELSE moving END', '["inventory_balances","sale_items","sales_invoices","products"]'::jsonb, '["company","product","period"]'::jsonb, '{}'::jsonb, '{"period":"invoice_date","as_of":"requested_date","primary":"snapshot","timezone":"source"}'::jsonb, '{"mode":"source-derived","maxAgeMinutes":60}'::jsonb, 'semantic-metric-layer', 'REVIEWED', '["metric.inventory_value"]'::jsonb, '["dashboard","recommendations"]'::jsonb, '["tenant","as_of","analysis_window"]'::jsonb, '["inventory_balances","sale_items","sales_invoices","products"]'::jsonb, null),
  ('metric.demand_forecast', 1, 'توقع الطلب', 'تقدير الطلب اعتماداً على سجل المبيعات الفعلي ونطاق التحليل', 'AVG(daily_sales) over requested analysis window', '["sale_items","sales_invoices","products"]'::jsonb, '["company","product","period"]'::jsonb, '{"status":["confirmed","posted","paid"]}'::jsonb, '{"period":"invoice_date","as_of":"requested_date","primary":"derived","timezone":"source"}'::jsonb, '{"mode":"source-derived","maxAgeMinutes":60}'::jsonb, 'semantic-metric-layer', 'REVIEWED', '[]'::jsonb, '["dashboard","reorder"]'::jsonb, '["tenant","as_of","analysis_window","confidence"]'::jsonb, '["sale_items","sales_invoices","products"]'::jsonb, null),
  ('metric.reorder_point', 1, 'نقطة إعادة الطلب', 'الطلب اليومي مضروباً في زمن التوريد والأيام الآمنة', 'avg_daily_demand * (lead_time_days + safety_days)', '["inventory_balances","sale_items","sales_invoices","products"]'::jsonb, '["company","product","period"]'::jsonb, '{}'::jsonb, '{"period":"invoice_date","as_of":"requested_date","primary":"derived","timezone":"source"}'::jsonb, '{"mode":"source-derived","maxAgeMinutes":60}'::jsonb, 'semantic-metric-layer', 'REVIEWED', '["metric.demand_forecast","metric.inventory_value"]'::jsonb, '["dashboard","recommendations","reorder"]'::jsonb, '["tenant","as_of","analysis_window","lead_time","safety_days"]'::jsonb, '["inventory_balances","sale_items","sales_invoices","products"]'::jsonb, null)
on conflict (metric_id, version, coalesce(company_id, '00000000-0000-0000-0000-000000000000'::uuid)) do nothing;