export type AccountingSystem='onyx-pro'|'motakamel-plus'|'rogsh'|'generic-arabic-erp'; export type CanonicalField='sku'|'item_name'|'category'|'unit'|'pack'|'warehouse'|'opening_balance'|'inbound'|'transfer_pending'|'posted_sales'|'unposted_sales'|'net_sales_qty'|'current_stock'|'avg_cost'|'inventory_value'|'min_stock'|'max_stock'|'daily_sales_rate'|'supplier_id'|'supplier_name'|'customer_id'|'customer_name'|'invoice_no'|'transaction_date'|'quantity'|'price'|'discount'|'net_amount'|'cost_amount'|'gross_profit'|'profit_margin'|'currency'|'opening_customer_balance'|'collections'|'returns'|'customer_balance'|'due_date'|'payment_status'|'document_no'|'document_type'|'source_warehouse'|'destination_warehouse'|'movement_type'|'adjustment_qty'|'expiry_date'|'serial_no'|'sales_rep'|'payment_method'|'account_no'|'account_name'|'debit'|'credit'|'period_balance'|'current_balance';
export interface HeaderDefinition {field:CanonicalField;aliases:string[];systems:AccountingSystem[];reports:string[];dataType:'text'|'number'|'date'|'currency'|'enum';priority:number;}
const common=(field:CanonicalField,aliases:string[],reports:string[],dataType:HeaderDefinition['dataType']='text'):HeaderDefinition=>({field,aliases,systems:['onyx-pro','motakamel-plus','rogsh','generic-arabic-erp'],reports,dataType,priority:10});
export const ACCOUNTING_HEADER_CATALOG:HeaderDefinition[]=[
common('sku',['رقم الصنف','كود الصنف','كود المادة','رقم المادة','رمز الصنف','رقم المنتج','SKU','Item Code','Product Code'],['items','inventory','sales','purchases','movements']),
common('item_name',['اسم الصنف','اسم المادة','اسم المنتج','البيان','الصنف','Item Name','Product Name'],['items','inventory','sales','purchases']),
common('category',['المجموعة','مجموعة الصنف','التصنيف','الفئة','التصنيف الرئيسي','Category','Group'],['items','inventory']),
common('unit',['الوحدة','وحدة القياس','الوحدة الأساسية','Unit','UOM'],['items','inventory','sales','purchases']),
common('pack',['العبوة','حجم العبوة','التعبئة','Pack','Package'],['items','inventory','sales','purchases']),
common('warehouse',['المخزن','المستودع','المستودع/المخزن','Warehouse','Store'],['inventory','movements']),
common('opening_balance',['الرصيد الافتتاحي','رصيد أول المدة','بداية المدة','Opening Balance'],['inventory','customer-balances','accounts'],'number'),
common('inbound',['الوارد','إجمالي الوارد','كمية الوارد','Inbound','Received Qty'],['inventory','movements'],'number'),
common('transfer_pending',['تحويل غير مستلم','تحويلات غير مستلمة','تحويل قيد الاستلام','Pending Transfer'],['inventory','transfers'],'number'),
common('posted_sales',['المبيعات المرحلة','مبيعات مرحّلة','صافي مبيعات مرحل','Posted Sales'],['inventory','sales'],'number'),
common('unposted_sales',['المبيعات غير المرحلة','مبيعات غير مرحّلة','صافي مبيعات لم يرحل','Unposted Sales'],['inventory','sales'],'number'),
common('net_sales_qty',['صافي المبيعات','صافي كمية المبيعات','المبيعات الصافية','Net Sales'],['inventory','sales'],'number'),
common('current_stock',['الرصيد الحالي','الرصيد','الرصيد المتوفر','الكمية المتوفرة','المتاح','Current Balance','Stock'],['inventory'],'number'),
common('avg_cost',['متوسط التكلفة','متوسط سعر التكلفة','التكلفة المتوسطة','Average Cost'],['inventory','sales'],'currency'),
common('inventory_value',['إجمالي القيمة','قيمة المخزون','قيمة الرصيد','Inventory Value'],['inventory'],'currency'),
common('min_stock',['الحد الأدنى','حد إعادة الطلب الأدنى','الحد الأدنى للمخزون','Minimum Stock'],['inventory','reorder'],'number'),
common('max_stock',['الحد الأقصى','الحد الأعلى','الحد الأقصى للمخزون','Maximum Stock'],['inventory','reorder'],'number'),
common('daily_sales_rate',['معدل البيع اليومي','متوسط البيع اليومي','معدل الاستهلاك اليومي','Daily Sales Rate'],['inventory','sales'],'number'),
common('supplier_id',['رقم المورد','كود المورد','رمز المورد','Supplier No','Supplier ID'],['suppliers','purchases']),
common('supplier_name',['اسم المورد','المورد','اسم الجهة الموردة','Supplier Name'],['suppliers','purchases']),
common('customer_id',['رقم العميل','كود العميل','رمز العميل','رقم الزبون','Customer No','Customer ID'],['customers','sales','receivables']),
common('customer_name',['اسم العميل','اسم الزبون','العميل','الزبون','Customer Name'],['customers','sales','receivables']),
common('invoice_no',['رقم الفاتورة','رقم الفاتورة/السند','رقم المستند','Invoice No','Document No'],['sales','purchases','receivables']),
common('transaction_date',['التاريخ','تاريخ الحركة','تاريخ العملية','تاريخ السند','Transaction Date','Date'],['sales','purchases','movements'],'date'),
common('quantity',['الكمية','كمية','العدد','Quantity','Qty'],['sales','purchases','movements'],'number'),
common('price',['السعر','سعر البيع','سعر الوحدة','سعر الشراء','Unit Price','Price'],['sales','purchases'],'currency'),
common('discount',['الخصم','قيمة الخصم','الخصم المكتسب','نسبة الخصم','Discount'],['sales','purchases'],'number'),
common('net_amount',['صافي المبيعات','الصافي','صافي القيمة','إجمالي صافي','Net Amount'],['sales','purchases','receivables'],'currency'),
common('cost_amount',['تكلفة المبيعات','التكلفة','تكلفة البضاعة','Cost of Sales'],['sales','profit'],'currency'),
common('gross_profit',['إجمالي الربح','الربح الإجمالي','مجمل الربح','Gross Profit'],['sales','profit'],'currency'),
common('profit_margin',['نسبة الربحية','هامش الربح','نسبة الربح','Profit Margin'],['sales','profit'],'number'),
common('currency',['العملة','العملة المحلية','نوع العملة','Currency'],['sales','purchases','receivables','accounts']),
common('opening_customer_balance',['الرصيد الافتتاحي','رصيد أول المدة','رصيد العميل الافتتاحي'],['customer-balances'],'currency'),
common('collections',['المبلغ المحصل','التحصيلات','المدفوع','المقبوض','التحصيل','Collections','Paid'],['receivables','customers'],'currency'),
common('returns',['المردودات','مرتجعات المبيعات','مرتجع','Sales Returns'],['sales','receivables'],'number'),
common('customer_balance',['الرصيد','رصيد العميل','المتبقي','الرصيد المستحق','Customer Balance','Balance'],['receivables'],'currency'),
common('due_date',['تاريخ الاستحقاق','موعد الاستحقاق','Due Date'],['receivables','payables'],'date'),
common('payment_status',['حالة السداد','حالة الدفع','مسدد/غير مسدد','Payment Status'],['receivables','payables']),
common('document_no',['رقم السند','رقم الحركة','رقم المستند','Document No','Voucher No'],['movements','accounts']),
common('document_type',['نوع السند','نوع المستند','نوع العملية','Document Type'],['movements','accounts']),
common('source_warehouse',['المستودع المحول منه','المخزن المصدر','من مخزن','Source Warehouse'],['transfers']),
common('destination_warehouse',['المستودع المحول إليه','المخزن المستلم','إلى مخزن','Destination Warehouse'],['transfers']),
common('movement_type',['نوع الحركة','الحركة','نوع المعاملة','Movement Type'],['movements','inventory']),
common('adjustment_qty',['كمية التسوية','كمية الجرد','فرق الجرد','Adjustment Qty'],['adjustments'],'number'),
common('expiry_date',['تاريخ الصلاحية','تاريخ الانتهاء','Expiry Date'],['items','inventory'],'date'),
common('serial_no',['الرقم التسلسلي','رقم التسلسل','Serial No'],['items','inventory','movements']),
common('sales_rep',['المندوب','مندوب المبيعات','اسم المندوب','Sales Rep'],['sales']),
common('payment_method',['طريقة الدفع','وسيلة الدفع','نوع السداد','Payment Method'],['sales','receivables']),
common('account_no',['رقم الحساب','كود الحساب','رمز الحساب','Account No'],['accounts','profit']),
common('account_name',['اسم الحساب','الحساب','Account Name'],['accounts','profit']),
common('debit',['مدين','الحركة المدينة','المدين','Debit'],['accounts'],'currency'),
common('credit',['دائن','الحركة الدائنة','الدائن','Credit'],['accounts'],'currency'),
common('period_balance',['رصيد الفترة السابقة','رصيد الفترة','رصيد أول الفترة','Period Balance'],['accounts'],'currency'),
common('current_balance',['الرصيد الحالي','الرصيد الختامي','رصيد نهاية الفترة','Current Balance'],['accounts'],'currency')
];
export function catalogHeadersFor(system:AccountingSystem,report:string){return ACCOUNTING_HEADER_CATALOG.filter(h=>h.systems.includes(system)&&h.reports.includes(report));}
export function learnHeaderAlias(field:CanonicalField,alias:string){const h=ACCOUNTING_HEADER_CATALOG.find(x=>x.field===field);if(h&&!h.aliases.includes(alias))h.aliases.push(alias);}
