export type OnyxReportKind='items'|'inventory'|'sales'|'purchases'|'customers'|'suppliers'|'receivables'|'payables'|'transfers'|'adjustments'|'documents'|'pricing'|'general-ledger'|'trial-balance'|'profit-loss'|'cashflow'|'distribution'|'sales-representatives'|'unknown';
export interface HeaderDefinition {canonical:string;aliases:string[];kind:OnyxReportKind[];valueType:'text'|'number'|'date'|'currency'|'quantity'|'percent'|'identifier';}
const h=(canonical:string,aliases:string[],kind:OnyxReportKind[],valueType:HeaderDefinition['valueType']):HeaderDefinition=>({canonical,aliases,kind,valueType});
export const ONYX_PRO_HEADER_CATALOG:HeaderDefinition[]=[
h('sku',['رقم الصنف','كود الصنف','رمز الصنف','رقم المادة','كود المادة','Item No','Item Number','Item Code','Product Code','SKU'],['items','inventory','sales','purchases','pricing','adjustments','transfers'],'identifier'),
h('item_name',['اسم الصنف','اسم المادة','اسم المنتج','وصف الصنف','الوصف','Item Name','Product Name','Description'],['items','inventory','sales','purchases','pricing'],'text'),
h('group',['المجموعة','مجموعة الصنف','المجموعة المخزنية','Item Group','Group','Category'],['items','inventory','sales','purchases'],'text'),
h('unit',['الوحدة','وحدة القياس','Unit','UOM','Unit of Measure'],['items','inventory','sales','purchases','pricing'],'text'),
h('package',['العبوة','حجم العبوة','التعبئة','Package','Pack','Packing'],['items','inventory','sales'],'text'),
h('warehouse',['المخزن','المستودع','المخزن الفرعي','Warehouse','Store','Location'],['inventory','sales','purchases','transfers','adjustments'],'text'),
h('warehouse_from',['المستودع المحول منه','المخزن المحول منه','From Warehouse'],['transfers'],'text'),
h('warehouse_to',['المستودع المحول إليه','المخزن المحول اليه','To Warehouse'],['transfers'],'text'),
h('opening_balance',['الرصيد الافتتاحي','Opening Balance','Beginning Balance'],['inventory','customers','suppliers','general-ledger'],'number'),
h('in_quantity',['الوارد','كمية الوارد','إجمالي الوارد','In Quantity','Received Quantity'],['inventory','purchases'],'quantity'),
h('unreceived_transfer',['تحويل غير مستلم','تحويلات غير مستلمة','Unreceived Transfer'],['inventory','transfers'],'quantity'),
h('net_in_quantity',['صافي الوارد','صافي كمية الوارد','Net In'],['inventory','purchases'],'quantity'),
h('posted_sales_quantity',['صافي مبيعات مرحل','المبيعات المرحلة','Posted Sales'],['inventory','sales'],'quantity'),
h('unposted_sales_quantity',['صافي مبيعات لم يرحل','المبيعات غير المرحلة','Unposted Sales'],['inventory','sales'],'quantity'),
h('net_sales_quantity',['صافي المبيعات','كمية صافي المبيعات','Net Sales Quantity'],['inventory','sales'],'quantity'),
h('current_balance',['الرصيد الحالي','الرصيد المتاح','الكمية المتوفرة','Available Quantity','Current Balance','On Hand'],['inventory','items'],'quantity'),
h('daily_sales_rate',['معدل البيع اليومي','متوسط البيع اليومي','Daily Sales Rate'],['inventory','sales'],'quantity'),
h('overall_sales_rate',['معدل البيع العام','متوسط البيع العام','Overall Sales Rate'],['inventory','sales'],'quantity'),
h('expected_stockout',['الفترة المتوقعة لنفاد الكمية','تاريخ النفاد المتوقع','Expected Stockout','Stockout Date'],['inventory'],'date'),
h('inventory_age',['عمر المخزون','عمر الصنف','Inventory Age','Stock Age'],['inventory'],'number'),
h('period_inventory_age',['عمر المخزون للفترة','عمر المخزون خلال الفترة','Period Inventory Age'],['inventory'],'number'),
h('average_cost',['متوسط التكلفة','متوسط سعر التكلفة','Average Cost','Weighted Average Cost'],['inventory','purchases','sales'],'currency'),
h('total_value',['إجمالي القيمة','قيمة المخزون','Total Value','Inventory Value'],['inventory','sales','purchases'],'currency'),
h('min_level',['الحد الأدنى','حد الطلب الأدنى','Minimum Level','Reorder Level'],['inventory'],'quantity'),
h('max_level',['الحد الأقصى','الحد الأعلى','Maximum Level'],['inventory'],'quantity'),
h('suggested_order_qty',['كمية الطلب المقترحة','الكمية المقترحة للطلب','Suggested Order Quantity'],['inventory','purchases'],'quantity'),
h('customer_id',['رقم العميل','كود العميل','رقم الزبون','Customer No','Customer Number','Customer ID'],['customers','sales','receivables','distribution'],'identifier'),
h('customer_name',['اسم العميل','اسم الزبون','العميل','Customer Name'],['customers','sales','receivables','distribution'],'text'),
h('customer_group',['مجموعة العملاء','تصنيف العميل','Customer Group'],['customers','sales'],'text'),
h('sales_rep',['مندوب المبيعات','المندوب','Sales Representative','Sales Rep'],['sales','distribution','sales-representatives'],'text'),
h('route',['خط السير','مسار المندوب','Route'],['distribution'],'text'),
h('governorate',['المحافظة','محافظة العميل','Governorate'],['customers','sales','distribution'],'text'),
h('city',['المدينة','مدينة العميل','City'],['customers','sales','distribution'],'text'),
h('currency',['العملة','Currency'],['customers','suppliers','sales','purchases','receivables','payables'],'text'),
h('customer_opening_balance',['الرصيد الافتتاحي للعميل','رصيد العميل الافتتاحي','Customer Opening Balance'],['customers','receivables'],'currency'),
h('sales_amount',['مبلغ المبيعات','قيمة المبيعات','Sales Amount'],['sales'],'currency'),
h('returns_amount',['مبلغ المردودات','قيمة المرتجعات','Returns Amount','Sales Returns'],['sales'],'currency'),
h('net_sales_amount',['صافي المبيعات','صافي قيمة المبيعات','Net Sales','Net Sales Amount'],['sales'],'currency'),
h('other_debit',['عمليات مدينة أخرى','مدين آخر','Other Debit'],['receivables','general-ledger'],'currency'),
h('collected_amount',['المبلغ المحصل','المحصل','التحصيل','Collected Amount'],['receivables','sales','distribution'],'currency'),
h('other_credit',['عمليات دائنة أخرى','دائن آخر','Other Credit'],['receivables','general-ledger'],'currency'),
h('balance',['الرصيد','الرصيد المستحق','الرصيد النهائي','Balance','Closing Balance'],['customers','suppliers','receivables','payables'],'currency'),
h('undue_checks',['شيكات لم تستحق','شيكات آجلة','Undue Checks'],['receivables','payables'],'currency'),
h('remaining_amount',['المبلغ المتبقي','المتبقي','Remaining Amount','Outstanding Amount'],['receivables','payables'],'currency'),
h('last_sale_date',['آخر تاريخ بيع','تاريخ آخر بيع','Last Sale Date'],['customers','sales'],'date'),
h('last_payment_date',['آخر تاريخ سداد','تاريخ آخر سداد','Last Payment Date'],['receivables'],'date'),
h('supplier_id',['رقم المورد','كود المورد','Supplier No','Supplier Number','Supplier ID'],['suppliers','purchases','payables'],'identifier'),
h('supplier_name',['اسم المورد','المورد','Supplier Name'],['suppliers','purchases','payables'],'text'),
h('invoice_no',['رقم الفاتورة','رقم الفاتورة/السند','رقم المستند','Invoice No','Invoice Number','Document No'],['sales','purchases','receivables','payables','documents'],'identifier'),
h('transaction_no',['رقم الحركة','رقم الحركة المخزنية','رقم الحركة','Transaction No'],['inventory','adjustments','transfers','documents'],'identifier'),
h('date',['التاريخ','تاريخ الحركة','تاريخ الفاتورة','تاريخ السند','Date','Transaction Date','Invoice Date'],['sales','purchases','inventory','adjustments','transfers','documents','general-ledger'],'date'),
h('document_type',['نوع السند','نوع الحركة','نوع المستند','Document Type','Transaction Type'],['documents','inventory','adjustments','transfers'],'text'),
h('entity_id',['رقم الجهة','كود الجهة','Entity No'],['documents'],'identifier'),
h('entity_name',['اسم الجهة','الجهة','Entity Name'],['documents'],'text'),
h('adjustment_quantity',['كمية التسوية','كمية التسوية المخزنية','Adjustment Quantity'],['adjustments'],'quantity'),
h('adjustment_type',['نوع التسوية','نوع الجرد','Adjustment Type'],['adjustments'],'text'),
h('cost',['التكلفة','تكلفة المبيعات','تكلفة الشراء','Cost','Sales Cost','Purchase Cost'],['sales','purchases','adjustments'],'currency'),
h('unit_price',['السعر','سعر الوحدة','سعر البيع','Unit Price','Selling Price'],['sales','purchases','pricing'],'currency'),
h('discount_amount',['الخصم المكتسب','قيمة الخصم','الخصم','Discount Amount','Discount'],['sales','purchases'],'currency'),
h('discount_percent',['نسبة الخصم','الخصم %','Discount %','Discount Percentage'],['sales','purchases'],'percent'),
h('gross_profit',['إجمالي الربح','الربح الإجمالي','Gross Profit'],['sales','profit-loss'],'currency'),
h('profit_margin',['نسبة الربحية','هامش الربح','Profit Margin','Margin %'],['sales','profit-loss'],'percent'),
h('payment_amount',['المدفوع','مبلغ الدفع','Paid Amount','Payment Amount'],['purchases','payables','sales','receivables'],'currency'),
h('due_date',['تاريخ الاستحقاق','تاريخ استحقاق الدفعات','Due Date','Payment Due Date'],['purchases','payables','receivables'],'date'),
h('transfer_no',['رقم التحويل','رقم سند التحويل','Transfer No'],['transfers'],'identifier'),
h('transfer_status',['الحالة','حالة التحويل','Transfer Status'],['transfers'],'text'),
h('quantity',['الكمية','العدد','Quantity','Qty'],['sales','purchases','inventory','documents'],'quantity'),
h('account_no',['رقم الحساب','كود الحساب','Account No','Account Number'],['general-ledger','trial-balance','profit-loss'],'identifier'),
h('account_name',['اسم الحساب','الحساب','Account Name'],['general-ledger','trial-balance','profit-loss'],'text'),
h('previous_balance',['رصيد الفترة السابقة','الرصيد السابق','Previous Balance'],['general-ledger','trial-balance','profit-loss'],'currency'),
h('debit',['الحركة المدينة','المدين','مدين','Debit'],['general-ledger','trial-balance','profit-loss'],'currency'),
h('credit',['الحركة الدائنة','الدائن','دائن','Credit'],['general-ledger','trial-balance','profit-loss'],'currency'),
h('current_balance_account',['الرصيد الحالي للحساب','الرصيد الحالي','Current Account Balance'],['general-ledger','trial-balance','profit-loss'],'currency'),
h('contribution_percent',['نسبة المساهمة','نسبة المساهمة %','Contribution %'],['profit-loss'],'percent'),
h('free_quantity',['الكمية المجانية','مجاني','Free Quantity','Free Qty'],['sales','purchases'],'quantity'),
h('expiry_date',['تاريخ الانتهاء','تاريخ الصلاحية','Expiry Date','Expiration Date'],['inventory','purchases'],'date'),
h('serial_no',['الرقم التسلسلي','رقم السيريال','Serial No','Serial Number'],['inventory','purchases'],'identifier'),
h('payment_method',['طريقة الدفع','وسيلة الدفع','Payment Method'],['sales','purchases','receivables','payables'],'text'),
h('description',['الوصف','البيان','Description','Narration'],['sales','purchases','documents','general-ledger'],'text'),
h('approval_status',['حالة الاعتماد','حالة الترحيل','Approval Status','Posting Status'],['documents','sales','purchases','general-ledger'],'text')
];
export function getOnyxProHeaderCatalog(){return ONYX_PRO_HEADER_CATALOG.map(x=>({...x,aliases:[...x.aliases],kind:[...x.kind]}));}
export function findOnyxHeaders(headers:string[]){const n=(s:string)=>s.toLowerCase().normalize('NFKC').replace(/[ً-ٟ]/g,'').replace(/[\s_\-./\\]+/g,' ').trim();const hs=headers.map(n);return ONYX_PRO_HEADER_CATALOG.map(d=>({...d,matchedAliases:d.aliases.filter(a=>hs.includes(n(a)))})).filter(d=>d.matchedAliases.length>0);}
