export type AlternativeGroupMode='detail'|'grouped';
export interface AlternativeGroup{groupId:string;tenantId:string;name:string;description?:string;baseUnit?:string;active:boolean;}
export interface AlternativeMember{groupId:string;sku:string;conversionToBase:number;priority?:number;active?:boolean;}
export interface AlternativeItemSnapshot{sku:string;groupId?:string;requestedUnits:number|null;stockUnits:number|null;netSalesUnits:number|null;avgDailyDemand:number|null;unitPrice?:number|null;conversionToBase?:number;}
export type AlternativeGroupDataState='KNOWN'|'INSUFFICIENT_DATA';
export interface AlternativeGroupAggregate{groupId:string;groupName:string;memberSkus:string[];requestedUnits:number|null;stockUnits:number|null;netSalesUnits:number|null;avgDailyDemand:number|null;daysOfCover:number|null;weightedFillRate:number|null;estimatedLostUnits:number|null;estimatedLostRevenue:number|null;dataState:AlternativeGroupDataState;}
function known(v:number|null|undefined):v is number{return Number.isFinite(v)}
function positive(v:number|null|undefined):number|null{return known(v)?Math.max(0,v):null}
export function validateAlternativeGroup(group:AlternativeGroup,members:AlternativeMember[]):void{if(!group.tenantId.trim()||!group.groupId.trim()||!group.name.trim())throw new Error('ALTERNATIVE_GROUP_INVALID');if(!members.length)throw new Error('ALTERNATIVE_GROUP_EMPTY');const seen=new Set<string>();for(const m of members){if(m.groupId!==group.groupId||!m.sku.trim()||seen.has(m.sku))throw new Error('ALTERNATIVE_GROUP_MEMBER_INVALID');if(!Number.isFinite(m.conversionToBase)||m.conversionToBase<=0)throw new Error('ALTERNATIVE_GROUP_CONVERSION_INVALID');seen.add(m.sku)}}
export function aggregateAlternativeGroups(groups:AlternativeGroup[],members:AlternativeMember[],items:AlternativeItemSnapshot[]):AlternativeGroupAggregate[]{const groupById=new Map(groups.filter(g=>g.active).map(g=>[g.groupId,g]));const memberBySku=new Map(members.filter(m=>m.active!==false).map(m=>[m.sku,m]));const out=new Map<string,AlternativeGroupAggregate>();for(const item of items){const member=memberBySku.get(item.sku);if(!member)continue;const group=groupById.get(member.groupId);if(!group)continue;const factor=member.conversionToBase;const a=out.get(group.groupId)??{groupId:group.groupId,groupName:group.name,memberSkus:[],requestedUnits:0,stockUnits:0,netSalesUnits:0,avgDailyDemand:0,daysOfCover:null,weightedFillRate:null,estimatedLostUnits:0,estimatedLostRevenue:0,dataState:'KNOWN' as AlternativeGroupDataState};if(!a.memberSkus.includes(item.sku))a.memberSkus.push(item.sku);const requested=positive(item.requestedUnits),stock=positive(item.stockUnits),sales=positive(item.netSalesUnits),demand=positive(item.avgDailyDemand);if(requested===null||stock===null||sales===null||demand===null)a.dataState='INSUFFICIENT_DATA';if(requested!==null)a.requestedUnits=(a.requestedUnits??0)+requested*factor;else a.requestedUnits=null;if(stock!==null&&a.stockUnits!==null)a.stockUnits+=stock*factor;else a.stockUnits=null;if(sales!==null&&a.netSalesUnits!==null)a.netSalesUnits+=sales*factor;else a.netSalesUnits=null;if(demand!==null&&a.avgDailyDemand!==null)a.avgDailyDemand+=demand*factor;else a.avgDailyDemand=null;if(requested!==null&&stock!==null){const fulfilled=Math.min(requested,stock);a.estimatedLostUnits=(a.estimatedLostUnits??0)+Math.max(0,requested-fulfilled)*factor;if(item.unitPrice!==null&&item.unitPrice!==undefined)a.estimatedLostRevenue=(a.estimatedLostRevenue??0)+Math.max(0,requested-fulfilled)*Math.max(0,item.unitPrice)}else{a.estimatedLostUnits=null;a.estimatedLostRevenue=null}out.set(group.groupId,a)}for(const a of out.values()){a.daysOfCover=a.dataState==='KNOWN'&&a.avgDailyDemand!==null&&a.avgDailyDemand>0&&a.stockUnits!==null?a.stockUnits/a.avgDailyDemand:null;a.weightedFillRate=a.dataState==='KNOWN'&&a.requestedUnits!==null&&a.requestedUnits>0&&a.estimatedLostUnits!==null?Math.max(0,Math.min(1,(a.requestedUnits-a.estimatedLostUnits)/a.requestedUnits)):null}return[...out.values()]}
export function chooseInventoryReportMode(mode:AlternativeGroupMode,items:AlternativeItemSnapshot[],groups:AlternativeGroup[],members:AlternativeMember[]):AlternativeItemSnapshot[]|AlternativeGroupAggregate[]{return mode==='detail'?items:aggregateAlternativeGroups(groups,members,items)}
