export type AlternativeGroupMode='detail'|'grouped';
export interface AlternativeGroup{groupId:string;tenantId:string;name:string;description?:string;baseUnit?:string;active:boolean;}
export interface AlternativeMember{groupId:string;sku:string;conversionToBase:number;priority?:number;active?:boolean;}
export interface AlternativeItemSnapshot{sku:string;groupId?:string;requestedUnits:number;stockUnits:number;netSalesUnits:number;avgDailyDemand:number;unitPrice?:number;conversionToBase?:number;}
export interface AlternativeGroupAggregate{groupId:string;groupName:string;memberSkus:string[];requestedUnits:number;stockUnits:number;netSalesUnits:number;avgDailyDemand:number;daysOfCover:number;weightedFillRate:number;estimatedLostUnits:number;estimatedLostRevenue:number;}
function n(v:number|undefined):number{return Number.isFinite(v)?Math.max(0,v as number):0}
export function validateAlternativeGroup(group:AlternativeGroup,members:AlternativeMember[]):void{if(!group.tenantId.trim()||!group.groupId.trim()||!group.name.trim())throw new Error('ALTERNATIVE_GROUP_INVALID');if(!members.length)throw new Error('ALTERNATIVE_GROUP_EMPTY');const seen=new Set<string>();for(const m of members){if(m.groupId!==group.groupId||!m.sku.trim()||seen.has(m.sku))throw new Error('ALTERNATIVE_GROUP_MEMBER_INVALID');if(!Number.isFinite(m.conversionToBase)||m.conversionToBase<=0)throw new Error('ALTERNATIVE_GROUP_CONVERSION_INVALID');seen.add(m.sku)}}
export function aggregateAlternativeGroups(groups:AlternativeGroup[],members:AlternativeMember[],items:AlternativeItemSnapshot[]):AlternativeGroupAggregate[]{const groupById=new Map(groups.filter(g=>g.active).map(g=>[g.groupId,g]));const memberBySku=new Map(members.filter(m=>m.active!==false).map(m=>[m.sku,m]));const out=new Map<string,AlternativeGroupAggregate>();for(const item of items){const member=memberBySku.get(item.sku);if(!member)continue;const group=groupById.get(member.groupId);if(!group)continue;const factor=n(member.conversionToBase)||1;const a=out.get(group.groupId)??{groupId:group.groupId,groupName:group.name,memberSkus:[],requestedUnits:0,stockUnits:0,netSalesUnits:0,avgDailyDemand:0,daysOfCover:Number.POSITIVE_INFINITY,weightedFillRate:1,estimatedLostUnits:0,estimatedLostRevenue:0};if(!a.memberSkus.includes(item.sku))a.memberSkus.push(item.sku);a.requestedUnits+=n(item.requestedUnits)*factor;a.stockUnits+=n(item.stockUnits)*factor;a.netSalesUnits+=n(item.netSalesUnits)*factor;a.avgDailyDemand+=n(item.avgDailyDemand)*factor;const fulfilled=Math.min(n(item.requestedUnits),n(item.stockUnits));a.estimatedLostUnits+=Math.max(0,n(item.requestedUnits)-fulfilled)*factor;a.estimatedLostRevenue+=Math.max(0,n(item.requestedUnits)-fulfilled)*n(item.unitPrice);out.set(group.groupId,a)}for(const a of out.values()){a.daysOfCover=a.avgDailyDemand>0?a.stockUnits/a.avgDailyDemand:Number.POSITIVE_INFINITY;a.weightedFillRate=a.requestedUnits>0?Math.max(0,Math.min(1,(a.requestedUnits-a.estimatedLostUnits)/a.requestedUnits)):1}return[...out.values()]}
export function chooseInventoryReportMode(mode:AlternativeGroupMode,items:AlternativeItemSnapshot[],groups:AlternativeGroup[],members:AlternativeMember[]):AlternativeItemSnapshot[]|AlternativeGroupAggregate[]{return mode==='detail'?items:aggregateAlternativeGroups(groups,members,items)}
