export type LiquidityClass='fast'|'slow'|'frozen';
export type PartnerType='customer'|'supplier'|'bank'|'exchange';
export type Priority='critical'|'high'|'normal'|'low';
export interface InventoryFlow{sku:string;name:string;stock:number;unitCost:number;dailySales:number;weeklySales:number;monthlySales:number;lastSaleDaysAgo:number;leadTimeDays:number;serviceLevel?:number;}
export interface InventoryInsight{sku:string;name:string;stockValue:number;daysOfCover:number|null;liquidity:LiquidityClass;velocity:'very-high'|'high'|'medium'|'low'|'none';stockoutDate:string|null;reorderPoint:number;maxStock:number;recommendedPurchase:number;priority:Priority;action:string;}
export interface Obligation{partnerId:string;partnerName:string;type:PartnerType;amount:number;dueDate:string;priority?:number;}
export interface CashPosition{date:string;openingCash:number;expectedInflow:number;expectedOutflow:number;minimumReserve:number;}
export interface CashPlan{date:string;openingCash:number;inflow:number;outflow:number;closingCash:number;reserveGap:number;status:'safe'|'tight'|'crisis';actions:string[];}
const n=(v:number)=>Number.isFinite(v)?v:0;
const isoAfter=(days:number)=>{const d=new Date();d.setDate(d.getDate()+Math.max(0,Math.ceil(days)));return d.toISOString().slice(0,10)};
export function analyzeInventoryFlow(rows:InventoryFlow[]):InventoryInsight[]{return rows.map(r=>{const d=n(r.dailySales);const cover=d>0?r.stock/d:null;const liquidity=cover===null?(r.lastSaleDaysAgo>90?'frozen':'slow'):cover<=14?'fast':cover<=60?'slow':'frozen';const velocity=d>=10?'very-high':d>=5?'high':d>=1?'medium':d>0?'low':'none';const lead=Math.max(1,n(r.leadTimeDays));const service=r.serviceLevel&&r.serviceLevel>0&&r.serviceLevel<1?r.serviceLevel:.95;const safety=Math.ceil(Math.sqrt(lead)*Math.max(d*.35,1)*(1+(service-.5)));const reorderPoint=Math.ceil(d*lead+safety);const maxStock=Math.ceil(d*(lead+30)+safety);const recommendedPurchase=Math.max(0,maxStock-r.stock);const priority:Priority=liquidity==='frozen'?'low':r.stock<=reorderPoint?'critical':cover!==null&&cover<=lead?'high':velocity==='very-high'?'high':'normal';const action=priority==='critical'?'إعادة طلب عاجلة':liquidity==='frozen'?'خطة تصريف المخزون الراكد':priority==='high'?'إعادة طلب قريب':'مراقبة الحركة';return{sku:r.sku,name:r.name,stockValue:n(r.stock)*n(r.unitCost),daysOfCover:cover===null?null:Number(cover.toFixed(1)),liquidity,velocity,stockoutDate:cover!==null?isoAfter(cover):null,reorderPoint,maxStock,recommendedPurchase,priority,action};});}
export function rankObligations(rows:Obligation[],asOf=new Date()):Obligation[]{return [...rows].sort((a,b)=>{const da=new Date(a.dueDate).getTime()-asOf.getTime();const db=new Date(b.dueDate).getTime()-asOf.getTime();const pa=(a.priority??0)*-86400000;const pb=(b.priority??0)*-86400000;return da+pa-db-pb;});}
export function buildCashPlan(position:CashPosition):CashPlan{const opening=n(position.openingCash),inflow=n(position.expectedInflow),outflow=n(position.expectedOutflow),reserve=Math.max(0,n(position.minimumReserve));const closing=opening+inflow-outflow;const gap=Math.max(0,reserve-closing);const status=closing<0||gap>opening*.25?'crisis':gap>0?'tight':'safe';const actions:string[]=[];if(status==='crisis')actions.push('تجميد المصروفات غير الضرورية','تسريع التحصيلات ذات الأولوية','إعادة جدولة الالتزامات الأعلى مرونة');else if(status==='tight')actions.push('رفع التحصيل اليومي','تأكيد آجال الموردين قبل السداد');return{date:position.date,openingCash:opening,inflow,outflow,closingCash:closing,reserveGap:gap,status,actions};}
export function buildLiquidityActions(inventory:InventoryInsight[],obligations:Obligation[],cash:CashPlan){const actions:{priority:Priority;title:string;reason:string;amount?:number}[]=[];for(const x of inventory.filter(i=>i.priority==='critical'))actions.push({priority:'critical',title:`إعادة طلب ${x.name}`,reason:`الرصيد المتوقع النفاد ${x.stockoutDate??'غير معروف'}، وحد الطلب ${x.reorderPoint}`,amount:x.recommendedPurchase});for(const o of obligations){const days=Math.ceil((new Date(o.dueDate).getTime()-Date.now())/86400000);if(days<=3)actions.push({priority:cash.status==='crisis'?'critical':'high',title:`استحقاق ${o.partnerName}`,reason:`مستحق خلال ${Math.max(0,days)} يوم`,amount:o.amount});}if(cash.status==='crisis')actions.push({priority:'critical',title:'خطة أزمة سيولة',reason:'الرصيد بعد التدفقات أقل من الاحتياطي الآمن'});return actions;}
