export type ForecastMethod='moving-average'|'linear-trend'|'exponential-smoothing';
export interface ForecastPoint{period:string;value:number}
export interface ForecastModel{name:ForecastMethod;forecast:number;error:number;weight:number}
export interface EnsembleForecast{forecast:number;lower:number;upper:number;models:ForecastModel[];confidence:number}
const clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
function mae(actual:number[],pred:number[]):number{if(!actual.length)return Infinity;return actual.reduce((s,v,i)=>s+Math.abs(v-(pred[i]??v)),0)/actual.length}
function moving(a:number[]):number{return a.slice(-3).reduce((s,v)=>s+v,0)/Math.min(3,a.length)}
function linear(a:number[]):number{const n=a.length;if(n<2)return a[0]??0;let sx=0,sy=0,sxx=0,sxy=0;for(let i=0;i<n;i++){sx+=i;sy+=a[i];sxx+=i*i;sxy+=i*a[i]}const d=n*sxx-sx*sx;const m=d?(n*sxy-sx*sy)/d:0;return(sy-m*sx)/n+m*n}
function exp(a:number,alpha=.3):number{if(!a.length)return 0;let level=a[0];for(let i=1;i<a.length;i++)level=alpha*a[i]+(1-alpha)*level;return level}
export function ensembleForecast(points:ForecastPoint[],horizon=1):EnsembleForecast{const a=points.map(p=>p.value).filter(Number.isFinite);if(!a.length)return{forecast:0,lower:0,upper:0,models:[],confidence:0};const candidates:[ForecastMethod,number][]=[['moving-average',moving(a)],['linear-trend',linear(a)],['exponential-smoothing',exp(a)]];const models=candidates.map(([name,forecast])=>{const train=a.slice(0,-1);const actual=a.slice(1);const pred=train.map((_,i)=>name==='moving-average'?moving(train.slice(0,i+1)):name==='linear-trend'?linear(train.slice(0,i+1)):exp(train.slice(0,i+1)));const error=train.length>1?mae(actual,pred):Math.abs(a[a.length-1]-forecast);return{name,forecast:forecast*Math.max(1,horizon),error:Number.isFinite(error)?error:0,weight:0}});const inv=models.map(m=>1/(m.error+1e-6));const total=inv.reduce((s,v)=>s+v,0);models.forEach((m,i)=>m.weight=inv[i]/total);const forecast=models.reduce((s,m)=>s+m.forecast*m.weight,0);const spread=models.reduce((s,m)=>s+m.weight*Math.abs(m.forecast-forecast),0);const confidence=clamp(100*(1-spread/(Math.abs(forecast)+1e-6)),0,100);return{forecast,lower:Math.max(0,forecast-1.96*(spread+1e-6)),upper:forecast+1.96*(spread+1e-6),models,confidence}}
