/** Free/local time-series primitives. No external API or paid model required. */
import { mean, stddev } from './statistics.ts';
export interface ForecastPoint { horizon:number; value:number; lower:number; upper:number; }
export interface ForecastResult { method:'naive'|'moving-average'|'ema'|'trend'; points:ForecastPoint[]; mae?:number; mape?:number; }
export function movingAverage(values:number[],window=7){return mean(values.slice(-Math.max(1,window)));}
export function forecastNaive(values:number[],horizon=7):ForecastResult{const base=values.at(-1)??0,sigma=stddev(values);return{method:'naive',points:Array.from({length:horizon},(_,i)=>({horizon:i+1,value:base,lower:Math.max(0,base-1.96*sigma),upper:base+1.96*sigma}))};}
export function forecastMovingAverage(values:number[],horizon=7,window=7):ForecastResult{const base=movingAverage(values,window),sigma=stddev(values.slice(-Math.max(1,window)));return{method:'moving-average',points:Array.from({length:horizon},(_,i)=>({horizon:i+1,value:base,lower:Math.max(0,base-1.96*sigma),upper:base+1.96*sigma}))};}
export function forecastEma(values:number[],horizon=7,alpha=.3):ForecastResult{let level=values[0]??0;const a=Math.min(1,Math.max(0,alpha));for(let i=1;i<values.length;i++)level=a*values[i]+(1-a)*level;const sigma=stddev(values);return{method:'ema',points:Array.from({length:horizon},(_,i)=>({horizon:i+1,value:level,lower:Math.max(0,level-1.96*sigma),upper:level+1.96*sigma}))};}
export function forecastLinear(values:number[],horizon=7):ForecastResult{const n=values.length;if(n<2)return forecastNaive(values,horizon);const mx=(n-1)/2,my=mean(values),den=values.reduce((s,_,i)=>s+(i-mx)**2,0),slope=den?values.reduce((s,v,i)=>s+(i-mx)*(v-my),0)/den:0,intercept=my-slope*mx,sigma=stddev(values);return{method:'trend',points:Array.from({length:horizon},(_,i)=>{const value=Math.max(0,intercept+slope*(n+i));return{horizon:i+1,value,lower:Math.max(0,value-1.96*sigma),upper:value+1.96*sigma}})};}
export function forecastAccuracy(actual:number[],predicted:number[]){const n=Math.min(actual.length,predicted.length);if(!n)return{mae:0,mape:0};const errors=actual.slice(0,n).map((v,i)=>Math.abs(v-predicted[i]));const mape=actual.slice(0,n).reduce((s,v,i)=>s+(v===0?0:Math.abs((v-predicted[i])/v)),0)/n*100;return{mae:mean(errors),mape};}
export function selectBestForecast(actual:number[],candidates:ForecastResult[]):ForecastResult{if(!actual.length||candidates.length<2)return candidates[0]??forecastNaive(actual);const scored=candidates.map(c=>{const preds=c.points.slice(0,Math.min(actual.length,c.points.length)).map(p=>p.value),acc=forecastAccuracy(actual.slice(0,preds.length),preds);return{c,...acc};}).sort((a,b)=>a.mae-b.mae),best=scored[0];return{...best.c,mae:best.mae,mape:best.mape};}
