import { type ReactNode } from 'react';

interface Column<T> { key:string; label:string; render?:(row:T)=>ReactNode; align?:'right'|'left'|'center'; className?:string; width?:string; }
interface DataTableProps<T> { columns:Column<T>[]; data:T[]; loading?:boolean; emptyMessage?:string; onRowClick?:(row:T)=>void; pageSize?:number; }

export function DataTable<T extends object>({ columns, data, loading, emptyMessage='لا توجد بيانات', onRowClick }:DataTableProps<T>) {
 if(loading)return <div className="p-5" role="status" aria-live="polite"><div className="space-y-2.5">{Array.from({length:6}).map((_,i)=><div key={i} className="skeleton h-12 w-full"/>)}</div></div>;
 if(!data||data.length===0)return <div className="flex min-h-44 flex-col items-center justify-center gap-2 p-8 text-center"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-ink-50 text-ink-300">∅</div><div className="text-sm font-semibold text-ink-600">{emptyMessage}</div><div className="text-xs text-ink-400">جرّب تغيير الفلاتر أو استيراد بيانات جديدة.</div></div>;
 return <div className="overflow-x-auto"><table className="w-full border-separate border-spacing-0"><thead><tr className="bg-ink-50/70">{columns.map(col=><th key={col.key} className={`border-b border-ink-100 px-4 py-3.5 text-[11px] font-bold text-ink-500 whitespace-nowrap first:pr-5 last:pl-5 ${col.align==='center'?'text-center':col.align==='left'?'text-left':'text-right'}`} style={{width:col.width}}>{col.label}</th>)}</tr></thead><tbody>{data.map((row,i)=>{const rowRecord=row as Record<string,unknown>;return <tr key={typeof rowRecord.id==='string'||typeof rowRecord.id==='number'?String(rowRecord.id):i} onClick={()=>onRowClick?.(row)} className={`group border-b border-ink-50 transition-colors ${onRowClick?'cursor-pointer hover:bg-primary-50/40':'hover:bg-ink-50/50'}`}>{columns.map(col=><td key={col.key} className={`border-b border-ink-50 px-4 py-3.5 text-sm text-ink-700 whitespace-nowrap group-last:border-0 ${col.align==='center'?'text-center':col.align==='left'?'text-left':'text-right'} ${col.className||''}`}>{col.render?col.render(row):rowRecord[col.key] as ReactNode}</td>)}</tr>})}</tbody></table></div>;
}
