const { app, BrowserWindow, dialog, ipcMain, Menu, Tray, nativeImage } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
let mainWindow=null, tray=null, selectedRoot=null, watchedRoot=null, watcher=null, pollTimer=null;
const known=new Map();
const pending=new Set();
const supported=new Set(['.pdf','.xlsx','.xls','.csv','.docx','.doc','.txt','.tsv','.ods','.json','.jsonl','.xml','.md','.markdown','.rtf','.jpg','.jpeg','.png','.webp','.tiff','.bmp']);
const isSupported=p=>supported.has(path.extname(p).toLowerCase());
const isInside=(root,target)=>{const rel=path.relative(root,target);return Boolean(rel)&&!rel.startsWith('..')&&!path.isAbsolute(rel);};
const configPath=()=>path.join(app.getPath('userData'),'folder-watch.json');
function loadSelectedRoot(){try{const raw=JSON.parse(fs.readFileSync(configPath(),'utf8'));if(typeof raw?.selectedRoot==='string'&&raw.selectedRoot.trim()){const root=path.resolve(raw.selectedRoot);const stat=fs.statSync(root);if(stat.isDirectory()){selectedRoot=root;return selectedRoot;}}}catch{}selectedRoot=null;return null;}
function persistSelectedRoot(root){fs.mkdirSync(path.dirname(configPath()),{recursive:true});fs.writeFileSync(configPath(),JSON.stringify({selectedRoot:root,updatedAt:new Date().toISOString()},null,2),'utf8');}
function clearPersistedRoot(){try{fs.rmSync(configPath(),{force:true});}catch{}}
function walk(root){const out=[],stack=[root];while(stack.length){const dir=stack.pop();let entries=[];try{entries=fs.readdirSync(dir,{withFileTypes:true});}catch{continue;}for(const e of entries){const full=path.join(dir,e.name);if(e.isDirectory())stack.push(full);else if(e.isFile()&&isSupported(full))out.push(full);}}return out.sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));}
async function waitForStableFile(filePath){let previous=null;for(let attempt=0;attempt<5;attempt+=1){let stat;try{stat=await fs.promises.stat(filePath);}catch{throw new Error('WATCH_FILE_NOT_AVAILABLE');}const current=`${stat.size}:${stat.mtimeMs}`;if(previous===current)return stat;previous=current;await new Promise(resolve=>setTimeout(resolve,400));}throw new Error('WATCH_FILE_STILL_WRITING');}
async function emitFile(filePath,reason='changed'){if(!mainWindow||!watchedRoot||!fs.existsSync(filePath)||!isSupported(filePath)||!isInside(watchedRoot,filePath)||pending.has(filePath))return;const relativePath=path.relative(watchedRoot,filePath);if(!relativePath||relativePath.startsWith('..')||path.isAbsolute(relativePath))return;pending.add(filePath);try{const stat=await waitForStableFile(filePath);const key=`${filePath}:${stat.size}:${stat.mtimeMs}`;if(known.get(filePath)===key)return;known.set(filePath,key);mainWindow.webContents.send('desktop-folder-watch:file',{relativePath,reason,size:stat.size,modifiedAt:new Date(stat.mtimeMs).toISOString()});}finally{pending.delete(filePath);}}
function rescan(){if(!watchedRoot)return;const current=new Set(walk(watchedRoot));for(const p of current)void emitFile(p,'scan');for(const p of [...known.keys()])if(p.startsWith(watchedRoot+path.sep)&&!current.has(p)){known.delete(p);mainWindow?.webContents.send('desktop-folder-watch:deleted',{path:path.relative(watchedRoot,p)});}}
function stopWatch(){watcher?.close();watcher=null;if(pollTimer)clearInterval(pollTimer);pollTimer=null;watchedRoot=null;known.clear();pending.clear();}
function startWatch(){if(!selectedRoot)throw new Error('WATCH_FOLDER_NOT_SELECTED');const root=path.resolve(selectedRoot);let stat;try{stat=fs.statSync(root);}catch{throw new Error('WATCH_FOLDER_NOT_AVAILABLE');}if(!stat.isDirectory())throw new Error('WATCH_FOLDER_NOT_DIRECTORY');stopWatch();watchedRoot=root;rescan();try{watcher=fs.watch(watchedRoot,{recursive:true},(_event,filename)=>{if(!filename)return;const relative=filename.toString();const full=path.resolve(watchedRoot,relative);if(!isInside(watchedRoot,full))return;setTimeout(()=>void emitFile(full,'filesystem'),200);});watcher.on('error',()=>{watcher=null;});}catch{watcher=null;}pollTimer=setInterval(rescan,30000);return{path:watchedRoot,name:path.basename(watchedRoot)};}
function createWindow(){mainWindow=new BrowserWindow({width:1440,height:920,minWidth:1100,minHeight:700,autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});const devUrl=process.env.VITE_DEV_SERVER_URL;if(devUrl)mainWindow.loadURL(devUrl);else mainWindow.loadFile(path.join(__dirname,'..','dist','index.html'));mainWindow.on('close',event=>{if(app.isQuitting)return;event.preventDefault();mainWindow.hide();});}
app.whenReady().then(()=>{loadSelectedRoot();ipcMain.handle('desktop-folder-watch:select',async()=>{const result=await dialog.showOpenDialog(mainWindow,{properties:['openDirectory']});if(result.canceled||!result.filePaths[0])return null;selectedRoot=path.resolve(result.filePaths[0]);persistSelectedRoot(selectedRoot);return{path:selectedRoot,name:path.basename(selectedRoot)};});ipcMain.handle('desktop-folder-watch:get-selected',()=>selectedRoot?{path:selectedRoot,name:path.basename(selectedRoot)}:null);ipcMain.handle('desktop-folder-watch:start',()=>startWatch());ipcMain.handle('desktop-folder-watch:stop',()=>{stopWatch();return true;});ipcMain.handle('desktop-folder-watch:forget',()=>{stopWatch();selectedRoot=null;clearPersistedRoot();return true;});ipcMain.handle('desktop-folder-watch:read-file',async(_event,relativePath)=>{if(!watchedRoot)throw new Error('WATCH_FOLDER_NOT_ACTIVE');if(typeof relativePath!=='string'||!relativePath.trim())throw new Error('WATCH_FILE_PATH_INVALID');const resolved=path.resolve(watchedRoot,relativePath);if(!isInside(watchedRoot,resolved))throw new Error('WATCH_FOLDER_PATH_OUTSIDE_ROOT');let realRoot,realFile;try{realRoot=await fs.promises.realpath(watchedRoot);realFile=await fs.promises.realpath(resolved);}catch{throw new Error('WATCH_FILE_NOT_AVAILABLE');}if(!isInside(realRoot,realFile)||!isSupported(realFile))throw new Error('WATCH_FILE_PATH_OUTSIDE_ROOT');await waitForStableFile(realFile);return fs.promises.readFile(realFile);});tray=new Tray(nativeImage.createEmpty());tray.setToolTip('Report-Advisor');tray.setContextMenu(Menu.buildFromTemplate([{label:'فتح Report-Advisor',click:()=>mainWindow?.show()},{label:'إيقاف مراقبة المجلد',click:()=>stopWatch()},{label:'نسيان مجلد المزامنة',click:()=>{stopWatch();selectedRoot=null;clearPersistedRoot();}},{label:'خروج',click:()=>{app.isQuitting=true;stopWatch();app.quit();}}]));tray.on('double-click',()=>mainWindow?.show());createWindow();});
app.on('window-all-closed',event=>event.preventDefault());app.on('before-quit',()=>{app.isQuitting=true;stopWatch();});app.on('activate',()=>mainWindow?.show());